### ISSUE TITLE
[BUG] Dask-Cudf Matrix Multiplication (Axis dimension mismatch)

### ISSUE THREAD

**Issue by tiketdatayash** [rapidsai/cudf#12240] opened 2022-11-24 05:35 UTC
Description
Generally the cudf consist's a in build function for matrix multiplication (ref:-https://docs.rapids.ai/api/cudf/stable/api_docs/api/cudf.DataFrame.dot.html). When using the same function with dask-cudf it results in axis-dimension mismatch.

**Steps/Code to reproduce bug**
Just create two dask_cudf data frame of appropriate dimensions and multiply them with df1.dot(df2,meta).
Please find the image attached below as a reference.
![image](https://user-images.githubusercontent.com/105515725/203701693-8b24c064-bd4b-47d2-b44f-dc716857099e.png)

**Expected behavior**
It should return a matrix with a dot product for the provided matrix with appropriate dimensions.

**Environment overview (please complete the following information)**
CPU-8GB
GPU-2

**Comment by wence-** [comment] 2022-11-24 18:33
Can you please provide a test case we can run to reproduce the bug? Manually copying from a screenshot is both difficult and error prone.

**Comment by jonathanlionoattiket** [comment] 2022-11-29 05:43
[daskcudf_simulated_jono.ipynb.zip](https://github.com/rapidsai/cudf/files/10110082/daskcudf_simulated_jono.ipynb.zip)

@wence- thanks just copying again from our previous query in https://forums.developer.nvidia.com/t/dask-cudf-matrix-multiplication-valueerror-axis-dimension-mismatch/234541?u=yash.kushwaha. 

For more context here as @tiketdatayash also part of my team, I have also tried this on simulated data (please check the attached Jupyter notebook in the zip file). The aim is to perform matrix multiplication on dask-cuDF to utilise GPU for our recommendation operations. As we are exploring this, we did encounter out of memory issue (currently exploring the set-up of dask kubernetes) on GPU utilisation.

Aside of that issue, now, we took a small sample (simulated) of what we have in our real environment case. We are able to perform cpu based matrix multiplication (current baseline), dask matrix multiplication, and normal cuDF matrix multiplication.

However, if you check the cell #19, it fails with the error: “axis dimension mismatch” although we have included the required meta.

**Comment by wence-** [comment] 2022-11-29 09:56
Thanks, this appears to be a bug in dask dataframe, I will take a look. Here is a reduced example:

```python
import dask.dataframe as dd
import pandas as pd
import numpy as np

A = pd.DataFrame(np.arange(12).reshape(3, 4))
B = pd.DataFrame(np.arange(4).reshape(4, 1))

dA = dd.from_pandas(A, npartitions=1)
dB = dd.from_pandas(B, npartitions=1)

dC = dA.dot(dB, meta=pd.DataFrame(columns=dB.columns).persist()
```

**Comment by wence-** [comment] 2022-11-29 11:46
I think that the issue is that dask does not actually implement `DataFrame.dot` (the implementation only works if the left operand is a `Series`), opened https://github.com/dask/dask/issues/9700.

Having said all that, can you explain why you are trying why you are trying to perform this matrix multiplication with dataframe objects? As I understand it from your example notebook, the actual matrices involved are sparse (sometimes very sparse). Fast algorithms for multiplying sparse matrices together work on non-zeros (rather than the full structure), the classic text here is [Gustavson, _Two algorithms for sparse matrices: Multiplication and permuted transposition_, ACM TOMS 4:250-269 (1978)](https://doi.org/10.1145/355791.355796). A variant of this approach is implemented by scipy.sparse. Since sparse matrix-matrix multiply is at the core of many numerical algorithms, a lot of work has gone in to developing fast approaches on a variety of hardware (see https://arxiv.org/pdf/2002.11273.pdf for a recent review of the state of the art). On GPUs I would probably recommend trying to see if [cuSPARSE](https://docs.nvidia.com/cuda/cusparse/index.html) fits the bill (which you can access through [`cupyx`](https://docs.cupy.dev/en/stable/reference/scipy_sparse.html)).

I think that [you can use](https://docs.dask.org/en/stable/array-sparse.html) dask.array with cupy sparse matrices, so if you need distributed memory (multi-GPU) parallelisation that would probably be a good place to start.

In contrast to this, cuDF (and hence dask-cudf) will use dense storage for the matrix, so will do a lot of redundant work. Moreover, the column-by-column data layout of a `DataFrame` is not amenable to fast dense matrix-matrix multiplication (since fast algorithms do not operate one column at a time). So if, in fact, your data are dense you are probably better off converting the `DataFrame` to a cupy array, performing the matrix-matrix multiplication there, and then converting back again [this depends a little on what else you are doing, conversion is not zero-cost, but if you need to do many multiplications it can be amortised].

**Comment by shwina** [comment] 2023-01-18 19:12
I'm going to go ahead and close this as not a bug (the issue seems to be in dask). If you have any follow-up questions, please feel free to reopen.

**Closed by shwina** 2023-01-18 19:12 UTC
Labels: bug, 0 - Backlog, dask
