### ISSUE TITLE
cudf read_csv is replace rows of data with None or nulls

### ISSUE THREAD

**Issue by kenhester** [rapidsai/cudf#873] opened 2019-02-06 03:44 UTC
**Describe the bug**
cudf read_csv is replace rows of data with None or nulls.  Furthermore, there are other rows that are missing.  Pandas reading the file that has 28M rows but cudf reads 14M. 

**Steps/Code to reproduce bug**
import pandas as pd
import nvstrings, cudf

file = 'test1.csv'
dfp = pd.read_csv(file, encoding="ISO-8859-1", error_bad_lines=False)

names = ["ID","Str1","Str2","Str3","Str4"]
types = ['int','str','str','str','str']
columns = cudf.io.csv.read_csv_strings(file, names=names, dtype=types, skiprows=1)

print('Data in pandas dataframe')
print(list(dfp.ix[:, 4]))
print('Shape {}:'.format(dfp.shape))

print('\n')
print('Data in cudf')
print(columns[4].to_host())
print('Shape {} / {}'.format(len(columns[0]), len(columns)))

**Expected behavior**
1. The row count between pandas and cudf should match.
2. The data in the rows should match.  No random nulls or None values in cudf dataframe where a string is present in pandas dataframe.

**Environment details (please complete the following information):**
 - Environment location: Bare-metal server, 4x V100
 - Method of cuDF install: RAPIDS 0.5 NGC container pulled 4-Feb
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
 - Please run and attach the output of the `cudf/print_env.sh` script to gather relevant environment details
 [Awaiting output from the script]

**Additional context**
Please request privately for sample data file that reproduces the issue.

**Comment by kenhester** [comment] 2019-02-06 17:41
[env.txt](https://github.com/rapidsai/cudf/files/2837559/env.txt)

**Comment by j-ieong** [comment] 2019-02-09 02:49
Update on this issue:

This was discussed and found that issue to be the presence of dangling quotation characters in the file. The CSV reader assumes these are start/end quotation pairs and ignores all the terminations between the them.

The determination of number of rows occurs before the row parsing step, and the detection is done in parallel on the GPU, on data chunks. With the limited visibility for each GPU thread, it would be difficult to distinguish a dangling quote from a legitimate quote.

**Comment by mjsamoht** [comment] 2019-02-13 00:40
We did some more experiments to understand how pandas behaves:

```
import pandas as pd

file = 'quotes.csv'
dfp = pd.read_csv(file, delimiter='|')
```

### Summary of pandas behavior
1. Quotation marks are considered as quotes only if the quotation mark is the first character of a column.
2. If the first character of a column is not a quotation mark, any following quotation marks will be treated like regular characters.
3. Because of item 2) pandas is unable to handle delimiters inside quotes that don't start at the beginning of a column.  In most cases pandas crashes.

### Example 1:
```
COL A|COL B|COL C
11111|"First row string"|End 1
22222|Second row string|End 2
```
- As expected pandas returns 2 rows because of item 1) above.
- Row 1 Col B:  `First row string`

### Example 2:
```
COL A|COL B|COL C
11111|First row string"|End 1
22222|Second row string|End 2
```
- Because of item 2) above pandas returns 2 rows
- Row 1 Col B:  `First row string"
`
### Example 3:
```
COL A|COL B|COL C
11111|"First row string|End 1
22222|Second row string"|End 2
```
- Because of item 1) above pandas returns 1 row
- Row 1 Col B:  `First row string|End 1\n22222|Second row string`

### Example 4:
```
COL A|COL B|COL C
11111|First row "|"string|End 1
22222|Second row string|End 2
```
- Because of item 2) above pandas doesn't know that the delimiter in quotes ("|") should be ignored and **pandas crashes**.

**Comment by randerzander** [comment] 2019-02-13 02:30
@kenhester as a sanity check, can you confirm via other means the number of rows in the file? Perhaps use `wc` on the command line to confirm pandas.read_csv is actually returning the correct row-count.

If it is, then I think we'd like to take you up on the offer to privately test with a sample of your data.

**Comment by mjsamoht** [comment] 2019-02-13 03:09
Create a file with the following content:
```
COL A|COL B|COL C
11111|First row string"|End 1
22222|Second row string|End 2
```
pandas will return two rows, while cudf will return one row.  If you specify `quotechar='\0'` for cudf it will also return two rows (same as pandas).

**Comment by mjsamoht** [comment] 2019-02-13 19:33
Let me summarize.  **The file in question here doesn't properly use quotation marks in pairs**.  

The reason why `pandas` behaves differently from `cudf` is because:
- `pandas` only enters `quotation mode` if the first character of a column is a quotation mark.  Otherwise, it will ignore all quotation marks (i.e. treat them like regular characters) until the next delimiter or line terminator is found.
- `cudf` enters `quotation mode` any time a quotation mark is encountered and will remain in this mode until the next quotation mark.  All characters between these quotation pairs will be treated as part of the same field.

We can match `pandas` behavior but then we will no longer be able to handle cases like this that are making correct use of quotation marks:
`11111,Some Name "San Jose, CA",5x546`

The second col starts with `S` for `Some`, which is not a quotation mark.  This means the second col will be `Some Name "San Jose`.  The `,` after `San Jose` will now be incorrectly interpreted as delimiter.  The third col will be ` CA"`, and there is a fourth col `5x546` that will likely lead to some error or warning.

**Comment by kkraus14** [comment] 2019-02-13 19:39
@mjsamoht @kenhester what's the behavior if the CSV readers have the `quoting` parameter set to 3 (QUOTE_NONE)?

If that resolves the issue is that sufficient @randerzander?

**Comment by mjsamoht** [comment] 2019-02-13 22:44
I'm not 100% sure what `quoting` does in pandas. In cudf it's a boolean that indicates whether quotation marks should be removed or not but does not affect the actual parsing process.  So specifying `quoting=False` won't work with cudf.  You need `quotechar='\0'`.

**Comment by kkraus14** [comment] 2019-02-13 22:52
This sounds like a bug in behavior then, rules I would expect as follows based on Pandas CSV rules:
```
csv.QUOTE_ALL (0)
Instructs writer objects to quote all fields.

No special behavior for reader.

csv.QUOTE_MINIMAL (1)
Instructs writer objects to only quote those fields which contain special characters such as delimiter, quotechar or any of the characters in lineterminator.

No special behavior for reader.

csv.QUOTE_NONNUMERIC (2)
Instructs writer objects to quote all non-numeric fields.

No special behavior for reader.

csv.QUOTE_NONE (3)
Instructs writer objects to never quote fields. When the current delimiter occurs in output data it is preceded by the current escapechar character. If escapechar is not set, the writer will raise Error if any characters that require escaping are encountered.

Instructs reader to perform no special processing of quote characters.
```

**Comment by mjsamoht** [comment] 2019-02-14 22:49
Yes, cudf behaves differently from pandas.  There are redundant quoting arguments in pandas so it gets a bit messy.  Let me try to summarize:
- If `quoting=3` all quotation marks are ignored and treated like other characters.  This is the same as `quotechar='\0'`.  Thus, the combination of `quoting=3` and `quotechar!='\0'` is not allowed.
- If `quoting!=3` and `quotechar='\0'` we have same behavior as above.
- If `quoting!=3` and `quotechar!='\0'` then `quotechar` is the quotation mark.  Quotation marks are removed and we expect them to happen in pairs.  If they don't occur in pairs cudf and pandas behave differently.
- Handling double quotes includes yet another argument `doublequote`. 

In cudf `quoting` is a Boolean that decides whether quotation marks should be removed or not.  This is different from pandas and we should probably modify this to match pandas.

**Comment by mjsamoht** [comment] 2019-02-15 21:23
@kkraus14 I think we should change the cudf behavior of `quoting` to match pandas.  Then it will be possible to ignore quotes with `quoting=QUOTE_NONE` like pandas, and reading the file in this issue will work.  

Beyond that I believe there is no action item for this issue.  While we always want to follow pandas' behavior with correctly formatted input, it's just not possible to always produce the same output with malformed files.

**Comment by mjsamoht** [comment] 2019-02-17 20:09
I filed issue #974 to change the cudf behavior of `quoting` to match pandas.  After that you can specify `quoting=QUOTE_NONE` to read the problematic file in this issue.  I believe there is no other action required for this issue.

**Comment by mjsamoht** [comment] 2019-03-04 20:51
Issue #974 is implemented and merged.  By specifying `quoting=3` it is now possible to ignore quotes, which allows reading files with missing quotation characters.  This will give the same result as pandas.

Note that we can't always produce the same output as pandas when the input file is malformed.  So there may be other cases in the future where cudf and pandas produce different results for malformed input files.

**Closed by mjsamoht** 2019-03-04 20:51 UTC
Labels: bug, cuIO

**Comment by trstovall** [comment] 2019-03-14 20:38
@kenhester Sorry for the necromancy, but I have read from multiple sources that string values in CSVs that need to be escaped must begin and end with double quotes.  Quotations within that string are then escaped using double quotes.  So, `Some Name "San Jose, CA"` is escaped as `"Some Name ""San Jose, CA"""`.

**Comment by kenhester** [comment] 2019-03-14 21:22
Is it possible to support quoting=NONE , and just look for the delimiter when parsing?

Ken Hester | NVIDIA Solutions Architect
c: 832-216-8736
khester@nvidia.com<mailto:khester@nvidia.com>

GTC 2019<https://www.nvidia.com/en-us/gtc/> |San Jose Convention Center|Workshops- March 17, 2019  |Conference- March 18-21,2019

**Comment by trstovall** [comment] 2019-03-14 21:31
Here's a sample of the default behavior of Python's `csv` library:
```python
>>> import csv
>>> row = [11111, 'Some Name "San Jose, CA"', '5x546']
>>> with open('some.csv', 'w') as f:
...   csv.writer(f).writerows(data)
... 
>>> with open('some.csv', 'r') as f:
...   print(repr(f.read()))
... 
'11111,"Some Name ""San Jose, CA""",5x546\n'
>>> with open('some.csv', 'r') as f:
...   row = next(csv.reader(f))
... 
>>> row
['11111', 'Some Name "San Jose, CA"', '5x546']
```

**Comment by trstovall** [comment] 2019-03-14 21:36
@kenhester Sure, that's possible, but since it isn't considered default behavior, it requires an out-of-band agreement between the writer and reader.

**Comment by kenhester** [comment] 2019-03-14 23:25
The file is exported without quoted strings, but has some free text entry fields in several languages and some have single and double quotes in the field.  To facilitate data cleanup, we will use the quoting=NONE to import the data.



Ken Hester | NVIDIA Solutions Architect
c: 832-216-8736
khester@nvidia.com<mailto:khester@nvidia.com>

GTC 2019<https://www.nvidia.com/en-us/gtc/> |San Jose Convention Center|Workshops- March 17, 2019  |Conference- March 18-21,2019
