### ISSUE TITLE
[BUG] cudf.concat(.., axis=1) does not work with NaN values.

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#5357] opened 2020-06-01 23:48 UTC
```
import cudf 
s1 = cudf.Series([50,100],index=["Alice","Tom"], name="col1")
s2 = cudf.Series([50,100,150],index=["Alice","Tom","Linda"], name="col2")
cudf.concat([s1,s2],axis=1)
```

This fails in cudf, but gives an output with Pandas, adding a NaN in the "Linda" row in col1.

**Comment by kkraus14** [comment] 2020-06-01 23:49
Duplicate of: https://github.com/rapidsai/cudf/issues/3498

**Closed by kkraus14** 2020-06-01 23:49 UTC
Labels: ? - Needs Triage, bug
