### ISSUE TITLE
[BUG] Unexpected OOM in dask_cudf repartition

### ISSUE THREAD

**Issue by afender** [rapidsai/cudf#6239] opened 2020-09-15 16:37 UTC
**Describe the bug**
I'm hitting an OOM error in `ddf.repartition(npartitions=n_gpu)`
This happens after successfully reading a dataset broken into `X` flies/chunks/partitions when I am trying to "consolidate" these partitions to `Y` GPUs with one partition per GPU (`Y<X`). 

**Steps/Code to reproduce bug**
In this example, I generate 20 files with 2 columns and 100M rows in each one, all integers. This represents a typical edge list workload for cuGraph.
I hit the OOM issue while the in-memory size of this input is 16GB (100M rows x 2columns x 20 parts x 4bytes ) and I have 96GB of device memory accorss 2 GPUs on the test machine. 

```python
from dask.distributed import futures_of, Client, default_client, wait
from dask_cuda import LocalCUDACluster
import dask_cudf
import os
from cudf.datasets import randomdata
import time

def main():

    cluster = LocalCUDACluster()
    client = Client(cluster)

    print("Generate data... ")
    if not os.path.exists('files_parquet'):
        os.mkdir('files_parquet')
    for x in range(20):
        df = randomdata(nrows=100000000,
                    dtypes={'src':int, 'dst':int},
                    seed=x)
        df.to_parquet('files_parquet/df'+str(x), index=False)

    print("read_parquet... ")
    ddf = dask_cudf.read_parquet('files_parquet')
    ddf = ddf.persist()     
    futures_of(ddf)
    wait(ddf)
    print (ddf)

    print("repartition... ")
    ddf = ddf.repartition(npartitions=len(client.scheduler_info()['workers']))
    ddf = ddf.persist()     
    futures_of(ddf)
    wait(ddf)
    print (ddf)

    client.close()
    cluster.close()

if __name__ == "__main__":
    main()

```

**Expected behavior**
All the data is already successfully loaded in memory so I'd have expected `repartition` to be in place or require a tiny amount of memory. Currently, it fails while the dataset takes less than 20% of the available device memory before calling repartition.

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit 0b28d706f4dc738653eb56af0c7693aba12cfc7c (HEAD -> branch-0.15, origin/branch-0.15, origin/HEAD)
     Merge: e63eb3110 ad7c716d4
     Author: GALI PREM SAGAR <sagarprem75@gmail.com>
     Date:   Mon Jul 27 11:31:34 2020 -0500
     
     Merge pull request #5766 from galipremsagar/5757
     
     [REVIEW] Fix issue related to `iloc` and slicing a `DataFrame`
     **git submodules***
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
     NAME="Ubuntu"
     VERSION="18.04.5 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.5 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux afhpz8 5.4.0-45-generic #49~18.04.2-Ubuntu SMP Wed Aug 26 16:29:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Tue Sep 15 11:22:10 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  Quadro RTX 8000     On   | 00000000:15:00.0 Off |                  Off |
     | 33%   46C    P8    26W / 260W |     11MiB / 48601MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   1  Quadro RTX 8000     On   | 00000000:2D:00.0  On |                  Off |
     | 34%   55C    P8    34W / 260W |   1584MiB / 48592MiB |     28%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |    0   N/A  N/A       986      G   /usr/lib/xorg/Xorg                  4MiB |
     |    0   N/A  N/A      1431      G   /usr/lib/xorg/Xorg                  4MiB |
     |    1   N/A  N/A       986      G   /usr/lib/xorg/Xorg                 71MiB |
     |    1   N/A  N/A      1121      G   /usr/bin/gnome-shell               10MiB |
     |    1   N/A  N/A      1431      G   /usr/lib/xorg/Xorg                581MiB |
     |    1   N/A  N/A      1563      G   /usr/bin/gnome-shell              311MiB |
     |    1   N/A  N/A      2966      G   ...token=8741989596276266395      294MiB |
     |    1   N/A  N/A     19302      G   ...AAAAAAAAA= --shared-files      237MiB |
     |    1   N/A  N/A     22292      G   ...AAAAAAAAA= --shared-files       70MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              12
     On-line CPU(s) list: 0-11
     Thread(s) per core:  2
     Core(s) per socket:  6
     Socket(s):           1
     NUMA node(s):        1
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               85
     Model name:          Intel(R) Xeon(R) Gold 6128 CPU @ 3.40GHz
     Stepping:            4
     CPU MHz:             3648.103
     CPU max MHz:         3700.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            6800.00
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            1024K
     L3 cache:            19712K
     NUMA node0 CPU(s):   0-11
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke md_clear flush_l1d
     
     ***CMake***
     /home/afender/miniconda3/envs/cugraph_dev/bin/cmake
     cmake version 3.18.2
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2020 NVIDIA Corporation
     Built on Wed_Jul_22_19:09:09_PDT_2020
     Cuda compilation tools, release 11.0, V11.0.221
     Build cuda_11.0_bu.TC445_37.28845127_0
     
     ***Python***
     /home/afender/miniconda3/envs/cugraph_dev/bin/python
     Python 3.8.5
     
     ***Environment Variables***
     PATH                            : /home/afender/miniconda3/envs/cugraph_dev/bin:/home/afender/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin:/home/afender/ompi/build/bin:/home/afender/ucx/build/bin
     LD_LIBRARY_PATH                 : :/usr/local/cuda/lib64:/home/afender/nccl/build/build/lib:/home/afender/ompi/build/lib:/home/afender/ucx/build/bin
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/afender/miniconda3/envs/cugraph_dev
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/afender/miniconda3/condabin/conda
     # packages in environment at /home/afender/miniconda3/envs/cugraph_dev:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       1_gnu    conda-forge
     abseil-cpp                20200225.2           he1b5a44_2    conda-forge
     alabaster                 0.7.12                     py_0    conda-forge
     argon2-cffi               20.1.0           py38h1e0a361_1    conda-forge
     arrow-cpp                 1.0.1           py38h1234567_1_cuda    conda-forge
     arrow-cpp-proc            1.0.1                      cuda    conda-forge
     asvdb                     0.4.0                      py_2    rapidsai
     async_generator           1.10                       py_0    conda-forge
     attrs                     20.2.0             pyh9f0ad1d_0    conda-forge
     aws-sdk-cpp               1.7.164              hba45d7a_2    conda-forge
     babel                     2.8.0                      py_0    conda-forge
     backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
     backports                 1.0                        py_2    conda-forge
     backports.functools_lru_cache 1.6.1                      py_0    conda-forge
     bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
     bokeh                     2.2.1            py38h32f6830_0    conda-forge
     boost                     1.72.0           py38h9de70de_0    conda-forge
     boost-cpp                 1.72.0               h7b93d67_2    conda-forge
     brotli                    1.0.9                he1b5a44_0    conda-forge
     brotlipy                  0.7.0           py38h1e0a361_1000    conda-forge
     bzip2                     1.0.8                h516909a_3    conda-forge
     c-ares                    1.16.1               h516909a_3    conda-forge
     ca-certificates           2020.6.20            hecda079_0    conda-forge
     certifi                   2020.6.20        py38h32f6830_0    conda-forge
     cffi                      1.14.1           py38h5bae8af_0    conda-forge
     chardet                   3.0.4           py38h32f6830_1006    conda-forge
     clang                     8.0.1                hc9558a2_2    conda-forge
     clang-tools               8.0.1                hc9558a2_2    conda-forge
     clangxx                   8.0.1                         2    conda-forge
     click                     7.1.2              pyh9f0ad1d_0    conda-forge
     cloudpickle               1.6.0                      py_0    conda-forge
     cmake                     3.18.2               h5c55442_0    conda-forge
     commonmark                0.9.1                      py_0    conda-forge
     cryptography              3.1              py38h766eaa4_0    conda-forge
     cudatoolkit               11.0.221             h6bb024c_0    nvidia
     cudf                      0.16.0a200910   cuda_11.0_py38_gac39e372d_1619    rapidsai-nightly
     cudnn                     8.0.0                cuda11.0_0    nvidia
     cugraph                   0.16.0a0+384.gbf6c27d3.dirty          pypi_0    pypi
     cupy                      7.8.0            py38hb7c6141_0    rapidsai
     curl                      7.71.1               he644dc0_5    conda-forge
     cython                    0.29.21          py38h950e882_0    conda-forge
     cytoolz                   0.10.1           py38h516909a_0    conda-forge
     dask                      2.25.0                     py_0    conda-forge
     dask-core                 2.25.0                     py_0    conda-forge
     dask-cuda                 0.16.0a200910           py38_86    rapidsai-nightly
     dask-cudf                 0.16.0a200910   py38_gac39e372d_1619    rapidsai-nightly
     decorator                 4.4.2                      py_0    conda-forge
     defusedxml                0.6.0                      py_0    conda-forge
     distributed               2.25.0           py38h32f6830_0    conda-forge
     dlpack                    0.3                  he1b5a44_1    conda-forge
     docutils                  0.16             py38h32f6830_1    conda-forge
     entrypoints               0.3             py38h32f6830_1001    conda-forge
     expat                     2.2.9                he1b5a44_2    conda-forge
     fastavro                  1.0.0.post1      py38h1e0a361_0    conda-forge
     fastrlock                 0.5              py38h950e882_0    conda-forge
     freetype                  2.10.2               he06d7ca_0    conda-forge
     fsspec                    0.8.1                      py_0    conda-forge
     future                    0.18.2           py38h32f6830_1    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     glog                      0.4.0                h49b9bf7_3    conda-forge
     grpc-cpp                  1.30.2               heedbac9_0    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     icu                       67.1                 he1b5a44_0    conda-forge
     idna                      2.10               pyh9f0ad1d_0    conda-forge
     imagesize                 1.2.0                      py_0    conda-forge
     importlib-metadata        1.7.0            py38h32f6830_0    conda-forge
     importlib_metadata        1.7.0                         0    conda-forge
     iniconfig                 1.0.1              pyh9f0ad1d_0    conda-forge
     ipykernel                 5.3.4            py38h23f93f0_0    conda-forge
     ipython                   7.18.1           py38h1cdfbd6_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     jedi                      0.17.2           py38h32f6830_0    conda-forge
     jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
     joblib                    0.16.0                     py_0    conda-forge
     jpeg                      9d                   h516909a_0    conda-forge
     jsonschema                3.2.0            py38h32f6830_1    conda-forge
     jupyter_client            6.1.7                      py_0    conda-forge
     jupyter_core              4.6.3            py38h32f6830_1    conda-forge
     jupyterlab_pygments       0.1.1              pyh9f0ad1d_0    conda-forge
     krb5                      1.17.1               hfafb76e_3    conda-forge
     lcms2                     2.11                 hbd6801e_0    conda-forge
     ld_impl_linux-64          2.34                 hc38a660_9    conda-forge
     libblas                   3.8.0               17_openblas    conda-forge
     libcblas                  3.8.0               17_openblas    conda-forge
     libcudf                   0.16.0a200910   cuda11.0_gac39e372d_1619    rapidsai-nightly
     libcurl                   7.71.1               hcdd3856_5    conda-forge
     libcypher-parser          0.6.2                         1    rapidsai
     libedit                   3.1.20191231         he28a2e2_2    conda-forge
     libev                     4.33                 h516909a_1    conda-forge
     libevent                  2.1.10               hcdb4288_2    conda-forge
     libffi                    3.2.1             he1b5a44_1007    conda-forge
     libgcc-ng                 9.3.0               h24d8f2e_16    conda-forge
     libgfortran-ng            7.5.0               hdf63c60_16    conda-forge
     libgomp                   9.3.0               h24d8f2e_16    conda-forge
     libhwloc                  2.1.0                h3c4fd83_0    conda-forge
     libiconv                  1.16                 h516909a_0    conda-forge
     liblapack                 3.8.0               17_openblas    conda-forge
     libllvm10                 10.0.1               he513fc3_3    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
     libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
     libpng                    1.6.37               hed695b0_2    conda-forge
     libprotobuf               3.12.4               h8b12597_0    conda-forge
     librmm                    0.16.0a200910   cuda11.0_g9d02c5b_365    rapidsai-nightly
     libsodium                 1.0.18               h516909a_0    conda-forge
     libssh2                   1.9.0                hab1572f_5    conda-forge
     libstdcxx-ng              9.3.0               hdf63c60_16    conda-forge
     libtiff                   4.1.0                hc7e4089_6    conda-forge
     libutf8proc               2.5.0                h516909a_2    conda-forge
     libuv                     1.39.0               h516909a_0    conda-forge
     libwebp-base              1.1.0                h516909a_3    conda-forge
     libxml2                   2.9.10               h68273f3_2    conda-forge
     llvmlite                  0.34.0           py38h4f45e52_1    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.9.2                he1b5a44_3    conda-forge
     markdown                  3.2.2                      py_0    conda-forge
     markupsafe                1.1.1            py38h1e0a361_1    conda-forge
     mistune                   0.8.4           py38h1e0a361_1001    conda-forge
     more-itertools            8.5.0                      py_0    conda-forge
     msgpack-python            1.0.0            py38hbf85e49_1    conda-forge
     nbclient                  0.5.0                      py_0    conda-forge
     nbconvert                 6.0.1            py38h32f6830_0    conda-forge
     nbformat                  5.0.7                      py_0    conda-forge
     nbsphinx                  0.7.1              pyh9f0ad1d_0    conda-forge
     nccl                      2.7.8.1              h4962215_0    nvidia
     ncurses                   6.2                  he1b5a44_1    conda-forge
     nest-asyncio              1.4.0                      py_0    conda-forge
     networkx                  2.5                        py_0    conda-forge
     notebook                  6.1.4            py38h32f6830_0    conda-forge
     numba                     0.51.2           py38hc5bc63f_0    conda-forge
     numpy                     1.19.1           py38hbc27379_2    conda-forge
     numpydoc                  1.1.0              pyh9f0ad1d_0    conda-forge
     olefile                   0.46                       py_0    conda-forge
     openssl                   1.1.1g               h516909a_1    conda-forge
     packaging                 20.4               pyh9f0ad1d_0    conda-forge
     pandas                    1.1.2            py38h950e882_0    conda-forge
     pandoc                    2.10.1               h516909a_0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.7.1              pyh9f0ad1d_0    conda-forge
     partd                     1.1.0                      py_0    conda-forge
     pexpect                   4.8.0            py38h32f6830_1    conda-forge
     pickleshare               0.7.5           py38h32f6830_1001    conda-forge
     pillow                    7.2.0            py38h9776b28_1    conda-forge
     pip                       20.2.3                     py_0    conda-forge
     pluggy                    0.13.1           py38h32f6830_2    conda-forge
     prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
     prompt-toolkit            3.0.7                      py_0    conda-forge
     psutil                    5.7.2            py38h1e0a361_0    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     py                        1.9.0              pyh9f0ad1d_0    conda-forge
     py-cpuinfo                7.0.0              pyh9f0ad1d_0    conda-forge
     pyarrow                   1.0.1           py38h1234567_1_cuda    conda-forge
     pycparser                 2.20               pyh9f0ad1d_2    conda-forge
     pygal                     2.4.0                      py_0    conda-forge
     pygments                  2.6.1                      py_0    conda-forge
     pynvml                    8.0.4                      py_1    conda-forge
     pyopenssl                 19.1.0                     py_1    conda-forge
     pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
     pyrsistent                0.17.2           py38h1e0a361_0    conda-forge
     pysocks                   1.7.1            py38h32f6830_1    conda-forge
     pytest                    6.0.1            py38h32f6830_0    conda-forge
     pytest-benchmark          3.2.3              pyh9f0ad1d_0    conda-forge
     python                    3.8.5           h1103e12_7_cpython    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     python-louvain            0.13                       py_0    conda-forge
     python_abi                3.8                      1_cp38    conda-forge
     pytz                      2020.1             pyh9f0ad1d_0    conda-forge
     pyyaml                    5.3.1            py38h1e0a361_0    conda-forge
     pyzmq                     19.0.2           py38ha71036d_0    conda-forge
     rapids-pytest-benchmark   0.0.13                     py_0    rapidsai
     re2                       2020.08.01           he1b5a44_1    conda-forge
     readline                  8.0                  he28a2e2_2    conda-forge
     recommonmark              0.6.0                      py_0    conda-forge
     requests                  2.24.0             pyh9f0ad1d_0    conda-forge
     rhash                     1.3.6             h14c3975_1001    conda-forge
     rmm                       0.16.0a200910   cuda_11.0_py38_g9d02c5b_365    rapidsai-nightly
     scikit-learn              0.23.2           py38hee58b96_0    conda-forge
     scipy                     1.5.2            py38h8c5af15_0    conda-forge
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                49.6.0           py38h32f6830_0    conda-forge
     six                       1.15.0             pyh9f0ad1d_0    conda-forge
     snappy                    1.1.8                he1b5a44_3    conda-forge
     snowballstemmer           2.0.0                      py_0    conda-forge
     sortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forge
     spdlog                    1.7.0                hc9558a2_2    conda-forge
     sphinx                    3.2.1                      py_0    conda-forge
     sphinx-markdown-tables    0.0.14             pyh9f0ad1d_1    conda-forge
     sphinx_rtd_theme          0.5.0              pyh9f0ad1d_0    conda-forge
     sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
     sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
     sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
     sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
     sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
     sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
     sphinxcontrib-websupport  1.2.4              pyh9f0ad1d_0    conda-forge
     sqlite                    3.33.0               h4cf870e_0    conda-forge
     tblib                     1.6.0                      py_0    conda-forge
     terminado                 0.8.3            py38h32f6830_1    conda-forge
     testpath                  0.4.4                      py_0    conda-forge
     threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
     thrift-cpp                0.13.0               h62aa4f2_3    conda-forge
     tk                        8.6.10               hed695b0_0    conda-forge
     toml                      0.10.1             pyh9f0ad1d_0    conda-forge
     toolz                     0.10.0                     py_0    conda-forge
     tornado                   6.0.4            py38h1e0a361_1    conda-forge
     traitlets                 5.0.4                      py_0    conda-forge
     typing_extensions         3.7.4.2                    py_0    conda-forge
     ucx                       1.8.1+g6b29558       ha5db111_0    rapidsai
     ucx-py                    0.16.0a200910+g6b29558        py38_111    rapidsai-nightly
     urllib3                   1.25.10                    py_0    conda-forge
     wcwidth                   0.2.5              pyh9f0ad1d_1    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
     xz                        5.2.5                h516909a_1    conda-forge
     yaml                      0.2.5                h516909a_0    conda-forge
     zeromq                    4.3.2                he1b5a44_3    conda-forge
     zict                      2.0.0                      py_0    conda-forge
     zipp                      3.1.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1009    conda-forge
     zstd                      1.4.5                h6597ccf_2    conda-forge
     
</pre></details>

**Comment by ayushdg** [comment] 2020-09-16 01:17
From what I've noticed: `repartition` doesn't necessarily concat partitions on the workers as is, but also shuffles the data around so that partitions are in order. For example if I have 2GPU's and a total of 6 partitions, after the read parquet step it's likely that the partition distribution may look something like this:
```
GPU0: Partitions from files [df0.parquet, df2.parquet, df4.parquet]
GPU1: Partitions from files [df1.parquet1, df3.parquet, df5.parquet]
```
When repartitioning dask shuffles the data so that the output is like this:
```
GPU0: Partitions from files [df0.parquet, df1.parquet, df2.parquet]
GPU1: Partitions from files [df3.parquet, df4.parquet, df5.parquet]
```
Which involves some memory overhead though I'm not sure if the >6x memory overhead is expected or not.

I'm not sure if this helps your use case but if the partition order doesn't matter and the goal is concatenating all partitions of a persisted dataframe within a worker I have a rough [Gist](https://gist.github.com/ayushdg/caa21ac0af8eaae31d3a518a3ccad595) which does this and should be faster as there are no shuffles. The additional memory overhead here would be the memory required to materialize the int64 index of the dataframe while concatenating. I believe `xgboost.dask` uses a similar concept for concatenating partitions within a worker.


cc: @rjzamora, @quasiben who are more familiar with shuffle/repartitioning and might have thoughts.

**Comment by quasiben** [comment] 2020-09-16 12:32
Hmm, I ran this example with a small modification but on two v100 (32GBs) as was not able to reproduce.  The small modification was adding `rmm`:

```python
cluster = LocalCUDACluster(CUDA_VISIBLE_DEVICES=[0,1],
                           rmm_pool_size='30GB')
```

**Comment by afender** [comment] 2020-09-16 15:00
I still repro after testing this change :( I didn't realize that pool allocation was enabled in this code, is it ON by default?
I was experimenting with this I found that reinitializing RMM : `rmm.reinitialize(pool_allocator=True, initial_pool_size=16000000000, maximum_pool_size=32000000000`)  also has no effect for me.

**Comment by ayushdg** [comment] 2020-09-17 07:25
Update: I was playing around with this example a bit more and noticed a few things that might help: 
> 16GB (100M rows x 2columns x 20 parts x 4bytes )
 
The columns created here are `int64` (8 Byte) columns so the memory usage of the dataset is actually 32GB across both GPUs or 16GB per GPU giving a 3x room for memory overhead.

One of the operations during repartition would be concatenating the dataframes which would materialize an int64 index effectively making the math 48GB (100M rows x 3columns x 20 parts x 8bytes ) or 24GB per GPU. 

Between the 2x memory overhead of concat (aside from index materialization) and shuffling data, the memory may not be enough for a repartition operation.

I also tried downcasting `src` and `dst` to an `int32` dtype resulting in the data taking 16GB across both GPUs and the repartition operation did succeed on 2 48GB cards.


> Hmm, I ran this example with a small modification on two v100 (32GBs) and was not able to reproduce. The small modification was adding rmm

@quasiben I was able to reproduce on 2V100's as well. Did you happen to run this in a Jupyter cell. I noticed a scenario where the Jupyter cell completed successfully without throwing an error but the dask dashboard showed the failed operation. Also any downstream operation like `len(ddf)` triggered the OOM error message in Jupyter.

**Comment by quasiben** [comment] 2020-09-17 15:49
> @quasiben I was able to reproduce on 2V100's as well. Did you happen to run this in a Jupyter cell. I noticed a scenario where the Jupyter cell completed successfully without throwing an error but the dask dashboard showed the failed operation. Also any downstream operation like len(ddf) triggered the OOM error message in Jupyter.

I ran in an ipython session but I started a new session when doing the reading.  Should we expect the write and read to be in a single pass ?

**Comment by ayushdg** [comment] 2020-09-17 17:03
> I ran in an ipython session but I started a new session when doing the reading. Should we expect the write and read to be in a single pass ?

Most of my tests had the read in a separate session (without the write)

**Comment by afender** [comment] 2020-09-17 17:05
Ah yes, it passes in 32 bits for me as well! Thanks, @ayushdg.

I am still surprised that repartition needs so much memory, even in `64bits` we are barely occupying half of the GPU before concatenating. In general, I wouldn't expect a concatenation operation to allocate. 

Also, did you notice that `repartition` is 4x slower than reading? Is this expected?
*** Read Time:  3.1s
*** repartition Time:  12.2 s

**Comment by ayushdg** [comment] 2020-09-17 17:25
>  In general, I wouldn't expect a concatenation operation to allocate.

Perhaps @galipremsagar or @kkraus14 can explain better but IIUC concat is not inplace and I usually see a 2x memory overhead.

> Also, did you notice that repartition is 4x slower than reading?

Yes I saw something similar. Some of the reasoning is in this [comment](https://github.com/rapidsai/cudf/issues/6239#issuecomment-693112687. If you check the dashboard most of the time goes in transferring data between GPUs. With UCX enabled the transfer speed should be significantly lower. 
Meanwhile if partition order doesn't matter, feel free to adapt some of the logic from this [example](https://gist.github.com/ayushdg/caa21ac0af8eaae31d3a518a3ccad595) which concats all partitions within a worker without transfers. Took about ~300ms for this example on my machine.

**Comment by kkraus14** [comment] 2020-09-17 18:46
> Perhaps @galipremsagar or @kkraus14 can explain better but IIUC concat is not inplace and I usually see a 2x memory overhead.

Concatenating each column turns multiple buffers into a single contiguous buffer so it absolutely needs to allocate. Add in string columns which have to track offsets as well and you need to do more than just memory copying too.

**Comment by afender** [comment] 2020-09-17 20:19
Thanks, @ayushdg yea I think we'll concat all partitions within a worker instead of calling repartition. We can catch up with some relabeling later on in graph pipelines. 

What's preventing dask spilling here btw? I was thinking that, in theory, the concatenated buffer could be allocated while parts are temporarily expelled and copied back one by one. Would that make sense?

**Comment by kkraus14** [comment] 2020-09-18 01:47
> What's preventing dask spilling here btw? I was thinking that, in theory, the concatenated buffer could be allocated while parts are temporarily expelled and copied back one by one. Would that make sense?

You'd need to set the `device_memory_limit` parameter when starting the `LocalCUDACluster` in order to indicate when Dask should start spilling the GPU memory.

**Comment by kkraus14** [comment] 2020-09-24 04:02
Closing as this has been answered.

**Closed by kkraus14** 2020-09-24 04:02 UTC
Labels: ? - Needs Triage, bug
