### ISSUE TITLE
[FEA] Add in high level support for arrow ipc

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#5657] opened 2020-07-08 18:38 UTC
**Is your feature request related to a problem? Please describe.**
We have a use case with spark where we want to communicate with an external process using arrow ipc.

In java this uses ` org.apache.arrow.vector.ipc.ArrowStreamReader` and `org.apache.arrow.vector.ipc.ArrowStreamWriter`
In python it uses `pyarrow.RecordBatchStreamWriter` and `pyarrow.ipc.open_stream`

I would like a way to be able to provide a stream of bytes and have it turn into a series of `cudf::Table` instances.  Conversely I would like a way to provide a series of `cudf::Table` instances and write them out to the stream in an efficient way. Preferable with a high level API.

Sadly because the part I am working with is in java I don't have direct access to the file descriptor to do direct I/O with.  Instead I am going to need some kind of layer of abstraction.

**Describe the solution you'd like**
I would love to have an API kind of like the I/O writers and readers.
`write_parquet_chunked_begin`
`write_parquet_chunked`
`write_parquet_chunked_end`

We would also need a read API something like
`read_arrow_chunked_begin`
`read_arrow_chunked_next`
`read_arrow_chunked_end`

**Describe alternatives you've considered**
I could just write it in java to do this, but I am hopeful that this is common enough that others will get some use out of it.

**Comment by kkraus14** [comment] 2020-07-08 18:42
@revans2 just to confirm, would you want to do this with device memory and/or host memory?

cc @trxcllnt @felipeblazing for visibility

**Comment by trxcllnt** [comment] 2020-07-08 18:49
We can use Arrow's own IPC primitives to do host and device reads/writes with minimal effort, but we'll either have to statically link `libarrow.so` into `libcudf.so`, or ship `libarrow.so` with cudf-java. We'll also be pinned to specific versions of libarrow.so, so if the Arrow format changes we'll need to release new versions of libcudf. If all that's acceptable, I don't see any reason not to add this.

**Comment by kkraus14** [comment] 2020-07-08 18:51
> We can use Arrow's own IPC primitives to do host and device reads/writes with minimal effort, but we'll either have to statically link libarrow.so into libcudf.so, or ship libarrow.so with cudf-java.

They're already statically linking libarrow into libcudf.so so we're covered on that front.

> We'll also be pinned to specific versions of libarrow.so, so if the Arrow format changes we'll need to release new versions of libcudf. If all that's acceptable, I don't see any reason not to add this.

We're already version pinned as well, so we should be good on both fronts.

**Comment by revans2** [comment] 2020-07-08 19:00
@kkraus14 
> just to confirm, would you want to do this with device memory and/or host memory?

On the arrow side the formatted data is going to show up on the host, it has to bounce through the JVM heap as part of it.  I am fine with taking a buffer on the GPU and transferring it back to the host.  That is not hard to do and we do it already in other places.

**Comment by kkraus14** [comment] 2020-07-08 20:30
Had an offline discussion with @revans2 and @trxcllnt to iron some things out. Ultimately libcudf shouldn't be responsible for the serialization / deserialization of Arrow host objects, so it was decided that the libcudf APIs should only take `arrow::RecordBatch` or `arrow::Table` as input/output objects and a user should use Arrow APIs to interact with those to accomplish IPC or whatever else they want to do.

Closing this as a duplicate of #1352.

**Closed by kkraus14** 2020-07-08 20:30 UTC
Labels: Spark, feature request, libcudf
