### ISSUE TITLE
[BUG] random row order of df.loc

### ISSUE THREAD

**Issue by daxiongshu** [rapidsai/cudf#3220] opened 2019-10-25 18:51 UTC
**Describe the bug**
`df.loc[ids]` results in random row order. It could lead to wrong results for partial assignments `df.loc[ids, col_A] = df.loc[ids, col_B]`

**Steps/Code to reproduce bug**
```
import cudf as gd
import numpy as np
print(gd.__version__) # 0.10.0
df = gd.DataFrame({'a':np.arange(10000)})
ids = np.arange(1000)
df.loc[ids].head().to_pandas()

    a
576    576
577    577
578    578
579    579
580    580

df.loc[ids].head().to_pandas() # just run it again and the result is different.

    a
992    992
993    993
994    994
995    995
996    996
```

**Expected behavior**
Row order is preserved after `df.loc` operation.

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda

**Environment details**
`conda install -c rapidsai -c nvidia -c conda-forge -c defaults rapids=0.10 python=3.7`

**Comment by shwina** [comment] 2019-10-27 13:41
One way to fix this would be to tack on a column of sequential values at the end of the input column, and then sort by that column after the join to retain ordering.

**Comment by kkraus14** [comment] 2020-03-17 21:45
Closing as duplicate of #4265

**Closed by kkraus14** 2020-03-17 21:45 UTC
Labels: bug, cuDF (Python)
