### ISSUE TITLE
[DOC] 10 Minutes to cuDF and Dask-cuDF out of date

### ISSUE THREAD

**Issue by sophwats** [rapidsai/cudf#10527] opened 2022-03-28 21:39 UTC
10 Minutes to cuDF And Dask-cuDF notebook returns an error when executed 

**Location of incorrect documentation**
Notebook is here in [docs](https://docs.rapids.ai/api/cudf/nightly/user_guide/10min.html)
and here in [git](https://github.com/rapidsai/cudf/blob/branch-22.06/docs/cudf/source/user_guide/10min.ipynb)
**Describe the problems or issues found in the documentation**

1. cell 53 gives a recursion error: `RecursionError: maximum recursion depth exceeded while calling a Python object`
2. cell 65 and 66 give an attribute error: `AttributeError: DataFrame object has no attribute as_matrix`

**Steps taken to verify documentation is incorrect**
cloned the cuDF repo, executed the notebook using `Restart Kernel and Run All Cells` from the `Kernel` menu. 
executing in a 22.04 RAPIDS kernel, built using RAPIDS Release selector tool, with conda and 22.04 (Nightly) on 8th March 2022. 

**Suggested fix for documentation**

to fix 2. above, the `.as_matrix()` in cells 65 and 66 should be replaced by `.as_numpy()`

**Comment by shwina** [comment] 2022-03-29 14:47
@sophwats Thanks for reporting. I addressed (2) in PR #10531, but I couldn't reproduce (1) using the latest build of cuDF 22.04. Perhaps it was fixed in the interim?

**Comment by sophwats** [comment] 2022-03-29 15:21
Agreed - I couldn't reproduce (1) on nightly this morning. Thanks for fixing (2).

**Closed** 2022-03-29 18:57 UTC
Labels: bug, doc, cuDF (Python)
