### ISSUE TITLE
[BUG] Dask-cudf groupby slower with sort=False for specific aggs

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#4117] opened 2020-02-11 01:52 UTC
**Describe the bug**
When performing a dask_cudf groupby with `sort=False` the timings are slower than `sort=True` if:
- Multiple aggregations are performed on the dataframe (any aggregation)
- If `mean` is the aggregation (probably because means results in two aggregations under the hood reducing it to the same condition as the previous point)

**Steps/Code to reproduce bug**
Gist [here](https://gist.github.com/ayushdg/e276b8f3118160c3d9aacaf2b754911c)

**Expected behavior**
`sort=False` should be identical if not faster in timings

**Environment overview (please complete the following information)**
- cudf=0.12 (release)
- dask/dask@2627a7d7fed05d2154758f3675040f6e90f46b40
- dask/distributed@e9cdc9e9c2ac4fb04bb2f9cf79d88a85043d4650

**Additional context**
- For both the multi agg and `mean` case the output with `sort=False` is sorted.

**Comment by rgsl888prabhu** [comment] 2020-05-07 15:03
This might have been resolved with ongoing performance improvement PRs.
```
In [13]:  
    ...: %%timeit 
    ...: x = ddf.groupby(by="a", sort=True).mean() 
    ...: x = x.persist() 
    ...: wait(x) 
    ...: del(x) 
    ...:  
    ...:                                                                                                                                                                                                                         
2.25 s ± 13.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [14]:  
    ...: %%timeit 
    ...: x = ddf.groupby(by="a", sort=False).mean() 
    ...: x = x.persist() 
    ...: wait(x) 
    ...: del(x) 
    ...:  
    ...:                                                                                                                                                                                                                         
1.95 s ± 2.52 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

```

@ayushdg can you please confirm.

**Comment by beckernick** [comment] 2021-06-03 22:50
Has this been resolved? cc @ayushdg

**Comment by beckernick** [comment] 2021-06-18 17:28
I can't reproduce this issue based on the gist. Closing. Please feel free to re-open if you notice similar behavior in the future.

**Closed by beckernick** 2021-06-18 17:28 UTC
Labels: bug, cuDF (Python), dask
