### ISSUE TITLE
[FEA] Clean way to convert object column to CategoricalColumn

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1716] opened 2019-05-13 16:22 UTC
We need a clean way to convert an object column (StringColumn) to a CategoricalColumn. As noted in #1664, this does not appear easy for a user to do without copying the data to pandas and then converting to a categorical column on the CPU.

From an initial look through, it appears to me that this may be a bit messy, as our current CategoricalColumn implementation is coupled to the data as a Buffer, which is currently not the underlying data for StringColumns. Perhaps one approach is for us to make this possible via hashing the StringColumn hidden from the end user.

As a developer, this will allow us to implement things like one hot encoding (`get_dummies` #1063 and also #223 in a general sense) on string columns without going back to the CPU.

**Comment by kkraus14** [comment] 2019-05-13 23:09
Duplicate of #1664

**Closed by kkraus14** 2019-05-13 23:09 UTC
Labels: ? - Needs Triage, feature request
