### ISSUE TITLE
[FEA] `unique()` doesn't guarantee ordering as values are seen and doesn't include `None`

### ISSUE THREAD

**Issue by vivanov10** [rapidsai/cudf#5554] opened 2020-06-23 07:24 UTC
**Is your feature request related to a problem? Please describe.**

`unique()` doesn't guarantee ordering as values are seen and doesn't include `None`

**Describe the solution you'd like**

Adjust the method behavior to be in line with Pandas

**Describe alternatives you've considered**

After the `unique()` call, convert the DataFrame to a `list` and deal with order

**Additional context**

Pandas example:
```python
import pandas as pd
df = pd.DataFrame({'a': [1.0, 1.0, None, 5, 4, 4, 4, 7, 2]})
df['a'].unique() # 5 comes before 2
```
Output:
```array([ 1., nan,  5.,  4.,  7.,  2.])```

cuDF example:
```python
import cudf as pd
df = pd.DataFrame({'a': [1.0, 1.0, None, 5, 4, 4, 4, 7, 2]})
df['a'].unique() # 2 comes before 5
```
Output:
```
0    null
1     1.0
2     2.0
3     4.0
4     5.0
5     7.0
```

**Comment by jrhemstad** [comment] 2020-06-23 12:24
cuDF does not always guarantee the same output order as Pandas. See https://github.com/rapidsai/cudf/issues/1781

Each function should be documented about this behavior. If `unique()` isn't documented to say the order isn't preserved, that will need to be remedied.

**Comment by shwina** [comment] 2020-06-23 16:02
Would be good to document this difference from Pandas and possibly a workaround as well in a `Notes` section of the docstring.

**Comment by vyasr** [comment] 2022-07-23 00:13
I'm going to close this as a duplicate of #1781 to consolidate discussion.

**Closed by vyasr** 2022-07-23 00:13 UTC
Labels: doc, good first issue, cuDF (Python)
