### ISSUE TITLE
[BUG] running small queries on dask-cudf crashes dask-cuda-worker

### ISSUE THREAD

**Issue by robertchristensen** [rapidsai/cudf#2659] opened 2019-08-22 04:49 UTC
**Describe the bug**
Running a dask-cudf cluster and running small operations results in workers being frequently killed by an unknown signal

**Steps/Code to reproduce bug**
I am running the application in a jupyter notebook, but here are the operations which results in the issue:

``` Python
from dask.distributed import Client
from dask_cuda import LocalCUDACluster

# create a local CUDA cluster
#cluster = LocalCUDACluster()
#client = Client(cluster)
client = Client("tcp://10.5.115.44:8786")
client

import cudf
import dask_cudf

df = cudf.DataFrame([('a', list(range(20))),
('b', list(reversed(range(20)))),
('c', list(range(20)))])

df['agg_col1'] = [1 if x % 2 == 0 else 0 for x in range(len(df))]

ddf = dask_cudf.from_cudf(df, npartitions=2)

print(df)

for x in range(1000):
  print(ddf.groupby('agg_col1').sum().compute())
```

The dask-cluster was started using dask-cuda-worker and dask-scheduler.

The for loop repeats 1000 times.  If I watch the logs from the dask-cuda-worker, I see that a worker has crashed and restarted around 250 times.  This also happens when I create a LocalCUDACluster, but it is more easy to view the logs if it it running separately.

The logs from dask-cuda-worker will repeat with a printout similar to this while it is processing the for loop:

```
distributed.nanny - WARNING - Worker process 11863 was killed by unknown signal
distributed.nanny - WARNING - Restarting worker
distributed.preloading - INFO - Import preload module: dask_cuda.initialize_context
distributed.worker - INFO -       Start worker at:    tcp://10.5.115.45:46871
distributed.worker - INFO -          Listening to:    tcp://10.5.115.45:46871
distributed.worker - INFO -          dashboard at:          10.5.115.45:37844
distributed.worker - INFO - Waiting to connect to:     tcp://10.5.115.44:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                         48
distributed.worker - INFO -                Memory:                  162.26 GB
distributed.worker - INFO -       Local Directory: /export/home/rochrist/worker-sndc_0t1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:     tcp://10.5.115.44:8786
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.nanny - WARNING - Worker process 11483 was killed by unknown signal
distributed.nanny - WARNING - Restarting worker
distributed.preloading - INFO - Import preload module: dask_cuda.initialize_context
distributed.worker - INFO -       Start worker at:    tcp://10.5.115.45:45130
distributed.worker - INFO -          Listening to:    tcp://10.5.115.45:45130
distributed.worker - INFO -          dashboard at:          10.5.115.45:41474
distributed.worker - INFO - Waiting to connect to:     tcp://10.5.115.44:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                         48
distributed.worker - INFO -                Memory:                  162.26 GB
distributed.worker - INFO -       Local Directory: /export/home/rochrist/worker-0i67pmby
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:     tcp://10.5.115.44:8786
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.nanny - WARNING - Worker process 12021 was killed by unknown signal
distributed.nanny - WARNING - Restarting worker
distributed.preloading - INFO - Import preload module: dask_cuda.initialize_context
distributed.worker - INFO -       Start worker at:    tcp://10.5.115.45:43110
distributed.worker - INFO -          Listening to:    tcp://10.5.115.45:43110
distributed.worker - INFO -          dashboard at:          10.5.115.45:33259
distributed.worker - INFO - Waiting to connect to:     tcp://10.5.115.44:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                         48
distributed.worker - INFO -                Memory:                  162.26 GB
distributed.worker - INFO -       Local Directory: /export/home/rochrist/worker-amig546_
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:     tcp://10.5.115.44:8786
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
```

Periodically I also see the error `SystemError: null argument to internal routine` in the logs as well.

**Expected behavior**
I would expect that running running this query multiple times would not result in as many failures. 

**Environment overview (please complete the following information)**
I am running this in a bare-metal environment.  I installed cuDF using conda.

**Comment by robertchristensen** [comment] 2019-08-29 23:17
I upgraded to RAPIDS 0.9 and still get the same issue, though it appearance less frequently (about 50 out of 1000 iterations results in one of the dask-cuda-clients restarting).

The nightly build does not seem to be working when I try to build a local dask cuda cluster due to an unrelated issue (I get a type error because it is trying to convert a dictionary to a sequence when it is trying to create a local cuda cluster), so I don't know if it is resolved in the nightly build.

**Comment by kkraus14** [comment] 2019-09-11 19:44
> I upgraded to RAPIDS 0.9 and still get the same issue, though it appearance less frequently (about 50 out of 1000 iterations results in one of the dask-cuda-clients restarting).
> 
> The nightly build does not seem to be working when I try to build a local dask cuda cluster due to an unrelated issue (I get a type error because it is trying to convert a dictionary to a sequence when it is trying to create a local cuda cluster), so I don't know if it is resolved in the nightly build.

The converting a dictionary to a sequence is a known issue that we're working on resolving between distributed and dask-cuda-worker. I'm still completely unable to reproduce this issue with 0.10 nightlies, @randerzander any chance you or someone on your team could try to repro with the 0.9 release?

**Comment by kkraus14** [comment] 2020-01-21 20:52
This has been unable to be reproduced so closing the issue. @robertchristensen if this is still an issue and you have a reproducer please let us know.

**Closed by kkraus14** 2020-01-21 20:52 UTC
Labels: bug, dask
