### ISSUE TITLE
[FEA] Support of StringColumn as numba udf input

### ISSUE THREAD

**Issue by K-Wu** [rapidsai/cudf#7301] opened 2021-02-04 00:40 UTC
**Is your feature request related to a problem? Please describe.**
Currently cuDF does not support StringColumn as numba udf input. But it will be very helpful for my Ph.D. research project to have this so that I can understand the performance comparison between numba regex implementation and what is in cuDF as one initial step.

**Describe the solution you'd like**
It seems to me StringColumn is a consecutive sequence of string metadata, each including the char pointer, its length, etc. I think we can just expose this to the numba user-defined function like other columns. Not sure if there is any pitfalls or infeasibility in this scheme. For example. Can the numba-compiled kernel visit the location the char pointer points to in this way? There is some related comments in the Issues, stating that string operation is prone to performance loss such as branching.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by shwina** [comment] 2021-02-08 21:39
Thanks for raising this issue.

> It seems to me StringColumn is a consecutive sequence of string metadata, each including the char pointer, its length, etc. I think we can just expose this to the numba user-defined function like other columns. N

I think we should clarify this a bit before further discussion,  a `Series` of strings is stored internally as _two_ sequences:

1. A column of character data
2. A column of offsets to the first character of each row (with an additional element storing the total number of characters)

So for example, the series `['a', 'bcd', 'ef']` is stored as the sequences `['a', 'b', 'c', 'd', 'e', 'f']` and `[0, 1, 4, 6]`.

**Comment by K-Wu** [comment] 2021-02-08 22:45
Hi @shwina ,

Thank you for your reply. Thanks for the clarification.

In view of this, will the requested udf functionality work if two columns are interfaced to numba? What will be the issues doing that? For example. The argument handling might be complicated by passing the character data column. Is it possible to pass only the metadata column to numba? I assume this question is equivalent to "Can numba access a device memory region pointed to by a pointer in the device memory that it has access to?"

**Comment by jrhemstad** [comment] 2021-02-08 22:51
Likely duplicate of https://github.com/rapidsai/cudf/issues/3646 and https://github.com/rapidsai/cudf/issues/111

The chief problem with UDFs on strings is intermediate materializations. When users can execute arbitrary string code, that can result in an arbitrary number of temporary string objects, which requires dynamic, device side memory allocation.

**Comment by kkraus14** [comment] 2021-02-16 22:00
Closing as duplicate of #3646

**Closed by kkraus14** 2021-02-16 22:00 UTC
Labels: ? - Needs Triage, feature request
