### ISSUE TITLE
[BUG] AttributeError when calling get_ipc_handle()

### ISSUE THREAD

**Issue by Iroy30** [rapidsai/cudf#4226] opened 2020-02-21 17:02 UTC
**Describe the bug**
Getting ipc handle using df['src']._column.data_array_view.get_ipc_handle() leads to AttributeError

**Steps/Code to reproduce bug**
>>> import cudf
>>> df =cudf.DataFrame()
>>> df['src']=[1,2,3]
>>> df['src']._column.data_array_view.get_ipc_handle()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/iroy/.conda/envs/snmg_pr/lib/python3.7/site-packages/numba/cuda/cudadrv/devicearray.py", line 320, in get_ipc_handle
    ipch = devices.get_context().get_ipc_handle(self.gpu_data)
  File "/home/iroy/.conda/envs/snmg_pr/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 847, in get_ipc_handle
    memory.owner.handle,
AttributeError: 'Buffer' object has no attribute 'handle'

**Comment by kkraus14** [comment] 2020-02-21 18:52
@Iroy30 would suggest raising an issue against Numba as well since this affects them directly outside of just cuDF.

**Comment by kkraus14** [comment] 2020-02-21 18:53
cc @jakirkham since we've chatted about this. Seems like we may just want to ducktype a `handle` attribute to Buffer with the ctypes type that numba expects.

**Comment by Iroy30** [comment] 2020-02-21 19:26
> @Iroy30 would suggest raising an issue against Numba as well since this affects them directly outside of just cuDF.

Meanwhile I'll try ducktyping from cugraph if that works. I believe it expects ctype c_ulong. Thanks for looking into this!

**Comment by kkraus14** [comment] 2020-02-21 19:31
I believe they device an actual type in their `drvapi` module that you can use that grabs it from the system

**Comment by Iroy30** [comment] 2020-02-21 19:32
not sure i understand what you mean

**Comment by kkraus14** [comment] 2020-02-21 20:38
https://github.com/numba/numba/blob/master/numba/cuda/cudadrv/drvapi.py#L12

**Comment by kkraus14** [comment] 2020-03-17 21:07
This is not a bug of cuDF but is a bug of Numba. Suggested raising an issue against Numba offline, so closing this.

**Closed by kkraus14** 2020-03-17 21:07 UTC
Labels: bug, cuDF (Python)

**Comment by jakirkham** [comment] 2020-03-26 09:25
Raised as issue ( https://github.com/numba/numba/issues/5429 ).
