### ISSUE TITLE
Vaex with cupy jitting vs cudf performance

### ISSUE THREAD

**Issue by maartenbreddels** [rapidsai/cudf#2805] opened 2019-09-15 19:41 UTC
Dear DataFrame friends,

Let me elaborate a bit on this tweet:
https://twitter.com/vaex_io/status/1172604096433594371?s=21

What I noticed at first, was the impressive performance of cuspatial(!), ~1ms/1million rows 🚀 . 

But then I saw that the performance using cudf, 13.7ms/1million rows and remembered that we did something very similar with vaex' DataFrame, which is using cupy to do JIT compiling to execute expressions on the GPU.
You can see our results here:
https://www.youtube.com/watch?time_continue=1068&v=2Tt0i823-ec
Which is about 5 seconds/1billion rows, or 5ms/1million rows. This is on an x1 extreme laptop (GTX 1650 GPU if not mistaken).

Is the titan rtx 5x faster than the GTX 1650? If so, then the 13.7ms/1million seems to low for cudf. If the benchmark ran there are valid, and I am not making some obvious mistake, this might reveal a performance issue with cudf.

The repo can be found here in case you want to copy/paste our code:
https://github.com/vaexio/vaex-talks/tree/master/2019-pydata-london

If you want to reproduce it with vaex (, this would be the short version:
```python
# conda install -c conda-forge vaex-core vaex-hdf5  # should work, or just install vaex
import vaex
import numpy as np
df = vaex.open('s3://vaex/taxi/yellow_taxi_2009_2015_f32.hdf5?anon=true')[:500_000_000]
# arc-distance in miles
def arc_distance(theta_1, phi_1, theta_2, phi_2):
    temp = (np.sin((theta_2-theta_1)/2*np.pi/180)**2
           + np.cos(theta_1*np.pi/180)*np.cos(theta_2*np.pi/180) * np.sin((phi_2-phi_1)/2*np.pi/180)**2)
    distance = 2 * np.arctan2(np.sqrt(temp), np.sqrt(1-temp))
    return distance * 3958.8


df['arc_distance_miles_numpy'] = arc_distance(df.pickup_longitude, df.pickup_latitude, 
                                              df.dropoff_longitude, df.dropoff_latitude)
df.nop(df.arc_distance_miles_numpy, progress=True)  # this will be slow, it will fetch
df.nop(df.arc_distance_miles_numpy, progress=True)  # on the cup
df['arc_distance_miles_numba'] = df['arc_distance_miles_numpy'].jit_numba()
# df_train['arc_distance_miles_cuda'] = df_train['arc_distance_miles_numpy'].jit_cuda()
df.nop(df.arc_distance_miles_numba, progress=True) # using numba
# df.nop(df.arc_distance_miles_cuda, progress=True)  # on the gpu
```

Notice that for benchmarking you might want to `df.nop(df.some_expression)` since vaex is lazy in evaluations. Or do a cheap operation like `df.column.sum()` like we do in our talk.
I hope this is useful information.

Regards,

Maarten Breddels - author of vaex - https://github.com/vaexio/vaex

**Comment by kkraus14** [comment] 2019-09-16 15:29
@maartenbreddels thanks for submitting this issue! I've been able to run your above example and I believe reproduce some performance numbers that you were seeing:

Numpy:
```
%%time

# Second run
df['arc_distance_miles_numpy'] = arc_distance(
    df.pickup_longitude,
    df.pickup_latitude, 
    df.dropoff_longitude,
    df.dropoff_latitude
)
df.nop(df.arc_distance_miles_numpy)
```
```
CPU times: user 1min 10s, sys: 9.62 s, total: 1min 19s
Wall time: 4.42 s
```

CPU JIT:
```
%%time

# Second run (with jit)
df['arc_distance_miles_numba'] = df['arc_distance_miles_numpy'].jit_numba()
df.nop(df.arc_distance_miles_numba) # using numba
```
```
CPU times: user 1min 28s, sys: 560 ms, total: 1min 29s
Wall time: 1.4 s
```

GPU JIT:
```
%%time

# Second run (with jit)
df['arc_distance_miles_cuda'] = df['arc_distance_miles_numpy'].jit_cuda()
df.nop(df.arc_distance_miles_cuda)  # on the gpu
```
```
CPU times: user 4.98 s, sys: 1.68 s, total: 6.66 s
Wall time: 1.36 s
```

Do these look correct / reasonable? My method has generally been running once with a `df.nop(..., progress=True)` to make sure the data is memmapped properly, and then run a 2nd time with just a time magic. These results are on a system with dual Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz and a V100 32GB GPU. This also looks to have been against 500 million rows, is that correct?

**Comment by kkraus14** [comment] 2019-09-16 16:54
Just to update with results from my testing thus far, continued with the 500MM row dataset and saw around the same performance for a JIT implementation:
```
from math import sin, cos, sqrt, pi, atan2

def arc_distance_gpu(pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, distance):
    for i, (theta_1, phi_1, theta_2, phi_2) in enumerate(zip(pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude)):
        temp = (sin((theta_2-theta_1)/2*pi/180)**2
               + cos(theta_1*pi/180)*cos(theta_2*pi/180) * sin((phi_2-phi_1)/2*pi/180)**2)
        distance[i] = 2 * atan2(sqrt(temp), sqrt(1-temp)) * 3958.8
```
```
%%time

# Second run
run2 = gdf.apply_rows(
    arc_distance_gpu,
    incols=['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude'],
    outcols=dict(distance=np.float32),
    kwargs=dict()
)
```
```
CPU times: user 796 ms, sys: 516 ms, total: 1.31 s
Wall time: 1.32 s
```

But we're seeing significantly better performance for the cuSpatial implementation, which is to be expected:
```
%%time

# First run -- no JIT overhead
distances = cuspatial.haversine_distance(
    gdf['pickup_longitude'],
    gdf['pickup_latitude'],
    gdf['dropoff_longitude'],
    gdf['dropoff_latitude']
)
```
```
CPU times: user 28 ms, sys: 64 ms, total: 92 ms
Wall time: 90.8 ms
```

I also scaled the dataset down to 50MM rows and saw somewhat linear scaling:
```
CPU times: user 8 ms, sys: 4 ms, total: 12 ms
Wall time: 14.1 ms
```

**Comment by maartenbreddels** [comment] 2019-09-16 17:42
Ah, you include the jitting in the timing here. Could you maybe run this with the jitting done before? Since now it measures the jitting + the evaluation. 

> GPU JIT:
> 
> ```
> %%time
> 
> # Second run (with jit)
> df['arc_distance_miles_cuda'] = df['arc_distance_miles_numpy'].jit_cuda()
> df.nop(df.arc_distance_miles_cuda)  # on the gpu
> ```
> 
> ```
> CPU times: user 4.98 s, sys: 1.68 s, total: 6.66 s
> Wall time: 1.36 s
> ```

That might explain the results, but it would be interesting to see the difference.

Who/what package does the jitting in cudf.apply_rows?, And can cudf do the jitting ahead of time (lets not go into the meaning of jitting now 😄)

**Comment by kkraus14** [comment] 2019-09-16 18:35
> Ah, you include the jitting in the timing here. Could you maybe run this with the jitting done before?

This is the second run so that the JIT kernel is cached at this point. The first run showed the JIT overhead quite a bit:
```
%%time

# First run
df['arc_distance_miles_cuda'] = df['arc_distance_miles_numpy'].jit_cuda()
# df.nop(df.arc_distance_miles_cuda, progress=True)  # on the gpu
df.nop(df.arc_distance_miles_cuda)
```
```
CPU times: user 32.5 s, sys: 6.5 s, total: 39 s
Wall time: 28.1 s
```
==============================
```
%%time

# Second run
df['arc_distance_miles_cuda'] = df['arc_distance_miles_numpy'].jit_cuda()
df.nop(df.arc_distance_miles_cuda)  # on the gpu
```
```
CPU times: user 5.35 s, sys: 5.67 s, total: 11 s
Wall time: 1.52 s
```
==============================
```
%%time

# Third run
df.nop(df.arc_distance_miles_cuda)  # on the gpu
```
```
CPU times: user 5.04 s, sys: 1.4 s, total: 6.44 s
Wall time: 1.39 s
```

**Comment by kkraus14** [comment] 2019-09-16 18:55
> Who/what package does the jitting in cudf.apply_rows?, And can cudf do the jitting ahead of time (lets not go into the meaning of jitting now 😄)

In general most of the JIT compilation in cudf is done via Numba, with the exceptions being certain unary/binaryops where we have a custom codepath with [Jitify](https://github.com/NVIDIA/jitify). Depending on the function, there's certain places we execute directly with numba and other places we take the PTX that Numba generates and inline it at the C++ layer. For `.apply_rows` here it's executed directly with Numba.

**Comment by kkraus14** [comment] 2019-09-16 19:08
So, did some digging, and it turns our `apply_rows` was using a super suboptimal block size of 64. In replacing that configuration with `.forall(len(df))` the performance comes close to `cuSpatial` native performance:
```
%%time

# First run - JIT overhead
run1 = gdf.apply_rows(
    arc_distance_gpu,
    incols=['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude'],
    outcols=dict(distance=np.float32),
    kwargs=dict(),
    pessimistic_nulls=False
)
```
```
CPU times: user 528 ms, sys: 84 ms, total: 612 ms
Wall time: 654 ms
```

```
%%time

# Second run - JIT Cached
run2 = gdf.apply_rows(
    arc_distance_gpu,
    incols=['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude'],
    outcols=dict(distance=np.float32),
    kwargs=dict(),
    pessimistic_nulls=False
)
```
```
CPU times: user 36 ms, sys: 48 ms, total: 84 ms
Wall time: 82 ms
```

Will submit a PR shortly 😄. Still to do: profile vaex to see what's going on under the hood with the JIT cuda path.

**Comment by maartenbreddels** [comment] 2019-09-16 19:31
Great results! That makes more sense to me, cuspatial shouldn't be so much faster for this relative straightforward operations, so that's settled.

The mystery to me is why the 657ms mentioned in that tweet using ~50M rows using cudf, maybe an older version of cudf?

I'd be interested if you can see how vaex is doing since I'm just using cupy as it is, and on top of that it is doing host->gpu->host memory copies (cudf does not). I'm not expecting vaex to outperform cudf because of this, and that's why I was so surprised, but it would be great if you can see what the bottleneck is.

**Comment by kkraus14** [comment] 2019-09-16 20:23
> The mystery to me is why the 657ms mentioned in that tweet using ~50M rows using cudf, maybe an older version of cudf?

Looks to be because of the issue I mentioned above of a bad blocksize setting that I'm throwing in a PR to address. I'd expect it to go to ~50ms afterwards and will ping Tomek to check afterwards.

> I'd be interested if you can see how vaex is doing since I'm just using cupy as it is, and on top of that it is doing host->gpu->host memory copies (cudf does not). I'm not expecting vaex to outperform cudf because of this, and that's why I was so surprised, but it would be great if you can see what the bottleneck is.

Looking into it now and will report back!

**Comment by kkraus14** [comment] 2019-09-17 01:44
> I'd be interested if you can see how vaex is doing since I'm just using cupy as it is, and on top of that it is doing host->gpu->host memory copies (cudf does not). I'm not expecting vaex to outperform cudf because of this, and that's why I was so surprised, but it would be great if you can see what the bottleneck is.

So profiling this at a high level has been tricky due to the threading going on inside of vaex. My guess is that the combination of memory allocation, memory deallocation, and host <--> device transfers are likely your bottleneck as they're nearly always the bottleneck for GPU code. If you have any guidance and how to get a CProfile output per thread or concatenate all the threads into a single profile that would be much appreciated.

On another note, the `cupy.fuse` function is a bit confusing as it doesn't like using numpy functions with a cupy array input or cupy functions with a numpy array input. I'm not sure what the behavior of passing numpy functions and inputs to an `@cupy.fuse` decorated function is unfortunately. @pentschev have you explored this area at all?

**Comment by drabastomek** [comment] 2019-09-17 03:40
Here's also why my results were constantly over 600ms for 42M: my haversine calc method was defined in the same cell as my calculations so every time I run the cell the method was incurring the compilation overhead. Moving the method def to separate cell took care of this. Looking forward to the .forall(...) PR! Thanks Keith and Maarten!

**Comment by pentschev** [comment] 2019-09-17 10:07
> On another note, the cupy.fuse function is a bit confusing as it doesn't like using numpy functions with a cupy array input or cupy functions with a numpy array input. I'm not sure what the behavior of passing numpy functions and inputs to an @cupy.fuse decorated function is unfortunately. @pentschev have you explored this area at all?

I did a bit, yes. It's doing CuPy kernel fusion, so I don't think it's supposed to work on NumPy functions/arrays at all. It's also limited to elementwise and reduction operations. A typical example would be the following:

```python
import cupy as cp

@cp.fuse
def fuse_test(a, b):
    return 2 * (cp.cos(a) + cp.sin(b))

fuse_test(cp.random.random(1000), cp.random.random(1000))
```

While the `fuse_test` is reduced to a single kernel call when wrapped with `@cupy.fuse`, it would instead be 4 kernel calls (`cupy_cos`, `cupy_sin`, `cupy_add`, `cupy_multiply`) if not.

I'm not sure if that answers your question entirely, happy to continue discussing if it doesn't.

**Comment by maartenbreddels** [comment] 2019-09-19 19:01
(I was just typing when I saw your reply coming in.. :))

> So profiling this at a high level has been tricky due to the threading going on inside of vaex. My guess is that the combination of memory allocation, memory deallocation, and host <--> device

I played a bit with for instance not sending back the memory, and it does shave of ~30 % of the time. But work in progress.

> Everything is running within "worker" threads from what I can see and CProfile doesn't see within those threads easily.

If you want to get a hold of the threads: `df.executor.thread_pool._threads` should help (it will only be filled after you do your first computation).

py-spy is a profiler I have mixed results with. found many performance issues with is, but also many false positives.

> Here's also why my results were constantly over 600ms for 42M: my haversine calc method was defined in the same cell as my calculations so every time I run the cell the method was incurring the compilation overhead.

Thanks for clarifying that!

**Comment by kkraus14** [comment] 2019-09-30 18:28
Going to close this issue as we resolved the known performance issues.

**Closed by kkraus14** 2019-09-30 18:28 UTC
Labels: Performance, bug, cuDF (Python)
