### ISSUE TITLE
[BUG] Behavior difference between pandas and cudf on date type

### ISSUE THREAD

**Issue by lazykyama** [rapidsai/cudf#2804] opened 2019-09-15 07:55 UTC
Hi, sorry in advance it's not a bug...

**Describe the bug**

When converting `pandas.DataFrame` including `datetime.date` as an index to `cudf.DataFrame` by `cudf.from_pandas()`, the result dataframe's index becomes `numpy.datetime64`.
It's not consistent behavior.

**Steps/Code to reproduce bug**

```
import datetime

import numpy as np
import pandas as pd

import cudf

basedate = datetime.date(2019, 1, 1)
datelist = [basedate + datetime.timedelta(delta) for delta in range(10)]

df = pd.DataFrame({
        'data': np.random.random((10, 7))
    },
    index=datelist,
    columns=list(range(7))
)
gdf = cudf.from_pandas(df)

print('Pandas.DataFrame: {}'.format(type(df.index[0])))
print('cudf.DataFrame: {}'.format(type(gdf.index[0])))
```

**Expected behavior**

`cudf.from_pandas()` should keep the type of data.
In this case, the index of returned dataframe should be `datetime.date` not `numpy.datetime64`.

**Environment overview (please complete the following information)**

 - Environment location: Docker
 - Method of cuDF install: Docker
   - `sudo nvidia-docker run --rm -it -v /path/to/data:/data -v $(p
wd):/ws -p 18888:8889 nvcr.io/nvidia/rapidsai/rapidsai:0.9-cuda10.0-runtime-ubuntu18.04`

**Environment details**

Modules and OS version are below.

* `cudf`: `0.9.0`
* `numpy`: `1.16.4`
* `pandas`: `0.24.2`

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```

**Additional context**

N/A.

**Comment by kkraus14** [comment] 2019-09-16 14:38
@lazykyama this is intended behavior from cuDF. In pandas if you create an index of `datetime.date` it will be an `object` dtype, which means it's backed by a numpy array of Python objects. This cannot be mirrored on the GPU, so as of now it's getting typecasted to a `datetime64[ms]` (our default datetime resolution as of now), but will be a `date32` type in the future when we support it.

I'm closing this as a wontfix.

**Closed by kkraus14** 2019-09-16 14:38 UTC
Labels: cuDF (Python), invalid, wontfix
