### ISSUE TITLE
`convert_string_to_dtype` in csv_reader is problematic

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1025] opened 2019-02-22 00:29 UTC
This bit of code in the `csv_reader` is problematic https://github.com/rapidsai/cudf/blob/0c7411ce1c75d87d842593e7f92402a67b879c7f/cpp/src/io/csv/csv_reader.cu#L854

It is difficult to maintain because it requires manual updating anytime a new `gdf_dtype` is added. Avoiding things like this is why the `type_dispatcher` was created: https://github.com/rapidsai/cudf/blob/branch-0.6/cpp/src/utilities/type_dispatcher.hpp

I am ignorant to the particulars surrounding this function and why it is needed. It may be the case that a function like this is necessary and unavoidable, however, a lot of thought should be put into if it can be done in such a way that is insulated against manual updating whenever a new `gdf_dtype` is added. 

One question I have is why the type is represented as a string?

**Comment by cwharris** [comment] 2020-09-13 16:41
The utility behind `convert_string_to_dtype` seems to be an artifact of these functions, where we parse column/dtype pairs from strings.

in the csv example `get_dtype_info` calls `convert_string_to_dtype`
https://github.com/rapidsai/cudf/blob/2bc8eb0edfdc2974a17b396f572d9f16f23caf3c/cpp/src/io/csv/reader_impl.cu#L624-L647

https://github.com/rapidsai/cudf/blob/2bc8eb0edfdc2974a17b396f572d9f16f23caf3c/cpp/src/io/json/reader_impl.cu#L476-L499

This sort of thing makes sense at the Python layer, but we should resolve to an `unordered_map` from `string` to `type_id`, before getting in to cpp land. libcdf could provide an overload that accepts `std::vector<type_id>` and deduces/generates the column names if necessary, but I'd prefer to reduce the surface area and let Python handle it.

**Comment by beckernick** [comment] 2021-07-23 18:12
@cwharris @jrhemstad is this still relevant? I no longer see `convertStringToDtype` in the codebase with a [basic search](https://github.com/rapidsai/cudf/search?q=convertStringToDtype&type=)

**Comment by cwharris** [comment] 2021-07-23 18:16
It was renamed to `convert_string_to_dtype`, and the issue is still relevant, but not really worth addressing in-and-of-itself. Eventually we should be able to get more perf out of csv by doing some major updates to it, and that would be the time where this could be addressed simultaneously.

**Comment by cwharris** [comment] 2021-07-23 18:17
@vuule has been discussing replacing type-strings at the python api, so maybe this overlaps with that work as well.

**Comment by vuule** [comment] 2021-07-23 18:31
I believe `convert_string_to_dtype` will be removed as part of https://github.com/rapidsai/cudf/issues/8240. Assigning to myself.

**Comment by beckernick** [comment] 2021-12-06 16:43
@vuule was `convert_string_to_dtype` ultimatel removed in the work done for #8240 ?

**Comment by vuule** [comment] 2021-12-06 18:49
Yes, it was. Closing as `convert_string_to_dtype` is no more.

**Closed by vuule** 2021-12-06 18:49 UTC
Labels: feature request, code quality, cuIO, tech debt
