### ISSUE TITLE
[FEA] Support comparisons on index operations

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#937] opened 2019-02-13 22:09 UTC
It would be nice if the following worked

    df[df.index > 5]

There is a WIP PR with tests for this here: https://github.com/rapidsai/cudf/pull/555

**Comment by kkraus14** [comment] 2019-02-13 22:15
Is this a duplicate of #556?

**Comment by mrocklin** [comment] 2019-02-13 22:17
Ah, indeed it is.

**Closed** 2019-02-13 22:18 UTC
Labels: ? - Needs Triage, dask, feature request
