### ISSUE TITLE
[BUG] Split_out error with Dask_cudf multi column groupby

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#3784] opened 2020-01-15 04:17 UTC
**Describe the bug**
I am unable to use the `split_out` parameter with a multicolumn groupby using Dask_cudf

**Steps/Code to reproduce bug**
```
import cudf
import dask_cudf
import numpy as np

df = cudf.DataFrame({'a':np.arange(100),'b':np.arange(100),'c':np.random.random(100)})
ddf = dask_cudf.from_cudf(df,5)
result = ddf.groupby(["a","b"]).agg({'c':'count'}, split_out=2)
len(result)
```
<details>
<summary> <b>Error stack trace </b></summary>
<pre>
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-69290ace8698> in <module>
----> 1 len(result)

/opt/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in __len__(self)
   3292             return super().__len__()
   3293         else:
-> 3294             return len(s)
   3295 
   3296     def __getitem__(self, key):

/opt/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in __len__(self)
    513     def __len__(self):
    514         return self.reduction(
--> 515             len, np.sum, token="len", meta=int, split_every=False
    516         ).compute()
    517 

/opt/conda/envs/rapids/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    163         dask.base.compute
    164         """
--> 165         (result,) = compute(self, traverse=False, **kwargs)
    166         return result
    167 

/opt/conda/envs/rapids/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    434     keys = [x.__dask_keys__() for x in collections]
    435     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 436     results = schedule(dsk, keys, **kwargs)
    437     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    438 

/opt/conda/envs/rapids/lib/python3.7/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     79         get_id=_thread_get_id,
     80         pack_exception=pack_exception,
---> 81         **kwargs
     82     )
     83 

/opt/conda/envs/rapids/lib/python3.7/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    484                         _execute_task(task, data)  # Re-execute locally
    485                     else:
--> 486                         raise_exception(exc, tb)
    487                 res, worker_id = loads(res_info)
    488                 state["cache"][key] = res

/opt/conda/envs/rapids/lib/python3.7/site-packages/dask/local.py in reraise(exc, tb)
    314     if exc.__traceback__ is not tb:
    315         raise exc.with_traceback(tb)
--> 316     raise exc
    317 
    318 

/opt/conda/envs/rapids/lib/python3.7/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    220     try:
    221         task, data = loads(task_info)
--> 222         result = _execute_task(task, data)
    223         id = get_id()
    224         result = dumps((result, id))

/opt/conda/envs/rapids/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

/opt/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in hash_shard(df, nparts, split_out_setup, split_out_setup_kwargs)
   4579         h = h.values
   4580     h %= nparts
-> 4581     return {i: df.iloc[h == i] for i in range(nparts)}
   4582 
   4583 

/opt/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in <dictcomp>(.0)
   4579         h = h.values
   4580     h %= nparts
-> 4581     return {i: df.iloc[h == i] for i in range(nparts)}
   4582 
   4583 

/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/indexing.py in __getitem__(self, arg)
    101             # tuple arguments into MultiIndex dataframes.
    102             try:
--> 103                 return self._getitem_tuple_arg(arg)
    104             except (TypeError, KeyError, IndexError):
    105                 return self._getitem_tuple_arg((arg, slice(None)))

/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/indexing.py in _getitem_tuple_arg(self, arg)
    289         # Iloc Step 1:
    290         # Gather the columns specified by the second tuple arg
--> 291         columns = self._get_column_selection(arg[1])
    292         if isinstance(self._df.columns, MultiIndex):
    293             columns_df = self._df.columns._get_column_major(self._df, arg[1])

/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/indexing.py in _get_column_selection(self, arg)
    383             return [cols[arg]]
    384         else:
--> 385             return cols[arg]
    386 
    387 

/opt/conda/envs/rapids/lib/python3.7/site-packages/pandas/core/indexes/base.py in __getitem__(self, key)
   3967 
   3968         key = com.values_from_object(key)
-> 3969         result = getitem(key)
   3970         if not is_scalar(result):
   3971             return promote(result)

ValueError: object __array__ method not producing an array
</pre>
</details>

**Expected behavior**
Regular groupby operation

**Environment overview (please complete the following information)**
 - 0.11 stable release docker

**Additional context**
No errors when split_out=1:
`len(ddf.groupby(["a","b"]).agg({'c':'count'}, split_out=1))`
No error when grouping by one column:
`len(ddf.groupby(["a"]).agg({'c':'count'}, split_out=3))`

Unable to test with 0.12 nightlies until the fix for #3717 is merged

**Comment by ayushdg** [comment] 2020-01-15 19:59
Update: As pointed out by @Nanthini10 `result = ddf.groupby(["a","b"]).c.count(split_out=2)` this works. 
Based on the discussion in #3319 it seems that the groupby operation takes a slightly different codepath when using `.agg`. This combined with multi index and `spit_out` probably doesn't go well together.

**Comment by beckernick** [comment] 2020-01-22 17:01
Transferring the other reproducer with a different API from #3854 :

```python
import dask_cudf
import cudf
from distributed import wait

from dask_cuda import LocalCUDACluster
from dask.distributed import Client

cluster = LocalCUDACluster(
    CUDA_VISIBLE_DEVICES="0"
)
client = Client(cluster)

df = cudf.datasets.randomdata(1000, dtypes={f"col{x}":int for x in range(5)})


ddf = dask_cudf.from_cudf(df, 10)
r = ddf.groupby(['col0', 'col1']).mean(split_out=2)
len(r)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-cee1a5c9cbba> in <module>
     16 ddf = dask_cudf.from_cudf(df, 10)
     17 r = ddf.groupby(['col0', 'col1']).mean(split_out=2)
---> 18 len(r)

/opt/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in __len__(self)
   3300             return super().__len__()
   3301         else:
-> 3302             return len(s)
   3303 
   3304     def __getitem__(self, key):

/opt/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in __len__(self)
    521     def __len__(self):
    522         return self.reduction(
--> 523             len, np.sum, token="len", meta=int, split_every=False
    524         ).compute()
    525 

/opt/conda/envs/rapids/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    163         dask.base.compute
    164         """
--> 165         (result,) = compute(self, traverse=False, **kwargs)
    166         return result
    167 

/opt/conda/envs/rapids/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    434     keys = [x.__dask_keys__() for x in collections]
    435     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 436     results = schedule(dsk, keys, **kwargs)
    437     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    438 

/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2574                     should_rejoin = False
   2575             try:
-> 2576                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2577             finally:
   2578                 for f in futures.values():

/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1872                 direct=direct,
   1873                 local_worker=local_worker,
-> 1874                 asynchronous=asynchronous,
   1875             )
   1876 

/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    767         else:
    768             return sync(
--> 769                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    770             )
    771 

/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    333     if error[0]:
    334         typ, exc, tb = error[0]
--> 335         raise exc.with_traceback(tb)
    336     else:
    337         return result[0]

/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils.py in f()
    317             if callback_timeout is not None:
    318                 future = gen.with_timeout(timedelta(seconds=callback_timeout), future)
--> 319             result[0] = yield future
    320         except Exception as exc:
    321             error[0] = sys.exc_info()

/opt/conda/envs/rapids/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1728                             exc = CancelledError(key)
   1729                         else:
-> 1730                             raise exception.with_traceback(traceback)
   1731                         raise exc
   1732                     if errors == "skip":

/opt/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in hash_shard()
   4592         h = h.values
   4593     h %= nparts
-> 4594     return {i: df.iloc[h == i] for i in range(nparts)}
   4595 
   4596 

/opt/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in <dictcomp>()
   4592         h = h.values
   4593     h %= nparts
-> 4594     return {i: df.iloc[h == i] for i in range(nparts)}
   4595 
   4596 

/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/indexing.py in __getitem__()
    106             # tuple arguments into MultiIndex dataframes.
    107             try:
--> 108                 return self._getitem_tuple_arg(arg)
    109             except (TypeError, KeyError, IndexError):
    110                 return self._getitem_tuple_arg((arg, slice(None)))

/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/indexing.py in _getitem_tuple_arg()
    297         # Iloc Step 1:
    298         # Gather the columns specified by the second tuple arg
--> 299         columns = self._get_column_selection(arg[1])
    300         if isinstance(self._df.columns, MultiIndex):
    301             columns_df = self._df.columns._get_column_major(self._df, arg[1])

/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/indexing.py in _get_column_selection()
    401             return [cols[arg]]
    402         else:
--> 403             return cols[arg]
    404 
    405 

/opt/conda/envs/rapids/lib/python3.7/site-packages/pandas/core/indexes/base.py in __getitem__()
   3967 
   3968         key = com.values_from_object(key)
-> 3969         result = getitem(key)
   3970         if not is_scalar(result):
   3971             return promote(result)

ValueError: object __array__ method not producing an array
```

```python
import dask.dataframe as dd
​
df = cudf.datasets.randomdata(1000, dtypes={f"col{x}":int for x in range(5)})
pdf = df.to_pandas()
​
ddf = dd.from_pandas(pdf, 10)
r = ddf.groupby(['col0', 'col1']).mean(split_out=2)
len(r)
949
```

**Comment by rjzamora** [comment] 2020-01-23 18:13
Just started investigating this - Here is a reproducer of what seems to be the root cause...

**Works fine (non-`MultiIndex`)**:
```python
import cudf, cupy

df = cudf.DataFrame(
    {
        "a": [0, 1, 2, 3, 4],
        "b": [0, 1, 2, 3, 4],
        "c": [1, 1, 1, 1, 1],
    }
)
comp = cupy.array([1, 1, 0, 0, 1])
comp_np = cupy.asnumpy(comp)

df.set_index(["a"]).iloc[comp == 0]  # OR: df.set_index(["a"]).iloc[comp_np == 0]
```

**Raises Error with `MultiIndex`**:
```python
df.set_index(["a", "b"]).iloc[comp == 0]  # OR: df.set_index(["a", "b"]).iloc[comp_np == 0]
```

Using a numpy array (`comp_np`) for the indexing results in an `IndexError`:
```
IndexError: index 2 is out of bounds for axis 0 with size 2
```

**Comment by thomcom** [comment] 2020-01-23 18:17
Thanks Rick! #3871 fixes this. :)

**Comment by rjzamora** [comment] 2020-01-23 18:21
> Thanks Rick! #3871 fixes this. :)

Sorry, looks like I had a stale web page up that didn't show recent progress - Thanks!

**Closed** 2020-01-23 19:33 UTC
Labels: bug, cuDF (Python), dask
