### ISSUE TITLE
[FEA]: Implement `DataFrame.<reduction>(axis=None)` by concatenating columns and then calling `<reduction>()`

### ISSUE THREAD

**Issue by mroeschke** [rapidsai/cudf#14930] opened 2024-01-30 00:38 UTC
`cudf.DataFrame.<reduction>(axis=None)` applies the reduction over all values in the DataFrame. Most reductions implement this by calling the reduction over each columns and then calling the reduction over that result. This didn't work for kurtosis and skew because `Column.skew/kurtosis` validates that there's enough samples in the column to calculate a result but cannot check the number of samples in other columns.

`kurtosis` and `skew` therefore concats all valid columns first before calculating the reduction. This method probably generally works for other columns too. To minimize code paths between reductions for `axis=None`, we should probably transitions towards the concat + op method.

**Comment by vyasr** [comment] 2024-02-09 00:08
We should also consider the potential perf implications of this change. The concatenation will require additional memory allocation, which slows things down, but it also allows us to do a single reduction operation. In practice I expect the perf change to be size-dependent: as the number of columns increases we'll get more benefit from the concatenation (especially for small data sizes that don't saturate the GPU in the absence of using multiple streams) whereas as the number of rows increases it might slow things down due to the need for larger allocations and copies.

**Comment by vyasr** [comment] 2024-05-17 20:37
Closing as a duplicate of #12335. I'm a bit confused by this issue since AFAICT we don't support the behavior described here yet, so I don't know what
>  Most reductions implement this by calling the reduction over each columns and then calling the reduction over that result.

is referring to. For example 
```
In [4]: df.sum(axis=None)
/home/coder/cudf/python/cudf/cudf/core/dataframe.py:6197: FutureWarning: In a future version, DataFrame.sum(axis=None) will return a scalar sum over the entire DataFrame. To retain the old behavior, use 'DataFrame.sum(axis=0)' or just '<class 'cudf.core.dataframe.DataFrame'>.sum()'
  warnings.warn(
Out[4]:
a     6
b    15
dtype: int64
```

Maybe @mroeschke is referring to the implementation in pandas? In any case, let's continue discussion on the other issue.

**Closed by vyasr** 2024-05-17 20:37 UTC
Labels: cuDF (Python), improvement
