### ISSUE TITLE
[BUG] Performance regression for read_csv on V100

### ISSUE THREAD

**Issue by calcatoggio** [rapidsai/cudf#12068] opened 2022-11-04 10:22 UTC
Dear Team,

I noticed a performance degradation running the PLAsTiCC challenge (https://www.kaggle.com/c/PLAsTiCC-2018/overview) with the latest Rapids library on Nvidia V100. It seems that the read_csv is taking much longer time.

Do I need to change some parameters ?

Times in seconds:
``` 

                             | readcsv | ETL | train_test_split | ML
Nvidia   V100 | rapids 22.08 | 80.830 | 7.134 | 0.004 | 7.023
Nvidia   V100  | rapids 0.15 | 23.792 | 6.570 | 0.004 | 4.153
```

Running the profiler, I noticed a Cuda memCpy Device to Device using a single device with Rapids 22.08 - unclear why?

![image](https://user-images.githubusercontent.com/117444024/199949586-b10ff443-1e3b-4385-8824-70acaed92800.png)

![image](https://user-images.githubusercontent.com/117444024/199950035-a247094a-5eec-4c3b-a2fe-210b1b636034.png)

Thanks

**Comment by vuule** [comment] 2022-11-04 18:06
Hi @calcatoggio , thank you for submitting the issue.
Could you please share the code that shows the parameters you are passing to `read_csv`?

**Comment by calcatoggio** [comment] 2022-11-04 18:47
Sure, I have the following read_csv, using `import cudf as gd`
```
t0 = timer()
train_gd = gd.read_csv('%s/training_set.csv' % PATH, names=ts_cols, dtype=ts_dtypes, skiprows=1)
test_gd = gd.read_csv('%s/test_set.csv' % PATH, names=ts_cols, dtype=ts_dtypes, skiprows=1 + SKIP_ROWS)
t1 = timer()
# print("Data Loading Part 1:", t1-t0)
t_readcsv += t1 - t0

...

aggs = {'flux': ['skew']}
t_etl_1 = timer()
t0 = timer()
test_gd = cudf_groupby_aggs(test_gd, group_id_col='object_id', aggs=aggs)
train_gd = cudf_groupby_aggs(train_gd, group_id_col='object_id', aggs=aggs)
t_groupby_agg += timer() - t0

...

t0 = timer()
test_gd = gd.read_csv('%s/test_set.csv' % PATH, names=ts_cols, dtype=ts_dtypes,
                      skiprows=1 + SKIP_ROWS)  # skip the header
train_gd = gd.read_csv('%s/training_set.csv' % PATH, names=ts_cols, dtype=ts_dtypes, skiprows=1)
t_readcsv += timer() - t0
```

**Comment by GregoryKimball** [comment] 2022-11-06 17:47
Hello @calcatoggio, thank you for sharing your observations. I took a careful look at the `0.15` and `22.10` versions of `cudf.read_csv` on an `A100` + AMD Epyc + SSD system. I realize this is a bit different from the `V100` and `22,08` condition you tested, but I expect the trends to be consistent. I used a 500 MB file with a mix of string, float and int column types. 

With local SSDs, one important factor on IO benchmarking is the state of the OS cache. In the data below I'm showing timing for the two cuDF versions with and without cache clearing. Where "cache cleared: True" it means that I ran `sudo sysctl vm.drop_caches=3` immediately before the IO timing. As expected, when the OS caches parts of the input csv file, then the runtime is much faster.
![image](https://user-images.githubusercontent.com/12725111/200186216-ce1387c3-0be1-4d4e-a731-ddfe3b6ffe73.png)

* Based on these results I don't observe significant differences between `0.15` and `22.10` csv readers. However the state of the OS cache does have a material impact with ~4x longer read times when the cache is clear. Would you please share more about the data storage you are using for your tests?
* In your original post you described 80s of read_csv time. This is a very long time! Would you please share more about the files you were reading? All of my single GPU benchmarks take <3 seconds.

**Comment by calcatoggio** [comment] 2022-11-07 13:50
Thanks a lot for your insight.
I tried to run it with `sudo sysctl vm.drop_caches=3` and I observed a longer runtime:
![image](https://user-images.githubusercontent.com/117444024/200303720-4c19a7f0-3b23-4dee-b65f-3f5fbf9517ff.png)

Should I try with other parameter to change the IO performance?

We are reading csv of several GBs and it seems to take quite some time!

**Comment by vuule** [comment] 2022-11-08 19:48
What is the value of `SKIP_ROWS` in your code? The `skiprows` parameter tends to impact performance, so I'm trying to understand why it's used here.

**Comment by calcatoggio** [comment] 2022-11-08 23:22
I'm using the following parameters:

GPU_MEMORY = args.gpu_memory
TEST_ROWS = 453653104
OVERHEAD = 1.2
SKIP_ROWS = int((1 - GPU_MEMORY / (32.0 * OVERHEAD)) * TEST_ROWS)

**Comment by vuule** [comment] 2022-11-08 23:38
Do you need to read the exact same number of rows in each call?
If not, using `byte_range` should be much faster because the reader does not need to scan skipped rows to find the first row to read.

**Comment by calcatoggio** [comment] 2022-11-10 11:54
Ok, in the meantime I measured the following time:

RAPIDS 22.10 timer details:
Data Loading Part 1 training: 1.1986182959517464
Data Loading Part 1 test: 41.293686766061

RAPIDS 0.15 timer details:
Data Loading Part 1 training: 1.1835743939736858
Data Loading Part 1 test: 11.474725326057523

using

```
166 if args.timer_on:
167     t0 = timer()
168 train_gd = gd.read_csv('%s/training_set.csv' % PATH, names=ts_cols, dtype=ts_dtypes, skiprows=1)
169 if args.timer_on:
170     t1 = timer()
171 test_gd = gd.read_csv('%s/test_set.csv' % PATH, names=ts_cols, dtype=ts_dtypes, skiprows=1 + SKIP_ROWS)
172 if args.timer_on:
173     t2 = timer()
174 if args.timer_on:
175     print("Data Loading Part 1 training:", t1-t0)
176     print("Data Loading Part 1 test:", t2-t1)

```

```
wc -l training_set.csv = 1421706
wc -l test_set.csv = 453653105
```

`SKIPROWS=264630977`

```
$head PLAsTiCC-data/test_set.csv
object_id,mjd,passband,flux,flux_err,detected
13,59798.3205,2,-1.299735,1.357315,0
13,59798.3281,1,-2.095392,1.148654,0
13,59798.3357,3,-0.923794,1.763655,0
13,59798.3466,4,-4.009815,2.602911,0
13,59798.3576,5,-3.403503,5.367328,0
```

I'm not sure how to explain the difference?

**Comment by GregoryKimball** [comment] 2022-11-14 04:58
Thank you @calcatoggio for sharing some additional details. It seems that the performance issue could be related to very large numbers of SKIPROWS.. 264 million in this case! I'll take a closer look at this type of case. Thank you also for sharing the snippet of the test file.

**Comment by GregoryKimball** [comment] 2022-11-20 21:28
@calcatoggio I did some follow-up investigation here with synthetic data and could not reproduce a performance regresssion in `read_csv`. My experiment read 200 MB chunks of a 2 GB csv file either by using `skiprows/nrows` or `byte_range`. We find that `skiprows/nrows` takes longer when you are reading the end of a file due to extra row processing, and both `0.15` and `22.12` show similar performance. As @vuule suggested, you can also use the `byte_range` parameter to achieve much faster read speeds. 
![image](https://user-images.githubusercontent.com/12725111/202927041-105b6aec-5ab4-4ff8-806f-d78206001892.png)
I intend to take a look at the "PLAsTiCC" data you are working with, but in the meantime I would encourage you to verify that the OS cache is cleared before each read_csv operation and also to experiment with the `byte_range` parameter.

**Comment by GregoryKimball** [comment] 2022-11-21 04:00
I downloaded the 19 GB `test_set.csv` file for "PLAsTiCC" from Kaggle and benchmarked some reading times with large values of `skiprows`.

The file has 453M rows. Reading it with `skiprows` of 260M showed loading times of:
* cuDF version `0.15`: 5.8, 5.5, 6.1s
* cuDF version `22.12`: 7.1, 7.2, 7.1s

So far I have not been able to reproduce the 4x performance regression that was reported. Please let me know if you are still observing an issue.

**Comment by calcatoggio** [comment] 2022-11-21 16:17
Thanks a lot for your help and the performance numbers, I will try again with the OS cache.

I will let you know if I still see the 4x performance regression.

**Comment by GregoryKimball** [comment] 2023-02-01 23:48
Closing for now, please feel free to raise another issue if you see evidence of poor CSV read performance!

**Closed by GregoryKimball** 2023-02-01 23:48 UTC
Labels: bug, 4 - Waiting on Author, cuIO, Performance
