### ISSUE TITLE
[BUG] CHANGELOG.md should not be based on yet-to-exist PR's

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#891] opened 2019-02-07 14:22 UTC
If you fix some issue or add some feature to cudf, and you create a PR for your changes - the **PR is guaranteed to be auto-rejected**. Why? Well, you need to add a `CHANGELOG.md` entry describing your changes; and these entries need to mention the PR's which introduces the change.

This is a Catch-22 situation - almost; we get around it by updating the committed code with a change to the `CHANGLOG.md` entry. But that is quite unwieldy.

There should be some mechanism for avoiding this can-never-be-accepted-as-is situation with PRs. Perhaps refer to issue numbers?

**Comment by jrhemstad** [comment] 2019-02-07 14:26
I see this as a feature, not a bug. It forces you to make sure you've updated the CHANGELOG.md before your PR can be accepted.

But it seems that your concern is about you can't update the CHANGELOG correctly until you've already submitted the PR (because you don't know what the PR# is). 

Personally, I never remember to update the CHANGELOG until I see that CI has failed on my PR anyways, so I don't find this to be an issue.

**Comment by eyalroz** [comment] 2019-02-07 16:32
If it is impossible to submit a valid PR until an invalid PR has been rejected - that's a bug... I realize it might not bother some people that much, or at all, but this shouldn't be the case. Changelogs should avoid reference to development support system artifacts anyway, unless absolutely necessary. IMHO.

**Comment by harrism** [comment] 2019-02-07 21:55
I don't see it as a bug. The feature is working as designed -- 30-60 seconds of developer time for each PR prevents our incredibly busy devops team from having to comb through PRs on release day to update the CHANGELOG. I don't think it hurts anyone to have a briefly invalid PR.

**Comment by harrism** [comment] 2019-02-07 22:06
I'm going to close this. I think it's useful to have references to the actual changes in the changelog.

**Closed by harrism** 2019-02-07 22:06 UTC
Labels: ? - Needs Triage, bug
