### ISSUE TITLE
[QST] How to Install/Build CuDf using PyArrow 3.0.0?

### ISSUE THREAD

**Issue by ziongh** [rapidsai/cudf#7596] opened 2021-03-15 02:18 UTC
I'm trying to use the newer version of Apache Arrow (3.0.0), because some libraries depend on it (vaex 4.0.0). And it would allow sharing data between Cudf and Vaex, and possible more libraries.

Is there any possible way to build it, or install it with arrow 3?

Thanks in advance

**Comment by kkraus14** [comment] 2021-03-26 21:04
Closing as duplicate of #7224

**Closed by kkraus14** 2021-03-26 21:04 UTC
Labels: ? - Needs Triage, question
