### ISSUE TITLE
Different behavior when applying functions on groupby objects using method 'sort' vs 'pygdf'

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#205] opened 2018-08-17 00:46 UTC
## Reporting a bug

- [X] I am using the latest version of PyGDF ~~from conda or~~ built from `master`.
- [X] I have included the following environment details:
      Linux Distro: Ubuntu 16.04, Linux Kernel: Linux 4.15.0-29-generic x86_64 , GPU Model: TITAN V
- [ ] I have included the following version information for:
      Arrow, CUDA,Numpy, Pandas, Python
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```
import numpy as np
import pygdf
from pygdf.dataframe import DataFrame

gdf = DataFrame()
gdf['f0'] = []
gdf['f1'] = []

record = np.array([(2,3),(2,3),(4,5)], dtype = np.dtype('f8,f8'))
new_gdf = DataFrame.from_records(record)
print('Method Pygdf')
print(new_gdf.groupby(['f0','f1'],method = 'pygdf').min())
print('\nMethod Sort')
new_gdf.groupby(['f0','f1'],method='sort').min()
```
Output:
```
Method Pygdf
    f0   f1
0  2.0  3.0
1  4.0  5.0

Method Sort
<pygdf.DataFrame ncols=0 nrows=0 >
```
The issue is only reproducible if `groupby` is performed on all the columns in the dataframe.
If not applied to all the columns of the dataframe, the outputs have different column names.
```
import numpy as np
import pygdf
from pygdf.dataframe import DataFrame

gdf = DataFrame()
gdf['f0'] = []
gdf['f1'] = []

record = np.array([(2,3),(2,3),(4,5)], dtype = np.dtype('f8,f8'))
new_gdf = DataFrame.from_records(record)
print('Method Pygdf')
print(new_gdf.groupby(['f0'],method = 'pygdf').min())
print('\nMethod Sort')
print(new_gdf.groupby(['f0'],method='sort').min())
```
Output:
```
Method Pygdf
    f0   f1
0  2.0  3.0
1  4.0  5.0

Method Sort
    f0 min_f1
0  2.0    3.0
1  4.0    5.0
```

**Comment by kkraus14** [comment] 2018-12-10 21:42
Closing as not a bug.

**Closed by kkraus14** 2018-12-10 21:42 UTC
Labels: bug
