### ISSUE TITLE
[BUG] Unable to install with CONDA

### ISSUE THREAD

**Issue by ValeryPolyakov** [rapidsai/cudf#2883] opened 2019-09-27 16:20 UTC
I am unable to install the package using conda:

conda install -c nvidia -c rapidsai -c numba -c conda-forge -c defaults cudf=0.8 python=3.6 cudatoolkit=10.0

Below is the message:

Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - cudf=0.8

Current channels:

  - https://conda.anaconda.org/nvidia/win-64
  - https://conda.anaconda.org/nvidia/noarch
  - https://conda.anaconda.org/rapidsai/win-64
  - https://conda.anaconda.org/rapidsai/noarch
  - https://conda.anaconda.org/numba/win-64
  - https://conda.anaconda.org/numba/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
  - https://conda.anaconda.org/bioconda/win-64
  - https://conda.anaconda.org/bioconda/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by ivenzor** [comment] 2019-09-30 16:33
I can't replicate your error. I executed the same command I conda was able to find the packages.

**Comment by ValeryPolyakov** [comment] 2019-09-30 20:48
Which channel are you using? Is it on the list above that I reported?

**Comment by ivenzor** [comment] 2019-09-30 21:02
I created a new 3.6 conda env and executed the same command you posted. cuDF got installed with no problems.

**Comment by j-ieong** [comment] 2019-09-30 21:59
Are you trying to install on Windows? Looks like it's searching through for those packages. Windows is currently unsupported.

**Comment by kkraus14** [comment] 2019-09-30 22:02
Closing as this is a duplicate of #28, we have no current plans to support Windows.

**Closed by kkraus14** 2019-09-30 22:02 UTC
Labels: conda, invalid

**Comment by ValeryPolyakov** [comment] 2019-09-30 22:04
I am not sure what to say. Still does not work for me. I am doing it on Windows, though.
