### ISSUE TITLE
[FEA] JNI: Support creating a null list scalar with the correct nested empty column inside.

### ISSUE THREAD

**Issue by firestarman** [rapidsai/cudf#8170] opened 2021-05-06 01:25 UTC
Besides setting the validity flag to `false`, we still need to create an empty column with the correct children for it, instead of the default column created by cpp.

**Comment by jlowe** [comment] 2021-05-06 15:21
Duplicate of #8140?

**Closed** 2021-05-08 00:55 UTC
Labels: Spark, cuDF (Java), feature request
