### ISSUE TITLE
[BUG] Discrepancy in how cudf.pandas and regular pandas saves list of str

### ISSUE THREAD

**Issue by qsimeon** [rapidsai/cudf#14547] opened 2023-12-03 23:56 UTC
Regular pandas:
```
import os
import ast

# try:
#     import cudf.pandas

#     cudf.pandas.install()
# except:
#     pass
import pandas as pd

# Example list of lists
data = {
    "Col1": ["Item1", "Item2", "Item3"],
    "NumberCol": [1, 2, 3],
    "ListCol": [
        [f"ABC{i}" for i in range(1, 400)],
        [f"ABC{i}" for i in range(1, 300)],
        [f"ABC{i}" for i in range(1, 500)],
    ],
    "TestCol": ["Test1", "Test2", "Test3"],
}

# Create DataFrame
df = pd.DataFrame(data)

# Show the DataFrame
print(df)

# Save to CSV
df.to_csv("list_data.csv", index=True, header=True)

# Read from CSV safely
df_loaded = pd.read_csv(
    os.path.join("list_data.csv"), converters={"ListCol": ast.literal_eval}
)

print("\ndf_loaded:\n", df_loaded)
print()
print("\ndf_loaded['ListCol']:\n", df_loaded["ListCol"])
print()
print("\npd.__version__:", pd.__version__)
```

Output
```
    Col1  NumberCol                                            ListCol TestCol
0  Item1          1  [ABC1, ABC2, ABC3, ABC4, ABC5, ABC6, ABC7, ABC...   Test1
1  Item2          2  [ABC1, ABC2, ABC3, ABC4, ABC5, ABC6, ABC7, ABC...   Test2
2  Item3          3  [ABC1, ABC2, ABC3, ABC4, ABC5, ABC6, ABC7, ABC...   Test3

df_loaded:
    Unnamed: 0   Col1  NumberCol  \
0           0  Item1          1   
1           1  Item2          2   
2           2  Item3          3   

                                             ListCol TestCol  
0  [ABC1, ABC2, ABC3, ABC4, ABC5, ABC6, ABC7, ABC...   Test1  
1  [ABC1, ABC2, ABC3, ABC4, ABC5, ABC6, ABC7, ABC...   Test2  
2  [ABC1, ABC2, ABC3, ABC4, ABC5, ABC6, ABC7, ABC...   Test3  


df_loaded['ListCol']:
 0    [ABC1, ABC2, ABC3, ABC4, ABC5, ABC6, ABC7, ABC...
1    [ABC1, ABC2, ABC3, ABC4, ABC5, ABC6, ABC7, ABC...
2    [ABC1, ABC2, ABC3, ABC4, ABC5, ABC6, ABC7, ABC...
Name: ListCol, dtype: object


pd <module 'pandas' from '/om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.10/site-packages/pandas/__init__.py'>; pd.__version__: 1.5.0
```

Now when I use cudf.pandas:
```
import os
import ast

try:
    import cudf.pandas

    cudf.pandas.install()
except:
    pass
import pandas as pd

# Example list of lists
data = {
    "Col1": ["Item1", "Item2", "Item3"],
    "NumberCol": [1, 2, 3],
    "ListCol": [
        [f"ABC{i}" for i in range(1, 400)],
        [f"ABC{i}" for i in range(1, 300)],
        [f"ABC{i}" for i in range(1, 500)],
    ],
    "TestCol": ["Test1", "Test2", "Test3"],
}

# Create DataFrame
df = pd.DataFrame(data)

# Show the DataFrame
print(df)

# Save to CSV
df.to_csv("list_data.csv", index=True, header=True)

# Read from CSV safely
df_loaded = pd.read_csv(
    os.path.join("list_data.csv"), converters={"ListCol": ast.literal_eval}
)

print("\ndf_loaded:\n", df_loaded)
print()
print("\ndf_loaded['ListCol']:\n", df_loaded["ListCol"])
print()
print("\npd {pd}; pd.__version__: {pd.__version__}")
```

Output:
```
    Col1  NumberCol                                            ListCol TestCol
0  Item1          1  [ABC1, ABC2, ABC3, ABC4, ABC5, ABC6, ABC7, ABC...   Test1
1  Item2          2  [ABC1, ABC2, ABC3, ABC4, ABC5, ABC6, ABC7, ABC...   Test2
2  Item3          3  [ABC1, ABC2, ABC3, ABC4, ABC5, ABC6, ABC7, ABC...   Test3

df_loaded:
    Unnamed: 0   Col1  NumberCol  \
0           0  Item1          1   
1           1  Item2          2   
2           2  Item3          3   

                                             ListCol TestCol  
0  [ABC1ABC2ABC3ABC4ABC5ABC6ABC7ABC8ABC9ABC10ABC1...   Test1  
1  [ABC1ABC2ABC3ABC4ABC5ABC6ABC7ABC8ABC9ABC10ABC1...   Test2  
2  [ABC1ABC2ABC3ABC4ABC5ABC6ABC7ABC8ABC9ABC10ABC1...   Test3  


df_loaded['ListCol']:
 0    [ABC1ABC2ABC3ABC4ABC5ABC6ABC7ABC8ABC9ABC10ABC1...
1    [ABC1ABC2ABC3ABC4ABC5ABC6ABC7ABC8ABC9ABC10ABC1...
2    [ABC1ABC2ABC3ABC4ABC5ABC6ABC7ABC8ABC9ABC10ABC1...
Name: ListCol, dtype: list

pd <module 'pandas' (ModuleAccelerator(fast=cudf, slow=pandas))>; pd.__version__: 1.5.0
```

I spent so long debugging this thinking it was a problem from having downgrade to pandas==1.5 (see my other issue). Please please fix this.

**Comment by qsimeon** [comment] 2023-12-04 00:06
I just noticed that if I don't use `ast.literal_eval` as a converter it seems like it does the right thing:
```
import os
import ast

try:
    import cudf.pandas

    cudf.pandas.install()
except:
    pass
import pandas as pd

# Example list of lists
data = {
    "Col1": ["Item1", "Item2", "Item3"],
    "NumberCol": [1, 2, 3],
    "ListCol": [
        [f"ABC{i}" for i in range(1, 400)],
        [f"ABC{i}" for i in range(1, 300)],
        [f"ABC{i}" for i in range(1, 500)],
    ],
    "TestCol": ["Test1", "Test2", "Test3"],
}

# Create DataFrame
df = pd.DataFrame(data)

# Show the DataFrame
print(df)

# Save to CSV
df.to_csv("list_data.csv", index=True, header=True)

# Read from CSV safely
df_loaded = pd.read_csv(
    os.path.join("list_data.csv")  # , converters={"ListCol": ast.literal_eval}
)

print("\ndf_loaded:\n", df_loaded)
print()
print("\ndf_loaded['ListCol']:\n", df_loaded["ListCol"])
print()
print(f"\npd {pd}; pd.__version__: {pd.__version__}")
```

I will try this with my main code as a quick fix for now, but an explanation for this strange behavior of `cudf.pandas` would be helpful in the documentation.

**Comment by wence-** [comment] 2023-12-05 12:31
Thanks for the report! I think this is a bug in cudf. Let me distil into a more minimal example that shows the underlying problem. What is going on here is that cudf cannot write columns with lists to CSV files directly. So we convert the on-device dataframe to pandas and then call `to_csv` on that pandas frame.

It seems like that should work fine:

```
import cudf
import pandas as pd

s = cudf.Series([["abc", "def"]])
print(s)
# 0    [abc, def]
# dtype: list

converted = s.to_pandas()
print(converted)
# 0    [abc, def]
# dtype: object

p = pd.Series([["abc", "def"]])
print(p)
# 0    [abc, def]
# dtype: object
```

Note the different dtype, since cudf implements list columns specially, rather than just a column of python objects.

This seems to look fine, since it looks like (from printing) that there is no difference between the `converted` series, and the "pandas-native" one `p`. However, if we inspect the first element of that series, we see a difference:

```
converted.values[0]
# array(['abc', 'def'], dtype=object)
p.values[0]
# ['abc', 'def']
```

So the converted series contains an array of numpy `array` objects, whereas the native series contains `list` objects. And now the problem occurs, because _printing_ the array object elides commas:

```
print(converted.values[0])
# ['abc' 'def']
#       ^--- No comma!
print(p.values[0])
# ['abc', 'def']
```

So, since the `to_csv` call just prints the contents with `str` (effectively), in the converted case we lose the comma and so the round-trip doesn't work.

We will need to fix this on the cudf side (so that round-tripping like this is possible).

In the interim, are you tied to CSV files? If you use parquet files instead (which have higher performance for read/write too) there's no such issue.

**Comment by wence-** [comment] 2023-12-05 12:46
Reported the underlying problem as #14568

**Comment by bdice** [comment] 2024-03-04 13:58
I'm going to close this and let #14568 be the primary issue for this topic, now that we know the root cause.

**Closed by bdice** 2024-03-04 13:58 UTC
Labels: bug
