### ISSUE TITLE
[DOC] Need complete Doxygen coverage of external libcudf APIs 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#699] opened 2019-01-15 21:48 UTC
Only some of the external APIs have Doxygen documentation. At minimum we need Doxygen documention for the APIs in `functions.h` and `io_functions.h`.

**Comment by harrism** [comment] 2019-02-12 20:53
Duplicate of #697

**Closed by harrism** 2019-02-12 20:53 UTC
Labels: doc
