### ISSUE TITLE
Require streams in public API for groupby aggregate.

### ISSUE THREAD

**Issue by bdice** [rapidsai/cudf#13737] opened 2023-07-24 18:25 UTC
In #13727, we added a public API accepting a stream while retaining the old overload that does not accept a stream. We are migrating to requiring streams in public APIs, so the old overload without a stream should be removed. We decided to accept this for 23.08 (during burndown) with the intent to fix in 23.10.

cc: @mythrocks @vyasr

**Comment by vyasr** [comment] 2023-07-24 20:17
The title here sounds like a duplicate of #11463, but I think the work here is a subset of that (a single API, and just a removal of the old API).

**Comment by davidwendt** [comment] 2024-12-13 20:27
Closed by https://github.com/rapidsai/cudf/pull/17324

**Closed by davidwendt** 2024-12-13 20:27 UTC
Labels: good first issue
