### ISSUE TITLE
[FEA] memory_usage

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#1937] opened 2019-06-06 12:35 UTC
It would be quite helpful to see the resource consumption of a cuDF object.  Pandas has `memory_usage`  which can be used like the following:

```python
In [40]: import pandas as pd

In [41]: df = pd.DataFrame({'a': range(1000)})

In [42]: df.memory_usage()
Out[42]:
Index      80
a        8000
dtype: int64
```

cuDF could do something similar:

```python

def memory_usage(self...)
    _data = self.as_gpu_matrix()
    return _data.alloc_size
```

Note `alloc_size` isn't quite right and we should instead use `nbytes` but I don't think numba has done a release with this feature:

https://github.com/numba/numba/blob/1360c4bb2a2ae1ea0726d9cdd4782b9dfd9ab198/numba/cuda/cudadrv/devicearray.py#L334-L339

cc @pentschev

**Comment by quasiben** [comment] 2019-06-06 22:05
@harrism noted that this information is already available with `sizeof`

> cudf.[DataFrame,Series,Index].__sizeof__()

**Comment by pentschev** [comment] 2019-06-07 13:00
Actually I now found a case where memory doesn't seem to match, here's a snippet for that:

```python
import cudf
import dask_cudf
from numba import cuda

rows = int(1e6)

free_before = cuda.current_context().get_memory_info()[0]
df = cudf.DataFrame([('A', [8] * rows), ('B', [32] * rows)])
free_after = cuda.current_context().get_memory_info()[0]
print("df size:          ", free_before - free_after)
print("df __sizeof__():  ", df.__sizeof__())

free_before = cuda.current_context().get_memory_info()[0]
cdf = dask_cudf.from_cudf(df, npartitions=16)
free_after = cuda.current_context().get_memory_info()[0]
print("cdf size:         ", free_before - free_after)
print("cdf __sizeof__(): ", sum(p.compute().__sizeof__() for p in cdf.partitions))
print("cdf alloc_size:   ", sum(p.compute().as_gpu_matrix().alloc_size for p in cdf.partitions))
```

The result I get:

```
df size:           25165824
df __sizeof__():   16000064
cdf size:          25165824
cdf __sizeof__():  32000000
cdf alloc_size:    16000000
```

It seems that `__sizeof__()` and `alloc_size` don't agree with each other, and both disagree with the actual memory being allocated? Of course, memory would not be _exact_, but it seems to take around 240MB, right in between both?

**Comment by jangorecki** [comment] 2019-08-25 12:13
Duplicate of #632

**Comment by rjzamora** [comment] 2019-12-13 19:16
Where are we stand on this @pentschev ?  Can we use `__sizeof__()` to implement `memory_usage()`?

I would like to use/test the [`partition_size`](https://github.com/dask/dask/blob/94c6b16581828c3fb6c31f1af6d795e7cb02f54c/dask/dataframe/core.py#L1069) argument in Dask's `repartition` method to avoid executing large `merge`/`set_index` operations with small/unbalanced partitions.  For this option, Dask assumes it can call `memory_usage` (which is not supported in cudf).

We can currently repartition the dataset by specifying the number of partitions or the exact divisions we want.  Using the `npartitions` option doesn't guarentee that the resulting partitions will be balanced.  Using `divisions` can work in some cases, but specifying a target partition size would be easiest for the user by far.

**Comment by pentschev** [comment] 2019-12-13 20:04
> Where do we stand on this @pentschev ? Can we use __sizeof__() to implement memory_usage()?

Yes, `__sizeof__` today will return actual device memory since https://github.com/rapidsai/cudf/pull/1967.

**Comment by rjzamora** [comment] 2019-12-13 20:11
> Yes, __sizeof__ today will return actual device memory since #1967.
Great - Thanks @pentschev !

**Comment by VibhuJawa** [comment] 2019-12-14 04:53
@rjzamora , I think we need to fix this too for memory usage. 
https://github.com/rapidsai/cudf/issues/3611

**Comment by rjzamora** [comment] 2019-12-14 05:24
> Edit: Sorry missed that @rjzamora you all ready are tracking the issue. Closing it. Oops

Sorry - I should have shared more clearly/widely when I realized the string problem :/

**Closed** 2019-12-17 14:54 UTC
Labels: cuDF (Python), feature request
