### ISSUE TITLE
CSV file can not run in GPU

### ISSUE THREAD

**Issue by bibek376** [rapidsai/cudf#15106] opened 2024-02-21 15:42 UTC
This issue template is intended to be used primarily for requests related to pandas accelerator mode. If you'd like to file a general cuDF feature request, please [click here](https://github.com/rapidsai/cudf/issues/new?assignees=&labels=%3F+-+Needs+Triage%2C+feature+request&projects=&template=feature_request.md&title=%5BFEA%5D).

**Missing Pandas Feature Request**
A clear and concise summary of the pandas function(s) you'd like to be able run with cuDF.

**Profiler Output**
If you used the profiler in pandas accelerator mode, please provide the full output of your profiling report.

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by shwina** [comment] 2024-02-21 15:53
Hi @bibek376 - thanks for raising this issue! Do you happen to have a code example that reproduces the issue you are seeing?

**Comment by vyasr** [comment] 2024-05-17 20:29
I'm going to close this since we don't have much to go on here, but feel free to reopen if you have further questions.

**Closed by vyasr** 2024-05-17 20:29 UTC
Labels: feature request, cuDF (Python)
