### ISSUE TITLE
[DOC] `10 Minutes to cuDF And Dask-cuDF` notebook shows jitify warning

### ISSUE THREAD

**Issue by nicbor** [rapidsai/cudf#14676] opened 2023-12-27 21:30 UTC
## Report incorrect documentation

**Location of incorrect documentation**
Notebook is here in [docs](https://docs.rapids.ai/api/cudf/stable/user_guide/10min/) and [nightly docs](https://docs.rapids.ai/api/cudf/nightly/user_guide/10min/)
and here in [git](https://github.com/rapidsai/cudf/blob/branch-24.02/docs/cudf/source/user_guide/10min.ipynb), apparently around cell 3. Though the github ui doesn't show these warnings, but the published docs do perhaps they're already fixed?

Side note: I notice a similar message in [cuml docs](https://docs.rapids.ai/api/cuml/stable/estimator_intro/#Random-Forest-Classification-and-Accuracy-metrics)

**Describe the problems or issues found in the documentation**
The warnings 
```
../../thread/thread_load.cuh(36): warning: cuda.h: [jitify] File not found
../../thread/thread_store.cuh(36): warning: cuda.h: [jitify] File not found
```
show up in the documentation.

**Steps taken to verify documentation is incorrect**
n/a

**Suggested fix for documentation**
If these warnings are not a concern, it would be good to at least add a footnote mentioning this, to reassure new cudf users.

A minor comment, but I hope it helps!

**Comment by bdice** [comment] 2024-03-04 19:17
This is still needed -- it's a duplicate of #12630, so I'll close this issue in favor of the other one.

**Closed by bdice** 2024-03-04 19:17 UTC
Labels: doc
