### ISSUE TITLE
[FEA] S3 parquet and csv reads

### ISSUE THREAD

**Issue by ivenzor** [rapidsai/cudf#2799] opened 2019-09-13 20:36 UTC
I'm trying to use rapids 0.9 to read parquet and csv files from s3.

My results are the following:
- dask.dataframe.read_parquet: success
- dask_cudf.read_parquet: _FileNotFoundError_
- cudf.read_parquet: _FileNotFoundError_

- pandas.read_csv: _success_
- cudf.read_csv: _FileNotFoundError_
- dask_cudf.read_csv: _success but very slow_ (issue #2798)

Summary: 
1) I'm not able to read parquet files in s3 with either dask_cudf.read_parquet or cudf.read_parquet
2) I'm not table to read csv files in s3 with cudf.read_csv. I can with dask_cudf.read_csv but very slowly.

Am I doing something wrong?

**Comment by ayushdg** [comment] 2019-09-13 22:05
Thanks @ivenzor for raising the issue!
- `cudf read from s3`: Cudf did not support reading from s3 (or other cloud sources) in 0.9. The feature #2635 was recently merged in 0.10 and should work with the latest nightly packages of 0.10

- `dask_cudf.read_parquet`: I can reproduce the `FileNotFoundError`. The [line](https://github.com/rapidsai/cudf/blob/branch-0.10/python/dask_cudf/dask_cudf/io/parquet.py#L35) here seems to be the problem. `piece.path` is the path to the file with the protocol stripped off (Eg: if the file is `gcs://anaconda-public-data/nyc-taxi/nyc.parquet/part.0.parquet` the variable would have a value `anaconda-public-data/nyc-taxi/nyc.parquet/part.0.parquet` which cudf assumes is a local file since it does not have any information about the protocol. 
Two initial ideas come to mind:
    -  If possible pass the full file path `protocol+piece.path`. 
    - Add a check: If `fs` is `local` pass down `piece.path` else pass `piece.open()` the open file handle similar to how `dask_cudf.read_csv` passes down the file to cudf

cc: @rjzamora

**Comment by rjzamora** [comment] 2019-09-16 13:57
> ...pass piece.open() the open file handle similar to how dask_cudf.read_csv passes down the file to cudf

Right - This is how dask handles the same situation in the pyarrow engine.   If cudf accepts a file handle, somthing like this *should* do the trick:

```python
with fs.open(piece.path, mode="rb") as f:
        df = cudf.read_parquet(
            f,
            engine="cudf",
            columns=columns,
            row_group=piece.row_group,
            strings_to_categorical=strings_to_cats,
            **kwargs.get("read", {}),
        )
```

**Comment by ayushdg** [comment] 2019-09-16 17:32
`Cudf.read_parquet` accepts the file handle and creates a `BytesIO` object by reading the buffer. This approach should work. Happy to make the fix if @rjzamora hasn't started work on it already.

**Comment by rjzamora** [comment] 2019-09-16 17:36
Go for it @ayushdg :) I wouldn't be able to get to it until later today.

**Closed** 2019-09-18 17:00 UTC
Labels: cuDF (Python), feature request
