### ISSUE TITLE
[BUG] branch-0.7 tests fail

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1623] opened 2019-05-03 22:34 UTC
Running `make test` with branch-0.7, pulled a couple of hours ago., I get failures with `TYPES_TEST`:
```
[ RUN      ] WrappersTest/0.CompoundAssignmentOperators
/home/eyalroz/src/blazing/cudf/cpp/tests/types/types_test.cpp:313: Failure
      Expected: t0
      Which is: 3
To be equal to: static_cast<UnderlyingType>(w0.value)
      Which is: 209652396
/home/eyalroz/src/blazing/cudf/cpp/tests/types/types_test.cpp:313: Failure
      Expected: t0
      Which is: 0
To be equal to: static_cast<UnderlyingType>(w0.value)
      Which is: 924231285
/home/eyalroz/src/blazing/cudf/cpp/tests/types/types_test.cpp:313: Failure
      Expected: t0
      Which is: 0
To be equal to: static_cast<UnderlyingType>(w0.value)
      Which is: 441365315
```
-snip-
```
/home/eyalroz/src/blazing/cudf/cpp/tests/types/types_test.cpp:313: Failure
      Expected: t0
      Which is: 0
To be equal to: static_cast<UnderlyingType>(w0.value)
      Which is: 1346794692
[  FAILED  ] WrappersTest/0.CompoundAssignmentOperators, where TypeParam = cudf::detail::wrapper<int, (gdf_dtype)11> (120 ms)
```
and again for some other types, so that we end up with:
```
[  FAILED  ] WrappersTest/0.CompoundAssignmentOperators, where TypeParam = cudf::detail::wrapper<int, (gdf_dtype)11>
[  FAILED  ] WrappersTest/1.CompoundAssignmentOperators, where TypeParam = cudf::detail::wrapper<long, (gdf_dtype)10>
[  FAILED  ] WrappersTest/2.CompoundAssignmentOperators, where TypeParam = cudf::detail::wrapper<int, (gdf_dtype)8>
[  FAILED  ] WrappersTest/3.CompoundAssignmentOperators, where TypeParam = cudf::detail::wrapper<long, (gdf_dtype)9>
```
This shouldn't happen. 

PS - My system is Devuan ASCII  (~= Debian Stretch), GNU/Linux , not officially supported.

**Comment by jrhemstad** [comment] 2019-05-04 03:37
Duplicate of https://github.com/rapidsai/cudf/issues/1544

@eyalroz what version of gcc are you using?

**Closed** 2019-05-04 03:38 UTC
Labels: ? - Needs Triage, bug

**Comment by eyalroz** [comment] 2019-05-04 07:36
@jrhemstad : The GCC version on Debian Stretch is 6.3.0.

**Comment by eyalroz** [comment] 2019-05-04 14:18
So, it's not clear this is a duplicate, since I don't get compilation warnings for TYPES_TEST (specifically, none regarding narrowing conversions).

**Comment by eyalroz** [comment] 2019-05-05 11:27
This was resolved by yesterday's PR, so probably a dupe.
