### ISSUE TITLE
[FEA] astype Category

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#2315] opened 2019-07-17 14:52 UTC
Currently cudf does not support astype('category') for converting a column (str, int, etc) to a category type.  As best as I can tell, cudf support for categoricals only works when building a cudf Series/Dataframe from a pandas series/dataframe which is type category

**Comment by kkraus14** [comment] 2019-07-17 14:55
Duplicate of #1664

**Comment by quasiben** [comment] 2019-07-17 14:56
Thanks @kkraus14

**Closed by kkraus14** 2019-07-17 14:55 UTC
Labels: ? - Needs Triage, feature request

**Comment by shwina** [comment] 2019-07-17 18:48
Fixed in #2318
