### ISSUE TITLE
[FEA] Implement Pandas Dataframe.sample() method

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#1426] opened 2019-04-13 09:41 UTC
**Is your feature request related to a problem? Please describe.**
I am porting some existing pandas code to cuDF, and I have noticed that the pandas _Dataframe.sample()_ method is not available yet in cuDF.

It is useful for this kind of code:

```
train_dataset = dataset.sample(frac=0.8,random_state=0)
test_dataset = dataset.drop(train_dataset.index)

```
**Describe the solution you'd like**
I would like that method to be available in cuDF.

**Describe alternatives you've considered**
None yet.

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by taureandyernv** [comment] 2019-06-19 17:21
@harrism, @mrocklin here is an interesting case where this lack of feature causes an error: dask-cudf allows a sample function to go through, and since it computes sample through cudf, it errors out saying we get this:

```
ddf= dask_cudf.from_cudf(df, npartitions = 2)
ddf_train = ddf.sample(frac=.1)
```
throws no error.  When running in the next cell
```
ddf_train.head().to_pandas.head()
```
you get the error (only showing the relevant parts of the trace): 
```/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/methods.py in sample(df, state, frac, replace)
    195 def sample(df, state, frac, replace):
    196     rs = np.random.RandomState(state)
--> 197     return df.sample(random_state=rs, frac=frac, replace=replace) if len(df) > 0 else df
    198 
    199 

/conda/envs/rapids/lib/python3.7/site-packages/cudf/dataframe/dataframe.py in __getattr__(self, key)
    216             return self[key]
    217 
--> 218         raise AttributeError("'DataFrame' object has no attribute %r" % key)
    219 
    220     def __getitem__(self, arg):

AttributeError: 'DataFrame' object has no attribute 'sample'
```
See, it goes to cudf for sample. 

If you run something like `ddf.test()` in the first cell instead of sample, it will immediately show
`AttributeError: 'DataFrame' object has no attribute 'test'` without going to cudf.

**Comment by taureandyernv** [comment] 2019-06-19 17:25
@miguelangel, @randerzander just told me about a new train test split function in cudf.  https://github.com/rapidsai/cuml/blob/branch-0.8/python/cuml/test/test_train_test_split.py.  Can't find it in the docs, so I was green lit to make a feature request issue about that :)

**Comment by jrhemstad** [comment] 2019-06-19 17:27
Looks to be a duplicate of https://github.com/rapidsai/cudf/issues/1879

**Comment by beckernick** [comment] 2019-06-19 17:46
@taureandyernv your original and comment example errors are expected behavior. `sample` exists as a dask method, but we haven't implemented it in cuDF. As a result, the error only occurs when the `getattr` tries to grab the non-existent `sample` method in cuDF. Dask looks for the `sample` method on the dask dataframe and finds it.

When you call `ddf.test()`, dask looks for a `test` method on the dask.dataframe object and cannot find it. I can't confirm since I don't have your exact example, but I'd bet the error shows that the attribute error comes from `dask/dataframe/core.py`, not anywhere in cuDF.

**Comment by miguelangel** [comment] 2019-06-19 17:53
Hi @taureandyernv,

Yes! Train_test_split might be a nice workaround for this functionality.

Hi @jrhemstad, I agree. #1879 is a duplicate of this feature request. Should #1879 be closed and refer to this issue, which was submitted first?

**Comment by taureandyernv** [comment] 2019-06-20 00:18
@miguelangel, I just used it for my new notebook and it seemed to have worked great.  I DO however still require sample(), as I have to do some data reduction for a portion of my dataset.

**Comment by harrism** [comment] 2019-06-20 03:12
@cjnolet left this comment on the now closed #1879: https://github.com/rapidsai/cudf/issues/1879#issuecomment-497710282

> I've been thinking over sampling without replacement primitive for cuML. We have needed this functionality in cuML for several different algorithms- shuffling for mini-batch SGD & pasting for Random Forests are two that immediately come to mind.
>
> This could be accomplished using thrust by generating a uniformly random vector of size n and sorting it by key, where the indices of the original vector are sorted by the randomly generated values. If some number of samples are needed that are smaller than n, let's call it m, you can just take the first m values from the resulting sorted array.

**Comment by ogreen** [comment] 2019-07-22 18:01
@harrism , @jrhemstad  any updates on sample() ?

**Comment by harrism** [comment] 2019-07-23 03:59
Not in libcudf. There's a PR in cuML though. We need priority motivation in order to plan it for libcudf.

**Comment by beckernick** [comment] 2019-12-12 02:14
For Python users, we could probably do the basic version of this in the layer as a stopgap by leveraging CuPy. (I felt the lack of it earlier today when trying to iteratively explore some data). Maybe something like:

```python
def sample(df, n=5, seed=None):
    if seed:
        cp.random.seed(seed)
    return df.iloc[cp.random.choice(df.index.to_series().values, n)]
```

**Comment by miguelangel** [comment] 2020-02-12 01:59
Hi all,

I was wondering if there is any ETA/update on this feature request.

Thanks!
Miguel

**Comment by jrhemstad** [comment] 2020-06-25 01:24
This would be pretty easy to implement now that @RAMitchell added `thrust::shuffle`: https://github.com/thrust/thrust/pull/1085

Just do a `shuffle` on a counting iterator `[0,n)` and use that as a gather map.

**Comment by gumdropsteve** [comment] 2020-06-25 03:48
Re #5573, thanks @karthikeyann 

Need `DataFrame.sample()` for educational purposes. Converting to/from pandas to use it causes too much confusion/disinterest. Thanks for considering.

**Comment by rgsl888prabhu** [comment] 2020-06-29 15:28
@kkraus14 How about using [cupy.random.choice](https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.random.choice.html#cupy.random.choice), it supports most of the required functionality and then we can call gather on top of it ?

**Comment by jrhemstad** [comment] 2020-06-29 18:50
> @kkraus14 How about using [cupy.random.choice](https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.random.choice.html#cupy.random.choice), it supports most of the required functionality and then we can call gather on top of it ?

Unless there is a compelling argument to the contrary, I think this should be a native libcudf feature.

**Comment by kkraus14** [comment] 2020-06-29 18:55
> > @kkraus14 How about using [cupy.random.choice](https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.random.choice.html#cupy.random.choice), it supports most of the required functionality and then we can call gather on top of it ?
> 
> Unless there is a compelling argument to the contrary, I think this should be a native libcudf feature.

I think it was just very low hanging fruit to do this with cupy and support all of the different options that Pandas API supports. Agreed it makes sense to move down to libcudf but I'm unclear on what options we'd want to support from the libcudf side.

@felipeblazing @williamBlazing Does blazing have a use for a sample function like this?

@jlowe @revans2 Does Spark have a use for a sample function like this?

**Comment by jlowe** [comment] 2020-06-29 23:24
> Does Spark have a use for a sample function like this?

Spark does have the ability to sample a DataFrame.  However I don't know if we will need to implement the identical sampling algorithm as Spark for compatibility with the CPU version.  If we want to wave our hands and say, "hey, you said sample x% and that's what we did" we're probably fine, but normally we strive to produce the same output as the CPU version for the same input, if possible, and that means sampling the same rows for a given input and sampler config.  We don't have a GPU version of Spark's sampler yet, so I could see using a general libcudf version like this, potentially with a config to enable, for users who just need any kind of sampling without caring too much about the sampling specifics.

On a related note, Spark's DataFrame can sample with or without replacement.  Is that planned for the libcudf version?

**Comment by kkraus14** [comment] 2020-06-29 23:27
> If we want to wave our hands and say, "hey, you said sample x% and that's what we did" we're probably fine, but normally we strive to produce the same output as the CPU version for the same input, if possible, and that means sampling the same rows for a given input and sampler config.

How does Spark do the RNG for sampling? Is this something even feasible to reproduce performantly on the GPU?

> On a related note, Spark's DataFrame can sample with or without replacement. Is that planned for the libcudf version?

I don't think there's a strong plan as we're currently doing requirements gathering, but Pandas also allows for sampling with or without replacement: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html

**Comment by jlowe** [comment] 2020-06-30 13:33
> How does Spark do the RNG for sampling? Is this something even feasible to reproduce performantly on the GPU?

Spark uses an [XOR shift RNG](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/util/random/XORShiftRandom.scala#L26-L50) which doesn't look amenable to parallel processing.  If we can't get a compatible sampler to perform on the GPU then we'll have no choice but to document the incompatibility, similar to what we do today for non-deterministic floating-point column reductions.  All of our GPU operator overrides can be independently disabled via configs, so users would still have a (not so perfomant) way to use the CPU sampler for compatibility if that is required.

**Comment by rgsl888prabhu** [comment] 2020-06-30 17:44
@jlowe Do you use weights as well in spark while sampling ?

**Comment by jlowe** [comment] 2020-06-30 18:17
> Do you use weights as well in spark while sampling ?

I couldn't find a built-in API in Spark to sample with a specified weight per row.

**Comment by harrism** [comment] 2020-07-01 12:33
cuRand provides an XORWOW PRNG, which is a member of the XOR-shift family of PRNGs. https://docs.nvidia.com/cuda/curand/host-api-overview.html

**Comment by kkraus14** [comment] 2020-07-01 14:55
@rgsl888prabhu okay, sounds like for a first pass in implementing this in libcudf lets not handle weights for now. So we should handle setting a number of samples, replacement, and setting a seed for the RNG.

**Comment by williamBlazing** [comment] 2020-07-01 18:57
In BlazingSQL we have a function we are using to get a table that contains a specified number of random samples taken from a source table. 

https://github.com/BlazingDB/blazingsql/blob/branch-0.15/engine/src/utilities/random_generator.cu#L64
std::unique_ptr<ral::frame::BlazingTable> generate_sample(
	const ral::frame::BlazingTableView & blazingTableView, std::size_t num_samples)

We have another API that allows for specifying a percentage, from which we can convert to num_samples.

**Comment by kkraus14** [comment] 2020-07-01 19:12
Looks like the API expected there is along the same lines as what we've been planning, except we plan to extend to allow controlling replacement and the random seed, so should still work as expected for you.

@rgsl888prabhu you should be good to move forward with this 👍

**Closed** 2020-07-15 14:07 UTC
Labels: cuDF (Python), feature request
