### ISSUE TITLE
[BUG]Query silently fails on creating large subset dataframes from original large dataframe - probably out of memory?

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cudf#2004] opened 2019-06-14 20:00 UTC
I'm using today's nightly and dual titan RTXs on ubuntu 16.04, python 3.7.  Dataset is about 8GB, most of the data is in 2010.  

If I create a dataframe for 2010 using query using the example below, it succeeds.  If i create a dataframe for 1980 using a similar query, it succeeds.  If i try to do both, in either order, the second query never finishes.  There is no error or stack trace.  It just says it is still processing.  I've let it run for quite some time.

example query:
```
df2010 = df.query('YEAR == 2010')
```

I have uploaded the dataset to google drive.  here is the sample code to replicate the error:

data: https://drive.google.com/file/d/1FWW3_4zIeUirvUmQu3nqNrPtmO-0RZis/view?usp=sharing

```
import pandas as pd
import cudf
import dask_cudf
import dask_cuml
import sys
import os
from pprint import pprint
import warnings
warnings.filterwarnings('ignore')
import gzip
def load_data(cached = 'ipums1970-2010.csv.gz',source='ipums'):
    if os.path.exists(cached) and source=='ipums':
        print('use ipums data')
        with gzip.open(cached) as f:
            #X = pd.read_csv(f)
            X = cudf.read_csv(f)
    else:
        print("no data")
    return X

df = load_data()
print('data',df.shape)
df2010 = df.query('YEAR == 2010')
print(df2010.head(5))
df1980 = df.query('YEAR == 1980') ## this second df never completes
print(df1980.head(5)) 
```

**Comment by kkraus14** [comment] 2019-06-15 17:31
> I'm using today's nightly and dual titan RTXs on ubuntu 16.04, python 3.7.
> 
> My Timeline dataset has 45 columns, and this many rows per year.
> 
> ```
> 2010    30871077
> 1980    11343120
> 2000     2808457
> 1990     2479020
> 1970     2029633
> ```
> 
> i tried to split out the years 2010 and 1980.
> 
> ```
> df1980 = df.query('YEAR == 1980')
> df2010 = df.query('YEAR == 2010')
> ```
> 
> Even after 1 hour, it was still processing. doing just 1970, it was done in seconds. No errors are thrown.

Is there any way you can create a minimal reproducer? I don't really have anything to go on here to try to debug this.

**Comment by taureandyernv** [comment] 2019-06-16 17:11
Spent a good bit of time trying to figure out where things truly fail, as it was part of a work flow.  Sorry for keeping you all in suspense.  There is no minimal reproducer in terms of dataset, so i uploaded and linked the data set and added the sample code

**Comment by kkraus14** [comment] 2019-08-14 15:32
@taureandyernv since there's been no update on this I'm going to close the issue for now. If you can build a reproducer feel free to reopen.

**Closed by kkraus14** 2019-08-14 15:32 UTC
Labels: bug, cuDF (Python)
