### ISSUE TITLE
[FEA] cudf.read_parquet support for column partitioned parquet datasets

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#6915] opened 2020-12-04 19:13 UTC
**Is your feature request related to a problem? Please describe.**
`cudf.read_parquet` supports reading a list of parquet files but does not support parquet datasets partitioned by columns.
`cudf.to_parquet(partitions_cols=...)` supports writing such parquet datasets.

**Describe the solution you'd like**
read_parquet call should work with partitioned parquet datasets. `dask_cudf.read_parquet` supports reading this and some of the logic might apply for cudf as well.

**Describe alternatives you've considered**
`dask_cudf.read_parquet` and `pandas.read_parquet` both support reading these datasets.

**Additional context**
N/A

**Comment by kkraus14** [comment] 2020-12-07 16:59
Duplicate of #5059

**Closed by kkraus14** 2020-12-07 16:59 UTC
Labels: ? - Needs Triage, feature request
