### ISSUE TITLE
[BUG] Wrong number of columns detected using cudf.read_csv on sparse csv

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#1237] opened 2019-03-19 21:39 UTC
**Describe the bug**
Hi,

I am reading a text file produced from a sparse matrix with blanks as column separator, where not all the rows contain the same number of columns.

When reading that file using cudf.read_csv method, it automatically detects 34 of the 38 columns the dataset has (it is very likely that the first rows do not contain 38 columns). 

**Steps/Code to reproduce bug**
Please, have a look at the screenshot below:

![2019-03-19 14_30_45-JupyterLab](https://user-images.githubusercontent.com/26169771/54643558-77da1500-4a54-11e9-9650-090f4dc59e46.png)

**Expected behavior**
Automatic detection of all the columns within the file.

**Environment details (please complete the following information):**
DGX-1 with today's nightly build

**Additional context**

**Comment by kkraus14** [comment] 2019-03-22 16:55
@miguelangel if you could provide a small reproducer or data sample that would be helpful for triaging.

**Comment by miguelangel** [comment] 2019-03-22 17:06
Sure! I have just sent you an email.

**Comment by mjsamoht** [comment] 2019-05-03 19:38
@miguelangel would it be possible to attach the sample input file to this issue?

**Comment by mjsamoht** [comment] 2019-05-03 19:51
A couple of questions:
1. We would need to know which cols are missing.  Let's say 'N' is the max number of cols, and a row contains 'M<N' cols.  Does this mean cols '1..M' are present and '(M+1)..N' are missing?
2. Will there be a header with col names?  Or can they be passed as input parameter?  If not, it will be difficult to support because we would have to parse the entire file upfront just to check the max number of cols.  Or dynamically add new cols as we detect them.  Either way would be problematic.

**Comment by miguelangel** [comment] 2019-05-03 21:24
Hi Thomas,

I have just sent you an email with the dataset (I cannot attach here, it is confidential).

In relation to your question, I would need to double check. I will try to do this weekend.

Regards,
Miguel

**Comment by mjsamoht** [comment] 2019-05-16 23:44
In the shared dataset not every row or record has the same number of columns.  And based on the values it also looks like the missing columns aren't simply the last 'N' columns.  Instead, the missing columns can be somewhere in the middle of the row.  This makes it impossible to figure out the correct column the data belongs to.

**Comment by kkraus14** [comment] 2019-07-03 22:59
Going to close this as malformed data. @miguelangel if Pandas is handling this and this is an issue for you feel free to reopen.

**Closed by kkraus14** 2019-07-03 22:59 UTC
Labels: bug, cuIO
