### ISSUE TITLE
[FEA] Support lists in skiprows

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#1170] opened 2019-03-12 17:18 UTC
It would be nice to be able to read files that have a missing line between header and data like the following:

```
a,b

1,2
3,4
```

In Pandas the solution here is to provide a list or tuple to the skiprows keyword like the following `skiprows=[1]` 

```python
In [2]: pd.read_csv('foo.csv', skiprows=[1])
Out[2]:
   a  b
0  1  2
1  3  4
```

**Comment by mrocklin** [comment] 2019-03-12 17:19
I care about this particularly because recent years of the NYCTaxi dataset have an empty line

**Comment by vuule** [comment] 2019-03-12 17:28
Is the line completely empty? If so, you should be able to get rid of it by setting skip_blank_lines to True.

**Comment by mrocklin** [comment] 2019-03-12 17:30
Oh, that's useful, and probably solves my immediate problem.  Thanks!

**Comment by mrocklin** [comment] 2019-03-12 17:57
cc @quasiben

**Comment by quasiben** [comment] 2019-03-12 19:31
You probably already know this, but `skiprows` does exist but it only takes an `int`.  We could change things to take a list of rows instead.  But as we do down the road you should also know about his conditional:

```python
    if byte_range is not None:
        if skipfooter != 0 or skiprows != 0 or nrows is not None:
            raise ValueError("""cannot manually limit rows to be read when
                                using the byte range parameter""")
```

**Comment by mjsamoht** [comment] 2019-03-13 18:11
The reason we don't support `skiprows` or `nrows` with `byte_range` is because it would be very efficient.  It would force us to parse the entire file in order to figure out which rows to skip, which would significantly impact perf for large files and go against the idea behind splitting up large files with dask.

Of course, if `skiprows` or `nrows` are defined relative to the beginning of the byte range that would be a different story.  But it's not clear how the user would be able to specify this.

**Comment by vyasr** [comment] 2022-07-14 23:13
Closing as a duplicate of #7268. Keeping that one because it includes the more general ask of either a list _or_ a callable, although I think it's unlikely that the latter will ever be supported even if the former is.

**Closed by vyasr** 2022-07-14 23:13 UTC
Labels: feature request, cuIO
