### ISSUE TITLE
[FEA]fillna() needs ‘method’ and ‘limit’ implementation

### ISSUE THREAD

**Issue by liuyangc1** [rapidsai/cudf#6752] opened 2020-11-12 19:52 UTC
It's helpful if I could use cuDF to fillna() with 'bfill' or 'ffill' method with a limit. The example python cpu code is shown below:
```
d = {'id': ['a', 'a','a','a','a','b','b','b','b','b','c','c','c','c','c'], \
     'time': ['1', '2', '4', '3', '5', '1', '2', '3', '4', '5','1', '2', '3', '4', '5'], \
     'status': [1, 2, 3, None, 5, 1, None, None, None, None, 3, None, 5, 6, 7]} 

df_locf = pd.DataFrame(data=d)
df_locf['new'] = df_locf.sort_values(by = ['time'], ascending = True).groupby('id')['status'].fillna(value = None, method = 'ffill', limit = 3)
```
when I worked with dask cudf, I got the error `NotImplementedError: The method keyword is not supported`

**Comment by davidwendt** [comment] 2020-11-12 19:57
Same as https://github.com/rapidsai/cudf/issues/1361

**Comment by beckernick** [comment] 2020-11-12 20:03
I think it's a duplicate of https://github.com/rapidsai/cudf/issues/4896

**Comment by kkraus14** [comment] 2020-11-17 16:11
Closing as duplicate of #4896

**Closed by kkraus14** 2020-11-17 16:11 UTC
Labels: ? - Needs Triage, feature request

**Comment by yidong72** [comment] 2020-11-19 21:22
I posted a workaround solution in #1361
