### ISSUE TITLE
[FEA] as_type() for Dataframes

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#2600] opened 2019-08-15 20:40 UTC
I am trying to cast values in a dataframe to another datatype, and get the error `AttributeError: 'DataFrame' object has no attribute 'astype'`. 

I think as_type() is available for Series, but it would be good to have it for DataFrames (like Pandas) as well.

Example snippet: 

```
import cudf
import numpy as np
df = cudf.DataFrame({"x": (np.arange(4) // 2).astype(float)})
df.astype(int)
```

**Comment by ayushdg** [comment] 2019-08-15 21:03
Duplicate of #2195

**Closed** 2019-08-15 21:28 UTC
Labels: ? - Needs Triage, feature request
