### ISSUE TITLE
how to concat?

### ISSUE THREAD

**Issue by faywang123** [rapidsai/cudf#1918] opened 2019-06-04 05:16 UTC
Hi, I tried to convert pandas code 
total_df = pd.concat([dfs])
to rapids ai: 

    total_df = pandas.DataFrame()
    for col in dfs[0].columns:
        new_col = None
        for gdf in dfs:
            if new_col is None:
                new_col = gdf[col]
            else:
                new_col = new_col.append(gdf[col])
        total_df[col] = new_col

but it failed in this line:
    new_col = new_col.append(gdf[col])
  File "/home/vibhora/conda/lib/python3.6/site-packages/cudf/dataframe/series.py", line 635, in append
    return Series(self._column.append(other_col))
  File "/home/vibhora/conda/lib/python3.6/site-packages/cudf/dataframe/column.py", line 540, in append
    data_dtype = np.result_type(self.data.dtype, other.data.dtype)
AttributeError: 'nvstrings' object has no attribute 'dtype'

Please advise...

**Comment by faywang123** [comment] 2019-06-04 05:17
My cudf version is '0.7.2+0.g3ebd286.dirty'

**Comment by kkraus14** [comment] 2019-06-04 06:03
@faywang123 you should be able to use `cudf.concat([dfs])` similarly to pandas. It looks like we have a bug in handling String columns with the append operator though.

**Comment by faywang123** [comment] 2019-06-04 17:32
Hi, I was using 
    total_df = pd.concat(dfs)
     originally, and it failed with the following error. I then switched to use the above code and it failed with different error. Should I open a bug report?

  File "/home/fayw/conda/lib/python3.6/site-packages/cudf/multi.py", line 52, in concat
    return DataFrame._concat(objs, axis=axis, ignore_index=ignore_index)
  File "/home/fayw/conda/lib/python3.6/site-packages/cudf/dataframe/dataframe.py", line 1054, in _concat
    for c in objs[0].columns]
  File "/home/fayw/conda/lib/python3.6/site-packages/cudf/dataframe/dataframe.py", line 1054, in <listcomp>
    for c in objs[0].columns]
  File "/home/fayw/conda/lib/python3.6/site-packages/cudf/dataframe/series.py", line 625, in _concat
    col = Column._concat([o._column for o in objs])
  File "/home/fayw/conda/lib/python3.6/site-packages/cudf/dataframe/column.py", line 78, in _concat
    if not o.is_type_equivalent(head):
  File "/home/fayw/conda/lib/python3.6/site-packages/cudf/dataframe/columnops.py", line 57, in is_type_equivalent
    remove_base(mine)
  File "/home/fayw/conda/lib/python3.6/site-packages/cudf/dataframe/columnops.py", line 55, in remove_base
    del dct[k]
KeyError: 'mask'

**Comment by kkraus14** [comment] 2019-06-05 02:24
@faywang123 would it be possible to give an example that reproduces the bug you're seeing?

**Comment by faywang123** [comment] 2019-06-05 05:16
Please see the attached.

**Comment by faywang123** [comment] 2019-06-05 05:23
[defect.zip](https://github.com/rapidsai/cudf/files/3255612/defect.zip)

**Comment by faywang123** [comment] 2019-06-05 05:25
This zip file contains:
data:
(1) defect_1_3c.csv
(2) defect_2_3c.csv
script:
(1) cudf_test_v3.py: concat using cudf, failed
(2) cudf_test_v4.py: concat using pandas, works

**Comment by shwina** [comment] 2019-06-05 16:12
Looks like the underlying issue is that `cudf.read_csv()` interprets your first column as a Datetime. Here's a simple reproducer of this behaviour:

```python
In [6]: cat test.csv                                                                                                                                                                                            
col1,col2
PB-01,PB01

In [7]: print(cudf.read_csv('test.csv'))                                                                                                                                                                        
                     col1  col2
0 1906-05-07T18:35:44.000  PB01
```

**Comment by faywang123** [comment] 2019-06-05 17:29
Interestingly, this problem does not always happen. Please see attached. 
[defect_2.zip](https://github.com/rapidsai/cudf/files/3258313/defect_2.zip)

**Comment by faywang123** [comment] 2019-06-05 17:30
This zip file contains the following files:
data:
(1) new_defect_1a.csv
(2) new_defect_2a.csv
(3) new_defect_3a.csv
script:
cudf_test_v4.py

**Comment by faywang123** [comment] 2019-06-05 17:32
Please note that cudf.concat using data files (1) and (2) works fine, but it fails using data files (2) and (3).
The error is:
  File "/home/fayw/conda/lib/python3.6/site-packages/cudf/dataframe/column.py", line 79, in _concat
    raise ValueError("All series must be of same type")
ValueError: All series must be of same type

**Comment by kkraus14** [comment] 2019-07-03 23:48
Closing this in favor of #1929

**Closed by kkraus14** 2019-07-03 23:48 UTC
Labels: cuDF (Python), question
