### ISSUE TITLE
[BUG] NumbaNotImplementedError : Trying to iterating through List stored in a Dataframe columns

### ISSUE THREAD

**Issue by NishantJadhav369** [rapidsai/cudf#11301] opened 2022-07-19 20:41 UTC
**Describe the bug**
Need GPU support to iterate through list stored in cudf column and need access to do operations on list elements

Reproducible code
```
test = cudf.DataFrame({'ID10':cudf.Series(np.arange(50,0,-10)),'ID20':pd.Series(np.arange(10,51,10)),'mapped_ID10':np.array([[10,20,30], [20,30], [40],[10],[30,40]]),'P':pd.Series(np.arange(100,501,100))})
test.head()
```

![mapperdf](https://user-images.githubusercontent.com/35873124/179843330-b0f7eca3-3eae-4610-b9d7-c909373daf56.png)

```
def calculate_parts(id10_list):   
    parts = [len(test_cpu[test_cpu.ID10 ==id10]) for id10 in id10_list]
    return parts

test.ID10.apply(calculate_parts)  
```
Output : NumbaNotImplementedError: list

Trying to achieve this which is possible in CPU support via **apply**

```

test_cpu = test.to_pandas()
test_cpu.mapped_ID10.apply(calculate_parts)

Expected output:
0    [1, 1, 1]
1       [1, 1]
2          [1]
3          [1]
4       [1, 1]
Name: mapped_ID10, dtype: object

```

Using cudf. Need support to map about 12M IDS

**Comment by shwina** [comment] 2022-07-22 13:43
Hi @NishantJadhav369 - I think the corner case in your example that returns all `1` has me a bit confused. To be clear, would you expect the following result?

```python
>>> df
   ID10 mapped_ID10
0     1      [1, 2]
1     1      [3, 4]
2     2      [1, 3]
3     3   [None, 3]

>>> df.mapped_ID10.apply(calculate_parts)
0    [2, 1]
1    [1, 0]
2    [2, 1]
3    [0, 1]
Name: mapped_ID10, dtype: object
```

**Comment by vyasr** [comment] 2022-10-18 00:07
@NishantJadhav369 could you clarify your needs based on the last comment?

**Comment by vyasr** [comment] 2022-10-20 16:32
I'm going to close this issue for now since the underlying issue is a duplicate of #11008 (running `apply` on list columns). Feel free to continue the conversation if there is still a misunderstanding with this specific example.

**Closed by vyasr** 2022-10-20 16:32 UTC
Labels: bug, cuDF (Python)
