### ISSUE TITLE
[FEA] Allow users to specify build/probe table for hash join

### ISSUE THREAD

**Issue by abc99lr** [rapidsai/cudf#4751] opened 2020-03-30 23:11 UTC
**Is your feature request related to a problem? Please describe.**
It could be useful if cuDF allows users (mostly data scientists) to specify which table to build the hash table and which table to probe against the hash table when doing hash join. Currently, cuDF always selects the smaller table to build and larger table to probe (if table sizes are the same, cuDF uses the right table to build) ([code](https://github.com/rapidsai/cudf/blob/branch-0.14/cpp/src/join/hash_join.cuh#L236)). Users should have the control on which table to build/probe. 

However, in some cases, we may want to build the hash table on the larger table, for example 
- In [distributed join project](https://github.com/rapidsai/distributed-join), we create one table with unique keys for building and another with non-unique keys for probing. The table with unique keys is not necessary to be the smaller table after all to all communication, and cuDF often build the hash table on the non-unique key tabes, which would introduce more collisions (worse performance). 

**Describe the solution you'd like**
We could add optional arguments to join APIs ([code](https://github.com/rapidsai/cudf/blob/branch-0.14/cpp/include/cudf/join.hpp)) but we may need a better solution because sort-based join shares the same API.

**Describe alternatives you've considered**
Currently there is no simple way to force cuDF to build hash table on the large input table. 

**Additional context**

cc @nsakharnykh

**Comment by jrhemstad** [comment] 2020-04-07 20:46
We can just always build on the `left` table and probe with the `right`, and then it's up to the user to specify which is which.

**Comment by jrhemstad** [comment] 2020-04-07 20:53
Actually, it's abstracted from the user that Join is implemented with a hash table, so I don't think it makes sense to provide this control in the top-level API. This is probably something more for an internal, detail API.

**Comment by abc99lr** [comment] 2020-04-08 16:41
I agree that we should not provide this control in the top-level API, but it would be great to have a more detailed API as you mentioned.

**Comment by nsakharnykh** [comment] 2020-04-08 17:02
I'm not sure I agree that this is should be an internal API. Even the Python user (data scientist) might know that e.g. left table has lots of duplicates, and hint libcudf to build a hash table for the right table explicitly. It's an "expert" mode, and relies on the fact that we're doing hash joins, but some data scientists would have such information (since they are familiar with data they are operating with). Can we have an optional parameter that forces cuDF to use a specific table as the "build" table? or some other way to provide table "properties", like sorted/lots of duplicates/hint which one to use for HT in joins, etc.

**Comment by harrism** [comment] 2020-04-20 06:11
But in general libcudf is already a bit of an expert API, so I could see it being exposed there, but that doesn't mean the data scientists would actually get access to it, because the Python API architects  might decide it should not be exposed. I think @kkraus14 might have opinions on that.

**Comment by kkraus14** [comment] 2020-04-20 14:08
We will not exposed that in the Python API for sure. Possibly in the Cython. That being said if we were to make it consistent I would suggest making the right table the table we build the hash table against and the left table we use for probing it as that pattern is more common.

**Comment by nsakharnykh** [comment] 2020-04-20 23:00
Ok, sounds like it should be exposed in libcudf, but not on the Python side then. How the API changes would look like?

**Comment by harrism** [comment] 2020-04-21 06:05
Hold on. Is there a user request for this in libcudf? The original request  is "it would be useful to data scientists". But @kkraus14 confirmed it won't be exposed in Python -- which implies he considers it not useful enough for data scientists to expose it. 

Is there a user request for this? I would like to not add features without motivation.

**Comment by kkraus14** [comment] 2020-04-21 06:13
Data engineers would possibly take advantage of this, but I think it makes more sense to expose this simply by consistently making the left table the probe table and the right table the build table.

From my data engineering experience it's most common to have the fact table as the left table and the dimension table as the right table. @revans2 @jlowe does this align with Spark expectations as well and your data engineering experience?

**Comment by nsakharnykh** [comment] 2020-04-21 13:19
BTW, I’m ok with @kkraus14’s proposal above, it will fix the perf issue we are seeing in the distributed join C++ code.

The original motivation for this feature is to have consistent performance for joins in distributed environment - after hash partitioning, the left and right table partitions might have different sizes and local join performance would tank if the wrong table is selected for the hash table build (and there is no overriding control for that in libcudf).

Also adding @felipeblazing for his opinion on this.

**Comment by jlowe** [comment] 2020-04-21 15:01
> does this align with Spark expectations as well and your data engineering experience?

Internally Spark supports using either side as the build table, but yes, in general Spark tends to produce plans where the right table is the one that is built and the left is the one that is streamed, probing the lookup table built by the right.

**Comment by jrhemstad** [comment] 2020-04-21 15:07
Join APIs are going to need some significant rework to support inequality joins in the future anyways. As part of that API overhaul, we'll likely have explicit sort vs. hash APIs, at which point we can allow the user to decide in the hash API which table is for building vs probing. 

See https://github.com/rapidsai/cudf/issues/2792#issuecomment-573899329

**Comment by nsakharnykh** [comment] 2020-06-18 14:54
+@gaohao95

**Comment by kkraus14** [comment] 2020-06-19 06:13
Closing in favor of #1087

**Closed by kkraus14** 2020-06-19 06:13 UTC
Labels: feature request, libcudf
