### ISSUE TITLE
[FEA] .sample()

### ISSUE THREAD

**Issue by gumdropsteve** [rapidsai/cudf#5573] opened 2020-06-24 23:08 UTC
**Is your feature request related to a problem? Please describe.**
I wish I could use cuDF to do `.sample()` like pandas.

**Describe the solution you'd like**
```python 
import cudf

df = cudf.read_csv('https://raw.githubusercontent.com/gumdropsteve/datasets/master/iris.csv')

df.sample(10)
```

**Describe alternatives you've considered**
```python
import cudf

df = cudf.read_csv('https://raw.githubusercontent.com/gumdropsteve/datasets/master/iris.csv')

df = df.to_pandas().sample(10)

df = cudf.DataFrame().from_pandas(df)

df
```

```python
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/gumdropsteve/datasets/master/iris.csv')

df = df.sample(10)

import cudf

df = cudf.DataFrame().from_pandas(df)

df
```

**Additional context**
Would also be cool to do this with `dask_cudf.DataFrame` like `.head()`, `.tail()`, or `.compute()`.

**Comment by karthikeyann** [comment] 2020-06-25 01:14
duplicate of https://github.com/rapidsai/cudf/issues/1426

**Closed** 2020-06-25 03:38 UTC
Labels: ? - Needs Triage, feature request
