### ISSUE TITLE
cuDF printing mismatches formatting precision of Pandas DF printing

### ISSUE THREAD

**Issue by MurrayData** [rapidsai/cudf#406] opened 2018-11-27 14:09 UTC
I'm reading in a set of Latitude and Longitude coordinates, captured by mobile devices in Ireland for an analysis project. In order to match them to location data for machine learning, I need to convert them into the local coordinate systems.

The data is in a CSV file, I am using Pandas to import the file, due to the outstanding negative numbers issue, but I tried reading directly and get similar results. Small errors are being introduced in the process:

So if I read the file using read_csv, I get small adjustments in the lat column. (Ignore the lon column, for now, as it contains all negative numbers.)

![image](https://user-images.githubusercontent.com/8914493/49086806-51962c80-f24d-11e8-8010-e365e197cd74.png)

If I then read the file via Pandas, it reads correctly without altering the values:

![image](https://user-images.githubusercontent.com/8914493/49086854-6ffc2800-f24d-11e8-914e-ea0fa2af9b04.png)

But if I then copy the columns to a GPU data frame, it introduces small errors:

![image](https://user-images.githubusercontent.com/8914493/49086900-928e4100-f24d-11e8-99c4-965065c8a80a.png)

I've attached the CSV file, it isn't confidential.

[irish.zip](https://github.com/rapidsai/cudf/files/2620287/irish.zip)

**Comment by kkraus14** [comment] 2018-11-28 03:01
cc @ogreen @BradReesWork I think this has to be in the libcudf side, any ideas on why we'd be getting these rounding errors?

**Comment by ogreen** [comment] 2018-11-28 03:09
@MurrayData , can you post the first 5 lines of the raw csv files here?
@kkraus14 , the fact that the inconsistency is repetitive even when copying from gdf implies that either the printing functionality of pandas is rounding up numbers (we will be able to confirm that with the raw csv file), that there might be a discrepancy somewhere with the floating point representation, or the conversion from pandas to gdf might need to be revisited.

**Comment by harrism** [comment] 2018-11-28 03:20
The CSV values match the print(pdf) line. What is the default floating point precision for read_csv?

**Comment by harrism** [comment] 2018-11-28 04:55
Hi @MurrayData, thanks for the report. First, I think you should update your installation of cuDF. I noticed you still have the negative floating point CSV problem, but that is fixed in the latest. Also, you refer to pygdf, which is out of date, so I'm wondering if you are using a "very old" version (where "Very old" is more than a month. 😄 )

I think this is not a bug, it's just pandas rounding the displayed value to the number of digits read in from the file. If you display the dataframe, you see the rounded version. If you just print a value, you will see the full precision. e.g. `print(df['lat'][0])` prints `54.60244399999999`, where `df` is a *pandas* dataframe, not a cuDF.

Also, you may be interested in this code, which is pure Python, no pandas or cuDF:
```python
x = 54.602444
print(x)
print('%.16f' % x)
```

Output: 
```
54.602444
54.6024439999999984
```

The image below shows my full experiment, which demonstrates that Python, pandas, and cuDF all store the same value for this input.

If there's something to enhance, it's the behavior of printing cuDF DataFrames. We could look at what pandas does for rounding for display.

As I mentioned previously, most decimal values are not exactly representable in finite-precision binary floating point. Specifically, only values where the denominator is a power of 2 are exactly representable. By way of exploration, this website lets you enter a decimal value and see the floating point value, and it will tell you whether or not the value is exact: https://www.exploringbinary.com/floating-point-converter/

<img width="592" alt="image" src="https://user-images.githubusercontent.com/783069/49129606-875a1480-f324-11e8-88cb-4da582391276.png">

**Comment by harrism** [comment] 2018-11-28 04:57
Removed the libcudf and cuda tags and set the cudf (Python) tag. If we decide to do anything on this issue, I believe it's just the formatting logic for printing cuDF DataFrames, which would be on the Python side.

**Comment by harrism** [comment] 2018-11-28 10:20
The native precision is higher than the precision in the file. It's only being rounded for printing. It is stored at fp64 precision.

**Comment by harrism** [comment] 2018-12-19 01:34
@kkraus14 Do you plan to change the print functionality for cuDF, or should this be closed as not a bug?

**Comment by mrocklin** [comment] 2018-12-19 02:13
Thoughts on just converting a sufficient subset of the data to a pandas dataframe and then reusing that logic?  Shouldn't take more than a few milliseconds to convert the necessary rows, and that's probably fast relative to the human time scale when this matters most.

**Closed** 2019-08-12 23:40 UTC
Labels: cuDF (Python), feature request
