### ISSUE TITLE
DataFrames cannot be created from_pandas with numeric column names. 

### ISSUE THREAD

**Issue by egoolish** [rapidsai/cudf#166] opened 2018-07-27 00:10 UTC
MWE:
```
df = pd.DataFrame()
for i in range(0, 1000):
  df[i] = [0, 1, 2, 3, 4, 5, 6]
gdf = DataFrame.from_pandas(df)
```

throws 
```
Traceback (most recent call last):
  File "test2.py", line 52, in <module>
    gdf = DataFrame.from_pandas(df)
  File "/conda/envs/gdf/lib/python3.6/site-packages/pygdf-0.1.0a2+137.g2f473b8-py3.6.egg/pygdf/dataframe.py", line 871, in from_pandas
    return df.set_index(dataframe.index.values)
  File "/conda/envs/gdf/lib/python3.6/site-packages/pygdf-0.1.0a2+137.g2f473b8-py3.6.egg/pygdf/dataframe.py", line 303, in set_index
    df[k] = self[k].set_index(index)
  File "/conda/envs/gdf/lib/python3.6/site-packages/pygdf-0.1.0a2+137.g2f473b8-py3.6.egg/pygdf/dataframe.py", line 175, in __getitem__
    raise TypeError(msg.format(arg))
TypeError: __getitem__ on type 0 is not supported
```

but replacing df[i] by df[str(i)] fixes the issue:
```
df = pd.DataFrame()
for i in range(0, 1000):
  df[str(i)] = [0, 1, 2, 3, 4, 5, 6]
gdf = DataFrame.from_pandas(df)
```

**Comment by kkraus14** [comment] 2018-07-27 15:54
Looks like the issue stems from __getitem__ expecting the column name datatype to be a string if it's not a slice.

https://github.com/gpuopenanalytics/pygdf/blob/master/pygdf/dataframe.py#L169

**Comment by mike-wendt** [comment] 2018-08-06 17:30
@egoolish is this fixed with the merge of #176?

**Comment by egoolish** [comment] 2018-08-06 18:53
I might have another docker caching issue but I don't think it is yet actually:
I tried the same code as above 
```
from pygdf import DataFrame as gdf
import pandas as pd


df = pd.DataFrame()
for i in range(0, 10):
    df[i] = [0, 1, 2, 3, 4, 5, 6]
print(df)
my_gdf = gdf.from_pandas(df)
print(my_gdf)
```
which throws the same error
```
   0  1  2  3  4  5  6  7  8  9
0  0  0  0  0  0  0  0  0  0  0
1  1  1  1  1  1  1  1  1  1  1
2  2  2  2  2  2  2  2  2  2  2
3  3  3  3  3  3  3  3  3  3  3
4  4  4  4  4  4  4  4  4  4  4
5  5  5  5  5  5  5  5  5  5  5
6  6  6  6  6  6  6  6  6  6  6
Traceback (most recent call last):
  File "test2.py", line 9, in <module>
    my_gdf = gdf.from_pandas(df)
  File "/conda/envs/gdf/lib/python3.6/site-packages/pygdf-0.1.0a2+264.g03602cf-py3.6.egg/pygdf/dataframe.py", line 1030, in from_pandas
    return df.set_index(dataframe.index.values)
  File "/conda/envs/gdf/lib/python3.6/site-packages/pygdf-0.1.0a2+264.g03602cf-py3.6.egg/pygdf/dataframe.py", line 306, in set_index
    df[k] = self[k].set_index(index)
  File "/conda/envs/gdf/lib/python3.6/site-packages/pygdf-0.1.0a2+264.g03602cf-py3.6.egg/pygdf/dataframe.py", line 178, in __getitem__
    raise TypeError(msg.format(arg))
TypeError: __getitem__ on type 0 is not supported

```
I then tried converting directly to a GDF first and THEN adding the column data, which works as expected when the initial Pandas DF has a string column name like so:
```
from pygdf import DataFrame as gdf
import pandas as pd


df = pd.DataFrame({'10': [1, 2, 3, 4, 5, 6, 7]})
print(df)
my_gdf = gdf.from_pandas(df)
print(my_gdf)
for i in range(0, 10):
     my_gdf[i] = [0, 1, 2, 3, 4, 5, 6]
print(my_gdf)
```
```
   10
0   1
1   2
2   3
3   4
4   5
5   6
6   7
    10
0    1
1    2
2    3
3    4
4    5
5    6
6    7
    10    0    1    2    3    4    5    6    7    8    9
0    1    0    0    0    0    0    0    0    0    0    0
1    2    1    1    1    1    1    1    1    1    1    1
2    3    2    2    2    2    2    2    2    2    2    2
3    4    3    3    3    3    3    3    3    3    3    3
4    5    4    4    4    4    4    4    4    4    4    4
5    6    5    5    5    5    5    5    5    5    5    5
6    7    6    6    6    6    6    6    6    6    6    6
```
but NOT when the initial Pandas DF has that int type column name:
```
...
df = pd.DataFrame({10: [1, 2, 3, 4, 5, 6, 7]})
...
```
```
   10
0   1
1   2
2   3
3   4
4   5
5   6
6   7
Traceback (most recent call last):
  File "test2.py", line 7, in <module>
    my_gdf = gdf.from_pandas(df)
  File "/conda/envs/gdf/lib/python3.6/site-packages/pygdf-0.1.0a2+264.g03602cf-py3.6.egg/pygdf/dataframe.py", line 1030, in from_pandas
    return df.set_index(dataframe.index.values)
  File "/conda/envs/gdf/lib/python3.6/site-packages/pygdf-0.1.0a2+264.g03602cf-py3.6.egg/pygdf/dataframe.py", line 306, in set_index
    df[k] = self[k].set_index(index)
  File "/conda/envs/gdf/lib/python3.6/site-packages/pygdf-0.1.0a2+264.g03602cf-py3.6.egg/pygdf/dataframe.py", line 178, in __getitem__
    raise TypeError(msg.format(arg))
TypeError: __getitem__ on type 10 is not supported
```
Note that the error message being thrown is dependent on the numeric column name: with the initial code it was throwing a "type 0" error because the first column name was 0. Here, where the example column name is 10, it throws a "type 10" error. Perhaps in some way the from_pandas() method is reading the actual value as the type?

**Comment by mrocklin** [comment] 2018-09-26 19:31
I also ran into this.  Minimal reproducer

```python
In [1]: import pandas as pd

In [2]: import pygdf as gd

In [3]: df = pd.DataFrame({0: [1]})

In [4]: gd.DataFrame.from_pandas(df)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-5c627d755869> in <module>()
----> 1 gd.DataFrame.from_pandas(df)

~/miniconda/envs/dask-gdf/lib/python3.6/site-packages/pygdf/dataframe.py in from_pandas(cls, dataframe)
   1089             df[colk] = dataframe[colk].values
   1090         # Set index
-> 1091         return df.set_index(dataframe.index.values)
   1092
   1093     def to_records(self, index=True):

~/miniconda/envs/dask-gdf/lib/python3.6/site-packages/pygdf/dataframe.py in set_index(self, index)
    323             df = DataFrame()
    324             for k in self.columns:
--> 325                 df[k] = self[k].set_index(index)
    326             return df
    327

~/miniconda/envs/dask-gdf/lib/python3.6/site-packages/pygdf/dataframe.py in __getitem__(self, arg)
    190         else:
    191             msg = "__getitem__ on type {!r} is not supported"
--> 192             raise TypeError(msg.format(arg))
    193
    194     def __setitem__(self, name, col):

TypeError: __getitem__ on type 0 is not supported
```

**Comment by kkraus14** [comment] 2018-09-26 19:33
@mrocklin I'd guess you have Pandas 0.23.4 while we currently only support 0.20.3. Pandas had an API change that expresses columns as a RangeIndex instead of normal ints.

**Comment by kkraus14** [comment] 2018-09-26 19:41
Looks like the issue is that Pandas will create the columns with types as numpy scalars and we only check for if they're an instance of `int`.

**Closed** 2019-01-10 22:38 UTC
Labels: bug, cuDF (Python)
