### ISSUE TITLE
[QST] What is the perfect usecase for cudf, especially dask_cudf in current landscape?

### ISSUE THREAD

**Issue by stucash** [rapidsai/cudf#13088] opened 2023-04-07 19:15 UTC
Last week I've been experimenting the workflow of `read.data -> groupby -> filter` and it was unfortunate that I found out `filter` wasn't supported after quite some prep work. Then I reviewed this [page](https://github.com/rapidsai/cudf/wiki/cuDF-groupby) and `dask_cudf` as a whole, it looked to me that, currently `dask_cudf` / `cudf` is most useful for operations that involve mostly, it not all, `mapreduce`  alike operations and mathematics on **numbers** (as opposed to `filter` alike operations). 

My usecase invovles filtering on python datetime objects and strings (before I do anything on numbers), and it looked to me that `dask_cudf` / `cudf`, are not meant for them (I understand the team may have plan to support these types and filtering on them, but I don't think these are to be as robust as operations on numbers, at least in the short term). 

I wanted to know, what is the usecase for `dask_cudf` ? Is it correct to say that I shall try my best to limit the usage of `dask_cudf` to numeric data?

For now the conclusion is I'll have to take out `dask_cudf`/'cudf` from my codebase until `filter` is implemented I guess (I don't see workaround for it).

**Comment by shwina** [comment] 2023-04-07 19:29
Hi @stucash -- thanks for raising this! Firstly, I will say that [this page](https://github.com/rapidsai/cudf/wiki/cuDF-groupby) is significantly out of date (3 years at this point...), so it may not represent the state of `groupby` currently.

There are two distinct issues that you've brought up:

1. Support for non-numeric data types (cuDF has significantly improved since 2020 in this regard)
2. Support for the `groupby.filter` API (this is still an issue: we don't support this API even today)

We'd like to understand more about your workflow, and see if we can suggest workarounds for any missing pieces of functionality in cuDF. Are you able to provide a code snippet that shows what exactly you'd like to achieve? If you can provide a fully-reproducible example with a representative dataset, that would be exponentially more helpful!

**Comment by bdice** [comment] 2023-04-07 19:38
We're disabling the cuDF wiki that was linked above because its contents are heavily outdated. For future readers of this issue, here are the former contents of that wiki page (last updated in 2020, currently 2023 so it's not a current reflection of cudf).

> # cuDF groupby
> 
> This page documents the design and features of `groupby` in cuDF.
> 
> ## Issues
> 
> The following cuDF issues relate to groupby and are presented in no particular order:
> 
> * [Dask DataFrames groupby...apply](https://github.com/rapidsai/cudf/issues/3682)
> * [Rank](https://github.com/rapidsai/cudf/issues/3591)
> * [Rolling groupby](https://github.com/rapidsai/cudf/issues/2789)
> * [Top N rows of group](https://github.com/rapidsai/cudf/issues/2592)
> 
> ## GroupBy features
> 
> - **Grouping**
>   - [x] A Python function, to be called on each of the axis labels.
>   - [x] A list or NumPy array of the same length as the selected axis.
>   - [x] A dict or Series, providing a label -> group name mapping.
>   - [x] For DataFrame objects, a string indicating a column to be used to group. Of course df.groupby('A') is just syntactic sugar for df.groupby(df['A']), but it makes life simpler.
>   - [x] For DataFrame objects, a string indicating an index level to be used to group.
>   - [x] A list of any of the above things.
> - **GroupBy object**
>   - [x] `sort=True/False`
>   - [ ] `GroupBy.groups`
>   - [x] Grouping by levels using `levels` argument
>   - [x] Grouping by a combination of levels and columns using a `Grouper` object
>   - [x] Column selection in groupby, e.g., `df.groupby('A')['C']`
>   - [x] Iterating through groups (`for name, group in df.groupby(..)`)
>   - [ ] Selecting a group (`df.groupby(...).get_group(...)`)
> - [ ] **Aggregation**
>   - [x] `mean()`
>   - [x] `sum()`
>   - [x] `size()`
>   - [x] `count()`
>   - [x] `std()`
>   - [x] `var()`
>   - [ ] `sem()`
>   - [x] `describe()`
>   - [ ] `first()`
>   - [ ] `last()`
>   - [x] `nth()`
>   - [x] `min()`
>   - [x] `max()`
>   - [x] `nunique()`
>   - [ ] Any function that reduces a `Series` to a single value (e.g., `df.groupby('a').agg(lambda s: 1)`.
>   - `agg()` interface
>     - [x] list
>     - [x] dict
>     - [ ] Named aggregation to control output column names (`df.groupby('a').agg(min_height=('col_name', 'agg_func'))`)
> - [ ] **Transformation**
>   - [ ] Transformation using `lambda` (`df.groupby('a').transform(lambda x: x - x.max())`)
>   - [ ] Broadcasting scalars to the size of each group when transforming (`df.groupby('a').transform(lambda x: x.max())`)
>   - [ ] Groupby rolling
> - [ ] **Filtration**
>   - [ ] `GroupBy.filter()`
> - [ ] **Dispatching to instance methods**
> - [ ] **Apply**
> - [ ] **Other features**
>   - [x] Exclusion of "nuisance" columns
>   - [ ] `observed` keyword for Categorical grouper
>   - [x] `NA` and `NaT` group handling
>   - [x] `Grouper` object
>   - [ ] `head()` and `tail()`
>   - [ ] `cumcount()`
> 
> ## What libcudf supports
> 
> Currently, `libcudf` supports the following aggregations for groupby:
> 
> ```
> COUNT_VALID
> COUNT_ALL
> SUM
> ARGMIN
> ARGMAX
> MIN
> MAX
> MEAN
> VARIANCE
> STD
> QUANTILE
> MEDIAN
> NUNIQUE
> NTH_ELEMENT
> ```
> 
> Only a subset of these aggregations are supported for string columns, namely:
> 
> ```
> COUNT_VALID
> COUNT_ALL
> ARGMIN
> ARGMAX
> MIN
> MAX
> NUNIQUE
> NTH_ELEMENT
> ```

**Comment by shwina** [comment] 2023-04-07 20:18
Just FYI, I just left a comment [here](https://github.com/rapidsai/cudf/issues/7354#issuecomment-1500609702) describing a simple workaround for `groupby.filter`, in case that is helpful to you.

**Comment by GregoryKimball** [comment] 2023-06-05 18:41
Thank you everyone for this discussion, I'll close this issue for now. It's a good outcome that the outdated content in the cuDF wiki is disabled.

**Closed by GregoryKimball** 2023-06-05 18:41 UTC
Labels: question, ? - Needs Triage
