### ISSUE TITLE
[BUG] Test run ends with rmm thrust::system::system_error

### ISSUE THREAD

**Issue by trxcllnt** [rapidsai/cudf#2002] opened 2019-06-14 16:29 UTC
**Describe the bug**
Test runs via `py.test -v -x` in the Dockerfile from a fresh check out ends with the following error:
```
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  rmm_allocator::deallocate(): RMM_FREE: initialization error
```

**Steps/Code to reproduce bug**
```sh
$ git clone --recurse-submodules -b branch-0.8 https://github.com/rapidsai/cudf && cd cudf
$ docker build --build-arg CUDA_VERSION="10.0" --build-arg LINUX_VERSION="ubuntu18.04" -t rapidsai/cudf:test .
$ docker run --rm rapidsai/cudf:test bash -c "cd /cudf && source activate cudf && py.test -v -x"
# ... test results ...
= 17012 passed, 719 skipped, 82 xfailed, 9 xpassed, 19295 warnings in 567.91 seconds =
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  rmm_allocator::deallocate(): RMM_FREE: initialization error
```

**Expected behavior**
The tests should complete normally.

**Environment details (please complete the following information):**
 - Environment location: Docker
 - Method of cuDF install: from source

<details>
<summary>Environment details:</summary>
<pre>
$ docker run --rm -e NVIDIA_VISIBLE_DEVICES=2 pataylor/rapidsai/cudf:test bash -c "cd /cudf && ./print_env.sh"
>
**git***
commit dff2b20fc4a680ce148477f4159041a655e05aaa (HEAD -> branch-0.8, origin/branch-0.8, origin/HEAD)
Merge: 144ce9a8 0466c0f8
Author: Vukasin Milovanovic <vukasin.milovanovic.87@gmail.com>
Date:   Thu Jun 13 16:33:19 2019 -0700

    Merge pull request #1981 from vuule/enh-ext-csv-cpp-api
    
    [REVIEW] Convert read_csv into a C++ API
**git submodules***
 b165e1fb11eeea64ccf95053e40f2424312599cc thirdparty/cub ((null))
fatal: not a git repository: /home/nfs/pataylor/dev/tmp/cudf/.git/modules/thirdparty/cub
fatal: failed to recurse into submodule 'thirdparty/cub'

***OS Information***
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
Linux a482960a5941 4.4.0-135-generic #161-Ubuntu SMP Mon Aug 27 10:45:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

***GPU Information***
Fri Jun 14 16:24:24 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.72       Driver Version: 410.72       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:0A:00.0 Off |                    0 |
| N/A   40C    P0    45W / 300W |     11MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

***CPU***
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              80
On-line CPU(s) list: 0-79
Thread(s) per core:  2
Core(s) per socket:  20
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               79
Model name:          Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
Stepping:            1
CPU MHz:             2682.109
CPU max MHz:         3600.0000
CPU min MHz:         1200.0000
BogoMIPS:            4389.87
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            51200K
NUMA node0 CPU(s):   0-19,40-59
NUMA node1 CPU(s):   20-39,60-79
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts flush_l1d

***CMake***

***g++***
/usr/bin/g++
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

***nvcc***
/usr/local/cuda/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

***Python***
/usr/bin/python
Python 2.7.15+

***Environment Variables***
PATH                            : /usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/conda/bin
LD_LIBRARY_PATH                 : /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/lib
NUMBAPRO_NVVM                   : /usr/local/cuda/nvvm/lib64/libnvvm.so
NUMBAPRO_LIBDEVICE              : /usr/local/cuda/nvvm/libdevice/
CONDA_PREFIX                    : 
PYTHON_PATH                     : 

***conda packages***
/conda/bin/conda
# packages in environment at /conda:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0  
ca-certificates           2019.5.15                     0  
certifi                   2019.3.9                 py37_0  
cffi                      1.12.2           py37h2e261b9_1  
chardet                   3.0.4                    py37_1  
conda                     4.6.14                   py37_0  
cryptography              2.6.1            py37h1ba5d50_0  
idna                      2.8                      py37_0  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libstdcxx-ng              8.2.0                hdf63c60_1  
ncurses                   6.1                  he6710b0_1  
openssl                   1.1.1c               h7b6447c_1  
pip                       19.0.3                   py37_0  
pycosat                   0.6.3            py37h14c3975_0  
pycparser                 2.19                     py37_0  
pyopenssl                 19.0.0                   py37_0  
pysocks                   1.6.8                    py37_0  
python                    3.7.3                h0371630_0  
readline                  7.0                  h7b6447c_5  
requests                  2.21.0                   py37_0  
ruamel_yaml               0.15.46          py37h14c3975_0  
setuptools                41.0.0                   py37_0  
six                       1.12.0                   py37_0  
sqlite                    3.27.2               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
urllib3                   1.24.1                   py37_0  
wheel                     0.33.1                   py37_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               h7b6447c_3  
</pre>
</details>

**Comment by harrism** [comment] 2019-06-19 04:01
Not likely an RMM issue. Remember that often uncaught previous exceptions / CUDA errors end up being reported when RMM checks for errors...  Likely due to improper error checking elsewhere.

**Comment by kkraus14** [comment] 2019-07-03 23:56
@trxcllnt Are you still experiencing this? We haven't been able to reproduce from what I've seen.

**Comment by trxcllnt** [comment] 2019-07-05 16:47
I wasn't seeing this for the past few weeks, then briefly started seeing it again the other day, but then it went away after the dask_cudf merge. So I'm not sure if it's been resolved with that merge, or if the addition of new tests doesn't tickle this bug anymore. We can close for now and reopen if it becomes an issue again.

**Comment by harrism** [comment] 2019-07-08 04:17
Thanks. Closing.

**Closed by harrism** 2019-07-08 04:17 UTC
Labels: RMM, bug, container, tests
