### ISSUE TITLE
[BUG]Buid fails about strings_column_factories.cuh to warp.cu

### ISSUE THREAD

**Issue by chenrui17** [rapidsai/cudf#7650] opened 2021-03-19 08:05 UTC
**Describe the bug**
/usr/local/cuda/bin/nvcc -forward-unknown-to-host-compiler -DBOOST_NO_CXX14_CONSTEXPR -DCUDA_API_PER_THREAD_DEFAULT_STREAM -DCUDF_VERSION=0.19.0 -DJITIFY_PRINT_LOG=0 -DJITIFY_USE_CACHE -DNVTX_DISABLE -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_OFF -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP -Dcudf_EXPORTS -I/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/build/_deps/dlpack-src/include -I/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/build/_deps/jitify-src -I/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/build/_deps/libcudacxx-src/include -I/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/include -I/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/build/include -I/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/src -I/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/build/_deps/arrow-src/cpp/src -I/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/build/_deps/arrow-src/cpp/src/generated -I/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/build/_deps/arrow-src/cpp/thirdparty/hadoop/include -I/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/build/_deps/arrow-src/cpp/thirdparty/flatbuffers/include -I/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/build/_deps/thrust-src -I/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/build/_deps/thrust-src/dependencies/cub -I/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/build/_deps/rmm-src/include -I/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/build/_deps/spdlog-src/include -isystem=/opt/rh/devtoolset-7/cmake/include -isystem=/usr/local/cuda/include -O3 -DNDEBUG --generate-code=arch=compute_60,code=[sm_60] --generate-code=arch=compute_70,code=[sm_70] --generate-code=arch=compute_75,code=[compute_75,sm_75] -Xcompiler=-fPIC --expt-extended-lambda --expt-relaxed-constexpr -Werror=cross-execution-space-call -Xcompiler=-Wall,-Werror,-Wno-error=deprecated-declarations -Xcompiler -pthread -std=c++14 -x cu -c /ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/src/strings/wrap.cu -o CMakeFiles/cudf.dir/src/strings/wrap.cu.o
/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/include/cudf/strings/detail/strings_column_factories.cuh: In instantiation of ‘cudf::strings::detail::make_strings_column(IndexPairIterator, IndexPairIterator, rmm::cuda_stream_view, rmm::mr::device_memory_resource*)::<lambda()> [with IndexPairIterator = const thrust::pair<const char*, int>*]’:
/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/include/cudf/strings/detail/strings_column_factories.cuh:108:179:   required from ‘struct cudf::strings::detail::make_strings_column(IndexPairIterator, IndexPairIterator, rmm::cuda_stream_view, rmm::mr::device_memory_resource*) [with IndexPairIterator = const thrust::pair<const char*, int>*]::<lambda()>’
/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/include/cudf/strings/detail/strings_column_factories.cuh:132:3:   required from ‘std::unique_ptr<cudf::column> cudf::strings::detail::make_strings_column(IndexPairIterator, IndexPairIterator, rmm::cuda_stream_view, rmm::mr::device_memory_resource*) [with IndexPairIterator = const thrust::pair<const char*, int>*]’
/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/src/strings/strings_column_factories.cu:53:93:   required from here
/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/include/cudf/strings/detail/strings_column_factories.cuh:99:40: internal compiler error: in maybe_undo_parenthesized_ref, at cp/semantics.c:1705
     auto const avg_bytes_per_row = bytes / std::max(strings_count - null_count, 1);
                                ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/include/cudf/strings/detail/strings_column_factories.cuh: In instantiation of ‘cudf::strings::detail::make_strings_column(IndexPairIterator, IndexPairIterator, rmm::cuda_stream_view, rmm::mr::device_memory_resource*)::<lambda()> [with IndexPairIterator = thrust::pair<const char*, int>*]’:
/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/include/cudf/strings/detail/strings_column_factories.cuh:108:179:   required from ‘struct cudf::strings::detail::make_strings_column(IndexPairIterator, IndexPairIterator, rmm::cuda_stream_view, rmm::mr::device_memory_resource*) [with IndexPairIterator = thrust::pair<const char*, int>*]::<lambda()>’
/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/include/cudf/strings/detail/strings_column_factories.cuh:132:3:   required from ‘std::unique_ptr<cudf::column> cudf::strings::detail::make_strings_column(IndexPairIterator, IndexPairIterator, rmm::cuda_stream_view, rmm::mr::device_memory_resource*) [with IndexPairIterator = thrust::pair<const char*, int>*]’
/tmp/tmpxft_00004fbf_00000000-5_split_record.compute_75.cudafe1.stub.c:16:431:   required from here
/ssd1/chenrui/build-cudf-2021-03-11/cudf/cpp/include/cudf/strings/detail/strings_column_factories.cuh:99:40: internal **compiler error: in maybe_undo_parenthesized_ref, at cp/semantics.c:1705
     auto const avg_bytes_per_row = bytes / std::max(strings_count - null_count, 1);**
                                ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.

**Steps/Code to reproduce bug**
 build libcudf with command `scl enable devtoolset-7 "java/ci/build-in-docker.sh"`

**Expected behavior**
build success

**Environment overview (please complete the following information)**
CentOS7.4 + gcc 7 + cuda10.2 + GPU V100

**Environment details**


**Additional context**

**Comment by chenrui17** [comment] 2021-03-19 11:09
It's likely a bug of gcc 7, and i switch to gcc 8, it's rework.

**Comment by davidwendt** [comment] 2021-03-19 13:13
I tried this with CentOS 7.9 that comes with docker image `nvidia/cuda:10.2-devel-centos7` and it does not fail for me with `gcc 7.5.0`.

**Comment by jlowe** [comment] 2021-03-19 13:19
We ran into the same issue with devtoolset-7 in the JNI build and switched to devtoolset-8 in #7645.  Closing this since it's not a bug in the libcudf source but rather a bug in the compiler.  Updating the compiler fixes the issue.

**Closed by jlowe** 2021-03-19 13:19 UTC
Labels: ? - Needs Triage, bug

**Comment by davidwendt** [comment] 2021-03-19 15:23
I was actually able to reproduce this with nvidia/cuda:10.2-devel-centos7 docker image using `gcc 7.5.0`
After doing some googling I found a work-around that got past the error. I will post a PR.
