### ISSUE TITLE
[QST] How do you extend the dataframe?

### ISSUE THREAD

**Issue by achapkowski** [rapidsai/cudf#3208] opened 2019-10-24 09:31 UTC
**What is your question?**
In the Pandas' ecosystem I can extend the dataframe by write extension arrays and accessors.  Does the `cuDF` have extension patterns?  The documentation doesn't describe this, but I am hoping it is an oversight.  

Though the product is great, it does not 100% fit the needs of the field I work in, so if I could create a subset of tools to work with the `cuDF` it would make life easier.

**Comment by thomcom** [comment] 2019-10-24 17:47
Hi @achapkowski, we've recently begun development on https://github.com/rapidsai/cuspatial. We're interested in finding more contributors from the geospatial community, so if you have comments, concerns, or recommendations, please let us know! `cuspatial` is going to be the best place to ask for geo specific implementations, and everything is built upon the same `cuDF` backbone.

As for extensions, it looks pretty straightforward to add extension accessors to `DataFrame`. I don't think that extension arrays are likely in the near future, as GPU support in `cuDF` depends on specific typed arrays that are readily accelerated in `CUDA`. New types would generally require new `CUDA` implementations - unless the types were simply wrappers for types that already exist in `cuDF`.

**Comment by achapkowski** [comment] 2019-10-24 18:15
@thomcom I looked at the project and it seems interesting.  I am concerned of the lack of types on Geometry objects and a few other things... I'll explore more and see if/how I can contribute.  

Thank you for the quick response.

**Comment by jonmmease** [comment] 2020-01-02 17:50
Hi, I'd like to follow up on this issue with a particular use case.

We've recently added cudf support to the datashader project, making it possible for datashader to aggregate points/lines from coordinates stored in the columns of a cudf `DataFrame`.  We've also recently added support to Datashader for aggregating polygons. Through the pandas/dask extension array system, we were able to develop extension arrays for storing columns of polygons/multipolygons in a pandas/dask `DataFrame` (These extension arrays are part of the new [`spatialpandas`](https://github.com/holoviz/spatialpandas) project).

Pandas allows extension arrays to be represented using arbitrary python data structures, which obviously would not be compatible with cudf's memory model. Our extension arrays store the polygon coordinates as nested `pyarrow` `ListArray` objects. My understanding is that cudf uses the arrow memory format, and so I wonder if it would be feasible for cudf to support extension arrays based on pyarrow array types.

If this were possible, then I think could add support to datashader for aggregating polygons using cudf.

cc @jbednar

**Comment by kkraus14** [comment] 2020-01-02 18:03
@jonmmease We're currently designing the cuDF equivalents of Arrow ListArray and StructArray. These will be first class supported dtypes and as far as I'm aware will follow the Arrow memory layout and be able to nicely round trip through Arrow without any conversions. Would support for those and associated type specific methods for those types solve your needs or do you need an ExtensionArray type system?

**Comment by jonmmease** [comment] 2020-01-02 19:11
> We're currently designing the cuDF equivalents of Arrow ListArray and StructArray. 

That sounds great.  Yeah, this would be enough for datashader to have a representation to iterate over. An ExtensionArray type system on top of this would still be useful in order to make it possible to define custom validation logic (e.g. Polygons must be closed) and to support GeoPandas style properties (e.g. `df.polys.area`).

But now that I think about it, perhaps an easier alternative would be to support subclassing `ListArray`/`StructArray`.

**Comment by kkraus14** [comment] 2020-01-02 19:21
> Yeah, this would be enough for datashader to have a representation to iterate over.

To be clear, in order for efficient execution on the GPU you can't iterate in Python or even on the CPU in C/C++. Unsure if that was a wording thing, but this won't be a Pandas `object` column where each row is an Arrow ListArray, but instead the entire column will have the memory layout of a ListArray.

You can still directly access the memory buffers underneath the column to use via Numba, which I hope combined with the built in functions we'll support will be enough for your use cases.

**Comment by jonmmease** [comment] 2020-01-02 19:35
Yes, datashader is entirely based on numba so by "iterate" I meant executing numba cuda kernels on the GPU buffers.

**Comment by kkraus14** [comment] 2020-05-29 16:44
Closing as duplicate of #514

**Closed by kkraus14** 2020-05-29 16:44 UTC
Labels: cuDF (Python), feature request
