### ISSUE TITLE
[BUG] cuDF python to_dlpack gpu memory leak

### ISSUE THREAD

**Issue by jperez999** [rapidsai/cudf#2400] opened 2019-07-25 22:25 UTC
When creating a dlpack from a cudf dataframe, using .to_dlpack(), GPU memory is leaked.

**Steps/Code to reproduce bug**
The following code shows the memory leak. Running only one loop utilizes 1852MiB (nvidia-smi). All five runs ends using 4970MiB (nvidia-smi).
```
for i in range(5):
    x = cudf.DataFrame([('a', list(range(34000000))),
                        ('b', list(reversed(range(34000000)))),
                        ('c', list(range(34000000)))])
    y = x.to_dlpack()
    b = torch.utils.dlpack.from_dlpack(y)
    a = b.to(device='cpu')
    del x,y,b
    torch.cuda.empty_cache()
    gc.collect()
```

**Expected behavior**
This should use the same memory over and over. The following methods using cupy and pytorch work as expected.

cupy:
```
for i in range(5):
    x = torch.randn((34000000, 2)) 
    q = x.to(device='cuda')
    y = torch.utils.dlpack.to_dlpack(q)
    z = cupy.fromDlpack(y)
    b = torch.utils.dlpack.from_dlpack(z.toDlpack())
    a = b.to(device='cpu')
    del x,q,y,z,b
    torch.cuda.empty_cache()
    gc.collect()
```
pytorch:
```
for i in range(5):
    x = torch.randn((34000000, 2)) 
    q = x.to(device='cuda')
    y = torch.utils.dlpack.to_dlpack(x)
    z = torch.utils.dlpack.from_dlpack(y)
    a = z.to(device='cpu')
    del x,q,y,z
    torch.cuda.empty_cache()
    gc.collect()
```

**Environment overview**
 - Environment location: docker
 - Method of cuDF install: rapids container
   - If method of install is [Docker]:  Custom container using rapidsai as source. 
```
docker run --runtime=nvidia --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 -p 3000:3000 --ipc=host --name dev_jump <internal_gitlab_ecr>/rapidsdl/docker:rapidsdl
```

**Environment details**

```
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     Not inside a git repository
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=16.04
     DISTRIB_CODENAME=xenial
     DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
     NAME="Ubuntu"
     VERSION="16.04.6 LTS (Xenial Xerus)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 16.04.6 LTS"
     VERSION_ID="16.04"
     HOME_URL="http://www.ubuntu.com/"
     SUPPORT_URL="http://help.ubuntu.com/"
     BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
     VERSION_CODENAME=xenial
     UBUNTU_CODENAME=xenial
     Linux ae7a5bcc2a1f 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Thu Jul 25 22:23:02 2019
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla V100-SXM2...  Off  | 00000000:06:00.0 Off |                    0 |
     | N/A   36C    P0    55W / 300W |  21597MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla V100-SXM2...  On   | 00000000:07:00.0 Off |                    0 |
     | N/A   33C    P0    43W / 300W |     11MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla V100-SXM2...  On   | 00000000:0A:00.0 Off |                    0 |
     | N/A   34C    P0    54W / 300W |  14183MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   3  Tesla V100-SXM2...  On   | 00000000:0B:00.0 Off |                    0 |
     | N/A   33C    P0    55W / 300W |  27230MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   4  Tesla V100-SXM2...  On   | 00000000:85:00.0 Off |                    0 |
     | N/A   32C    P0    43W / 300W |     11MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   5  Tesla V100-SXM2...  On   | 00000000:86:00.0 Off |                    0 |
     | N/A   35C    P0    54W / 300W |    502MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   6  Tesla V100-SXM2...  On   | 00000000:89:00.0 Off |                    0 |
     | N/A   38C    P0    57W / 300W |   4970MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   7  Tesla V100-SXM2...  On   | 00000000:8A:00.0 Off |                    0 |
     | N/A   33C    P0    55W / 300W |  23202MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:          x86_64
     CPU op-mode(s):        32-bit, 64-bit
     Byte Order:            Little Endian
     CPU(s):                80
     On-line CPU(s) list:   0-79
     Thread(s) per core:    2
     Core(s) per socket:    20
     Socket(s):             2
     NUMA node(s):          2
     Vendor ID:             GenuineIntel
     CPU family:            6
     Model:                 79
     Model name:            Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
     Stepping:              1
     CPU MHz:               3054.476
     CPU max MHz:           3600.0000
     CPU min MHz:           1200.0000
     BogoMIPS:              4392.06
     Virtualization:        VT-x
     L1d cache:             32K
     L1i cache:             32K
     L2 cache:              256K
     L3 cache:              51200K
     NUMA node0 CPU(s):     0-19,40-59
     NUMA node1 CPU(s):     20-39,60-79
     Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts flush_l1d
     
     ***CMake***
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
     Copyright (C) 2015 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2018 NVIDIA Corporation
     Built on Sat_Aug_25_21:08:01_CDT_2018
     Cuda compilation tools, release 10.0, V10.0.130
     
     ***Python***
     /conda/envs/rapids/bin/python
     Python 3.6.8
     
     ***Environment Variables***
     PATH                            : /conda/envs/rapids/bin:/conda/condabin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/conda/bin
     LD_LIBRARY_PATH                 : /usr/local/nvidia/lib:/usr/local/nvidia/lib64
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /conda/envs/rapids
     PYTHON_PATH                     :
     
     ***conda packages***
     /conda/condabin/conda
     # packages in environment at /conda/envs/rapids:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     aiohttp                   3.5.4                    pypi_0    pypi
     altair                    3.1.0                    pypi_0    pypi
     argparse                  1.4.0                    pypi_0    pypi
     arrow-cpp                 0.12.1           py36h0e61e49_0    conda-forge
     arviz                     0.4.1                      py_0    conda-forge
     asn1crypto                0.24.0                   py36_0
     async-timeout             3.0.1                    pypi_0    pypi
     atomicwrites              1.3.0                      py_0    conda-forge
     attrs                     19.1.0                     py_0    conda-forge
     backcall                  0.1.0                      py_0    conda-forge
     beautifulsoup4            4.7.1                    py36_1
     binutils_impl_linux-64    2.31.1               h6176602_1
     binutils_linux-64         2.31.1               h6176602_7
     blas                      1.0                    openblas
     bleach                    3.1.0                      py_0    conda-forge
     block-bootstrap-pytorch   0.1.5                    pypi_0    pypi
     bokeh                     1.2.0                    py36_0
     boost-cpp                 1.68.0            h11c811c_1000    conda-forge
     bootstrap-pytorch         0.0.13                   pypi_0    pypi
     bottleneck                1.2.1            py36h035aef0_1
     bzip2                     1.0.6             h14c3975_1002    conda-forge
     ca-certificates           2019.6.16            hecc5488_0    conda-forge
     certifi                   2019.6.16                py36_1    conda-forge
     cffi                      1.12.3           py36h8022711_0    conda-forge
     cftime                    1.0.3.4         py36hd352d35_1001    conda-forge
     chardet                   3.0.4                    py36_1
     clang_variant             1.0               cling_6.14.06    conda-forge
     clangdev                  5.0.0             h935a590_1004    conda-forge
     click                     7.0                        py_0    conda-forge
     cling                     0.5               he860b03_1007    conda-forge
     cloudpickle               1.2.1                      py_0    conda-forge
     colr                      0.8.9                    pypi_0    pypi
     cppzmq                    4.3.0             hc9558a2_1001    conda-forge
     cryptography              2.6.1            py36h1ba5d50_0
     cudatoolkit               10.0.130                      0
     cudf                      0.8.0                    py36_0    rapidsai/label/cuda10.0
     cugraph                   0.8.1                    py36_0    rapidsai/label/cuda10.0
     cuml                      0.8.0           cuda10.0_py36_0    rapidsai/label/cuda10.0
     cupy-cuda100              6.2.0                    pypi_0    pypi
     curl                      7.65.2               hbc83047_0
     cycler                    0.10.0                     py_1    conda-forge
     cymem                     2.0.2            py36hfd86e86_0
     cython                    0.29.12          py36he6710b0_0    anaconda
     cytoolz                   0.9.0.1         py36h14c3975_1001    conda-forge
     dask                      2.0.0                      py_0    conda-forge
     dask-core                 2.0.0                      py_0    conda-forge
     dask-cuda                 0.8.0                    py36_0    rapidsai/label/cuda10.0
     dask-cudf                 0.8.0                    py36_0    rapidsai/label/cuda10.0
     dask-cuml                 0.8.0                    py36_0    rapidsai/label/cuda10.0
     dask-xgboost              0.2.0.dev28      cuda10.0py37_0    rapidsai/label/xgboost
     dataclasses               0.6                      py36_0    fastai
     dbus                      1.13.6               he372182_0    conda-forge
     decorator                 4.4.0                      py_0    conda-forge
     defusedxml                0.5.0                      py_1    conda-forge
     dill                      0.2.9                    py36_0
     distributed               2.0.1+1.gf8af742          pypi_0    pypi
     dragonfly-opt             0.1.3                    pypi_0    pypi
     entrypoints               0.3                   py36_1000    conda-forge
     expat                     2.2.5             he1b5a44_1003    conda-forge
     fastai                    1.0.55                        1    fastai
     fastprogress              0.1.21                     py_0    fastai
     fastrlock                 0.4                      pypi_0    pypi
     fontconfig                2.13.1            he4413a7_1000    conda-forge
     freetype                  2.10.0               he983fc9_0    conda-forge
     future                    0.17.1                   pypi_0    pypi
     gcc_impl_linux-64         7.3.0                habb00fd_1    conda-forge
     gcc_linux-64              7.3.0                h553295d_7    conda-forge
     gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
     glib                      2.58.3            h6f030ca_1001    conda-forge
     gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
     gstreamer                 1.14.5               h36ae1b5_0    conda-forge
     gxx_impl_linux-64         7.3.0                hdf63c60_1    conda-forge
     gxx_linux-64              7.3.0                h553295d_7    conda-forge
     h5py                      2.9.0           nompi_py36hf008753_1102    conda-forge
     hdf4                      4.2.13            h9a582f1_1002    conda-forge
     hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
     heapdict                  1.0.0                 py36_1000    conda-forge
     icu                       58.2              hf484d3e_1000    conda-forge
     idna                      2.8                      py36_0
     idna-ssl                  1.1.0                    pypi_0    pypi
     ignite                    0.2.0                    py36_0    pytorch
     importlib_metadata        0.18                     py36_0    conda-forge
     intel-openmp              2019.4                      243
     ipdb                      0.12                     pypi_0    pypi
     ipykernel                 5.1.1            py36h5ca1d4c_0    conda-forge
     ipython                   7.3.0            py36h24bf2e0_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     ipywidgets                7.5.0                      py_0    conda-forge
     jedi                      0.14.0                   py36_0    conda-forge
     jinja2                    2.10.1                     py_0    conda-forge
     joblib                    0.13.2                     py_0    conda-forge
     jpeg                      9c                h14c3975_1001    conda-forge
     json5                     0.8.4                      py_0    conda-forge
     jsonschema                3.0.1                    py36_0    conda-forge
     jupyter-server-proxy      1.1.0                    pypi_0    pypi
     jupyter_client            5.3.1                      py_0    conda-forge
     jupyter_core              4.4.0                      py_0    conda-forge
     jupyterlab                1.0.2                    py36_0    conda-forge
     jupyterlab-bokeh-server   0.2.0                    pypi_0    pypi
     jupyterlab_server         1.0.0                      py_1    conda-forge
     kiwisolver                1.1.0            py36hc9558a2_0    conda-forge
     krb5                      1.16.1               h173b8e3_7
     libblas                   3.8.0                7_openblas    conda-forge
     libcblas                  3.8.0                7_openblas    conda-forge
     libcudf                   0.8.0                cuda10.0_0    rapidsai/label/cuda10.0
     libcugraph                0.8.1                cuda10.0_0    rapidsai/label/cuda10.0
     libcuml                   0.8.0                cuda10.0_0    rapidsai/label/cuda10.0
     libcumlmg                 0.0.0.dev0         cuda10.0_373    nvidia/label/cuda10.0
     libcurl                   7.65.2               h20c2e04_0
     libedit                   3.1.20181209         hc058e9b_0
     libffi                    3.2.1                hd88cf55_4
     libgcc-ng                 9.1.0                hdf63c60_0
     libgfortran-ng            7.3.0                hdf63c60_0
     libgpuarray               0.7.6             h14c3975_1003    conda-forge
     libiconv                  1.15              h516909a_1005    conda-forge
     liblapack                 3.8.0                7_openblas    conda-forge
     libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
     libnvstrings              0.8.0                cuda10.0_0    rapidsai/label/cuda10.0
     libopenblas               0.2.20               h9ac9557_7
     libpng                    1.6.37               hed695b0_0    conda-forge
     libprotobuf               3.6.1             hdbcaa40_1001    conda-forge
     librmm                    0.8.0                cuda10.0_0    rapidsai/label/cuda10.0
     libsodium                 1.0.17               h516909a_0    conda-forge
     libssh2                   1.8.2                h22169c7_2    conda-forge
     libstdcxx-ng              9.1.0                hdf63c60_0
     libtiff                   4.0.10            h57b8799_1003    conda-forge
     libuuid                   2.32.1            h14c3975_1000    conda-forge
     libxcb                    1.13              h14c3975_1002    conda-forge
     libxgboost                0.90.rapidsdev1      cuda10.0_1    rapidsai/label/xgboost
     libxml2                   2.9.9                h13577e0_0    conda-forge
     lightgbm                  2.2.1            py36he6710b0_0
     llvmlite                  0.27.0dev0      py36hf484d3e_19    numba
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     mako                      1.0.10                     py_0    conda-forge
     markupsafe                1.1.1            py36h14c3975_0    conda-forge
     matplotlib                3.1.0            py36h5429711_0
     mistune                   0.8.4           py36h14c3975_1000    conda-forge
     mkl                       2019.4                      243
     more-itertools            4.3.0                 py36_1000    conda-forge
     msgpack-numpy             0.4.3.2                  py36_0
     msgpack-python            0.6.1            py36h6bb024c_0    conda-forge
     multidict                 4.5.2                    pypi_0    pypi
     munch                     2.3.2                    pypi_0    pypi
     murmurhash                1.0.2            py36he6710b0_0
     nbconvert                 5.5.0                      py_0    conda-forge
     nbformat                  4.4.0                      py_1    conda-forge
     nccl                      2.4.6.1              cuda10.0_0    nvidia
     ncurses                   6.1                  he6710b0_1
     netcdf4                   1.5.1.2          py36had58050_0    conda-forge
     networkx                  2.3                        py_0    conda-forge
     ninja                     1.9.0            py36hfd86e86_0
     nlohmann_json             3.6.1                he1b5a44_0    conda-forge
     notebook                  6.0.0                    py36_0    conda-forge
     numba                     0.41.0          py36h637b7d7_1000    conda-forge
     numexpr                   2.6.5           py36_nomklhaa809a4_0  [nomkl]
     numpy                     1.16.2           py36h8b7e671_1    conda-forge
     nvidia-ml-py3             7.352.0                    py_0    fastai
     nvstrings                 0.8.0                    py36_0    rapidsai/label/cuda10.0
     olefile                   0.46                       py_0    conda-forge
     openblas                  0.3.5             h9ac9557_1001    conda-forge
     opencv-python             4.1.0.25                 pypi_0    pypi
     openssl                   1.1.1c               h516909a_0    conda-forge
     packaging                 19.0                       py_0    conda-forge
     pandas                    0.23.4          py36h637b7d7_1000    conda-forge
     pandas-profiling          1.4.1                    py36_0
     pandoc                    2.7.3                         0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     parquet-cpp               1.5.1                         4    conda-forge
     parso                     0.5.0                      py_0    conda-forge
     partd                     1.0.0                      py_0    conda-forge
     patsy                     0.5.1                      py_0    conda-forge
     pcre                      8.41              hf484d3e_1003    conda-forge
     pexpect                   4.7.0                    py36_0    conda-forge
     pickleshare               0.7.5                 py36_1000    conda-forge
     pillow                    5.3.0           py36h00a061d_1000    conda-forge
     pip                       19.1.1                   py36_0
     plac                      0.9.6                    py36_0
     plotly                    4.0.0                    pypi_0    pypi
     pluggy                    0.12.0                     py_0    conda-forge
     preshed                   2.0.1            py36he6710b0_0
     pretrainedmodels          0.7.4                    pypi_0    pypi
     prometheus_client         0.7.1                      py_0    conda-forge
     prompt_toolkit            2.0.9                      py_0    conda-forge
     protobuf                  3.9.0                    pypi_0    pypi
     psutil                    5.6.3            py36h516909a_0    conda-forge
     pthread-stubs             0.4               h14c3975_1001    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     py                        1.8.0                      py_0    conda-forge
     py-cpuinfo                5.0.0                    pypi_0    pypi
     py-xgboost                0.90.rapidsdev1  cuda10.0py36_1    rapidsai/label/xgboost
     pyarrow                   0.12.1           py36hbbcf98d_0    conda-forge
     pybench                   0.0.0.dev0                dev_0    <develop>
     pycparser                 2.19                     py36_1    conda-forge
     pygments                  2.4.2                      py_0    conda-forge
     pygpu                     0.7.6           py36h3010b51_1000    conda-forge
     pymc3                     3.7                        py_0    conda-forge
     pyopenssl                 19.0.0                   py36_0
     pyparsing                 2.4.0                      py_0    conda-forge
     pyqt                      5.9.2            py36hcca6a23_0    conda-forge
     pyrsistent                0.15.2           py36h516909a_0    conda-forge
     pysocks                   1.7.0                    py36_0
     pytest                    4.6.3                    py36_0    conda-forge
     pytest-benchmark          3.2.2                    pypi_0    pypi
     python                    3.6.8                h0371630_0
     python-dateutil           2.8.0                      py_0    conda-forge
     pytorch                   1.1.0           py3.6_cuda10.0.130_cudnn7.5.1_0    pytorch
     pytz                      2019.1                     py_0    conda-forge
     pyyaml                    5.1.1            py36h516909a_0    conda-forge
     pyzmq                     18.0.2           py36h1768529_2    conda-forge
     qt                        5.9.7                h52cfd70_2    conda-forge
     readline                  7.0                  h7b6447c_5
     regex                     2018.01.10      py36h14c3975_1000    fastai
     requests                  2.22.0                   py36_0
     retrying                  1.3.3                    pypi_0    pypi
     rmm                       0.8.0                    py36_0    rapidsai/label/cuda10.0
     scikit-learn              0.21.2           py36hcdab131_1    conda-forge
     scipy                     1.3.0            py36h921218d_0    conda-forge
     seaborn                   0.9.0                      py_0    conda-forge
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                41.0.1                   py36_0
     simpervisor               0.3                      pypi_0    pypi
     sip                       4.19.8          py36hf484d3e_1000    conda-forge
     six                       1.12.0                py36_1000    conda-forge
     skipthoughts              0.0.0                    pypi_0    pypi
     snakeviz                  1.0.0                    py36_0
     sortedcontainers          2.1.0                      py_0    conda-forge
     soupsieve                 1.8                      py36_0
     spacy                     2.0.18          py36hf484d3e_1000    fastai
     sqlite                    3.28.0               h7b6447c_0
     statsmodels               0.10.0           py36hc1659b7_0    conda-forge
     tabulate                  0.8.3                    pypi_0    pypi
     tblib                     1.4.0                      py_0    conda-forge
     tensorboardx              1.8                      pypi_0    pypi
     termcolor                 1.1.0                    pypi_0    pypi
     terminado                 0.8.2                    py36_0    conda-forge
     testpath                  0.4.2                   py_1001    conda-forge
     theano                    1.0.4           py36hf484d3e_1000    conda-forge
     thinc                     6.12.1          py36h637b7d7_1000    fastai
     thrift-cpp                0.12.0            h0a07b25_1002    conda-forge
     tk                        8.6.8                hbc83047_0
     toolz                     0.9.0                      py_1    conda-forge
     torchvision               0.3.0           py36_cu10.0.130_1    pytorch
     tornado                   6.0.3            py36h516909a_0    conda-forge
     tqdm                      4.32.1                     py_0
     traitlets                 4.3.2                 py36_1000    conda-forge
     typing                    3.6.4                    py36_0
     typing-extensions         3.7.4                    pypi_0    pypi
     ujson                     1.35             py36h14c3975_0
     urllib3                   1.24.2                   py36_0
     wcwidth                   0.1.7                      py_1    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     wheel                     0.33.4                   py36_0
     widgetsnbextension        3.5.0                    py36_0    conda-forge
     wrapt                     1.10.11          py36h14c3975_2
     xarray                    0.12.3                     py_0    conda-forge
     xeus                      0.21.1               h4d8c418_2    conda-forge
     xeus-cling                0.7.1                he513fc3_0    conda-forge
     xgboost                   0.90.rapidsdev1  cuda10.0py36_1    rapidsai/label/xgboost
     xorg-libxau               1.0.9                h14c3975_0    conda-forge
     xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
     xtl                       0.6.5                hc9558a2_0    conda-forge
     xz                        5.2.4                h14c3975_4
     yaml                      0.1.7             h14c3975_1001    conda-forge
     yarl                      1.3.0                    pypi_0    pypi
     zeromq                    4.3.2                he1b5a44_2    conda-forge
     zict                      1.0.0                      py_0    conda-forge
     zipp                      0.5.1                      py_0    conda-forge
     zlib                      1.2.11               h7b6447c_3
     zstd                      1.4.0                h3b9ef0a_0    conda-forge
```

**Comment by kkraus14** [comment] 2019-08-02 00:39
Confirmed this and am triaging, looks like a memory leak somewhere in libcudf but haven't pinpointed it quite yet.

**Comment by harrism** [comment] 2019-08-09 03:52
I need a repro that doesn't depend on pytorch or containers. Is that possible?

**Comment by harrism** [comment] 2019-08-09 04:31
This code will actually run. The code in the description is missing imports.

```
import cudf
import torch
import torch.utils.dlpack
import gc

for i in range(5):
  x = cudf.DataFrame([('a', list(range(34000000))),
                      ('b', list(reversed(range(34000000)))),
                      ('c', list(range(34000000)))])
  y = x.to_dlpack()
  b = torch.utils.dlpack.from_dlpack(y)
  a = b.to(device='cpu')
  del x,y,b
  torch.cuda.empty_cache()
  gc.collect()
```

**Comment by harrism** [comment] 2019-08-09 05:23
@kkraus14 in dlpack.pyx I did some simple print debugging of the following function by adding print statements.

```
cdef void dlmanaged_tensor_pycapsule_deleter(object pycap_obj):
    print("pycapsule deleter called")
    cdef DLManagedTensor* dlpack_tensor= <DLManagedTensor*>0
    try:
        dlpack_tensor = <DLManagedTensor*>pycapsule.PyCapsule_GetPointer(
            pycap_obj, 'used_dltensor')
        print("used_dltensor: not calling dlpack_tensor deleter")
        return  # we do not call a used capsule's deleter
    except Exception:
        dlpack_tensor = <DLManagedTensor*>pycapsule.PyCapsule_GetPointer(
            pycap_obj, 'dltensor')
        print("dltensor unused")
    print("Calling dlpack_tensor deleter")
    dlpack_tensor.deleter(dlpack_tensor)
```

I get this output:

```
pycapsule deleter called
used_dltensor: not calling dlpack_tensor deleter
pycapsule deleter called
used_dltensor: not calling dlpack_tensor deleter
pycapsule deleter called
used_dltensor: not calling dlpack_tensor deleter
pycapsule deleter called
used_dltensor: not calling dlpack_tensor deleter
pycapsule deleter called
used_dltensor: not calling dlpack_tensor deleter
```

That explains the leak: the pycapsule deleter is being called, but when it sees `used_dltensor` it chooses not to call the libcudf `dlpack_tensor`'s deleter.

This is because Pytorch `from_dlpack` sets the tensor pycapsule's name to `used_dltensor` so we never get a chance to delete it...

 https://github.com/pytorch/pytorch/blob/02d3c302d85ff2126e8d75f13b0f187a70580952/torch/csrc/Module.cpp#L399-L400

I'm not sure what the right thing to do here is, but the memory leak is not in the libcudf C++ code, since it doesn't deal with pycapsules.

**Comment by harrism** [comment] 2019-08-09 05:32
Looking at other implementations of from_dlpack, it appears that the intent is for from_dlpack to take the memory pointer directly out of the dl_tensor struct and use it in the receiving library. The creating library no longer owns that memory and so the dl_tensor is marked as used so that passing it to another from_dlpack will fail. Is this correct? 

In this case I would think that it's the responsibility of the owner (the library that implements from_dlpack) to call the dl_tensor.deleter  when it is finished.

**Comment by harrism** [comment] 2019-08-09 05:49
Hmmm, it appears the pytorch should call the dltensor deleter after it takes ownership. https://github.com/pytorch/pytorch/blob/02d3c302d85ff2126e8d75f13b0f187a70580952/torch/csrc/Module.cpp#L385-L388

Unfortunately I can't figure out how to get cuDF to use a custom-built RMM right now since RMM was moved to conda, so I can't figure out how to check if the deleter is called. @kkraus14 what is the new process for getting cuDF cmake to find my local RMM repo instead of the one in conda?

**Closed** 2019-08-09 11:53 UTC
Labels: bug, cuDF (Python), libcudf (C++/CUDA)
