### ISSUE TITLE
[BUG]TypeError: String Arrays is not yet implemented in cudf

### ISSUE THREAD

**Issue by robomike** [rapidsai/cudf#12989] opened 2023-03-22 00:30 UTC
A few notes:
I downloaded the nightly build of 23.04 
1.  My code worked in previous versions.
2. This is my data: 

  | Unnamed: 0 | Date | Customer_ID | SKU_Category | SKU | Quantity | Sales_Amount
-- | -- | -- | -- | -- | -- | -- | --
1 | 1.454285e+09 | 2547 | X52 | 63.0 | 1.0 | 3.13
2 | 1.454285e+09 | 822 | 2ML | 922.0 | 1.0 | 5.46
3 | 1.454285e+09 | 3686 | 0H2 | 1932.0 | 1.0 | 6.35
4 | 1.454285e+09 | 3719 | 0H2 | 776.0 | 1.0 | 5.59
5 | 1.454285e+09 | 9200 | 0H2 | 2971.0 | 1.0 | 6.88

This is my code:

```python
#divide into training and test data
tempX=df[['Date','SKU','Customer_ID']]
tempY=df['Quantity']
x_train, x_test, y_train, y_test = cuml.train_test_split(tempX, tempY, train_size=0.2)
```

This is my error:

```
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?53a34625-7c91-43dc-bc93-1ef4e2c51593)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/miniconda3/envs/rapids-23.04/lib/python3.10/site-packages/cudf/utils/utils.py:273, in GetAttrGetItemMixin.__getattr__(self, key)
    272 try:
--> 273     return self[key]
    274 except KeyError:

File ~/miniconda3/envs/rapids-23.04/lib/python3.10/contextlib.py:79, in ContextDecorator.__call__.<locals>.inner(*args, **kwds)
     78 with self._recreate_cm():
---> 79     return func(*args, **kwds)

File ~/miniconda3/envs/rapids-23.04/lib/python3.10/site-packages/cudf/core/dataframe.py:1161, in DataFrame.__getitem__(self, arg)
   1160 if _is_scalar_or_zero_d_array(arg) or isinstance(arg, tuple):
-> 1161     return self._get_columns_by_label(arg, downcast=True)
   1163 elif isinstance(arg, slice):

File ~/miniconda3/envs/rapids-23.04/lib/python3.10/contextlib.py:79, in ContextDecorator.__call__.<locals>.inner(*args, **kwds)
     78 with self._recreate_cm():
---> 79     return func(*args, **kwds)

File ~/miniconda3/envs/rapids-23.04/lib/python3.10/site-packages/cudf/core/dataframe.py:1905, in DataFrame._get_columns_by_label(self, labels, downcast)
   1900 """
   1901 Return columns of dataframe by `labels`
   1902 
   1903 If downcast is True, try and downcast from a DataFrame to a Series
...
   5558     Return a CuPy representation of the StringColumn.
   5559     """
-> 5560     raise TypeError("String Arrays is not yet implemented in cudf")

TypeError: String Arrays is not yet implemented in cudf
```

**Comment by bdice** [comment] 2023-03-22 03:58
Hi @robomike, thanks for filing this issue. This is a better issue for the [cuML repository](https://github.com/rapidsai/cuml), but I can attempt to answer here. It looks like cuML only supports splitting DataFrames with numeric data. For example, this works for me:

```python
import cudf
import cuml

df = cudf.DataFrame({
    "Date": [2547, 822, 3686, 3719, 9200],
    "Customer_ID": ["X52", "2ML", "0H2", "0H2", "0H2"],
    "SKU": [1.0, 1.0, 1.0, 1.0, 1.0],
    "Quantity": [3.13, 5.46, 6.35, 5.59, 6.88],
})

X = df[["Date", "SKU"]]
Y = df["Quantity"]

X_train, X_test, Y_train, Y_test = cuml.train_test_split(X, Y, train_size=0.6)

print("X_train:\n", X_train)
print("X_test:\n", X_test)
```

The result varies by random seed, but one sample output is:
```
X_train:
    Date  SKU
4  9200  1.0
3  3719  1.0
2  3686  1.0
X_test:
    Date  SKU
0  2547  1.0
1   822  1.0
```

One potential workaround that would support strings would be to split the training/test data using `cudf` directly. You can do that using code like this:

```python
# Randomly shuffle the input rows
df = df.sample(frac=1)

# Use the first 20% of the indices for training, matching the example above
train_indices = range(0, len(df) // 5)
test_indices = range(len(df) // 5, len(df))
df_train = df.iloc[train_indices]
df_test = df.iloc[test_indices]
```

Hope that helps!

**Comment by robomike** [comment] 2023-03-22 13:42
@bdice 
![image](https://user-images.githubusercontent.com/4317367/226922678-a71f62a5-dee8-4a96-8c0e-af063efdbf9a.png)

The image shows that this actually works as expected in the stable version.  It is broken in the nightly build.  And it is a cuDF error.

**Comment by vyasr** [comment] 2024-05-17 18:17
There are a couple of issues here. The columns in the dataframe above are not all numerical: the "Customer_ID" column is a string. This is the cause of the "String Arrays is not yet implemented in cudf" error:
```
In [133]: X = cudf.DataFrame({
     ...:      "Date": [2547, 822, 3686, 3719, 9200],
     ...:      "SKU": [1.0, 1.0, 1.0, 1.0, 1.0],
     ...:      "Customer_ID": ["X52", "2ML", "0H2", "0H2", "0H2"],
     ...: })

In [134]: X["Customer_ID"].to_cupy()
...
TypeError: String Arrays is not yet implemented in cudf
```

As for why this is happening, we need to dig into cuml's code base for why it is trying to convert a cudf column into a cupy array. That is not in general a valid operation because cudf supports some data types that cupy does not. Therefore, any cuml code path that needs to support those additional types cannot convert to cupy. Given that this code worked before 23.04 according to the OP, that suggests that something changed in cuml's implementation between 23.02 and 23.04 where cuml started requesting a cupy array from cudf where it did not do so previously.

It looks like this issue was raised recently in cuml as well in https://github.com/rapidsai/cuml/issues/5834, so I'm going to close this issue for now to focus discussion there. If there is an ask for cudf that comes out of that, we can reopen this issue or create a new one, but most likely this is something that will need to be fixed in cuml.

**Closed by vyasr** 2024-05-17 18:17 UTC
Labels: bug

**Comment by vyasr** [comment] 2024-05-17 18:20
For completeness, here is a self-contained reproducer:
```
import cudf
import cuml

X = cudf.DataFrame({
    "Date": [2547, 822, 3686, 3719, 9200],
    "SKU": [1.0, 1.0, 1.0, 1.0, 1.0],
    "Customer_ID": ["X52", "2ML", "0H2", "0H2", "0H2"],
})

Y = cudf.Series([3.13, 5.46, 6.35, 5.59, 6.88])

cuml.train_test_split(X, Y, train_size=0.2)
```
