### ISSUE TITLE
[BUG] cudf outer join on 'categorical` column results in inaccurate merged data frame

### ISSUE THREAD

**Issue by rnyak** [rapidsai/cudf#3994] opened 2020-01-29 21:19 UTC
**Describe the bug**
cudf outer join on categorical column does not yield accurate results.

**Steps/Code to reproduce bug**

```
cdf1 = cudf.DataFrame({'id1': ["0", "1", "2", "3"],'id2': [25, 45, 12, 7]})
cdf2 = cudf.DataFrame({'id1': ["0", "1", "2", "4"],'id3': [25, 45, 1, 7]})
pdf1= pd.DataFrame({'id1': ["0", "1", "2", "3"],'id2': [25, 45, 12, 7]})
pdf2 = pd.DataFrame({'id1': ["0", "1", "2", "4"],'id3': [25, 45, 1, 7]})

pdf1['id1'] = pdf1['id1'].astype("category")
pdf2['id1'] = pdf2['id1'].astype("category")
cdf1['id1'] = cdf1['id1'].astype("category")
cdf2['id1'] = cdf2['id1'].astype("category")

pdf_merged_out= pdf1.merge(pdf2, how='left', on='id1')
gdf_merged_out= cdf1.merge(cdf2, how='left', on='id1')

```

```
pdf_merged_out

	id1	id2	id3
0	0	25	25.0
1	1	45	45.0
2	2	12	1.0
3	3	7	NaN

```

```
gdf_merged_out

	id1	id2	id3
0	0	25	25
1	1	45	45
2	2	12	1
3	4	7	7

```

**Expected behavior**
We expect to have "null" values for unmatched rows when doing outer join. This is the expected merged cudf:

```
gdf_merged_out

	id1	id2	id3
0	0	25	25
1	1	45	45
2	2	12	1
3	3	7	null
```

**Environment overview (please complete the following information)**
 - Environment location: [Docker]
 - Method of cuDF install: [ Docker]
 - cudf version: 0.11

**Comment by beckernick** [comment] 2020-01-30 14:35
This is likely a duplicate of #3496

**Comment by kkraus14** [comment] 2020-01-30 14:37
Closing as duplicate of #3496

**Closed by kkraus14** 2020-01-30 14:37 UTC
Labels: bug, cuDF (Python)
