### ISSUE TITLE
[FEA] Support *logical* boolean operators 

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1564] opened 2019-05-01 20:43 UTC
**Describe the bug**
Support bitwise operations between Boolean columns. This is necessary downstream in dask-cudf for cummin and cummax.

**Steps/Code to reproduce bug**
```python
import cudf

s = cudf.Series(list(range(10)))
(s > 1) | (s < 2)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-312-791f0e4ebb29> in <module>
      1 s = cudf.Series(list(range(10)))
----> 2 (s > 1) | (s < 2)

/conda/envs/cudf/lib/python3.7/site-packages/cudf-0.7.0.dev0+565.gf6ad6de.dirty-py3.7-linux-x86_64.egg/cudf/dataframe/series.py in __or__(self, other)
    517         series.
    518         """
--> 519         return self._bitwise_binop(other, 'or')
    520 
    521     def __xor__(self, other):

/conda/envs/cudf/lib/python3.7/site-packages/cudf-0.7.0.dev0+565.gf6ad6de.dirty-py3.7-linux-x86_64.egg/cudf/dataframe/series.py in _bitwise_binop(self, other, op)
    503         else:
    504             raise TypeError(
--> 505                 f"Operation 'bitwise {op}' not supported between "
    506                 f"{self.dtype.type.__name__} and {other.dtype.type.__name__}"
    507             )

TypeError: Operation 'bitwise or' not supported between bool_ and bool_
```

**Expected behavior**

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
 - Please run and attach the output of the `cudf/print_env.sh` script to gather relevant environment details
 

**Additional context**

**Comment by harrism** [comment] 2019-05-02 00:26
This may have worked before #1142, but I'm not sure. Perhaps @devavret can comment. Let's look at fixing this for 0.8

**Comment by beckernick** [comment] 2019-05-02 00:30
Thanks Mark. As a note, I was built from the following when I tried to use this:

```
commit 8989ada060e152c38949c75d792d4bb018e3752e (HEAD -> branch-0.7, origin/branch-0.7, origin/HEAD)
Merge: c81152e4 9f53eb89
Author: Jake Hemstad <jhemstad@nvidia.com>
Date:   Tue Apr 30 08:12:55 2019 -0500
```

**Comment by devavret** [comment] 2019-05-15 12:06
Does this really need a bitwise operation? I'm thinking if I reroute `|`, `&`, `^` operators for `bool_` type from bitwise to logical, it should work as desired right?

**Comment by jrhemstad** [comment] 2019-05-15 13:37
> Does this really need a bitwise operation? I'm thinking if I reroute `|`, `&`, `^` operators for `bool_` type from bitwise to logical, it should work as desired right?

I think @beckernick really means "logical", _not_ bitwise.

Pandas uses `|`, `&`, `^` for _logical_ operators, not bitwise. 

See: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#boolean-indexing

> Another common operation is the use of boolean vectors to filter the data. The operators are: | for or, & for and, and ~ for not.

And: https://stackoverflow.com/a/54358361/11341974

**Comment by beckernick** [comment] 2019-05-15 13:47
@jrhemstad is correct. Thanks for updating this issue's title to better reflect the intended functionality

**Comment by harrism** [comment] 2019-05-16 01:02
Seems to be a duplicate of #1517?

**Closed** 2019-05-27 18:47 UTC
Labels: cuDF (Python), feature request
