### ISSUE TITLE
[FEA] Upgrade cudf arrow version to the latest 

### ISSUE THREAD

**Issue by nirandaperera** [rapidsai/cudf#7436] opened 2021-02-24 15:48 UTC
**Is your feature request related to a problem? Please describe.**
We are working on an integration with cudf in our project Cylon (https://github.com/cylondata/cylon). Cylon is currently using arrow 2.0.0 and we are almost in-sync with the latest arrow developments. Arrow had some major API changes from 1.x to 2.x and because of that, it is difficult for Cylon to downgrade to arrow 1.x. The only solution we see is, to manage two branches. We'd love to continue to work on the cudf integration and it would be great if the arrow dependency could be upgraded. 

**Describe the solution you'd like**
Arrow dependency to be upgraded to 2.0.0+ 

**Describe alternatives you've considered**
Managing two branches of Cylon with and without cudf support (this is exceedingly difficult, given our small team)

**Additional context**

**Comment by kkraus14** [comment] 2021-02-24 17:03
Closing as duplicate of #7224. We are going to be trying to upgrade to 3.0.0 in v0.19.

**Closed by kkraus14** 2021-02-24 17:03 UTC
Labels: ? - Needs Triage, feature request
