### ISSUE TITLE
DataFrame::merge, on-keyword argument needs string not just list

### ISSUE THREAD

**Issue by muellren** [rapidsai/cudf#517] opened 2018-12-13 18:56 UTC
## Reporting a bug

```python
left = cudf.DataFrame()
right = cudf.DataFrame()
left['key'] = [1, 2, 5, 7, 1]
left['lval'] = [2.0, 3.0, 1.0, 0.0, 5.0]
right['key'] = [i for i in range(10)]
right['rval'] = [3, 2, 6, 4, 1, 2, 3, 4, 1, 5]

gdf = left.merge(right, on='key')
```
Error:
```
KeyError                                  Traceback (most recent call last)
<ipython-input-10-491c301eaa06> in <module>
      6 right['rval'] = [3, 2, 6, 4, 1, 2, 3, 4, 1, 5]
      7 
----> 8 gdf = left.merge(right, on='key')

~/anaconda3/envs/cudf_dev/lib/python3.5/site-packages/cudf-0.4.0-py3.5-linux-x86_64.egg/cudf/dataframe/dataframe.py in merge(self, other, on, how, lsuffix, rsuffix, type, method)
    919 
    920         for name in on:
--> 921             if pd.api.types.is_categorical_dtype(self[name]):
    922                 lcats = self[name].cat.categories
    923                 rcats = other[name].cat.categories

~/anaconda3/envs/cudf_dev/lib/python3.5/site-packages/cudf-0.4.0-py3.5-linux-x86_64.egg/cudf/dataframe/dataframe.py in __getitem__(self, arg)
    216         """
    217         if isinstance(arg, str) or isinstance(arg, int):
--> 218             s = self._cols[arg]
    219             s.name = arg
    220             return s

KeyError: 'k'
```

Expected behavior: same as for list of str 
```python
gdf = left.merge(right, on=['key'])
```

The docstring  states for argument on:
```
on : label or list; defaults to None
       Column or index level names to join on. These must be found in
       both DataFrames.
```

- [X] I am using the latest version of cuDF from conda, built from master, or
built from the latest tagged release: master
- [X] I have included the version or commit hash I am using for reference (commit 7aa3799).
- [X] I have included the following environment details: Ubuntu 16.04, 4.15.0-4-generic, GTX 1080
- [X] I have included the following version information for:
Arrow (0.10.0), cmake (3.13.1), CUDA (9.2.148), gcc/g++ (5.4.0), Numpy, Pandas (0.23.4), Python (3.5.5)
- [X] I have included below a minimal working reproducer

**Comment by bahaugen** [comment] 2018-12-14 03:58
Is this different than #340?

**Comment by thomcom** [comment] 2018-12-16 04:51
No this duplicates #340. Thanks for the fix!

**Comment by harrism** [comment] 2019-01-09 05:53
#340 was closed. Can this be closed too?

**Comment by bahaugen** [comment] 2019-01-10 02:52
I think this is a duplicate of #340 and can be closed.

**Closed** 2019-01-10 03:36 UTC
Labels: cuDF (Python), good first issue
