### ISSUE TITLE
[BUG] Groupby aggregation on a column with a null value throws error

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#1754] opened 2019-05-15 20:08 UTC
**Describe the bug**
Given a cudf Dataframe where any aggregation is being performed on a column that has one or more Null values returns an error

**Steps/Code to reproduce bug**
```
import cudf
df = cudf.DataFrame()
a = [2]*9
a.append(None)
df['a'] = a
df['b'] = [1]*10
df.groupby(by=['b'],as_index=False).min()
```
Output:
```
---------------------------------------------------------------------------
GDFError                                  Traceback (most recent call last)
<ipython-input-91-999f2fa24ff0> in <module>
      7 print(df.to_pandas())
      8 print(df.dtypes)
----> 9 df.groupby(by=['b'],as_index=False).min()

/conda/envs/rapids/lib/python3.7/site-packages/cudf-0.7.1+8.g4b6f402.dirty-py3.7-linux-x86_64.egg/cudf/groupby/groupby.py in min(self, sort)
    329 
    330     def min(self, sort=True):
--> 331         return self._apply_basic_agg("min", sort)
    332 
    333     def max(self, sort=True):

/conda/envs/rapids/lib/python3.7/site-packages/cudf-0.7.1+8.g4b6f402.dirty-py3.7-linux-x86_64.egg/cudf/groupby/groupby.py in _apply_basic_agg(self, agg_type, sort_results)
    183                     agg_groupby._df._cols[by] = self._df._cols[by]
    184         return _cpp_apply_basic_agg(agg_groupby, agg_type,
--> 185                                     sort_results=sort_results)
    186 
    187     def apply_multiindex_or_single_index(self, result):

cudf/bindings/groupby.pyx in cudf.bindings.groupby._apply_basic_agg()

cudf/bindings/groupby.pyx in cudf.bindings.groupby._apply_agg()

cudf/bindings/cudf_cpp.pyx in cudf.bindings.cudf_cpp.check_gdf_error()

GDFError: b'GDF_VALIDITY_UNSUPPORTED'
```

**Expected behavior**
The aggregation should be performed and it should work normally.

**Environment details (please complete the following information):**
 - Environment location: Docker
 - Method of cuDF install: from source
 - Cudf version 0.7.1

**Comment by kkraus14** [comment] 2019-05-15 20:10
Duplicate of #544

**Closed by kkraus14** 2019-05-15 20:10 UTC
Labels: ? - Needs Triage, bug
