### ISSUE TITLE
cuDF needs multi-index support for columns

### ISSUE THREAD

**Issue by kenhester** [rapidsai/cudf#483] opened 2018-12-08 17:51 UTC
## Feature request
groupby in cudf does not produce the same output dataframe structure as pandas. 

## Reporting a bug
The groupby in cudf is not compatible or portable to pandas.  The groupby in cudf flattens the indices and prepends the operator 'max' to the new column.  Pandas requires the reset_index() and the column rename to have the same structure in the resulting dataframe.

```
import cudf
<...read_csv code here...>
df2 = df[['a', 'b']].groupby('a').max()
<...more code here...>
df2.drop_column('max_b')

Output of *df2*
        a                                max_b 
0  100007365142                             0
1  100007386460                             0
2  100011322040                             0
3  100015192562                             0
4  100015874399                             0
```
```
import pandas pd
<...read_csv code here...>
df2 = df[['a', 'b']].groupby('a').max().reset_index()
df2.rename(columns={'b':'max_b'}, inplace=True)
<...more code here...>
df2.drop('max_b', axis=1, inplace=True)

Output of *df2* without reset_index
                                            b
a                                      
100007365142                                0
100007386460                                0
100011322040                                0
100015192562                                0
100015874399                                0

Output of *df2* with reset_index and column rename
        a                                 max_b 
0  100007365142                             0
1  100007386460                             0
2  100011322040                             0
3  100015192562                             0
4  100015874399                             0
```

- [ ] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. 
- [ ] I have included the version or commit hash I am using for reference.
- [ ] I have included the following environment details:
      Linux Distro, Linux Kernel, GPU Model
- [ ] I have included the following version information for:
      Arrow, cmake, CUDA, gcc/g++, Numpy, Pandas, Python
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by kkraus14** [comment] 2018-12-10 20:18
This is due to the choice to not support multi-indexes in order to support multiple aggregations on a single column. Closing this as a won't fix unless there's significant pushback.

**Comment by mrocklin** [comment] 2018-12-15 17:07
(@kkraus14 and I had an in-person conversation about this, but I thought I'd re-hash part of that conversation here)

I'd like to push back on this.  I think that there is value to supporting the same semantics as Pandas.  In particular this has two benefits:

1.  Lower cognitive load for existing Pandas users
2.  Better integration with other pandas-friendly dataframe projects, like dask.dataframe

Supporting multi-indexes on columns doesn't force us to support them on rows, which is where I tend to see more resistance to multi-indexes.  We might reuse the `pandas.MultiIndex` object for simplicity.

**Comment by mrocklin** [comment] 2018-12-17 17:32
Can I ask that we reopen this issue?  (I don't have permissions to do this)

**Comment by mrocklin** [comment] 2019-01-10 19:15
Small example

```python
import pandas as pd
import cudf

df = cudf.DataFrame({'x': [1, 2, 3], 'y': [1, 2, 1]})

>>> df.groupby('y').agg({'x': 'mean'}).to_pandas()
   y  mean_x
0  1       2
1  2       2

>>> df.to_pandas().groupby('y').agg({'x': 'mean'})
   x
y
1  2
2  2
```

**Comment by thomcom** [comment] 2019-01-31 20:57
Hey @mrocklin I've got a minimal fix for your minimal reproducer:
https://www.dropbox.com/s/gnana44wgx2xqwo/Screenshot%202019-01-31%2013.55.05.png?raw=1

We still don't support multi index or multi aggregation, but we support singles!

**Comment by mrocklin** [comment] 2019-01-31 20:57
Awesome. I'm looking forward to trying it out.

**Comment by quasiben** [comment] 2019-02-21 17:28
@kkraus14 @thomcom do you have an estimate on supporting MultiIndexes ?  Is this something for after conferences  ?

**Comment by mrocklin** [comment] 2019-02-21 17:36
For context, it looks like we need multi-indexes specifically for dask groupby aggregations using the `agg` method and a column accessor like ...

    df.groupby(...).x.agg(['mean', 'sum'])

The following two seem to work today

    df.groupby(...).agg({'x': ['mean', 'sum']})
    df.gropuby(...).x.mean()

This might be sufficiently rare that we don't want to prioritize it if it's expensive to do on the cudf side.

**Comment by thomcom** [comment] 2019-02-21 18:50
I'm working on it today. I either expect to have it done within a week or to identify that our existing architecture makes it too hard.

**Comment by mrocklin** [comment] 2019-02-21 18:51
If it takes a week then we should punt and work on other things.

**Closed** 2019-05-02 17:48 UTC
Labels: cuDF (Python), dask, feature request, proposal
