### ISSUE TITLE
[BUG] cmake fails to configure static libcudf build

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#15270] opened 2024-03-11 16:47 UTC
**Describe the bug**
After #15178 cmake will fail to configure libcudf as a static library.  Configuration fails with:
```
CMake Error: install(EXPORT "cudf-exports" ...) includes target "cudf" which requires target "nvtx3-cpp" that is not in any export set.
CMake Error in CMakeLists.txt:
  export called with target "cudf" which requires target "nvtx3-cpp" that is
  not in any export set.
```

**Steps/Code to reproduce bug**
Execute the following cmake command from `cpp/build`:
```
cmake .. -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DCMAKE_CUDA_ARCHITECTURES=70 -DCUDA_STATIC_RUNTIME=ON -DCUDF_ENABLE_ARROW_S3=OFF -DCUDF_ENABLE_ARROW_PARQUET=ON -DCUDF_USE_ARROW_STATIC=ON -DCUDF_USE_PER_THREAD_DEFAULT_STREAM=ON
```

**Expected behavior**
cmake configures successfully

**Comment by bdice** [comment] 2024-03-11 20:45
Fixed by #15271. I verified that Spark builds in https://github.com/NVIDIA/spark-rapids-jni/pull/1855 are getting further along. I'll be filing a PR to spark-rapids-jni to fix any remaining issues caused by Spark's use of libcudf internal headers.

**Closed by bdice** 2024-03-11 20:45 UTC
Labels: bug, libcudf, CMake, helps: Spark
