### ISSUE TITLE
[FEA] backtick support in DataFrame.query

### ISSUE THREAD

**Issue by mattf** [rapidsai/cudf#12507] opened 2023-01-09 21:46 UTC
**Is your feature request related to a problem? Please describe.**
writing code using `import cudf as pd`

**Describe the solution you'd like**
same behavior as `import pandas as pd`
```
In [1]: import cudf as pd

In [2]: pd.__version__
Out[2]: '22.12.0'

In [3]: df = pd.DataFrame({'a !': [0, 1, 2]})

In [4]: df.query('`a !` == 1')
Traceback (most recent call last):

  File ~/.local/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3378 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Cell In [4], line 1
    df.query('`a !` == 1')

  File ~/.local/lib/python3.9/site-packages/cudf/core/dataframe.py:4174 in query
    boolmask = queryutils.query_execute(self, expr, callenv)

  File ~/.local/lib/python3.9/site-packages/cudf/utils/queryutils.py:210 in query_execute
    compiled = query_compile(expr)

  File ~/.local/lib/python3.9/site-packages/cudf/utils/queryutils.py:144 in query_compile
    info = query_parser(expr)

  File ~/.local/lib/python3.9/site-packages/cudf/utils/queryutils.py:67 in query_parser
    tree = ast.parse(text)

  File /usr/lib/python3.9/ast.py:50 in parse
    return compile(source, filename, mode, flags,

  File <unknown>:1
    `a !` == 1
    ^
SyntaxError: invalid syntax


In [5]: df.to_pandas().query('`a !` == 1')
Out[5]: 
   a !
1    1
```

**Additional context**
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html

**Comment by vyasr** [comment] 2023-01-09 22:55
Closing as a duplicate of #3000

**Closed by vyasr** 2023-01-09 22:55 UTC
Labels: feature request, ? - Needs Triage
