### ISSUE TITLE
[FEA] implement GroupBy value_counts

### ISSUE THREAD

**Issue by Pedrexus** [rapidsai/cudf#12876] opened 2023-03-02 04:20 UTC
**Is your feature request related to a problem? Please describe.**
I wish to execute a value_counts operation on groupby on both DataFrame and Series.

References: 
- https://pandas.pydata.org/docs/dev/reference/api/pandas.core.groupby.DataFrameGroupBy.value_counts.html
- https://pandas.pydata.org/docs/dev/reference/api/pandas.core.groupby.SeriesGroupBy.value_counts.html

**Describe the solution you'd like**

```python
import cudf

df = cudf.DataFrame({
    'gender': ['male', 'male', 'female', 'male', 'female', 'male'],
   'education': ['low', 'medium', 'high', 'low', 'high', 'low'],
   'country': ['US', 'FR', 'US', 'FR', 'FR', 'FR']
})

df.groupby('gender').value_counts()

# AttributeError: DataFrameGroupBy object has no attribute value_counts
```

**Describe alternatives you've considered**

My work around is to run instead

```python
df.to_pandas().groupby('gender').value_counts()
# gender  education  country
# female  high       FR         1
#                    US         1
# male    low        FR         2
#                    US         1
#         medium     FR         1
# dtype: int64
```

**Additional context**

**Comment by shwina** [comment] 2023-03-06 15:54
Thanks for reporting. This seems like a duplicate of #12789, so I'm closing in favor of that issue.

**Closed by shwina** 2023-03-06 15:54 UTC
Labels: feature request, ? - Needs Triage
