### ISSUE TITLE
[BUG] Remove pytest x-failures as pandas bug fixes are merged

### ISSUE THREAD

**Issue by brandon-b-miller** [rapidsai/cudf#5581] opened 2020-06-25 20:41 UTC
**Describe the bug**
In the process of upgrading to Pandas 1.0, we were forced to x-fail some tests due to various changes in Pandas behavior. Some of these were intentional changes, and more discussion is warranted around if and to what extent we should attempt to replicate the behavior. Others were simply bugs that we reported, or were already being worked on when we noticed them. This issue tracks these cases, so that we can re-enable the relevant tests as things are fixed in patch versions of pandas. 

- ~~test_dataframe.py::test_isin_dataframe, https://github.com/pandas-dev/pandas/issues/34256~~
- test_json::test_json_writer, https://github.com/pandas-dev/pandas/issues/31464
- test_string::test_string_cat, https://github.com/pandas-dev/pandas/issues/33425
- test_rolling::test_rolling_series_basic, test_rolling_dataframe_basic, https://github.com/rapidsai/cudf/issues/5580

**Comment by vyasr** [comment] 2022-07-12 00:48
Closing as a duplicate of #7386.

**Closed by vyasr** 2022-07-12 00:48 UTC
Labels: bug, pandas, tests, cuDF (Python)
