### ISSUE TITLE
[BUG] mean() fails on groupby

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#1064] opened 2019-02-27 19:24 UTC
nycsmall.csv:

```
VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,cudf_groupby_level_index
1,2017-01-09 11:13:28,2017-01-09 11:25:45,1,3.3,1,2313200,263,161,1,12.5,0.0,0.5,2.0,0.0,0.30000000000000004,15.3,1
1,2017-01-09 11:32:27,2017-01-09 11:36:01,1,0.9,1,2313200,186,234,1,5.0,0.0,0.5,1.45,0.0,0.30000000000000004,7.25,1
```

```
import pandas as pd
import cudf

df = pd.read_csv('nycsmall.csv')
df.groupby(df.passenger_count).mean()
print(df.groupby(df.passenger_count).mean())

cdf = cudf.read_csv('nycsmall.csv')
cdf.groupby(cdf.passenger_count).min().to_pandas()

cdf.groupby(cdf.passenger_count).mean().to_pandas()
```

The call on groupby().mean() fails with the following:

```
---------------------------------------------------------------------------
GDFError                                  Traceback (most recent call last)
<ipython-input-9-6ae1e588e916> in <module>
----> 1 cdf.groupby(cdf.passenger_count).mean().to_pandas()

~/GitRepos/cudf/python/cudf/groupby/groupby.py in mean(self, sort)
    318 
    319     def mean(self, sort=True):
--> 320         return self._apply_basic_agg("mean", sort)
    321 
    322     def agg(self, args):

~/GitRepos/cudf/python/cudf/groupby/groupby.py in _apply_basic_agg(self, agg_type, sort_results)
    250         result = self._apply_agg(
    251             agg_type, result, add_col_values, ctx, val_columns,
--> 252             val_columns_out, sort_result=sort_results)
    253 
    254         # If a Groupby has one index column and one value column

~/GitRepos/cudf/python/cudf/groupby/groupby.py in _apply_agg(self, agg_type, result, add_col_values, ctx, val_columns, val_columns_out, sort_result)
    194                 out_col_values,
    195                 out_col_agg,
--> 196                 ctx)
    197 
    198             if (err is not None):

~/miniconda3/envs/cudf-dev/lib/python3.7/site-packages/libgdf_cffi/wrapper.py in wrap(*args)
     25                     if errcode != self._api.GDF_SUCCESS:
     26                         errname, msg = self._get_error_msg(errcode)
---> 27                         raise GDFError(errname, msg)
     28 
     29                 wrap.__name__ = fn.__name__

GDFError: GDF_UNSUPPORTED_DTYPE
```

cc @jrhemstad any ideas what's going on here ?  I can try and reduce the columns to figure out what's  going on if that's helpful

**Comment by jrhemstad** [comment] 2019-02-27 19:38
What's the type on the `passenger_count` column?

**Comment by quasiben** [comment] 2019-02-27 19:39
`passenger_count` is int64

```
VendorID                             int64
tpep_pickup_datetime        datetime64[ms]
tpep_dropoff_datetime       datetime64[ms]
passenger_count                      int64
trip_distance                      float64
RatecodeID                           int64
store_and_fwd_flag                   int64
PULocationID                         int64
DOLocationID                         int64
payment_type                         int64
fare_amount                        float64
extra                              float64
mta_tax                            float64
tip_amount                         float64
tolls_amount                       float64
improvement_surcharge              float64
total_amount                       float64
cudf_groupby_level_index             int64
dtype: object
```

**Comment by jrhemstad** [comment] 2019-02-27 19:44
Hmmmm, `int64` is definitely supported. Not sure where the `GDF_UNSUPPORTED_DTYPE` is being thrown from. 

I'll try to repro locally.

**Comment by jrhemstad** [comment] 2019-02-27 21:56
I was able to reproduce locally, however I discovered that even when I distill your repro down to:

```
import pandas as pd
import cudf

cdf = cudf.read_csv('nycsmall.csv')

cdf.groupby(cdf.passenger_count).mean()
```

That the `libcudf` `gdf_group_by` function is getting called _twice_ when it should be only getting called once.

The first call succeeds, but the second call's arguments are garbage and happens to fail on the `GDF_UNSUPPORTED_DTYPE` check.

**Comment by thomcom** [comment] 2019-02-27 22:06
Thanks @jrhemstad. This might be caused by `__getattr__` making a call to `__getitem__` which creates a copy of the original groupby object. I'm mostly responsible for this and am looking into it.

**Comment by thomcom** [comment] 2019-02-27 23:06
I don't know what the problem is - normally `agg_func` is called for each column that we're grouping by.

**Comment by thomcom** [comment] 2019-03-07 00:24
Hmm it is failing on the datetime columns! :) I don't think it is unreasonable to `mean` a datetime but the most straighforward solution is to convert the datetimes to ints, mean them, and convert them back.
I solved the problem by dropping 'tpep_pickup_datetime' and 'tpep_dropoff_datetime'

**Comment by jrhemstad** [comment] 2019-03-07 00:29
> Hmm it is failing on the datetime columns! :) I don't think it is unreasonable to `mean` a datetime but the most straighforward solution is to convert the datetimes to ints, mean them, and convert them back.
> I solved the problem by dropping 'tpep_pickup_datetime' and 'tpep_dropoff_datetime'

I've still got a bunch of lingering questions.

We are grouping on the `passenger_count` column, whose type was `int64`, not `datetime`. The other column's shouldn't matter for the groupby.

Furthermore, this doesn't explain why the `gdf_groupby` function being called twice?

**Comment by thomcom** [comment] 2019-03-08 15:10
I have a fix for this coming right up, and an explanation. Sorry about the delay - I've been moving all week.

**Comment by thomcom** [comment] 2019-03-08 17:49
I'm going to take a stab at your questions:
1. In our implementation, each column is grouped by `passenger_count`, one at a time. `gdf_groupby` should be called the number of times as there are columns.
2. `gdf_groupby` is called twice because it is called once for `VendorID`, successfully, then once for `tpep_pickup_datetime`, which fails.

**Comment by thomcom** [comment] 2019-03-08 17:50
```
cdf = cudf.read_csv('nycsmall.csv')
cdf = cdf.drop(['tpep_pickup_datetime', 'tpep_dropoff_datetime'])
pdf = cdf.to_pandas()
print(pdf.groupby(pdf.passenger_count).mean())
print(cdf.groupby(cdf.passenger_count).mean())
```
``` output
                 VendorID  passenger_count  trip_distance  RatecodeID  \
passenger_count                                                         
1                     1.0              1.0            2.1         1.0   

                 store_and_fwd_flag  PULocationID  DOLocationID  payment_type  \
passenger_count                                                                 
1                         2313200.0         224.5         197.5           1.0   

                 fare_amount  extra  mta_tax  tip_amount  tolls_amount  \
passenger_count                                                          
1                       8.75    0.0      0.5       1.725           0.0   

                 improvement_surcharge  total_amount  cudf_groupby_level_index  
passenger_count                                                                 
1                                  0.3        11.275                       1.0  
   VendorID  passenger_count  trip_distance  RatecodeID  store_and_fwd_flag  PULocationID  DOLocationID ...  total_amount
1       1.0              1.0            2.1         1.0           2313200.0         224.5         197.5 ...        11.275
[7 more columns]
```

**Comment by thomcom** [comment] 2019-03-08 18:20
Reopening to discuss how we should handle unsupported columns.

**Comment by thomcom** [comment] 2019-03-08 18:21
```python
cdf = cudf.read_csv('nycsmall.csv')
pdf = cdf.to_pandas()
print(pdf.groupby(by=["passenger_count"], as_index=True).agg('mean'))
cdf = cdf.drop(['tpep_pickup_datetime', 'tpep_dropoff_datetime'])
print(cdf.groupby(by=["passenger_count"], as_index=True).agg('mean'))
```
``` output
                 VendorID  trip_distance  RatecodeID  store_and_fwd_flag  \
passenger_count                                                            
1                     1.0            2.1         1.0           2313200.0   

                 PULocationID  DOLocationID  payment_type  fare_amount  extra  \
passenger_count                                                                 
1                       224.5         197.5           1.0         8.75    0.0   

                 mta_tax  tip_amount  tolls_amount  improvement_surcharge  \
passenger_count                                                             
1                    0.5       1.725           0.0                    0.3   

                 total_amount  cudf_groupby_level_index  
passenger_count                                          
1                      11.275                       1.0  
   mean_VendorID  mean_trip_distance  mean_RatecodeID  mean_store_and_fwd_flag  mean_PULocationID  mean_DOLocationID  mean_payment_type ...  mean_cudf_groupby_level_index
passenger_count
1            1.0                 2.1              1.0                2313200.0              224.5              197.5                1.0 ...                            1.0
[7 more columns]
```
Pandas drops columns that are unsupported dtypes during the groupby call, as you can see from the output above. Should we do the same, or is the error originally reported by @quasiben a valid way to behave?

**Comment by thomcom** [comment] 2019-03-08 18:23
I can drop the columns if they are unsupported dtypes if that is an important use case.

**Comment by quasiben** [comment] 2019-03-08 18:39
I think dropping unsupported dtypes makes sense.  This would also apply to `median()` as well

**Comment by jrhemstad** [comment] 2019-03-08 18:42
> I think dropping unsupported dtypes makes sense. This would also apply to `median()` as well

Less work for me! Ship it!

**Comment by jrhemstad** [comment] 2019-04-09 16:37
@thomcom @quasiben is this issue resolved?

**Comment by thomcom** [comment] 2019-05-02 13:37
No, the right solution is to drop unsupported dtypes during the agg op in accordance with pandas. That's not going to happen for 0.7.

**Closed** 2019-05-09 18:40 UTC
Labels: bug, libcudf (C++/CUDA)
