### ISSUE TITLE
[FEA] Set the index of a dataframe/series

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#967] opened 2019-02-17 03:49 UTC
It would be useful to be able to assign an index to a dataframe or index object

    df.index = df2.index

This might be achieved either by ...

1.  Removing the property and just using an attribute
2.  Creating a property setter

cc @thomcom @kkraus14

**Comment by kkraus14** [comment] 2019-02-19 17:54
duplicate of #824

**Closed by kkraus14** 2019-02-19 17:54 UTC
Labels: ? - Needs Triage, dask, feature request
