### ISSUE TITLE
does it work in windows?

### ISSUE THREAD

**Issue by LowinLi** [rapidsai/cudf#449] opened 2018-12-05 07:36 UTC
## Reporting a bug

- [ ] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. 
- [ ] I have included the version or commit hash I am using for reference.
- [ ] I have included the following environment details:
      Linux Distro, Linux Kernel, GPU Model
- [ ] I have included the following version information for:
      Arrow, cmake, CUDA, gcc/g++, Numpy, Pandas, Python
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by datametrician** [comment] 2018-12-05 07:43
@LowinLi we currently do not support windows. Hopefully, we will provide windows support in the future.

**Comment by harrism** [comment] 2018-12-05 09:45
This is a duplicate of #28. Please add comments on that issue. Closing this one.

**Closed by harrism** 2018-12-05 09:45 UTC
Labels: duplicate, feature request
