### ISSUE TITLE
[BUG] new binops is much slower than old version

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#3659] opened 2019-12-20 22:31 UTC
**Describe the bug**
The new binops implementation has a much slower than the old implementation. The compile time is a lot longer and so is the run time.

**Steps/Code to reproduce bug**
We have been porting over the java code to run with the new libcudf++ API.  The binpos tests that we run from before take.
7 seconds cold (nothing in the cache) and 0.06 seconds hot (a second run with everything is in the cache).

Under the new cudf::column API we see
18 seconds when cold and 0.57 seconds when hot.

We even disabled several of the tests that use strings that don't work and it is the same performance. 

**Expected behavior**
I would expect the new code to be as fast or faster.  Not 2+x slower to compile and 10x slower to run.

**Comment by kkraus14** [comment] 2019-12-20 23:28
cc @devavret @trxcllnt

**Comment by jrhemstad** [comment] 2019-12-21 14:53
The slower compile time isn't surprising, though I wouldn't expect it to be _that_ much slower. However, I wouldn't expect we'd be running slower from cache too. I'd be curious to see an nsight profile to show where the time is being spent.

**Comment by devavret** [comment] 2019-12-23 11:27
I'm guessing that the old binops puts its cache in `/tmp` while the new one will try to put it in home directory (provided it be specified). While `/tmp` lies on the machine itself, home could be an nfs mount and that might cause slowdown in reading.

**Comment by devavret** [comment] 2019-12-23 13:10
Ok my earlier diagnosis might be wrong. There is a considerable size difference between the cache files of the two types. Sample legacy kernel is 2 KB and looks like this 
[prog_binop.kernel_v_s_long int_long int_long int_Add.txt](https://github.com/rapidsai/cudf/files/3994996/prog_binop.kernel_v_s_long.int_long.int_long.int_Add.txt) 

and the new one is 76 KB and looks like this 
[prog_binop.experimental.cudf::experimental::kernel_v_s_int8_t_int16_t_int32_t_Add.txt](https://github.com/rapidsai/cudf/files/3995001/prog_binop.experimental.cudf.experimental.kernel_v_s_int8_t_int16_t_int32_t_Add.txt)

**Comment by devavret** [comment] 2019-12-23 19:54
Yep, that's where it's spending all the time. Actually, it seems to be taking time in `cuModuleLoadDataEx` so while it **is** about the file size, it's not the time spent in reading it but in loading the data into the current context.

**Comment by revans2** [comment] 2019-12-30 16:22
If it really is just load times to pull in the cached kernels I am not too concerned.  The tests we are running are with a very small amount of data so the load time can easily be blown out of proportion. I would like to spend some time eventually looking at ways that we can reduce the JIT compile time, but that can come later when we finish porting the java API to column++ and we can run some benchmarks to see how much of an impact it is likely to really have.

**Comment by harrism** [comment] 2020-01-22 01:39
I looked at the new generated PTX and it looks like there are a ton of unused .global data declarations. Could this be an NVRTC bug? Shouldn't it prune the unused ones?

**Comment by harrism** [comment] 2020-02-04 00:42
Update, there is an internal NVIDIA bug filed against NVRTC to fix the unused .global declarations which should eliminate the code bloat. But that won't be available until CUDA 11.x In the meantime, @benbarsdell suggested that he can add pruning of these declarations as an option in Jitify.

**Comment by harrism** [comment] 2020-02-11 03:30
Update: I tested with the branch of jitify in NVIDIA/jitify#40 and confirmed that it fixes. We need to add a new compiler flag to all calls to jitify to use it. I am in the process of adding that flag and verifying nothing breaks. I will then open a PR. We need for NVIDIA/jitify#40 to be merged so that we can use this.

**Comment by harrism** [comment] 2020-02-11 04:04
@revans2 I opened #4119 with a fix. We can't merge until jitify merges the PR it depends on, but if you would like to test it out locally to see if it fixes the perf regression that would be great.

**Closed** 2020-02-12 07:11 UTC
Labels: Jitify, Spark, bug, libcudf (C++/CUDA), libcudf++
