### ISSUE TITLE
[FEA] Support string columns for `query` operation

### ISSUE THREAD

**Issue by drabastomek** [rapidsai/cudf#3040] opened 2019-10-10 15:58 UTC
**Describe the bug**
Filtering on two string columns throws an AttributeError

**Steps/Code to reproduce bug**
Here's a minimal example.

```
import cudf 

sample = cudf.DataFrame({
      'a': ['A1', 'B2', 'C3']
    , 'b': ['A1', 'B1', 'C1'] 
}) 

# bug
sample.query('a != b')
```

**Expected behavior**
DataFrame with two rows, excluding row 0.

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker nightly
   - docker pull rapidsai/rapidsai-nightly:cuda10.0-runtime-ubuntu18.04
   - docker run --runtime=nvidia --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 rapidsai/rapidsai-nightly:cuda10.0-runtime-ubuntu18.04

**Comment by kkraus14** [comment] 2019-10-10 22:18
@drabastomek String columns are not yet supported for anything UDF related, including `query`, `apply_rows`, `apply_chunks`, etc., going to update this to a feature request.

**Comment by kkraus14** [comment] 2019-10-10 22:19
Note this is super non-trivial and likely won't come soon.

**Comment by kkraus14** [comment] 2020-05-29 20:05
Closing as duplicate of #1195

**Closed by kkraus14** 2020-05-29 20:05 UTC
Labels: cuDF (Python), feature request, numba
