### ISSUE TITLE
[FEA]Transform multiple columns at the same time based on patterns, currently use for-loop as a work around

### ISSUE THREAD

**Issue by liuyangc1** [rapidsai/cudf#6753] opened 2020-11-12 20:09 UTC
We want to transform multiple columns with the same pattern at the same time using the same logic, or by applying the same function. There is a function in dplyr call `muate_at()` https://dplyr.tidyverse.org/reference/mutate_all.html. We currently use for loop to transform multiple variables with same pattern, it would be nice to have something like mutate_at() to achieve this or we are happy to know if there are better ways to achieve this than use the for loop. The for loop code we wrote is shown below:
```
import re
variables = [i for i in df.columns if re.match('^abceefg.*$', i) or re.match('^abcd*$', i)] # faked patterns here
print(variables)  # our real-world usecase would have ~50 matched variables
for var in variables:
    df = df.map_partitions(udf)
```

**Comment by kkraus14** [comment] 2020-11-17 16:12
Closing as duplicate of #1501

**Closed by kkraus14** 2020-11-17 16:12 UTC
Labels: ? - Needs Triage, feature request
