### ISSUE TITLE
[BUG]cudf.read_csv doesn't extract all records from file

### ISSUE THREAD

**Issue by ntaherkhani** [rapidsai/cudf#6569] opened 2020-10-20 23:01 UTC
**Describe the bug**
I am trying to read csv file using cudf.read_csv . when I am getting length of datfarme it is less than the number of records in file. 
when I am reading csv file using dask.dataframe , it returns all records. 

I did this test using cudf 0.14.0. 

did I miss some setting in cudf.read_csv? or my cudf version is old and cudf should be updated? 

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by harrism** [comment] 2020-10-20 23:12
Hi @ntaherkhani can you provide an example CSV file and a minimal reproducer (Python code)? Also, can you try a more recent version of cuDF? (0.15 has been released for a while, 0.16 is about to be released tomorrow).

**Comment by ntaherkhani** [comment] 2020-10-21 11:56
Hi @harrism  I tried through cudf 0.15 as well . I am still missing some rows. 
I cannot share the data that I am using. I have 49 columns that all of them are considered as string type. I am reading csv file through hdfs path.  
these are the lines of code that I am using for reading csv data:

import dask.dataframe as ddf
import dask_cudf as dcdf
import cudf

data_type={}
for col in list_of_columns:
    data_type.update({col:'str'})

path="hdfs://servername/path_to_csv_file/file_name.csv"

df= cudf.read_csv(path, sep='\t', names=list_of_columns, dtype =data_type)
print("size of dataframe: " , len(df))
print("loaded dataframe: " )
print(df)

Also, I have another issue with setting the path. I have an entry path with subfolders that in these subfolders there are my csv files. but when I set the path as  
path="hdfs://servername/path_to_parent_folder/*" 
or 
path="hdfs://servername/path_to_parent_folder/*/*/*/*.csv"
both cudf and dask cannot find the csv files in subfolders. so, I firstly find a list of csv files and their paths and then read one by one file and concat datfarmes. 
please let me know how I can set the path as well.

Thanks.

**Comment by rjzamora** [comment] 2020-10-21 14:12
>I cannot share the data that I am using. I have 49 columns that all of them are considered as string type

Ideally, a minimal reproducer is not your real data anyway - Are you able to reproduce the problem by generating a small synthetic dataset? For example...

```python
import cudf
import numpy as np
from dask.dataframe.io.demo import names

ncols = 49
nrows = 1000
df = cudf.DataFrame(
    {
        f"col_{i}": np.random.choice(names, nrows)
        for i in range(ncols)
    }
)
df.to_csv(...)
```

Regarding the path issue: You should be able to pass a list of file paths to `dask_cudf.read_csv` is the glob-string approach is not working for your use case.

**Comment by ntaherkhani** [comment] 2020-10-22 17:17
Hi,
Thanks @rjzamora for your response. 
the problem with cudf read_csv was solved. it was related to our dat that we dont use "quoting" in our csv files and I should ignore it when I am reading csv files. So, I change the code to :
df= cudf.read_csv(path, sep='\t', names=list_of_columns, dtype =data_type ,  quoting=3)

regarding path issue: I tried with dask_cudf and list of files, but it is so slower than cudf and concat. 
my dask settings are:

os.environ["DASK_UCX__CUDA_COPY"] = "True"  
os.environ["DASK_UCX__TCP"] = "True"
os.environ["DASK_UCX__NVLINK"] = "True"
os.environ["DASK_UCX__INFINIBAND"] = "True"
os.environ["DASK_UCX__NET_DEVICES"] = "enp1s0f0"
    
 cluster = LocalCUDACluster(        
            protocol="ucx",
            enable_tcp_over_ucx=False,
            enable_infiniband=False,
            enable_nvlink=True,

        )
client = Client(cluster)

**Comment by beckernick** [comment] 2020-10-22 17:53
How many GPUs are part of your LocalCUDACluster?

**Comment by ntaherkhani** [comment] 2020-10-22 18:08
I have 8 GPUs.

**Comment by kkraus14** [comment] 2020-10-22 23:48
It's likely that the default `chunksize` in dask is causing the GPUs to be underutilized versus cudf reading in whole files at once. Regardless, the issue is fixed based on your comment with the quoting so I'm closing this issue.

**Closed by kkraus14** 2020-10-22 23:48 UTC
Labels: ? - Needs Triage, bug, cuIO
