### ISSUE TITLE
[FEA] cudf.read_csv does not recognize 'low_memory' keyword argument

### ISSUE THREAD

**Issue by mattf** [rapidsai/cudf#11935] opened 2022-10-17 18:59 UTC
**Is your feature request related to a problem? Please describe.**
rewriting code from pandas into cudf, trying to use `import cudf as pd`

**Describe the solution you'd like**
`cudf.read_csv` matching https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

**Comment by quasiben** [comment] 2022-10-17 19:09
Does `low_memory` feature need to be implemented on the GPU or do you think we can simply "ignore" and not error out for that kwarg ?

**Comment by shwina** [comment] 2022-10-18 13:02
I think we might be able to implement it in terms of the `chunksize` argument, which we do support. @thomcom made a similar suggestion [here](https://github.com/rapidsai/cudf/issues/11915#issuecomment-1277988562).

**Comment by beckernick** [comment] 2022-10-18 13:27
This is a duplicate of https://github.com/rapidsai/cudf/issues/4999 . Would recommend we consolidate discussion in one of the issues.

**Comment by shwina** [comment] 2022-10-18 14:03
Let's go ahead and close this one then.

**Closed by shwina** 2022-10-18 14:03 UTC
Labels: feature request, cuDF (Python), cuIO
