### ISSUE TITLE
[BUG] Differences in column types when loading csv with pandas.read_csv() and cudf.read_csv() 

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#1765] opened 2019-05-16 07:41 UTC
**Describe the bug**
Hi,

When trying to read the attached csv file with Pandas and cuDF, the resulting dataframes have different column types.

![image](https://user-images.githubusercontent.com/26169771/57835073-19b08080-77be-11e9-82b7-938853e670db.png)

**Steps/Code to reproduce bug**
Run the following code on the attached dataset: [ipums_easy.zip](https://github.com/rapidsai/cudf/files/3185890/ipums_easy.zip)

(please, remember to unzip it before trying the example below):

```
import pandas as pd
import cudf

# read data from csv file into pandas and cudf dataframes
pdf = pd.read_csv('ipums_easy.csv')
gdf = cudf.read_csv('ipums_easy.csv')

print(pdf.dtypes.iloc[18:23])
print(gdf.dtypes.iloc[18:23])
```

**Expected behavior**
Same results between pandas and cuDF.

**Environment details (please complete the following information):**
AWS instance (p3.8xlarge) with the RAPIDS v0.7 from NGC.

**Comment by OlivierNV** [comment] 2019-05-16 15:47
Looks like these columns are completely empty -> sounds like read_csv() should default to float64 instead of int8 for empty column

**Comment by mjsamoht** [comment] 2019-05-16 18:00
This is really a duplicate of the remaining issue #1598 where we have to decide how to treat empty columns.  In that issue the preferred choice is string.  Here it is float64.

IMO, defaulting to string makes more sense than float64.  But either way, we have to pick one.

**Comment by vuule** [comment] 2019-05-21 19:29
@mjsamoht The two issues are not exactly the same. In #1598, the dataframe does not have any rows so we can pick any default column type(s). In this issue, all rows contain null values, so cudf picks int8 to reduce the amount of memory allocated, while the field validity is tracked in a separate array. Pandas probably has to use floats to represent null values (no additional validity flag).
We can modify the behavior to match Pandas, but IMO the change would be a negative for cuDF.

**Comment by mjsamoht** [comment] 2019-05-23 20:57
We decided against matching pandas' behavior for this issue.  Switching from `int8` to `float64` for what is essentially garbage data is a waste of memory.

See #1826 for discussion.

**Closed by mjsamoht** 2019-05-23 20:57 UTC
Labels: bug, cuIO

**Comment by miguelangel** [comment] 2019-05-23 23:04
Hi @mjsamoht,

It makes sense to me. Thank you for working on this issue.

Nevertheless, I was wondering if there is any other data type which might be even more efficient (in terms of memory), than int8. Boolean maybe? char(1)? Not sure if these datatypes are supported nor how they are represented in the RAPIDS C++ layer. Just sharing my thoughts.

**Comment by mjsamoht** [comment] 2019-05-24 00:34
Int8 would be the same as char(1), which is 1 byte.  And Boolean are also represented as 1 byte so I don’t think there is another data type with less than 1 byte.

--
Thomas
