### ISSUE TITLE
[BUG] `MAX_INT` in Join column results in uninformative memory error

### ISSUE THREAD

**Issue by samshipengs** [rapidsai/cudf#662] opened 2019-01-10 15:41 UTC
I was trying to merge two cudf dataframes on a column called `card_id` (I set it as `'int'` type), 

`df_left.merge(df_right, on=['card_id'], how='left')`

where `df_left` has following shape and dtypes,
`(1963032, 14) `

```
authorized_flag                  int32
card_id                          int32
city_id                          int64
category_1                       int32
installments                     int64
category_3                       int32
merchant_category_id             int64
merchant_id                      int32
month_lag                        int64
purchase_amount                float64
purchase_date           datetime64[ms]
category_2                     float64
state_id                         int64
subsector_id                     int64
```

and the `df_right`:
`(201918, 6)`

```
first_active_month      int32
card_id                 int32
feature_1               int64
feature_2               int64
feature_3               int64
target                float64
```

I'm getting following error:

```
File "/home/sam/anaconda3/lib/python3.6/site-packages/cudf/dataframe/dataframe.py", line 958, in merge
    method=method)
  File "cudf/bindings/join.pyx", line 26, in cudf.bindings.join.join
  File "cudf/bindings/join.pyx", line 125, in cudf.bindings.join.join
  File "cudf/bindings/cudf_cpp.pyx", line 205, in cudf.bindings.cudf_cpp.check_gdf_error
cudf.bindings.GDFError.GDFError: b'GDF_MEMORYMANAGER_ERROR'
```

I had been checking gpu memory on nvidia-smi, it never exceeded 600MB. I'm not sure what the issue might be here

**Comment by jrhemstad** [comment] 2019-01-10 16:03
Can you please attach your environment details produced from this script https://github.com/rapidsai/cudf/blob/branch-0.5/print_env.sh

**Comment by samshipengs** [comment] 2019-01-10 16:07
```
***OS Information***
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
Linux rapids-testing 4.15.0-1026-gcp #27~16.04.1-Ubuntu SMP Fri Dec 7 09:59:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

***GPU Information***
Thu Jan 10 16:05:34 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.54                 Driver Version: 396.54                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P0    33W / 250W |    389MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1728      G   /usr/lib/xorg/Xorg                            82MiB |
|    0     18408      C   /home/sam_dessa/anaconda3/bin/python3.6      297MiB |
+-----------------------------------------------------------------------------+

***CPU***
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU @ 2.30GHz
Stepping:              0
CPU MHz:               2300.000
BogoMIPS:              4600.00
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat arch_capabilities

***CMake***
/home/sam_dessa/anaconda3/bin/cmake
Traceback (most recent call last):
  File "/home/sam_dessa/anaconda3/bin/cmake", line 7, in <module>
    from cmake import cmake
ModuleNotFoundError: No module named 'cmake'

***g++***
/usr/bin/g++
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


***nvcc***
/usr/local/cuda/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148

***Python***
/home/sam_dessa/anaconda3/bin/python
Python 3.6.6

***Environment Variables***
PATH                            : /home/sam_dessa/bin:/home/sam_dessa/.local/bin:/home/sam_dessa/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/cuda/bin:/snap/bin
LD_LIBRARY_PATH                 :
NUMBAPRO_NVVM                   :
NUMBAPRO_LIBDEVICE              :
CONDA_PREFIX                    : /home/sam_dessa/anaconda3
PYTHON_PATH                     :
```

I left out the conda packages part as its a long list

**Comment by jrhemstad** [comment] 2019-01-10 16:32
Would you be able to do a Debug build of libcudf from source and install that into your environment and try running your reproducer?

The instructions for building from source are here: 
https://github.com/rapidsai/cudf/blob/branch-0.5/README.md

To get a Debug build, the only change you need to make is:
`cmake .. -DCMAKE_INSTALL_PREFIX=/install/path -DCMAKE_BUILD_TYPE=Debug`

If that doesn't give any different results, you could then try running your reproducer through `cuda-gdb` (with the debug build of libcudf installed):

`cuda-gdb -ex r --args python <programname>.py <arguments>`

If you could provide the output of both of these things, that would be helpful.

**Comment by samshipengs** [comment] 2019-01-10 16:36
So I found what could have caused it and I can reproduce the error,
when I was loading the csvs for `df_left` and df_right`, I was setting the column `card_id` dtype to be `'int'`, which the data would look something like this:

```
01-10 16:30:56 [rapids_helpers.py:71] [INFO] 
  first_active_month    card_id  feature_1  feature_2  feature_3              target
0         2147483647   56617322 5986561771 5986561772 5986561773           7362098.0
1            2016706 2147483647          5          2          1          -0.8202826
2            2016701 2147483647          4          1          0 0.39291325000000005
3            2015708 2147483647          2          2          0  0.6880559900000001
4            2016709 2147483647          4          3          0 0.14249520000000004
```

The error goes away when I set the dtype of the `card_id` to be `'category'`, which would give this:
```
01-10 16:29:38 [rapids_helpers.py:71] [INFO] 
  first_active_month     card_id  feature_1  feature_2  feature_3              target
0         2147483647   -22090408 5986561771 5986561772 5986561773           7362098.0
1            2016706 -1012285432          5          2          1          -0.8202826
2            2016701 -1012285432          4          1          0 0.39291325000000005
3            2015708 -1012285432          2          2          0  0.6880559900000001
4            2016709 -1012285432          4          3          0 0.14249520000000004
```

I noticed the difference on the `card_id` values, probably due to different encodings used, but I thought having `card_id` as `int` type would only be more efficient, why it would even give error?

**Comment by jrhemstad** [comment] 2019-01-10 16:52
Oh... I believe I see what the problem is. Thanks for posting the sample of your data.

When you set `card_id` dtype to `int`, then some of the values you are getting are `2147483647` which is `2^31 -1` or `MAX_INT`. 

That value is used as a special "sentinel" value in the `merge` implementation and if your input dataset contains that value, then you'll run into problems, as you've seen.

We'll have to discuss if/how we can better give an error in this situation.

**Comment by samshipengs** [comment] 2019-01-10 17:09
Thanks for the reply. ( forgot to mention the data sample above was `df_right` the smaller dataframe of the merge).
Although then I did a `value_counts` on the `card_id` when I set it to `'int'` when I was loading it from csv, the printed result doesn't seem right:

```
2147483647 201917
56617322      1
```

which means all the `car_id` gets mapped to `MAX_INT` except for the first one.

**Comment by samshipengs** [comment] 2019-01-10 17:30
oh my mistake ...., there should be an error in my code, somehow when I was using pandas to load the data and trying to take a peak of what the original data actually was, it turns out they appear to be all `Nan` after loaded:
``` 
[INFO] Load train data
                   first_active_month card_id  feature_1  feature_2  \
card_id                           NaN     NaN        NaN        NaN   
feature_1                         NaN     NaN        NaN        NaN   
feature_2                         NaN     NaN        NaN        NaN   
feature_3                         NaN     NaN        NaN        NaN   
first_active_month                NaN     NaN        NaN        NaN   
                    feature_3  target  
card_id                   NaN     NaN  
feature_1                 NaN     NaN  
feature_2                 NaN     NaN  
feature_3                 NaN     NaN  
first_active_month        NaN     NaN 
```
so the `NaN` probably are responsible for those `MAX_INT`. (although Im still trying to figure out whats wrong in my code)

**Comment by samshipengs** [comment] 2019-01-10 17:48
Here is the original data (`df_right`):

```01-10 17:39:54 [pandas_bench.py:59] [INFO] Load train data
           card_id  feature_1    ...     first_active_month    target
0  C_ID_92a2005557          5    ...             2017-06-01 -0.820283
1  C_ID_3d0044924f          4    ...             2017-01-01  0.392913
2  C_ID_d639edf6cd          2    ...             2016-08-01  0.688056
3  C_ID_186d6a6901          4    ...             2017-09-01  0.142495
4  C_ID_cdbd2c0db2          1    ...             2017-11-01 -0.159749 
```

**Comment by kkraus14** [comment] 2019-02-13 16:56
This looks like: #919 in that you should be using `category` instead of `object` for your dtype and we will compute a 32 bit integer hash for it. We're working to resolve that bug which should resolve this.

**Comment by kkraus14** [comment] 2019-02-13 17:00
This was recently resolved by #927 so it would be great if you could try this with 0.6 at some point.

**Comment by mjsamoht** [comment] 2019-03-18 17:55
@samshipengs can you confirm whether this is still an open issue with 0.6?

**Comment by samshipengs** [comment] 2019-03-19 14:42
@mjsamoht I settled with something else last time when I run into this error (e.g. spark or multiprocessing), I will try to confirm if this is resolved soon.

**Closed** 2019-07-03 22:13 UTC
Labels: bug, cuIO, libcudf (C++/CUDA)
