### ISSUE TITLE
[BUG] distributed dask_cudf.read_parquet much slower in ipython/jupyter vs python

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#10163] opened 2022-01-28 22:43 UTC
**Describe the bug**
When doing a `dask_cudf.read_parquet` on a `LocalCUDACluster` I see a significant performance difference when running the same code in a ipython/jupyter session vs running it as a standalone python script. 

From the profiles it seems like most of the delta is actually coming from time taken to `deserialize` in both instances. 

**Steps/Code to reproduce bug**
```python
from dask_cuda import LocalCUDACluster
from distributed import Client, wait, performance_report
import dask_cudf
import dask
import time

write_data = False
perf_report_fname = "py-perf.html"

if __name__ == "__main__":
    cluster = LocalCUDACluster()
    client = Client(cluster)

    if write_data:
        dask.datasets.timeseries(start="2022-01-01", end="2024-01-01").to_parquet("test_data.parquet")


    with performance_report(filename=perf_report_fname):
        ddf = dask_cudf.read_parquet("test_data.parquet")
        t1 = time.time()
        ddf = ddf.persist()
        wait(ddf)
        print(time.time() - t1)
```

This takes about `~12s` in ipython vs `~4s` as a standalone script

**Expected behavior**
Comparable perf in both scenarios. 

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda 22.02 nightly

**Environment details**
python version: 3.8
ipython version: 8.0.1

**Additional context**
1. Attaching the performance report from both runs which shows similar compute but wildly different task deserialization time (visible in the task graph as well). 
[perf_reports.zip](https://github.com/rapidsai/cudf/files/7962254/perf_reports.zip)

2. Happened to observe this on `dask_cudf.read_parquet` but might be impacting other apis as well. 

3. Doesn't seem to be an issue when using `dd.read_parquet` with the same cluster

**Comment by jakirkham** [comment] 2022-01-28 23:03
Is `read_parquet` at the end of a cell (or in its own cell)? If so, IPython or Jupyter may be generating a `repr` for it, which could be slow (depending on what that entails)

**Comment by ayushdg** [comment] 2022-01-28 23:15
in this situation `read_parquet` is in the same cell as everything else in the script above. I just copy pasted the reproducer into a single ipython cell and ran the same thing there

**Comment by ayushdg** [comment] 2022-01-28 23:50
Couple of more findings:
- The time taken to deserialize gets worse as number of workers increases. Eg: At 2 workers it takes about ~3s per worker vs 16 workers takes ~7.5s per worker.

- In an older Rapids version this deserialization takes about ~350ms:
```
dask                      2021.9.1           pyhd8ed1ab_0    conda-forge
dask-core                 2021.9.1           pyhd8ed1ab_0    conda-forge
dask-cuda                 21.12.00a211012         py38_20    rapidsai-nightly
dask-cudf                 21.12.00a211012 py38_g18c9763a83_113    rapidsai-nightly
```

While in the latest release it takes about ~7.5s:
```
dask                      2021.11.2          pyhd8ed1ab_0    conda-forge
dask-core                 2021.11.2          pyhd8ed1ab_0    conda-forge
dask-cuda                 21.12.00                 py38_0    rapidsai
dask-cudf                 21.12.02        cuda_11_py38_g06540b9b37_0    rapidsai
```

I verified this by keeping the ipython version constant so it's most likely some changes in distributed/dask-cuda/dask-cudf/dask that might have caused this change in behavior

**Comment by jakirkham** [comment] 2022-01-29 00:25
I'm still wondering if it is a `repr` thing. Maybe try adding a semicolon after the problematic line?

**Comment by jakirkham** [comment] 2022-01-29 03:40
Have we tried with IPython 7? Wondering if something changed in that major version bump

**Comment by beckernick** [comment] 2022-01-31 15:26
Do we see this behavior without dask-cuda / GPU data structures?

**Comment by ayushdg** [comment] 2022-01-31 17:33
> I'm still wondering if it is a repr thing. Maybe try adding a semicolon after the problematic line?

Tried but didn't seem to change performance.

> Have we tried with IPython 7? Wondering if something changed in that major version bump

Yup, verified that it's reproducible in ipython v7.26.0 and seems to have appeared b/w rapids 22.10 and 22.12


> Do we see this behavior without dask-cuda / GPU data structures?

Nope, without a cluster I see similar perf in both situations.

**Comment by quasiben** [comment] 2022-01-31 17:47
@jacobtomlinson would you have time to look at this ?  Do you think something in HTML reprs is doing something funky ?

**Comment by jacobtomlinson** [comment] 2022-02-01 13:37
Calling an HTML repr could have side effects I guess, but given that @ayushdg said the semicolon hasn't made a difference then perhaps it's not that.

**Comment by quasiben** [comment] 2022-02-01 16:16
Still exploring the repr deserialization time could you store the output of wait in a dummy variable:

> _ = wait(ddf)

**Comment by ayushdg** [comment] 2022-02-01 18:06
> Still exploring the repr deserialization time could you store the output of wait in a dummy variable.

This did not seem to impact the runtime either. I did notice however that the long `deserialize-read-parquet` time does coincide with a spike in unmanaged memory of about `1GB` stored per worker on the dashboard.

**Comment by beckernick** [comment] 2022-02-01 23:00
(The below compares running as a Python script with running the code snippet inside an IPython session).

In the 21.12 environment, I see the observed deserialization slowdown in IPython. 

In the 21.08 environment, I do **not** see the observed slowdown in IPython. I do see slightly more deserialization time when running in IPython, but it's not the 1.5+ seconds change I see in 21.12+.

21.12 partial environment:
```
conda list | grep "dask\|distrib\|cudf\|fsspec"
cudf                      21.12.02        cuda_11_py38_g06540b9b37_0    rapidsai
cudf_kafka                21.12.02        py38_g06540b9b37_0    rapidsai
dask                      2021.11.2          pyhd8ed1ab_0    conda-forge
dask-core                 2021.11.2          pyhd8ed1ab_0    conda-forge
dask-cuda                 21.12.00                 py38_0    rapidsai
dask-cudf                 21.12.02        cuda_11_py38_g06540b9b37_0    rapidsai
distributed               2021.11.2        py38h578d9bd_0    conda-forge
fsspec                    2022.1.0           pyhd8ed1ab_0    conda-forge
libcudf                   21.12.02        cuda11_g06540b9b37_0    rapidsai
libcudf_kafka             21.12.02          g06540b9b37_0    rapidsai
```

21.08 partial environment:
```
conda list | grep "dask\|distrib\|cudf\|fsspec"
cudf                      21.08.03        cuda_11.2_py38_ge4313b6a1e_0    rapidsai
cudf_kafka                21.08.03        py38_ge4313b6a1e_0    rapidsai
dask                      2021.7.1           pyhd8ed1ab_0    conda-forge
dask-core                 2021.7.1           pyhd8ed1ab_0    conda-forge
dask-cuda                 21.08.00                 py38_0    rapidsai
dask-cudf                 21.08.03        py38_ge4313b6a1e_0    rapidsai
distributed               2021.7.1         py38h578d9bd_0    conda-forge
fsspec                    2022.1.0           pyhd8ed1ab_0    conda-forge
libcudf                   21.08.03        cuda11.2_ge4313b6a1e_0    rapidsai
libcudf_kafka             21.08.03          ge4313b6a1e_0    rapidsai
```

Could this perhaps be related to parquet reader changes in between 21.08 and now? I know there was some work going on related to fsspec. With that said, my current 21.08 environment resolves for `fsspec=2022.1.0` and it doesn't see the large slowdown.


As a note, in the 22.02 and 22.04 environments I was not able to reproduce this behavior by switching the `dask_cudf.read_parquet` calls to `dask.dataframe.read_parquet` while still using LocalCUDACluster.

**Comment by ayushdg** [comment] 2022-02-01 23:05
Thanks for reproducing @beckernick, this is inline with the behavior I've observed as well. The ipython version has a higher deserialization time vs python but not by the margin observed in 22.12. 

I did some preliminary testing by changing the dask, distributed and dask-cuda versions to something older and that didn't fix things, so it's most likely changes to fsspec or dask-cudf/cudf that are most likely.

**Comment by quasiben** [comment] 2022-02-02 15:51
As an experiment I tried pre-importing cudf/dask-cudf and this seemed to change both the overall time and the task stream.  @ayushdg can you try the following before the perf-report call

```
def f():
    import cudf
    import dask_cudf
client.run(f)
```

**Comment by ayushdg** [comment] 2022-02-02 19:03
Thanks @quasiben can confirm that pre-importing cudf seems to fix the performance issue:
```python
def f():
    import cudf
client.run(f)
```

Do folks here have any idea on what might have changed in cudf that made the serialization/deserialization time for the import so much slower in ipython? 
Ideally I expect to not want to make this a common pattern with jupyter

**Comment by quasiben** [comment] 2022-02-02 19:38
I still don't know what has changed but cudf _is not_ loaded at launch time when running with ipython.  

```
In [1]: from dask_cuda import LocalCUDACluster
   ...: from distributed import Client, wait, performance_report
   ...: import dask_cudf
   ...: import dask
   ...: import time
   ...:
   ...: write_data = False
   ...: perf_report_fname = "py-perf.html"
   ...:
   ...: if __name__ == "__main__":
   ...:     cluster = LocalCUDACluster()
   ...:     client = Client(cluster)
   ...:     client.wait_for_workers(8)
   ...:
   ...:     # with performance_report(filename=perf_report_fname):
   ...:     #     ddf = dask_cudf.read_parquet("test_data.parquet")
   ...:     #     t1 = time.time()
   ...:     #     ddf = ddf.persist()
   ...:     #     wait(ddf)
   ...:     #     print(time.time() - t1)
1.9746086597442627
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize

In [2]:
```

The time print out is coming from me testing how long it takes to load cudf (inject into cudf.__init__.py).  Running with Python we see all the time statements for each worker and the client

```
(cudf_dev) bzaitlen@dgx15:/datasets/bzaitlen/GitRepos$ !python
python test-cudf.py
2.1023261547088623
1.633681058883667
1.661799430847168
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
1.5975863933563232
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
1.718400239944458
1.701127529144287
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
1.8037216663360596
1.772298812866211
1.7877326011657715
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
```

**Comment by quasiben** [comment] 2022-02-02 21:43
Also, the long import times is something brought in another issue.  More recently here: https://github.com/rapidsai/cudf/issues/627#issuecomment-1019417913

**Comment by quasiben** [comment] 2022-02-02 21:58
I wonder if this is due to some strangeness with how ipython/jupyter handles spawn/fork and whether the imports get serialized and executed on the workers

**Comment by quasiben** [comment] 2022-02-04 14:29
It's not strangeness but rather when spawning, there is no script in the ipython/jupyter context for the worker to load and thus we don't see the import of cudf/dask-cudf.  We could potentially resolve this in dask-cuda with an optional plugin to autoload cudf/dask-cudf.

**Comment by quasiben** [comment] 2022-02-04 14:57
@pentschev quickly wrote this PR in dask-cuda https://github.com/rapidsai/dask-cuda/pull/854 which allows users to define pre-imports like the following:

> cluster = LocalCUDACluster(pre_import=["cudf"])

My testing showed this resolved the issue.  @ayushdg can you confirm ?

**Comment by randerzander** [comment] 2022-02-04 16:10
> My testing showed this resolved the issue. @ayushdg can you confirm ?

The dask-cuda PR worked for me to fix this. Thanks!

**Comment by quasiben** [comment] 2022-02-07 15:51
Are we good to close this issue ?  I did follow up with a bit of profiling in https://github.com/rapidsai/cudf/issues/627 in trying to understand the slow import times

**Comment by ayushdg** [comment] 2022-02-07 18:46
I think we should be good to close this issue and follow up on #627 to identify what changed between 21.10 and 21.12

**Closed** 2022-02-07 18:47 UTC
Labels: bug, ? - Needs Triage
