### ISSUE TITLE
[BUG] Builds are not reproducible

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#11533] opened 2022-08-15 14:08 UTC
**Describe the bug**
I tried to redo an older 22.10 build from a specific SHA hash and it failed.  see https://github.com/NVIDIA/spark-rapids-jni/issues/479  It looks like cudf always pulls the latest version of rapids-cmake. So if rapids-cmake ever changes older builds are impacted and we have no way to keep the exact version of rapids-cmake.

**Expected behavior**
I check out a specific version of cudf from git it always builds exactly the same.  Code does not magically change on me without my knowledge.

If CUDF always wants to run on the latest version, that is fine. But then we need a way to be able to set the exact SHA version we want for rapids-cmake.

**Comment by robertmaynard** [comment] 2022-08-29 18:05
> It looks like cudf always pulls the latest version of rapids-cmake.
cudf on a given branch ( 22.10 )  will pull the latest version of rapids-cmake on the same branch. Likewise for dependencies like `rmm` which are also pulled via branch names.

If you need to test with a specific version of rapids-cmake you can follow this guide https://github.com/rapidsai/rapids-cmake#overriding-rapidscmake which shows how specify a specific version ( GIT_TAG can also be a SHA ). You would place this in the `fetch_rapids.cmake` before any other statement.

**Comment by revans2** [comment] 2022-08-29 19:44
@robertmaynard I see that this was closed and then re-opened again. Are there plans to do more for this? The docs you pointed us to I think are workable, and we can probably patch CUDF as we build it to get a consistent version. But if you are going to do more, like expose the version through a CMAKE variable or something it would be good to understand that, because I don't want to patch CUDF unless I have to.

**Comment by robertmaynard** [comment] 2022-08-29 20:08
I accidently closed, and didn't want to come across as presumptious so I re-opened.

The balance between ease of use and reproducibility for 'nightly' builds is hard, and we currently go towards ease of use. We could move over to explicit SHA's but we would need to develop some infrastructure first. Primarily we need a robust way to ensure that during code-freeze all projects have synced to the same rapids-cmake SHA.

**Comment by revans2** [comment] 2022-08-30 20:32
I was thinking of something very simple. Like an environment variable for the SHA and if it is not set, then it defaults to what happens today. I realize that for most of rapids and CUDF in particular that ease of use is paramount.  All I would like is a way to be able to set this without having to patch CUDF itself. I could even write up the patch myself. I mostly want to have someones blessing that this is acceptable.

**Comment by robertmaynard** [comment] 2022-09-06 12:07
The ability to pin rapids-cmake is coming to all consumers via https://github.com/rapidsai/rapids-cmake/pull/257 which will allow you to pin by passing `-Drapids-cmake-sha=<sha>`

**Comment by robertmaynard** [comment] 2022-10-06 13:57
Closing since https://github.com/rapidsai/rapids-cmake/pull/257 has been merged

**Comment by bdice** [comment] 2024-01-19 18:03
@robertmaynard We reopened this issue. Is there work to be done for cudf specifically, or would all the work be in `rapids-cmake` and `spark-rapids-jni`?

**Comment by robertmaynard** [comment] 2024-01-19 19:39
> @robertmaynard We reopened this issue following discussion with the Spark team. Is there work to be done for cudf specifically, or would all the work be in `rapids-cmake` and `spark-rapids-jni`?

No work in libcudf, all the work will be in `rapids-cmake` and `spark-rapids-jni`

**Comment by vyasr** [comment] 2024-05-14 00:47
I'm closing this since I believe all the requirements were addressed in https://github.com/rapidsai/rapids-cmake/pull/530 and its follow-ups. @robertmaynard please reopen if I am mistaken.

**Closed by vyasr** 2024-05-14 00:47 UTC
Labels: bug, 2 - In Progress, helps: Spark

**Comment by robertmaynard** [comment] 2024-05-14 17:04
> I'm closing this since I believe all the requirements were addressed in [rapidsai/rapids-cmake#530](https://github.com/rapidsai/rapids-cmake/pull/530) and its follow-ups. @robertmaynard please reopen if I am mistaken.

You are correct.
