### ISSUE TITLE
[BUG] Passing str/object to UDF for apply_rows() fails

### ISSUE THREAD

**Issue by AshishSardana** [rapidsai/cudf#7228] opened 2021-01-27 16:35 UTC
**Describe the bug**
In a data frame, I have a column "uid" (dtype string). Other columns "history", "impression" are also of dtype string, with text separated with _spaces_.
I have to unroll the data in "impression" column to generate more rows. 
Impression column looks like - `N78206-0 N78206-0 N78699-1 N71090-1` i.e. 
**_impression_id_number-label_of_that_impression id_** N78206-0
So I want to create new row for each impression id. When I try to use `cudf.apply_rows()` or `cudf.apply_chunks()` on a UDF performing this operation, I cannot give input to UDFs as a `str` or `object` or `list`.
Even if I give input as a `np.int64 `or `np.float64` , I cannot produce a output as string or list or object using UDFs. Also, I have to create a separate column for each entry in #history column which has a string type.

**Steps/Code to reproduce bug**

```
#####Simple DF for replicating####

import pandas as pd
import cudf

data_test = pd.DataFrame({'impression_id': {0: 1, 1: 2, 2: 3},
 'uid': {0: 'U87243', 1: 'U598644', 2: 'U532401'},
 'time': {0: '11/10/2019 11:30:54 AM',
  1: '11/12/2019 1:45:29 PM',
  2: '11/13/2019 11:23:03 AM'},
 'history': {0: 'N8668 N39081 N65259 N79529 ',
  1: 'N56056 N8726',
  2: 'N128643 N87446 N122948'},
 'impressions': {0: 'N78206-0 N78699-1 N71090-1',
  1: 'N47996-0 N25587-1 N37544-0 N36266-1',
  2: 'N103852-0 N53474-0 N127836-0 N47925-1'}})
  
datac = cudf.DataFrame.from_pandas(data_test)

def conditional_add(x,out):
    for i, a in enumerate(x):
        out[i] = x.str.split(n=1).fillna(0)

df = datac.apply_rows(conditional_add,
                   incols={'history':'x'},
                   outcols={'out': str },
                   kwargs={}
                  )

```

_df.head() output_:
![image](https://user-images.githubusercontent.com/55958748/106010364-5bdb3c00-60df-11eb-8332-0fb636649ea7.png)

**ERROR:**
```
TypeError                                 Traceback (most recent call last)
<ipython-input-14-3bea461b2ac1> in <module>
      3         out[i] = x.str.split(n=1).fillna(0)
      4 
----> 5 df = datac.apply_rows(conditional_add,
      6                    incols={'history':'x'},
      7                    outcols={'out': str },

/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/dataframe.py in apply_rows(self, func, incols, outcols, kwargs, pessimistic_nulls, cache_key)
   4267                 current_col_dtype
   4268             ):
-> 4269                 raise TypeError(
   4270                     "User defined functions are currently not "
   4271                     "supported on Series with dtypes `str` and `category`."

TypeError: User defined functions are currently not supported on Series with dtypes `str` and `category`.
```

**Expected behavior**
I want each impression id entry to unroll. One row per impression id element. Also, I want history entries in the unrolled into columns , if history entry doesn't exit then value should be None or 0.
Attched the code for expected output dataframe in expected_output_applyrows.txt
[expected_output_applyrows.txt](https://github.com/AshishSardana/merlin-notebook/files/5881158/expected_output_applyrows.txt)

*_df_final.head() output_*
![image](https://user-images.githubusercontent.com/55958748/106011028-18cd9880-60e0-11eb-99e2-e80a12c2f748.png)

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker
 - Docker Container Used:  gitlab-master.nvidia.com:5005/rapidsdl/docker/rapidsdl_joc:latest

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details:
env_info.txt File has been attached.
[envlog.txt](https://github.com/AshishSardana/merlin-notebook/files/5872673/envlog.txt)

**Comment by kkraus14** [comment] 2021-01-27 16:56
Duplicate of #3802

**Closed by kkraus14** 2021-01-27 16:56 UTC
Labels: ? - Needs Triage, bug
