### ISSUE TITLE
[BUG] cuDF csv reader cannot decompress gzipped data

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#3378] opened 2019-11-14 15:09 UTC
I’m unable to decompress a gzipped file with cuDF’s csv reader, but pandas succeeds. Getting the following error from a nightly runtime container `rapidsai/rapidsai-nightly:0.11-cuda10.1-runtime-ubuntu18.04` from 11/12/19's early morning (EST) build. Pandas can read the gzipped file; both libraries can read the file if it is already decompressed.

Details on slack.

```python
RuntimeError: cuDF failure at: /conda/conda-bld/libcudf_1573500575489/work/cpp/src/io/csv/legacy/csv_reader_impl.cu:237: Cannot decompress data
```

cuDF:
```python
import cudf
df = cudf.read_csv("/path/to/data.dat.gz",
            sep="|",
            header=None,
            compression='gzip',
                  )
print(df.shape)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-b7a1f0e748a0> in <module>
      3             sep="|",
      4             header=None,
----> 5             compression='gzip',
      6                   )
      7 print(df.shape)

/opt/conda/envs/rapids/lib/python3.6/site-packages/cudf/io/csv.py in read_csv(filepath_or_buffer, lineterminator, quotechar, quoting, doublequote, header, mangle_dupe_cols, usecols, sep, delimiter, delim_whitespace, skipinitialspace, names, dtype, skipfooter, skiprows, dayfirst, compression, thousands, decimal, true_values, false_values, nrows, byte_range, skip_blank_lines, parse_dates, comment, na_values, keep_default_na, na_filter, prefix, index_col, **kwargs)
     80         na_filter=na_filter,
     81         prefix=prefix,
---> 82         index_col=index_col,
     83     )
     84 

cudf/_lib/csv.pyx in cudf._lib.csv.read_csv()

cudf/_lib/csv.pyx in cudf._lib.csv.read_csv()

RuntimeError: cuDF failure at: /conda/conda-bld/libcudf_1573500575489/work/cpp/src/io/csv/legacy/csv_reader_impl.cu:237: Cannot decompress data
```

Pandas:
```python
import pandas as pd
df = pd.read_csv("/path/to/data.dat.gz",
            sep="|",
            header=None,
            compression='gzip',
                  )
print(df.shape)
(24475810, 34)
```

**Comment by OlivierNV** [comment] 2019-11-14 16:03
I believe that is a dupe of issue #731 (assuming the uncompressed file is greater than 4GB)

**Comment by randerzander** [comment] 2019-11-14 20:18
Closing as duplicate of https://github.com/rapidsai/cudf/issues/731. @beckernick please re-open if you disagree

**Closed by randerzander** 2019-11-14 20:18 UTC
Labels: bug, cuIO, libcudf (C++/CUDA)
