### ISSUE TITLE
[BUG] the function character_ngrams does not allow the use of the second argument (as_list)

### ISSUE THREAD

**Issue by BastienRance** [rapidsai/cudf#10050] opened 2022-01-14 13:44 UTC
**Describe the bug**
The call to function _character_ngrams_ does not allow the use of the second argument.

**Steps/Code to reproduce bug**

The use of a second positioned argument returns an exception
`
import cudf
str_series = cudf.Series(['abcd','efgh','xyz'])
str_series.str.character_ngrams(3,True)
`

The use of a named argument does not have the expected behavior
`
import cudf
str_series = cudf.Series(['abcd','efgh','xyz'])
str_series.str.character_ngrams(n=3,as_list=True)
`

**Expected behavior**
Both code should return (as stated in the documentation):
`
0    [abc, bcd]
1    [efg, fgh]
2         [xyz]
`

Tested within the nvidia RAPIDS docker (https://hub.docker.com/r/rapidsai/rapidsai/) downloaded on January 6, 2022. (Rapids 21.12)

**Comment by beckernick** [comment] 2022-01-14 14:06
I am unable to reproduce this in the 21.12 release on bare metal.

```python
(rapids-21.12) nicholasb@$ ipython
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import cudf
   ...:
   ...: str_series = cudf.Series(["abcd", "efgh", "xyz"])
   ...: str_series.str.character_ngrams(3, True)
   ...: str_series.str.character_ngrams(3, as_list=True)
Out[1]:
0    [abc, bcd]
1    [efg, fgh]
2         [xyz]
dtype: list
```

Could you please share the specific code you used and the full traceback?

**Comment by beckernick** [comment] 2022-01-21 20:48
I'm going to close this, as we were unable to reproduce it in the current stable or nightly (22.02) release. Please feel free to re-open to continue the discussion.

**Closed by beckernick** 2022-01-21 20:48 UTC
Labels: bug, question
