### ISSUE TITLE
fillna leaving np.nan entries as is 

### ISSUE THREAD

**Issue by egoolish** [rapidsai/cudf#183] opened 2018-08-01 23:26 UTC
```
from pygdf import Series
import numpy as np

df = Series([5, 1, 8, np.nan, 4, np.nan, 3, 7, np.nan, 3, 1, np.nan])
print(df)
df = df.fillna(-1)
print(df)
```
returns 
```
 0  5.0
 1  1.0
 2  8.0
 3  nan
 4  4.0
 5  nan
 6  3.0
 7  7.0
 8  nan
 9  3.0
10  1.0
11  nan

 0  5.0
 1  1.0
 2  8.0
 3  nan
 4  4.0
 5  nan
 6  3.0
 7  7.0
 8  nan
 9  3.0
10  1.0
11  nan
```
where nan values are left unchanged.

**Comment by kkraus14** [comment] 2018-08-02 01:59
I believe this isn't an issue with the `fillna` function, but rather how we're creating Series objects. Following your example:
```
from pygdf import Series
import numpy as np

df = Series([5, 1, 8, np.nan, 4, np.nan, 3, 7, np.nan, 3, 1, np.nan])
print(df.has_null_mask)
print(df.null_count)
```

You'd expect to output `True` and then `4`. But instead outputs `False` and `0`. The same issue appears when creating Series objects from Pandas Series as well.

**Comment by kkraus14** [comment] 2018-08-02 02:00
Relevant: #135

**Comment by kkraus14** [comment] 2018-12-10 21:22
Closing as not a bug. Nulls are represented by bitmask, not `nan`.

**Closed by kkraus14** 2018-12-10 21:22 UTC
Labels: bug
