### ISSUE TITLE
calls to unique() raise RuntimeError("Freeing dead memory")

### ISSUE THREAD

**Issue by kevingerman** [rapidsai/cudf#407] opened 2018-11-27 19:27 UTC
## Reporting a bug

When a CUDF is created with CSV Reader any call to unique on a series in that DF generates exceptions. 

Stack traces, env details, reproduction script and conda yml found here - https://gist.github.com/kevingerman/5e1446a810a49a6027a2949e87c9a6cf

**Comment by kevingerman** [comment] 2018-11-27 20:04
Same thing when creating cudf.DataFrame using constructor.

```
import cudf

gdf=cudf.DataFrame( [ ( 'a', [1,2,3,4,5,6,7,8,9,0] ) ] )
gdf.a.unique()
```

**Comment by kevingerman** [comment] 2018-11-27 20:10
Issue does not reproduce when run with #09c7ee950e885a7b29b6c2e0dd73fda338e37422

**Comment by harrism** [comment] 2018-11-27 20:54
Related to #403?

**Comment by kkraus14** [comment] 2018-11-27 21:07
I'm unable to reproduce the issue when using a conda install of `cudf`, `libcudf`, and `libcudf_cffi` with CUDA 9.2 on your constructor snippet above. Could you try reinstalling your library to confirm it isn't an issue with your install?

**Comment by kevingerman** [comment] 2018-11-27 22:33
For good measure I rebuilt my container pulling cudf and deps from conda and was able to reproduce the error.   Gist updated with Dockerfile.    However, the issue does not reproduce when run against a build of current master branch.


```
(rapids) conda@add15191b3b6:/workflow$ conda list
# packages in environment at /conda/envs/rapids:
#
# Name                    Version                   Build  Channel
arrow-cpp                 0.10.0           py36h70250a7_0    conda-forge
asv                       0.3.1                     <pip>
blas                      1.0                         mkl  
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
certifi                   2018.10.15            py36_1000    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
cudatoolkit               9.2                           0  
cudf                      0.3.0                    py36_0    rapidsai
cython                    0.28.5           py36hfc679d8_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
intel-openmp              2019.1                      144  
libcudf                   0.3.0                 cuda9.2_0    rapidsai
libcudf_cffi              0.3.0            cuda9.2_py36_0    rapidsai
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
llvmlite                  0.25.0dev0      py36hf484d3e_20    numba
mkl                       2018.0.3                      1  
mkl_fft                   1.0.6                    py36_0    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
numba                     0.40.0dev0      np115py36hf484d3e_254    numba
numpy                     1.15.0           py36h1b885b7_0  
numpy-base                1.15.0           py36h3dfced4_0  
nvstrings                 0.0.3            cuda9.2_py36_0    nvidia
openssl                   1.0.2p               h470a237_1    conda-forge
pandas                    0.20.3                   py36_1    conda-forge
parquet-cpp               1.5.0.pre            h83d4a3d_0    conda-forge
pip                       18.1                  py36_1000    conda-forge
pyarrow                   0.10.0           py36hfc679d8_0    conda-forge
pycparser                 2.19                       py_0    conda-forge
python                    3.6.7                h5001a0f_1    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.7                     py_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
setuptools                40.6.2                   py36_0    conda-forge
six                       1.11.0                py36_1001    conda-forge
sqlite                    3.25.3               hb1c47c0_0    conda-forge
tk                        8.6.9                ha92aebf_0    conda-forge
walmart-benchmark         0.1.0                     <pip>
wheel                     0.32.3                   py36_0    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

**Comment by kevingerman** [comment] 2018-11-27 22:41
Just for good measure I rebuilt my container which pulls cudf and deps from conda and was able to reproduce the issue.   Gist updated with Dockerfile.

```
(rapids) conda@add15191b3b6:/workflow$ conda list
# packages in environment at /conda/envs/rapids:
#
# Name                    Version                   Build  Channel
arrow-cpp                 0.10.0           py36h70250a7_0    conda-forge
asv                       0.3.1                     <pip>
blas                      1.0                         mkl  
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
certifi                   2018.10.15            py36_1000    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
cudatoolkit               9.2                           0  
cudf                      0.3.0                    py36_0    rapidsai
cython                    0.28.5           py36hfc679d8_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
intel-openmp              2019.1                      144  
libcudf                   0.3.0                 cuda9.2_0    rapidsai
libcudf_cffi              0.3.0            cuda9.2_py36_0    rapidsai
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
llvmlite                  0.25.0dev0      py36hf484d3e_20    numba
mkl                       2018.0.3                      1  
mkl_fft                   1.0.6                    py36_0    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
numba                     0.40.0dev0      np115py36hf484d3e_254    numba
numpy                     1.15.0           py36h1b885b7_0  
numpy-base                1.15.0           py36h3dfced4_0  
nvstrings                 0.0.3            cuda9.2_py36_0    nvidia
openssl                   1.0.2p               h470a237_1    conda-forge
pandas                    0.20.3                   py36_1    conda-forge
parquet-cpp               1.5.0.pre            h83d4a3d_0    conda-forge
pip                       18.1                  py36_1000    conda-forge
pyarrow                   0.10.0           py36hfc679d8_0    conda-forge
pycparser                 2.19                       py_0    conda-forge
python                    3.6.7                h5001a0f_1    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.7                     py_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
setuptools                40.6.2                   py36_0    conda-forge
six                       1.11.0                py36_1001    conda-forge
sqlite                    3.25.3               hb1c47c0_0    conda-forge
tk                        8.6.9                ha92aebf_0    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

**Comment by kkraus14** [comment] 2018-11-28 23:55
`numba                     0.40.0dev0      np115py36hf484d3e_254    numba` can you pull a newer version of numba? we should be able to use a proper 0.40 or 0.41 release.

**Comment by kevingerman** [comment] 2018-11-30 22:13
Resolved by explicitly setting the numba version `numba>=0.41` in my conda environment.

However, the cudf recipe still specifies [numba>=0.40.0dev](https://github.com/rapidsai/cudf/blob/master/conda/recipes/cudf/meta.yaml#L32)

**Comment by kkraus14** [comment] 2018-11-30 22:14
> Resolved by explicitly setting the numba version `numba>=0.41` in my conda environment.
> 
> However, the cudf recipe still specifies [numba>=0.40.0dev](https://github.com/rapidsai/cudf/blob/master/conda/recipes/cudf/meta.yaml#L32)

Awesome, could you submit a pull request to resolve this? Ideally we'd like to support 0.40.0 and 0.41.0 without grabbing dev versions.

**Comment by kkraus14** [comment] 2019-01-08 20:30
This is a numba issue, unrelated to our codebase and other issues related to numba version are already open, closing.

**Closed by kkraus14** 2019-01-08 20:30 UTC
Labels: bug, cuDF (Python)
