### ISSUE TITLE
[BUG] possible leak in libcudf (with RMM)

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#3795] opened 2020-01-15 22:14 UTC
**Describe the bug**
I think there is a memory leak in cudf operations when using RMM Pool.  This is after the great libcudf++ merge.  We found this by looking at `Free/Alloc` calls made by RMM and observed more calls to `Alloc` compared with `Free`

**Steps/Code to reproduce bug**
```python
In [1]: import rmm

In [2]: from io import StringIO

In [3]: import pandas as pd
import
In [4]: import cudf

In [5]: rmm.reinitialize(pool_allocator=True, initial_pool_size=10**10, logging=True)
Out[5]: 0

In [6]: cdf = cudf.DataFrame({'a': 1, 'b': 'c'})

In [7]: cdf.a.null_count
Out[7]: 0

In [8]: del cdf

In [9]: df = pd.read_csv(StringIO(rmm.csv_log()))

In [10]: df[df['Event Type'] == 'Free'].count()
Out[10]:
Event Type        61
Device ID         61
Address           61
Stream            61
Size (bytes)      61
Free Memory       61
Total Memory      61
Current Allocs    61
Start             61
End               61
Elapsed           61
Location          61
dtype: int64

In [11]: df[df['Event Type'] == 'Alloc'].count()
Out[11]:
Event Type        64
Device ID         64
Address           64
Stream            64
Size (bytes)      64
Free Memory       64
Total Memory      64
Current Allocs    64
Start             64
End               64
Elapsed           64
Location          64
dtype: int64
```

We also observed similar behavior with calls to `count` and `groupby['a'].sum()`

cc @pentschev @kkraus14

**Comment by kkraus14** [comment] 2020-01-15 22:16
cc @shwina I think this looks like a memory leak in `cudf::column_view(...).null_count()`.

**Comment by kkraus14** [comment] 2020-01-15 22:26
a more minimal example that should also leak:
```
import cudf
cudf_col = cudf.core.column.column.as_column([1])
print(cudf_col.null_count)
```

**Comment by jrhemstad** [comment] 2020-01-15 22:45
Whether or not there is a leak is almost certainly independent of whether or not pool mode is used. 

I looked through `column_view::null_count()` and I'm 99.99999% certain there is no memory leak there. The only allocation happens for a single `device_scalar`: https://github.com/rapidsai/cudf/blob/e9b8748fdc3aaacc641a07b07be78c79ef5110dc/cpp/src/bitmask/null_mask.cu#L357

which through RAII is guarantee to call it's destructor, which will free the associated memory. 

Are we sure this isn't an issue with garbage collection and lazy freeing of memory?

**Comment by kkraus14** [comment] 2020-01-15 22:47
Doesn't `rmm` logging log allocations even in pool mode? The codepath for `null_count` in Python basically immediately goes to creating a `column_view` and calling `.null_count()` against that `column_view`.

**Comment by jrhemstad** [comment] 2020-01-15 22:47
> Doesn't rmm logging log allocations even in pool mode?

Yes, it logs allocations independent of what mode is used.

**Comment by kkraus14** [comment] 2020-01-15 22:58
Using the tip of branch-0.12 on both RMM and cuDF I'm unable to reproduce:
```
0
Event Type        56
Device ID         56
Address           56
Stream            56
Size (bytes)      56
Free Memory       56
Total Memory      56
Current Allocs    56
Start             56
End               56
Elapsed           56
Location          56
dtype: int64
Event Type        56
Device ID         56
Address           56
Stream            56
Size (bytes)      56
Free Memory       56
Total Memory      56
Current Allocs    56
Start             56
End               56
Elapsed           56
Location          56
dtype: int64
```

**Comment by kkraus14** [comment] 2020-01-15 23:43
Closing as @pentschev confirmed he can no longer reproduce either. Will open a new issue if a memory leak is discovered.

**Closed by kkraus14** 2020-01-15 23:43 UTC
Labels: bug, cuDF (Python)

**Comment by quasiben** [comment] 2020-01-16 03:06
sorry, for the noise and thanks for looking.

For the record I was using:

```
cudf 0.12.0b+1268.g815c75c
rmm 0.12.0a200114
```
