### ISSUE TITLE
Installation code for conda does not work on MacOS 

### ISSUE THREAD

**Issue by adam-erickson** [rapidsai/cudf#197] opened 2018-08-07 19:23 UTC
```
PackagesNotFoundError: The following packages are not available from current channels:
  - pygdf=0.1.0a2
```

**Comment by kkraus14** [comment] 2018-08-07 19:31
@adam-erickson I'm unable to reproduce this issue on my end. What system architecture are you on : linux / osx / windows?

Did you make sure to include the relevant channels in your install command? It should look like:
```
conda install -c numba -c conda-forge -c gpuopenanalytics/label/dev -c defaults pygdf=0.1.0a2
```

**Comment by adam-erickson** [comment] 2018-08-07 19:40
Yes. This issue occurred on MacOS with a relatively fresh install of Anaconda.

**Comment by kkraus14** [comment] 2018-08-07 20:32
@adam-erickson We aren't currently supporting osx builds or publishing osx builds on conda. I'd try to build libgdf and pygdf from source following the instructions on the readme and open a new issue if you run into issues.

**Comment by adam-erickson** [comment] 2018-08-07 21:06
@kkraus14 Thank you for looking into this, I've been excited to try the new GPU dataframes for some time now. Many machine learning folks use MacOS, so I would recommend supporting it in the future. Also, there should be a `libgdf` Homebrew formula ([link](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md)).

**Comment by kkraus14** [comment] 2018-08-08 05:39
@adam-erickson We will look into supporting MacOS in the future and if we do so, we will support installing via conda and Homebrew at a bare minimum.

For now, it may be possible to build libgdf and pygdf from source on MacOS. Do you have an NVIDIA GPU and CUDA installed in your MacOS environment?

**Comment by hudarsono** [comment] 2019-05-28 10:23
Is there any guideline to build from source in mac? It seems that the conda build env depends on rmm and nvstrings, which only available on linux.

**Comment by kkraus14** [comment] 2019-07-03 22:52
Going to close this as #1123 has more detailed information about the same issue of MacOS support.

**Closed by kkraus14** 2019-07-03 22:52 UTC
Labels: feature request
