### ISSUE TITLE
[QST] Unable to checkout rmm during cudf(v0.6.0) git clone

### ISSUE THREAD

**Issue by pradghos** [rapidsai/cudf#1312] opened 2019-03-29 06:19 UTC
**What is your question?**
``` 
Unable to checkout rmm during cudf(v0.6.0) git clone.  Did any body face this issue before ? 

git clone --recursive https://github.com/rapidsai/cudf -b v0.6.0
Cloning into 'cudf'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 36019 (delta 4), reused 16 (delta 4), pack-reused 35999
Receiving objects: 100% (36019/36019), 17.44 MiB | 9.64 MiB/s, done.
Resolving deltas: 100% (24437/24437), done.
Note: checking out '69021704458d465852f971623e11bff25dbdee79'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

Submodule 'thirdparty/cub' (https://github.com/rapidsai/thirdparty-cub.git) registered for path 'thirdparty/cub'
Submodule 'thirdparty/dlpack' (https://github.com/rapidsai/dlpack.git) registered for path 'thirdparty/dlpack'
Submodule 'thirdparty/jitify' (https://github.com/rapidsai/jitify.git) registered for path 'thirdparty/jitify'
Submodule 'thirdparty/moderngpu' (https://github.com/rapidsai/thirdparty-moderngpu.git) registered for path 'thirdparty/moderngpu'
Submodule 'thirdparty/rmm' (https://github.com/rapidsai/rmm.git) registered for path 'thirdparty/rmm'
Cloning into 'thirdparty/cub'...
remote: Enumerating objects: 32647, done.
remote: Total 32647 (delta 0), reused 0 (delta 0), pack-reused 32647
Receiving objects: 100% (32647/32647), 16.50 MiB | 9.93 MiB/s, done.
Resolving deltas: 100% (28622/28622), done.
Submodule path 'thirdparty/cub': checked out 'b165e1fb11eeea64ccf95053e40f2424312599cc'
Cloning into 'thirdparty/dlpack'...
remote: Enumerating objects: 140, done.
remote: Total 140 (delta 0), reused 0 (delta 0), pack-reused 140
Receiving objects: 100% (140/140), 53.02 KiB | 0 bytes/s, done.
Resolving deltas: 100% (47/47), done.
Submodule path 'thirdparty/dlpack': checked out '5c792cef3aee54ad8b7000111c9dc1797f327b59'
Cloning into 'thirdparty/jitify'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 135 (delta 10), reused 8 (delta 3), pack-reused 115
Receiving objects: 100% (135/135), 150.92 KiB | 0 bytes/s, done.
Resolving deltas: 100% (76/76), done.
Submodule path 'thirdparty/jitify': checked out 'c7c55b38333f5fa9ad5ec5e0804d5c9eedd14de2'
Cloning into 'thirdparty/moderngpu'...
remote: Enumerating objects: 1296, done.
remote: Total 1296 (delta 0), reused 0 (delta 0), pack-reused 1296
Receiving objects: 100% (1296/1296), 6.73 MiB | 3.31 MiB/s, done.
Resolving deltas: 100% (648/648), done.
Submodule path 'thirdparty/moderngpu': checked out 'c1fd31df008d79f727483e795b1ee1ce45b782ca'
Cloning into 'thirdparty/rmm'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 1124 (delta 2), reused 5 (delta 1), pack-reused 1113
Receiving objects: 100% (1124/1124), 390.63 KiB | 0 bytes/s, done.
Resolving deltas: 100% (511/511), done.
fatal: reference is not a tree: 28b6161bb668d266b06d0dd6cea4e0d880146c75
Unable to checkout '28b6161bb668d266b06d0dd6cea4e0d880146c75' in submodule path 'thirdparty/rmm'
``` 

Issue : 
``` 
fatal: reference is not a tree: 28b6161bb668d266b06d0dd6cea4e0d880146c75
Unable to checkout '28b6161bb668d266b06d0dd6cea4e0d880146c75' in submodule path 'thirdparty/rmm'
```

**Comment by harrism** [comment] 2019-04-02 01:43
I can confirm a local repro.

**Comment by harrism** [comment] 2019-04-02 01:45
@pradghos Since the master branch is now cudf 0.6.1, you can change your clone command to this:

`git clone --recursive https://github.com/rapidsai/cudf` and it works.  Will look into the issue with specifying the branch...

**Comment by pradghos** [comment] 2019-04-02 12:52
@harrism : Thanks for looking . yes. `git clone --recursive https://github.com/rapidsai/cudf` works.  Fixing the `specifying branch clone` issue would really help in case user wants to stick to specific `release tag`.

**Comment by raydouglass** [comment] 2019-04-02 13:39
Here is a workaround:

```
git clone --recursive https://github.com/rapidsai/cudf -b v0.6.1
cd cudf
git submodule sync thirdparty/rmm
git submodule update --init --recursive --remote thirdparty/rmm
```

**Comment by harrism** [comment] 2019-05-06 00:14
Since we have a workaround, I'm pushing this to v0.8. However, I do believe there is a problem with our release process in that releases point to the master branch of submodules, so leaving open to discuss.

**Comment by harrism** [comment] 2019-08-11 09:19
RMM is no longer a submodule in cudf. Closing.

**Closed by harrism** 2019-08-11 09:19 UTC
Labels: bug, git
