### ISSUE TITLE
[BUG] cudf 21.06.01 conda env libthrift version mismatch

### ISSUE THREAD

**Issue by pxLi** [rapidsai/cudf#8570] opened 2021-06-21 07:57 UTC
**Describe the bug**
install cudf w/ 
`conda install -y -c rapidsai -c rapidsai-nightly -c nvidia -c conda-forge -c defaults cudf=21.06.01 python=3.8 cudatoolkit=11.0`

conda installed version,
```
# conda list | grep libthrift
libthrift                 0.14.2               he6d91bd_0    conda-forge
# conda list | grep cudf
cudf                      21.06.01        cuda_11.0_py37_g101fc0fda4_2    rapidsai
libcudf                   21.06.01        cuda11.0_g101fc0fda4_2    rapidsai
```

but required 0.14.1,
```
[2021-06-21T07:10:03.043Z] Traceback (most recent call last):
[2021-06-21T07:10:03.043Z]   File "/home/ubuntu/spark-rapids/dist/target/rapids-4-spark_2.12-21.06.0-SNAPSHOT.jar/rapids/daemon_databricks.py", line 132, in manager
[2021-06-21T07:10:03.043Z]   File "/home/ubuntu/spark-rapids/dist/target/rapids-4-spark_2.12-21.06.0-SNAPSHOT.jar/rapids/worker.py", line 37, in initialize_gpu_mem
[2021-06-21T07:10:03.043Z]     from cudf import rmm
[2021-06-21T07:10:03.043Z]   File "/databricks/conda/envs/databricks-ml-gpu/lib/python3.7/site-packages/cudf/__init__.py", line 76, in <module>
[2021-06-21T07:10:03.043Z]     from cudf.io import (
[2021-06-21T07:10:03.043Z]   File "/databricks/conda/envs/databricks-ml-gpu/lib/python3.7/site-packages/cudf/io/__init__.py", line 9, in <module>
[2021-06-21T07:10:03.043Z]     from cudf.io.parquet import (
[2021-06-21T07:10:03.043Z]   File "/databricks/conda/envs/databricks-ml-gpu/lib/python3.7/site-packages/cudf/io/parquet.py", line 8, in <module>
[2021-06-21T07:10:03.043Z]     from pyarrow import dataset as ds, parquet as pq
[2021-06-21T07:10:03.043Z]   File "/databricks/conda/envs/databricks-ml-gpu/lib/python3.7/site-packages/pyarrow/dataset.py", line 24, in <module>
[2021-06-21T07:10:03.043Z]     from pyarrow._dataset import (  # noqa
[2021-06-21T07:10:03.043Z] ImportError: libthrift.so.0.14.1: cannot open shared object file: No such file or directory
```

**Comment by beckernick** [comment] 2021-06-21 13:40
Looks like 0.14.2 was released uploaded to conda forge yesterday, and pyarrow 1.0.1 is not compatible.

https://github.com/conda-forge/thrift-cpp-feedstock/pull/57

cc @shwina @galipremsagar @ajschmidt8

**Comment by beckernick** [comment] 2021-06-21 13:46
I can't reproduce this with a fresh environment version of the command supplied above. Conda solves for thrift-cpp 0.14.1 @galipremsagar 

`conda create -n test -c rapidsai -c rapidsai-nightly -c nvidia -c conda-forge -c defaults cudf=21.06.01 python=3.8 cudatoolkit=11.0`

**Comment by galipremsagar** [comment] 2021-06-21 15:16
I can't repro this error with `21.08` & `21.06` aswell:
```
conda create -n rapids-21.08 -c rapidsai-nightly -c nvidia -c conda-forge     rapids-blazing=21.08 python=3.8 cudatoolkit=11.2 ucx ucx-py ucx-proc=*=gpu
```

```
pgali@dt07:/nvme/0/pgali/cudf$ conda list | grep "thrift"
libthrift                 0.14.1               he6d91bd_1    conda-forge
thrift                    0.13.0           py38h709712a_2    conda-forge
thrift_sasl               0.3.0           py38h1e0a361_1002    conda-forge
```

**Comment by pxLi** [comment] 2021-06-22 01:24
talked in other thread, there are 2 pyarrow
```
  pyarrow           1.0.1  py37hb63ea2f_40_cuda  # libthrift 0.14.2
  pyarrow           1.0.1  py37h72578d1_5_cuda   # libthrift 0.14.1
```
and it could randomly pick one of them, 
if py37h72578d1_5_cuda, then we are good. if py37hb63ea2f_40_cuda, then the pyarrow import will fail

**Comment by galipremsagar** [comment] 2021-07-12 17:49
Closing this issue as the dependency has been pinned, please feel free to reopen if this issue re-occurs.

**Closed by galipremsagar** 2021-07-12 17:49 UTC
Labels: bug, conda
