### ISSUE TITLE
[BUG]cudaErrorIllegalAddress error encountered while reading parquet files saved by cuDF

### ISSUE THREAD

**Issue by wujinzhong** [rapidsai/cudf#3642] opened 2019-12-19 05:48 UTC
**Describe the bug**
I used cuDF to generate thousands of parquet files with N columns, and read the files in with dask_cudf (DGX1 16GB) and do some groupby and aggregation operations upon it. I run several rounds to test its performance. While reading parquet files, this cudaErrorIllegalAddress occurs in some rounds I run. When it occurs, most of the time the application can go forward to the end of the round successfully; sometimes it crashes the app. 

**Steps/Code to reproduce bug**
I generate random data and saved to parquet files(~4000 files, several hundred GB) with this py script:

import cudf, dask_cudf
import base64
import pandas as pd
import random
import numpy as np
import os

def generate_string_series(number, minRandRange, maxRandRange):
    stringList = []
    for i in range(number):
        randnum = random.randrange(minRandRange, maxRandRange)
        str = base64.b64encode(os.urandom(randnum)).decode("utf-8")
        stringList.append(str)
    return pd.Series(stringList)

def generate_positive_and_zero_integer_series(number, minRandRange, maxRandRange):
    res = [random.randrange(minRandRange, maxRandRange) for i in range(number)]
    return pd.Series(res)

def get_columns():
    return ['col0','col1','col2','col3','col4','col5','col6','col7','col8','col9'
            ,'col10','col11','col12','col13','col14','col15','col16','col17','col18','col19']
def get_columns_type():
    return ['object','int64','object','object','int64','int64','object','object','object','int64'
            ,'object','object','object','object','object','object','int64','object','object','object']

def generate_parquet_file(filepath, rows, columns, columns_type):
    pdf = pd.DataFrame()
    for i, col in enumerate(columns):
        if columns_type[i] == "int64":
            pdf[col] = generate_positive_and_zero_integer_series(rows, 0, 100)
        elif columns_type[i] == "object":
            pdf[col] = generate_string_series(rows, 0, 100)
        else:
            print("error column type:", col)
            pdf[col] = generate_positive_and_zero_integer_series(rows, 0, 100)
    cdf = cudf.from_pandas(pdf)
    cdf = cdf.to_parquet(filepath, compression="gzip")

rows_per_file = 6_000
for i in range(4000):
    filepath = "./data/parquet_random_{:0>4d}".format( i )
    print("generate file: ", filepath)
    generate_parquet_file(filepath, rows_per_file, get_columns(), get_columns_type())

**Steps/Code to reproduce bug**
Tested with this py script:

import os
import re
import sys
import time
import cudf
import pynvml
import getopt
import pandas as pd
import dask_cudf
from dask_cuda import LocalCUDACluster
from dask.distributed import Client, wait
import dask

def get_columns():
    return ['col0','col1','col2','col3','col4','col5','col6','col7','col8','col9'
            ,'col10','col11','col12','col13','col14','col15','col16','col17','col18','col19']

def ls_dir(path):
    result = []
    for file_path in os.listdir(path):
        file_path = os.path.join(path, file_path)
        if os.path.isfile(file_path):
            result.append(file_path)
        elif os.path.isdir(file_path):
            sub_result = ls_dir(file_path)
            if not sub_result:
                print('empty ', sub_result)
            else:
                result += sub_result
        else:
            print('unknow ', file_path)
    return sorted(result)

def file_filter(file_list):
    new_file_list = []
    for file in file_list:
        if re.search('parquet', file) is None:
            continue
        else:
            new_file_list.append(file)
    return new_file_list

cluster = []
client = []
if __name__ == '__main__':
    cluster = LocalCUDACluster(dashboard_address=":7689",
                               n_workers=8,
                               threads_per_worker=1,
                               processes=True,
                               device_memory_limit=None,
                               CUDA_VISIBLE_DEVICES='0,1,2,3,4,5,6,7')

    client = Client(cluster)
    
    def initialize_rmm():
        import rmm
        rmm.reinitialize(
            pool_allocator=False, # default is False
            managed_memory=True, # default is False
            #initial_pool_size=14<, # set to 2GiB. Default is 1/2 total GPU memory
            devices=[0,1,2,3,4,5,6,7], # GPU device  IDs to register. By default registers only GPU 0.
            logging=False, # default is False -- has perf overhead
        )       
        import cudf

    client.run(initialize_rmm)

def main(round_num, file_num):
    file_list = file_filter(ls_dir('/data/parquet/'))
    df = dask_cudf.read_parquet(file_list[:file_num], skip_rows=-1, num_rows=-1, string_to_categorical=False,columns=top20_columns())
    df = df.persist()
    dfc = df.groupby('col4').mean().persist()
    dfc = dfc.compute()
    dfc.to_csv("/foo_dask_{:0>2d}_{:0>7d}.csv".format(round_num, file_num))

if __name__ == "__main__":
    for rd in range(1,5):
        print("round {}".format(rd))
        file_num = 1
        for i in range(0,14):
            main(rd, file_num)
            file_num *= 2

if __name__ == "__main__":
    client.close()

**Error log**
distributed.worker - WARNING -  Compute Failed
Function:  read_parquet_part
args:      (<function CudfEngine.read_partition at 0x7f6c97f71400>, <fsspec.implementations.local.LocalFileSystem object at 0x7f6c97535c18>, Empty DataFrame
Columns: [col0,col1,col2,col3,col4,col5,col6,col7,col8,col9
            ,col10,col11,col12,col13,col14,col15,col16,col17,col18,col19]
Index: [], ('/xxxxx/f2ee721581c84b33bb9adb34eed9c298.parquet', None, []), ['col0','col1','col2','col3','col4','col5','col6','col7','col8','col9'
            ,'col10','col11','col12','col13','col14','col15','col16','col17','col18','col19'], None, {'partitions': None, 'categories': None, 'skip_rows': -1, 'num_rows': -1, 'string_to_categorical': False})
kwargs:    {}
Exception: RuntimeError('CUDA error encountered at: /conda/conda-bld/libcudf_1571332716676/work/cpp/src/io/parquet/parquet_reader_impl.cu:469: 77 cudaErrorIllegalAddress an illegal memory access was encountered',)

**Expected behavior**
Expect no cudaErrorIllegalAddress error occurs.

**Environment overview (please complete the following information)**
 - Environment location: [Docker]
 - Method of cuDF install: [Docker]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
docker pull rapidsai/rapidsai:cuda10.0-runtime-ubuntu18.04-py3.7
nvidia-docker run -it -v /home/myhome:/myhome rapidsai/rapidsai:cuda10.0-runtime-ubuntu18.04-py3.7 bash

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

<details><summary>Click here to see environment details</summary><pre>

     **git***
     commit df321e5f39b03c53bc5eb7fb51313573f2a0a3ec (HEAD -> master, origin/master)
     Merge: efe8b65 2eecf93
     Author: Taurean Dyer <46935140+taureandyernv@users.noreply.github.com>
     Date:   Wed Dec 11 14:51:15 2019 -0800

     Merge pull request #282 from rlratzel/master

     [HOTFIX] Removing KNN MNMG notebook since it is no longer supported in the current release.
     **git submodules***

     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
     NAME="Ubuntu"
     VERSION="18.04.3 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.3 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux 90c3a35ad2ac 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

     ***GPU Information***
     Thu Dec 19 05:20:57 2019
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla V100-SXM2...  On   | 00000000:06:00.0 Off |                    0 |
     | N/A   42C    P0    57W / 300W |   2632MiB / 16130MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla V100-SXM2...  On   | 00000000:07:00.0 Off |                    0 |
     | N/A   44C    P0    61W / 300W |    538MiB / 16130MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla V100-SXM2...  On   | 00000000:0A:00.0 Off |                    0 |
     | N/A   45C    P0    60W / 300W |    614MiB / 16130MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   3  Tesla V100-SXM2...  On   | 00000000:0B:00.0 Off |                    0 |
     | N/A   43C    P0    69W / 300W |    626MiB / 16130MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   4  Tesla V100-SXM2...  On   | 00000000:85:00.0 Off |                    0 |
     | N/A   43C    P0    61W / 300W |    578MiB / 16130MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   5  Tesla V100-SXM2...  On   | 00000000:86:00.0 Off |                    0 |
     | N/A   45C    P0    58W / 300W |    568MiB / 16130MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   6  Tesla V100-SXM2...  On   | 00000000:89:00.0 Off |                    0 |
     | N/A   50C    P0    61W / 300W |    618MiB / 16130MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   7  Tesla V100-SXM2...  On   | 00000000:8A:00.0 Off |                    0 |
     | N/A   52C    P0   101W / 300W |   3279MiB / 16130MiB |     35%      Default |
     +-------------------------------+----------------------+----------------------+

     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     +-----------------------------------------------------------------------------+

     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              80
     On-line CPU(s) list: 0-79
     Thread(s) per core:  2
     Core(s) per socket:  20
     Socket(s):           2
     NUMA node(s):        2
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               79
     Model name:          Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
     Stepping:            1
     CPU MHz:             3124.417
     CPU max MHz:         3600.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            4389.82
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            256K
     L3 cache:            51200K
     NUMA node0 CPU(s):   0-19,40-59
     NUMA node1 CPU(s):   20-39,60-79
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts flush_l1d

     ***CMake***

     ***g++***

     ***nvcc***

     ***Python***
     /opt/conda/envs/rapids/bin/python
     Python 3.7.3

     ***Environment Variables***
     PATH                            : /opt/conda/envs/rapids/bin:/opt/conda/condabin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/conda/bin:/conda/bin
     LD_LIBRARY_PATH                 : /opt/conda/envs/rapids/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/lib
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /opt/conda/envs/rapids
     PYTHON_PATH                     :

     ***conda packages***
     /opt/conda/condabin/conda
     # packages in environment at /opt/conda/envs/rapids:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main    conda-forge
     _tflow_select             2.1.0                       gpu
     absl-py                   0.8.1                    py37_0    conda-forge
     aiohttp                   3.6.2            py37h516909a_0    conda-forge
     arrow-cpp                 0.15.0           py37h090bef1_2    conda-forge
     astor                     0.7.1                      py_0    conda-forge
     async-timeout             3.0.1                   py_1000    conda-forge
     attrs                     19.3.0                     py_0    conda-forge
     backcall                  0.1.0                      py_0    conda-forge
     blas                      2.14                   openblas    conda-forge
     bleach                    3.1.0                      py_0    conda-forge
     bokeh                     1.4.0                    py37_0    conda-forge
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     brotli                    1.0.7             he1b5a44_1000    conda-forge
     bzip2                     1.0.8                h516909a_2    conda-forge
     c-ares                    1.15.0            h516909a_1001    conda-forge
     ca-certificates           2019.11.28           hecc5488_0    conda-forge
     cairo                     1.16.0            hfb77d84_1002    conda-forge
     certifi                   2019.11.28               py37_0    conda-forge
     cfitsio                   3.470                hb60a0a2_2    conda-forge
     chardet                   3.0.4                 py37_1003    conda-forge
     click                     7.0                        py_0    conda-forge
     cloudpickle               1.2.2                      py_1    conda-forge
     cudatoolkit               10.0.130                      0    nvidia
     cudf                      0.11.0                   py37_0    rapidsai
     cudnn                     7.6.0                cuda10.0_0    nvidia
     cugraph                   0.11.0                   py37_0    rapidsai
     cuml                      0.11.0          cuda10.0_py37_0    rapidsai
     cupti                     10.0.130                      0
     cupy                      6.6.0            py37h809cb0f_1    conda-forge
     curl                      7.65.3               hf8cf82a_0    conda-forge
     cuspatial                 0.11.0                   py37_0    rapidsai
     cycler                    0.10.0                     py_2    conda-forge
     cython                    0.29.14          py37he1b5a44_0    conda-forge
     cytoolz                   0.10.1           py37h516909a_0    conda-forge
     dask                      2.9.0                      py_0    conda-forge
     dask-core                 2.9.0                      py_0    conda-forge
     dask-cuda                 0.11.0                   py37_0    rapidsai
     dask-cudf                 0.11.0                   py37_0    rapidsai
     dask-glm                  0.2.0                      py_1    conda-forge
     dask-labextension         1.0.3                      py_0    conda-forge
     dask-ml                   1.1.1                      py_0    conda-forge
     dask-xgboost              0.2.0.dev28      cuda10.0py36_0    rapidsai
     dbus                      1.13.6               he372182_0    conda-forge
     decorator                 4.4.1                      py_0    conda-forge
     defusedxml                0.6.0                      py_0    conda-forge
     distributed               2.9.0                      py_0    conda-forge
     dlpack                    0.2                  he1b5a44_1    conda-forge
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     entrypoints               0.3                   py37_1000    conda-forge
     expat                     2.2.5             he1b5a44_1004    conda-forge
     fastavro                  0.22.7           py37h516909a_0    conda-forge
     fastrlock                 0.4             py37he1b5a44_1000    conda-forge
     fontconfig                2.13.1            h86ecdb6_1001    conda-forge
     freetype                  2.10.0               he983fc9_1    conda-forge
     freexl                    1.0.5             h14c3975_1002    conda-forge
     fsspec                    0.6.1                      py_0    conda-forge
     gast                      0.2.2                      py_0    conda-forge
     gdal                      2.4.3            py37h5f563d9_9    conda-forge
     geos                      3.7.2                he1b5a44_2    conda-forge
     geotiff                   1.5.1                hbd99317_7    conda-forge
     gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
     gflags                    2.2.2             he1b5a44_1002    conda-forge
     giflib                    5.1.7                h516909a_1    conda-forge
     glib                      2.58.3          py37h6f030ca_1002    conda-forge
     glog                      0.4.0                he1b5a44_1    conda-forge
     google-pasta              0.1.8                      py_0    conda-forge
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     grpcio                    1.23.0           py37he9ae1f9_0    conda-forge
     gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
     gstreamer                 1.14.5               h36ae1b5_0    conda-forge
     h5py                      2.10.0          nompi_py37h513d04c_100    conda-forge
     hdf4                      4.2.13            hf30be14_1003    conda-forge
     hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     idna                      2.8                   py37_1000    conda-forge
     importlib_metadata        1.2.0                    py37_0    conda-forge
     ipykernel                 5.1.3            py37h5ca1d4c_0    conda-forge
     ipython                   7.3.0            py37h24bf2e0_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     jedi                      0.15.1                   py37_0    conda-forge
     jinja2                    2.10.3                     py_0    conda-forge
     joblib                    0.14.0                     py_0    conda-forge
     jpeg                      9c                h14c3975_1001    conda-forge
     json-c                    0.13.1            h14c3975_1001    conda-forge
     json5                     0.8.5                      py_0    conda-forge
     jsonschema                3.2.0                    py37_0    conda-forge
     jupyter-server-proxy      1.2.0                      py_0    conda-forge
     jupyter_client            5.3.3                    py37_1    conda-forge
     jupyter_core              4.6.1                    py37_0    conda-forge
     jupyterlab                1.0.7                    py37_0    conda-forge
     jupyterlab-nvdashboard    0.1.11                   pypi_0    pypi
     jupyterlab_server         1.0.6                      py_0    conda-forge
     kealib                    1.4.10            h58c409b_1005    conda-forge
     keras-applications        1.0.8                      py_1    conda-forge
     keras-preprocessing       1.1.0                      py_0    conda-forge
     kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
     krb5                      1.16.3            h05b26f9_1001    conda-forge
     ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
     libblas                   3.8.0               14_openblas    conda-forge
     libcblas                  3.8.0               14_openblas    conda-forge
     libclang                  9.0.0           default_hde54327_4    conda-forge
     libcudf                   0.11.0               cuda10.0_0    rapidsai
     libcugraph                0.11.0               cuda10.0_0    rapidsai
     libcuml                   0.11.0               cuda10.0_0    rapidsai
     libcumlprims              0.11.0a191211      cuda10.0_130    rapidsai-nightly
     libcurl                   7.65.3               hda55be3_0    conda-forge
     libcuspatial              0.11.0               cuda10.0_0    rapidsai
     libdap4                   3.20.4               hd3bb157_0    conda-forge
     libedit                   3.1.20170329      hf8c457e_1001    conda-forge
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1             he1b5a44_1006    conda-forge
     libgcc-ng                 7.3.0                hdf63c60_2    conda-forge
     libgdal                   2.4.3                h2f07a13_9    conda-forge
     libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
     libiconv                  1.15              h516909a_1005    conda-forge
     libkml                    1.3.0             h4fcabce_1010    conda-forge
     liblapack                 3.8.0               14_openblas    conda-forge
     liblapacke                3.8.0               14_openblas    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libllvm9                  9.0.0                hc9558a2_3    conda-forge
     libnetcdf                 4.7.1           nompi_h94020b1_102    conda-forge
     libnvstrings              0.11.0               cuda10.0_0    rapidsai
     libopenblas               0.3.7                h5ec1e0e_5    conda-forge
     libpng                    1.6.37               hed695b0_0    conda-forge
     libpq                     11.5                 hd9ab2ff_2    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librmm                    0.11.0               cuda10.0_0    rapidsai
     libsodium                 1.0.17               h516909a_0    conda-forge
     libspatialite             4.3.0a            h4f6d029_1032    conda-forge
     libssh2                   1.8.2                h22169c7_2    conda-forge
     libstdcxx-ng              7.3.0                hdf63c60_2    conda-forge
     libtiff                   4.1.0                hfc65ed5_0    conda-forge
     libuuid                   2.32.1            h14c3975_1000    conda-forge
     libuv                     1.33.1               h516909a_0    conda-forge
     libxcb                    1.13              h14c3975_1002    conda-forge
     libxgboost                1.0.0dev.rapidsai0.11      cuda10.0_1    rapidsai
     libxkbcommon              0.9.1                hebb1f50_0    conda-forge
     libxml2                   2.9.10               hee79883_0    conda-forge
     llvmlite                  0.30.0           py37h8b12597_1    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     markdown                  3.1.1                      py_0    conda-forge
     markupsafe                1.1.1            py37h516909a_0    conda-forge
     matplotlib                3.1.2                    py37_1    conda-forge
     matplotlib-base           3.1.2            py37h250f245_1    conda-forge
     mistune                   0.8.4           py37h516909a_1000    conda-forge
     more-itertools            8.0.2                      py_0    conda-forge
     msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
     multidict                 4.6.1            py37h516909a_0    conda-forge
     multipledispatch          0.6.0                      py_0    conda-forge
     nbconvert                 5.6.1                    py37_0    conda-forge
     nbformat                  4.4.0                      py_1    conda-forge
     nccl                      2.4.6.1              cuda10.0_0    nvidia
     ncurses                   6.1               hf484d3e_1002    conda-forge
     networkx                  2.4                        py_0    conda-forge
     nodejs                    13.0.0               h10a4023_1    conda-forge
     nomkl                     2.0                           0
     notebook                  6.0.1                    py37_0    conda-forge
     nspr                      4.24                 he1b5a44_0    conda-forge
     nss                       3.47                 he751ad9_0    conda-forge
     numba                     0.46.0           py37hb3f55d8_1    conda-forge
     numpy                     1.17.3           py37h95a1406_0    conda-forge
     nvstrings                 0.11.0                   py37_0    rapidsai
     olefile                   0.46                       py_0    conda-forge
     openblas                  0.3.7                he1df0ab_5    conda-forge
     openjpeg                  2.3.1                h981e76c_3    conda-forge
     openssl                   1.1.1d               h516909a_0    conda-forge
     opt_einsum                3.1.0                      py_0    conda-forge
     packaging                 19.2                       py_0    conda-forge
     pandas                    0.24.2           py37hb3f55d8_1    conda-forge
     pandoc                    2.8.1                         0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.5.1                      py_0    conda-forge
     partd                     1.0.0                      py_0    conda-forge
     patsy                     0.5.1                      py_0    conda-forge
     pcre                      8.43                 he1b5a44_0    conda-forge
     pexpect                   4.7.0                    py37_0    conda-forge
     pickleshare               0.7.5                 py37_1000    conda-forge
     pillow                    6.2.1            py37hd70f55b_1    conda-forge
     pip                       19.3.1                   py37_0    conda-forge
     pixman                    0.38.0            h516909a_1003    conda-forge
     pluggy                    0.13.0                   py37_0    conda-forge
     poppler                   0.67.0               h14e79db_8    conda-forge
     poppler-data              0.4.9                         1    conda-forge
     postgresql                11.5                 hc63931a_2    conda-forge
     proj                      6.2.1                hc80f0dc_0    conda-forge
     prometheus_client         0.7.1                      py_0    conda-forge
     prompt-toolkit            2.0.10                   pypi_0    pypi
     protobuf                  3.8.0            py37he1b5a44_2    conda-forge
     psutil                    5.6.7            py37h516909a_0    conda-forge
     pthread-stubs             0.4               h14c3975_1001    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     py                        1.8.0                      py_0    conda-forge
     py-xgboost                1.0.0dev.rapidsai0.11  cuda10.0py37_1    rapidsai
     pyarrow                   0.15.0           py37h8b68381_1    conda-forge
     pygments                  2.5.2                      py_0    conda-forge
     pynvml                    8.0.3                      py_0    conda-forge
     pyparsing                 2.4.5                      py_0    conda-forge
     pyqt                      5.12.3           py37hcca6a23_1    conda-forge
     pyqt5-sip                 4.19.18                  pypi_0    pypi
     pyqtwebengine             5.12.1                   pypi_0    pypi
     pyrsistent                0.15.6           py37h516909a_0    conda-forge
     pytest                    5.3.1                    py37_0    conda-forge
     python                    3.7.3                h357f687_2    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     pytz                      2019.3                     py_0    conda-forge
     pyyaml                    5.2              py37h516909a_0    conda-forge
     pyzmq                     18.1.1           py37h1768529_0    conda-forge
     qt                        5.12.5               hd8c4c69_1    conda-forge
     rapids                    0.11.0          cuda10.0_py37_11    rapidsai
     rapids-xgboost            0.11.0          cuda10.0_py37_11    rapidsai
     re2                       2019.12.01           he1b5a44_0    conda-forge
     readline                  8.0                  hf8c457e_0    conda-forge
     rmm                       0.11.0                   py37_0    rapidsai
     scikit-learn              0.22             py37hcdab131_1    conda-forge
     scipy                     1.3.2            py37h921218d_0    conda-forge
     seaborn                   0.9.0                      py_2    conda-forge
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                42.0.2                   py37_0    conda-forge
     simpervisor               0.3                        py_1    conda-forge
     six                       1.13.0                   py37_0    conda-forge
     snappy                    1.1.7             he1b5a44_1002    conda-forge
     sortedcontainers          2.1.0                      py_0    conda-forge
     sqlite                    3.30.1               hcee41ef_0    conda-forge
     statsmodels               0.10.2           py37hc1659b7_0    conda-forge
     tblib                     1.4.0                      py_0    conda-forge
     tensorboard               2.0.0              pyhb38c66f_1
     tensorflow                2.0.0           gpu_py37h768510d_0
     tensorflow-base           2.0.0           gpu_py37h0ec5d1f_0
     tensorflow-estimator      2.0.0              pyh2649769_0
     termcolor                 1.1.0                      py_2    conda-forge
     terminado                 0.8.3                    py37_0    conda-forge
     testpath                  0.4.4                      py_0    conda-forge
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.10               hed695b0_0    conda-forge
     toolz                     0.10.0                     py_0    conda-forge
     tornado                   6.0.3            py37h516909a_0    conda-forge
     traitlets                 4.3.3                    py37_0    conda-forge
     tzcode                    2019a             h516909a_1002    conda-forge
     umap-learn                0.3.10                   py37_0    conda-forge
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     wcwidth                   0.1.7                      py_1    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     werkzeug                  0.16.0                     py_0    conda-forge
     wheel                     0.33.6                   py37_0    conda-forge
     wrapt                     1.11.2           py37h516909a_0    conda-forge
     xerces-c                  3.2.2             h8412b87_1004    conda-forge
     xgboost                   1.0.0dev.rapidsai0.11  cuda10.0py37_1    rapidsai
     xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
     xorg-libice               1.0.10               h516909a_0    conda-forge
     xorg-libsm                1.2.3             h84519dc_1000    conda-forge
     xorg-libx11               1.6.9                h516909a_0    conda-forge
     xorg-libxau               1.0.9                h14c3975_0    conda-forge
     xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
     xorg-libxext              1.3.4                h516909a_0    conda-forge
     xorg-libxrender           0.9.10            h516909a_1002    conda-forge
     xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
     xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
     xorg-xproto               7.0.31            h14c3975_1007    conda-forge
     xz                        5.2.4             h14c3975_1001    conda-forge
     yaml                      0.2.2                h516909a_1    conda-forge
     yarl                      1.3.0           py37h516909a_1000    conda-forge
     zeromq                    4.3.2                he1b5a44_2    conda-forge
     zict                      1.0.0                      py_0    conda-forge
     zipp                      0.6.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1006    conda-forge
     zstd                      1.4.3                h3b9ef0a_0    conda-forge

</pre></details>

**Additional context**

**Comment by OlivierNV** [comment] 2019-12-22 02:03
Does this reproduce with the 'official' cudf 0.11 release ? The call stack with libcudf_1571332716676 appears to point to an older build that is missing some reader fixes (parquet_reader_impl for cudf 0.11 should be in the legacy folder).

**Comment by wujinzhong** [comment] 2019-12-24 01:08
> Does this reproduce with the 'official' cudf 0.11 release ? The call stack with libcudf_1571332716676 appears to point to an older build that is missing some reader fixes (parquet_reader_impl for cudf 0.11 should be in the legacy folder).

Yes, with latest RAPIDS 0.11 from here https://rapids.ai/start.html; and I can reproduce it with RAPIDS 0.10 too.

**Comment by OlivierNV** [comment] 2020-01-20 17:36
Since the compression is gzip, and it seems that the illegal access occured after decompression, I'm wondering if this could be the same issue as #3800 (fixed by PR #3821 )

**Comment by kkraus14** [comment] 2020-01-21 20:50
@wujinzhong Please try with the latest 0.12 nightly or 0.12 when it is released and feel free to reopen this if this issue still persists.

**Closed by kkraus14** 2020-01-21 20:50 UTC
Labels: bug, cuIO
