### ISSUE TITLE
[QST] Unable to install Rapids AI on Ubuntu 20.04

### ISSUE THREAD

**Issue by VigneshN1997** [rapidsai/cudf#10771] opened 2022-05-02 23:40 UTC
Hi all,

I am trying to install the rapids ai module using conda using the command:

conda create -n rapids-22.04 -c rapidsai -c nvidia -c conda-forge \
    rapids=22.04 python=3.8 cudatoolkit=11.5 dask-sql

But I get the following error:

PackagesNotFoundError: The following packages are not available from current channels:

  - rapids=22.04

Current channels:

  - https://conda.anaconda.org/rapidsai/linux-ppc64le
  - https://conda.anaconda.org/rapidsai/noarch
  - https://conda.anaconda.org/nvidia/linux-ppc64le
  - https://conda.anaconda.org/nvidia/noarch
  - https://conda.anaconda.org/numba/linux-ppc64le
  - https://conda.anaconda.org/numba/noarch
  - https://conda.anaconda.org/conda-forge/linux-ppc64le
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-ppc64le
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-ppc64le
  - https://repo.anaconda.com/pkgs/r/noarch

I have tried older versions of the package too but I get the same error.

I am not sure how to resolve this.

**Comment by quasiben** [comment] 2022-05-03 02:09
I just tried the above with `mamba` and was unable to reproduce.  I'd expect this to work with conda as well (though maybe take slightly longer).   Are you using latest conda (4.12.0) ?  If so, would you be willing to try with the [mamba installer](https://github.com/mamba-org/mamba)

**Comment by VigneshN1997** [comment] 2022-05-03 17:07
Hi. Sure I will give it a try. I think the issue could be because of the architecture being [ppc64le] and not x64 but yea I will try it using mamba too

**Comment by quasiben** [comment] 2022-05-03 17:17
Ah yes, RAPIDS does not support `ppc64le` conda builds

**Comment by beckernick** [comment] 2022-05-23 16:51
I'm going to close this issue as answered, but please feel free to reopen the discussion.

**Closed by beckernick** 2022-05-23 16:51 UTC
Labels: question, ? - Needs Triage
