### ISSUE TITLE
[BUG] Failed to import Python cudf in the recent nightly releases

### ISSUE THREAD

**Issue by firestarman** [rapidsai/cudf#9622] opened 2021-11-08 04:58 UTC
**Describe the bug**
Failed to import the cudf python module due to the error below in the latest nightly release (11-07).

```
Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liangcail/miniconda3/envs/cudf-python-rt/lib/python3.8/site-packages/cudf/__init__.py", line 4, in <module>
    validate_setup()
  File "/home/liangcail/miniconda3/envs/cudf-python-rt/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 18, in validate_setup
    from rmm._cuda.gpu import (
  File "/home/liangcail/miniconda3/envs/cudf-python-rt/lib/python3.8/site-packages/rmm/__init__.py", line 16, in <module>
    from rmm import mr
  File "/home/liangcail/miniconda3/envs/cudf-python-rt/lib/python3.8/site-packages/rmm/mr.py", line 14, in <module>
    from rmm._lib.memory_resource import (
  File "/home/liangcail/miniconda3/envs/cudf-python-rt/lib/python3.8/site-packages/rmm/_lib/__init__.py", line 15, in <module>
    from .device_buffer import DeviceBuffer
  File "rmm/_lib/device_buffer.pyx", line 1, in init rmm._lib.device_buffer
ImportError: /home/liangcail/miniconda3/envs/cudf-python-rt/lib/python3.8/site-packages/rmm/_lib/memory_resource.cpython-38-x86_64-linux-gnu.so: undefined symbol: cudaMemPoolCreate, version libcudart.so.11.0
>>> 
```

**Steps/Code to reproduce bug**
Install the latest nightly version of Python cudf .
  `conda install -c rapidsai-nightly -c nvidia -c numba -c conda-forge cudf python=3.8 cudatoolkit=11.0`,
Then open a Python shell and execute `import cudf`.

**Expected behavior**
The `import` statement should not fail.

**Environment overview (please complete the following information)**
 - Environment location:  Bare-metal
 - Method of cuDF install: [conda]

 ***conda packages***
```
     /home/liangcail/miniconda3/condabin/conda
     # packages in environment at /home/liangcail/miniconda3/envs/cudf-python-rt:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       1_gnu    conda-forge
     abseil-cpp                20210324.2           h9c3ff4c_0    conda-forge
     arrow-cpp                 5.0.0           py38hd93b8a5_0_cuda    conda-forge
     arrow-cpp-proc            3.0.0                      cuda    conda-forge
     attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
     aws-c-cal                 0.5.11               h95a6274_0    conda-forge
     aws-c-common              0.6.2                h7f98852_0    conda-forge
     aws-c-event-stream        0.2.7               h3541f99_13    conda-forge
     aws-c-io                  0.10.5               hfb6a706_0    conda-forge
     aws-checksums             0.1.11               ha31a3da_7    conda-forge
     aws-sdk-cpp               1.8.186              hb4091e7_3    conda-forge
     bzip2                     1.0.8                h7f98852_4    conda-forge
     c-ares                    1.17.1               h7f98852_1    conda-forge
     ca-certificates           2021.10.8            ha878542_0    conda-forge
     cachetools                4.2.2              pyhd8ed1ab_0    conda-forge
     certifi                   2021.10.8        py38h578d9bd_1    conda-forge
     cudatoolkit               11.0.221             h6bb024c_0    nvidia
     cudf                      21.12.00a211105 cuda_11.0_py38_g4cba672c17_224    rapidsai-nightly
     cudnn                     8.0.0                cuda11.0_0    nvidia
     cupy                      8.0.0            py38hb7c6141_0    rapidsai-nightly
     dlpack                    0.5                  h9c3ff4c_0    conda-forge
     fastavro                  1.4.4            py38h497a2fe_0    conda-forge
     fastrlock                 0.6              py38h709712a_1    conda-forge
     fsspec                    2021.7.0           pyhd8ed1ab_0    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     glog                      0.5.0                h48cff8f_0    conda-forge
     grpc-cpp                  1.38.1               h36ce80c_0    conda-forge
     importlib-metadata        4.6.1            py38h578d9bd_0    conda-forge
     importlib_metadata        4.6.1                hd8ed1ab_0    conda-forge
     iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
     krb5                      1.19.1               hcc1bbae_0    conda-forge
     ld_impl_linux-64          2.36.1               hea4e1c9_1    conda-forge
     libblas                   3.9.0                9_openblas    conda-forge
     libbrotlicommon           1.0.9                h7f98852_5    conda-forge
     libbrotlidec              1.0.9                h7f98852_5    conda-forge
     libbrotlienc              1.0.9                h7f98852_5    conda-forge
     libcblas                  3.9.0                9_openblas    conda-forge
     libcudf                   21.12.00a211107 cuda11.0_g4cba672c17_224    rapidsai-nightly
     libcurl                   7.77.0               h2574ce0_0    conda-forge
     libedit                   3.1.20191231         he28a2e2_2    conda-forge
     libev                     4.33                 h516909a_1    conda-forge
     libevent                  2.1.10               hcdb4288_3    conda-forge
     libffi                    3.3                  h58526e2_2    conda-forge
     libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
     libgfortran-ng            9.3.0               hff62375_19    conda-forge
     libgfortran5              9.3.0               hff62375_19    conda-forge
     libgomp                   9.3.0               h2828fa1_19    conda-forge
     liblapack                 3.9.0                9_openblas    conda-forge
     libllvm10                 10.0.1               he513fc3_3    conda-forge
     libnghttp2                1.43.0               h812cca2_0    conda-forge
     libopenblas               0.3.15          pthreads_h8fe5266_1    conda-forge
     libprotobuf               3.16.0               h780b84a_0    conda-forge
     librmm                    21.12.00a211107 cuda11_g76ae622_20_no_cma    rapidsai-nightly
     libssh2                   1.9.0                ha56f1ee_6    conda-forge
     libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
     libthrift                 0.14.2               he6d91bd_1    conda-forge
     libutf8proc               2.6.1                h7f98852_0    conda-forge
     llvmlite                  0.37.0           py38he1b5a44_0    numba
     lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
     more-itertools            8.8.0              pyhd8ed1ab_0    conda-forge
     nccl                      2.7.8.1            h4962215_100    nvidia
     ncurses                   6.2                  h58526e2_4    conda-forge
     numba                     0.54.1          np1.11py3.8hc13618b_g39aef3deb_0    numba
     numpy                     1.20.3           py38h9894fe3_1    conda-forge
     nvtx                      0.2.3            py38h497a2fe_0    conda-forge
     openssl                   1.1.1k               h7f98852_0    conda-forge
     orc                       1.6.9                h58a87f1_0    conda-forge
     packaging                 21.0               pyhd8ed1ab_0    conda-forge
     pandas                    1.3.1            py38h1abd341_0    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     pip                       21.1.3             pyhd8ed1ab_0    conda-forge
     pluggy                    1.0.0            py38h578d9bd_2    conda-forge
     protobuf                  3.16.0           py38h709712a_0    conda-forge
     py                        1.10.0             pyhd3deb0d_0    conda-forge
     pyarrow                   5.0.0           py38hed47224_0_cuda    conda-forge
     pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
     pytest                    6.2.5            py38h578d9bd_1    conda-forge
     python                    3.8.10          h49503c6_1_cpython    conda-forge
     python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
     python_abi                3.8                      2_cp38    conda-forge
     pytz                      2021.1             pyhd8ed1ab_0    conda-forge
     re2                       2021.06.01           h9c3ff4c_0    conda-forge
     readline                  8.1                  h46c0cb4_0    conda-forge
     rmm                       21.12.00a211107 cuda_11_py38_g76ae622_20    rapidsai-nightly
     s2n                       1.0.10               h9b69904_0    conda-forge
     setuptools                58.5.3           py38h578d9bd_0    conda-forge
     six                       1.16.0             pyh6c4a22f_0    conda-forge
     snappy                    1.1.8                he1b5a44_3    conda-forge
     spdlog                    1.8.5                h4bd325d_0    conda-forge
     sqlite                    3.36.0               h9cd32fc_0    conda-forge
     sre_yield                 1.2              py38h32f6830_2    conda-forge
     tk                        8.6.10               h21135ba_1    conda-forge
     toml                      0.10.2             pyhd8ed1ab_0    conda-forge
     typing_extensions         3.10.0.0           pyha770c72_0    conda-forge
     wheel                     0.36.2             pyhd3deb0d_0    conda-forge
     xz                        5.2.5                h516909a_1    conda-forge
     zipp                      3.5.0              pyhd8ed1ab_0    conda-forge
     zlib                      1.2.11            h516909a_1010    conda-forge
     zstd                      1.5.0                ha95c52a_0    conda-forge

```

**Comment by beckernick** [comment] 2021-11-08 15:13
@firestarman could you try with a more recent nightly or provide a reproducible example with system information?

I am unable to reproduce this issue with the current nightly installed with the traditional install of `mamba create -n cudf-21.12 -c rapidsai-nightly -c nvidia -c conda-forge cudf=21.12 python=3.8 cudatoolkit=11.0` (note that this nightly is at a more recent commit of libcudf and a different numba version).

```
conda list | grep "rapids\|numba"
cudf                      21.12.00a211105 cuda_11.0_py38_g4cba672c17_224    rapidsai-nightly
cupy                      8.0.0            py38hb7c6141_0    rapidsai-nightly
libcudf                   21.12.00a211108 cuda11.0_g4cba672c17_224    rapidsai-nightly
librmm                    21.12.00a211104 cuda11.0_gef1981d_17    rapidsai-nightly
numba                     0.53.1           py38h8b71fd7_1    conda-forge
rmm                       21.12.00a211104 cuda_11.0_py38_gef1981d_17    rapidsai-nightly```

**Comment by pxLi** [comment] 2021-11-09 06:26
Thanks! libcudf 211105-211107 builds have the issue, newer libcudf like 21.12.00a**211108**/21.12.00a**211109** works fine

close this issue

**Comment by pxLi** [comment] 2021-11-09 09:02
looks like this is all about timing this `g3280be232d_233` failed again

I just failed `mamba create -n cudf-21.12 -c rapidsai-nightly -c nvidia -c conda-forge cudf=21.12 python=3.8 cudatoolkit=11.0` again
```
cudf                      21.12.00a211109 cuda_11.0_py38_g3280be232d_233    rapidsai-nightly
libcudf                   21.12.00a211109 cuda11.0_g3280be232d_233    rapidsai-nightly
librmm                    21.12.00a211109 cuda11_g728a117_21_no_cma    rapidsai-nightly
rmm                       21.12.00a211109 cuda_11_py38_g728a117_21    rapidsai-nightly
```

```
>>> import cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/cudf/__init__.py", line 4, in <module>
    validate_setup()
  File "/opt/conda/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 18, in validate_setup
    from rmm._cuda.gpu import (
  File "/opt/conda/lib/python3.8/site-packages/rmm/__init__.py", line 16, in <module>
    from rmm import mr
  File "/opt/conda/lib/python3.8/site-packages/rmm/mr.py", line 14, in <module>
    from rmm._lib.memory_resource import (
  File "/opt/conda/lib/python3.8/site-packages/rmm/_lib/__init__.py", line 15, in <module>
    from .device_buffer import DeviceBuffer
  File "rmm/_lib/device_buffer.pyx", line 1, in init rmm._lib.device_buffer
ImportError: /opt/conda/lib/python3.8/site-packages/rmm/_lib/memory_resource.cpython-38-x86_64-linux-gnu.so: symbol cudaMemPoolCreate, version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference
```

some packages have incompatible issues here, and since the build continues delivering packages, at some time it could pass, but some did not

**Comment by galipremsagar** [comment] 2021-11-09 12:43
I ran into a similar issue:
```
pgali@dt07:/nvme/0/pgali/cudf$ python
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nvme/0/pgali/envs/cudf110/lib/python3.8/site-packages/cudf/__init__.py", line 4, in <module>
    validate_setup()
  File "/nvme/0/pgali/envs/cudf110/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 18, in validate_setup
    from rmm._cuda.gpu import (
  File "/nvme/0/pgali/envs/cudf110/lib/python3.8/site-packages/rmm/__init__.py", line 16, in <module>
    from rmm import mr
  File "/nvme/0/pgali/envs/cudf110/lib/python3.8/site-packages/rmm/mr.py", line 14, in <module>
    from rmm._lib.memory_resource import (
  File "/nvme/0/pgali/envs/cudf110/lib/python3.8/site-packages/rmm/_lib/__init__.py", line 15, in <module>
    from .device_buffer import DeviceBuffer
  File "rmm/_lib/device_buffer.pyx", line 1, in init rmm._lib.device_buffer
ImportError: /nvme/0/pgali/envs/cudf110/lib/python3.8/site-packages/rmm/_lib/memory_resource.cpython-38-x86_64-linux-gnu.so: symbol cudaMemPoolCreate version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference
>>> exit()
pgali@dt07:/nvme/0/pgali/cudf$ conda list | grep "librmm"
librmm                    21.12.00a211109 cuda11_g728a117_21_no_cma    rapidsai-nightly
pgali@dt07:/nvme/0/pgali/cudf$ conda list 
# packages in environment at /nvme/0/pgali/envs/cudf110:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
abseil-cpp                20210324.2           h9c3ff4c_0    conda-forge
arrow-cpp                 5.0.0           py38hb22f866_11_cuda    conda-forge
arrow-cpp-proc            3.0.0                      cuda    conda-forge
aws-c-auth                0.6.4                h66ccdbb_3    conda-forge
aws-c-cal                 0.5.12               hf5774b0_2    conda-forge
aws-c-common              0.6.11               h7f98852_0    conda-forge
aws-c-compression         0.2.14               hcbdb60a_2    conda-forge
aws-c-event-stream        0.2.7               hb3c4c74_24    conda-forge
aws-c-http                0.6.6                h0021954_1    conda-forge
aws-c-io                  0.10.9               h14fba84_3    conda-forge
aws-c-mqtt                0.7.8                h8df633b_2    conda-forge
aws-c-s3                  0.1.27               h8e2754f_1    conda-forge
aws-checksums             0.1.12               hcbdb60a_1    conda-forge
aws-crt-cpp               0.17.1               hf793bd7_3    conda-forge
aws-sdk-cpp               1.9.120              hab07a0e_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cachetools                4.2.4              pyhd8ed1ab_0    conda-forge
cudatoolkit               11.0.221             h6bb024c_0    nvidia
cudf                      21.12.00a211109 cuda_11.0_py38_g3280be232d_233    rapidsai-nightly
cudnn                     8.0.0                cuda11.0_0    nvidia
cupy                      8.0.0            py38hb7c6141_0    rapidsai-nightly
dlpack                    0.5                  h9c3ff4c_0    conda-forge
fastavro                  1.4.7            py38h497a2fe_1    conda-forge
fastrlock                 0.8              py38h709712a_1    conda-forge
fsspec                    2021.11.0          pyhd8ed1ab_0    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
glog                      0.5.0                h48cff8f_0    conda-forge
grpc-cpp                  1.40.0               h05f19cf_2    conda-forge
krb5                      1.19.2               hcc1bbae_3    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libblas                   3.9.0           12_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h7f98852_6    conda-forge
libbrotlidec              1.0.9                h7f98852_6    conda-forge
libbrotlienc              1.0.9                h7f98852_6    conda-forge
libcblas                  3.9.0           12_linux64_openblas    conda-forge
libcudf                   21.12.00a211109 cuda11.0_g3280be232d_233    rapidsai-nightly
libcurl                   7.79.1               h2574ce0_1    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h9c3ff4c_4    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgfortran-ng            11.2.0              h69a702a_11    conda-forge
libgfortran5              11.2.0              h5c6108e_11    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
liblapack                 3.9.0           12_linux64_openblas    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libnghttp2                1.43.0               h812cca2_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libprotobuf               3.18.1               h780b84a_0    conda-forge
librmm                    21.12.00a211109 cuda11_g728a117_21_no_cma    rapidsai-nightly
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libthrift                 0.15.0               he6d91bd_1    conda-forge
libutf8proc               2.6.1                h7f98852_0    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
llvmlite                  0.36.0           py38h4630a5e_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
nccl                      2.7.8.1            h4962215_100    nvidia
ncurses                   6.2                  h58526e2_4    conda-forge
numba                     0.53.1           py38h8b71fd7_1    conda-forge
numpy                     1.21.4           py38he2449b9_0    conda-forge
nvtx                      0.2.3            py38h497a2fe_0    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
orc                       1.7.1                h68e2c4e_0    conda-forge
packaging                 21.0               pyhd8ed1ab_0    conda-forge
pandas                    1.3.4            py38h43a58ef_1    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
protobuf                  3.18.1           py38h709712a_0    conda-forge
pyarrow                   5.0.0           py38hb90f683_11_cuda    conda-forge
pyparsing                 3.0.5              pyhd8ed1ab_0    conda-forge
python                    3.8.12          hb7a2778_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
re2                       2021.09.01           h9c3ff4c_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
rmm                       21.12.00a211109 cuda_11_py38_g728a117_21    rapidsai-nightly
s2n                       1.1.1                h9b69904_0    conda-forge
setuptools                58.5.3           py38h578d9bd_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
spdlog                    1.8.5                h4bd325d_0    conda-forge
sqlite                    3.36.0               h9cd32fc_2    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
typing_extensions         3.10.0.2           pyha770c72_0    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge
```

**Comment by galipremsagar** [comment] 2021-11-09 12:57
Note this doesn't happen on 11.2, only happens on 11.0.

**Comment by pxLi** [comment] 2021-11-19 02:44
not seeing this for several days, close it

**Closed by pxLi** 2021-11-19 02:44 UTC
Labels: bug, question
