### ISSUE TITLE
[FEA]Support "\r\n" as lineterminator in read_csv() function 

### ISSUE THREAD

**Issue by amanda-peng** [rapidsai/cudf#12743] opened 2023-02-09 06:31 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish I could use cuDF to do [...]
The read_csv() function doesn't support line terminator of  "\r\n" (Windows Enter). When specify with lineterminator='\r', there will be '\n***' in the first column, while set the lineterminator='\n' (default), there will be a '***\r' in the last column. Which are not what I expected. 

**Describe the solution you'd like**
Support the multiple character terminators in read_csv() function 

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by davidwendt** [comment] 2023-02-09 13:23
This appears to be a duplicate of #6752

**Comment by revans2** [comment] 2023-02-09 15:15
> This appears to be a duplicate of #6752

@davidwendt Are you sure? #6752 is a closed issue around fillna, that doesn't look like it has anything to do with reading CSV.

**Comment by bdice** [comment] 2023-02-09 15:47
To clarify: this works automatically for Pandas despite the lineterminator only accepting a single character because its Python mode reader (and apparently the C engine as well?) treats \r\n as a single newline character. Python usually translates to “universal” newlines \n on read.

**Comment by GregoryKimball** [comment] 2023-04-02 22:11
Thank you @amanda-peng for raising this issue. This is a long-standing ask, so I'll close this as duplicate, and promote #6572 as "Needs Owner"

**Closed by GregoryKimball** 2023-04-02 22:11 UTC
Labels: feature request, ? - Needs Triage
