### ISSUE TITLE
[FEA] Allow concatenation of dataframes with different columns

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1162] opened 2019-03-11 19:08 UTC
**Is your feature request related to a problem? Please describe.**
As a user, I want to concatenate dataframes with some columns in common and some columns not in common. In pandas, I am able to do this. By default, cells in dataframes that correspond to previously missing columns are set as NaN.

**Describe the solution you'd like**
I would `cudf.multi.concat` to behave like `pd.concat` in the following example:

```
import cudf
import pandas as pd

gdf1 = cudf.DataFrame({'a':[1,2,3]})
gdf2 = cudf.DataFrame({'b':[1,2,3]})

cudf.multi.concat([gdf1, gdf2])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-64-7ac2b0e086a7> in <module>
      5 gdf2 = cudf.DataFrame({'b':[1,2,3]})
      6 
----> 7 cudf.multi.concat([gdf1, gdf2])

/conda/envs/rapids/lib/python3.7/site-packages/cudf-0.7.0.dev0+509.gb1f70a81.dirty-py3.7-linux-x86_64.egg/cudf/multi.py in concat(objs, axis, ignore_index)
     50 
     51     if typ is DataFrame:
---> 52         return DataFrame._concat(objs, axis=axis, ignore_index=ignore_index)
     53     elif typ is Series:
     54         return Series._concat(objs, axis=axis)

/conda/envs/rapids/lib/python3.7/site-packages/cudf-0.7.0.dev0+509.gb1f70a81.dirty-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py in _concat(cls, objs, axis, ignore_index)
    916         if len(set(frozenset(o.columns) for o in objs)) != 1:
    917             what = set(frozenset(o.columns) for o in objs)
--> 918             raise ValueError('columns mismatch: {}'.format(what))
    919 
    920         objs = [o for o in objs]

ValueError: columns mismatch: {frozenset({'a'}), frozenset({'b'})}
```

```
import pandas as pd
import cudf
import pandas as pd

gdf1 = cudf.DataFrame({'a':[1,2,3]})
gdf2 = cudf.DataFrame({'b':[1,2,3]})

pd.concat([gdf1.to_pandas(), gdf2.to_pandas()])
	a	b
0	1.0	NaN
1	2.0	NaN
2	3.0	NaN
0	NaN	1.0
1	NaN	2.0
2	NaN	3.0
```

**Describe alternatives you've considered**
The natural alternative is to explicitly force all dataframes to have the superset of columns. This is a bit onerous (both as a user and from a memory perspective) and also requires global knowledge of the superset of columns, which isn't always desirable or necessarily feasible.

**Comment by kkraus14** [comment] 2019-04-11 17:34
duplicate of #188

**Closed by kkraus14** 2019-04-11 17:34 UTC
Labels: cuDF (Python), feature request, libcudf (C++/CUDA)
