### ISSUE TITLE
[BUG] ORC file sizes can be much larger than CPU version

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#12066] opened 2022-11-03 21:21 UTC
**Describe the bug**
Depending on the outcome of the analysis of this I could also see this being a new feature. I am filing this as a bug for now in hopes that we can treat it that way.  We have a customer that noticed that writing their data with ORC produces files that are about 4x larger using the RAPIDS accelerator for Apache Spark compared to using vanilla Apache Spark. Because we do not have access to their data we tried to reproduce this using TPC-DS data, specifically the catalog sales table.  In trying to reproduce it we notices that CUDF is actually really good at compressing ORC files. In many cases when the data is essentially ordered in a random way CUDF produces smaller files than the CPU does.  But when we sort the data by `cs_sold_date_sk`, which the original input data should be sorted by in TPC-DS, CUDF produces larger files.  This is not for all columns. Some columns from CUDF are smaller than the CPU versions, but enough columns are larger that overall the entire size is about 12.4% larger. This is no where near the 4x larger our customer saw, but looking at a few columns like `cs_sold_date_sk` that is almost 10x larger or `cs_sold_time_sk` that is nearly twice as large as the CPU version you can see how we could get to 4x larger with the right data is possible. Especially when you realize that each of these files have some overhead with the ORC footer/etc that is reduced when you have more columns in a single file.

**Steps/Code to reproduce bug**
I can give you the spark queries that I ran to reproduce the data, but I think it is simpler to just show some files.  I have places the per_column files [here](https://drive.google.com/drive/folders/1jn0kKEmlPIa3MLM73wScTROdrkY1BqYo?usp=share_link)  The ones that I am most concerned about are 

|column|pct_diff|size diff MiB|
|-|-|-|
|cs_sold_date_sk|829%|0.24|
|cs_sold_time_sk|97%|19.37|
|cs_bill_addr_sk|83%|17.87|

I am hoping that there is a compression algorithm that we didn't implement that the CPU does, or we just don't have as large of a window when doing run-length-encoding compared to the CPU. Not really sure on this. I don't have enough visibility into it.

I did notice a few clear differences in the output.
  1. we are including validity buffers/presence streams on some columns that the CPU does not. I don't think this impacts the total output size that much. I think this is because we are using the chunked writer and writes everything with validity because it does not know if a new table would show up later with a null in a column.  I think this is fixable, but like I said I don't think this is the majority of the problem.
  2. I also noticed that we have a lot more stripes compared to the CPU. It looks like we slice the data into stripes based off of the number of rows, where as the CPU keeps adding in and compressing data until the compressed strip size matches a target size. This is prior to using the general purpose compression. I am not sure how simple/difficult something like this would be. I can see that for `cs_sold_date_sk` it appears to make a big difference, but it is hard to tell because the data size of the single stripe from the CPU is smaller than a single stripe on the GPU that has 1/13th the data stored in it.

**Expected behavior**
I really would like to have some confidence that the output size of the same data is not going to be orders of magnitude larger when using the GPU. This can add up to real world costs both in terms of storage costs and in the time it takes to read and write so much more data.

**Comment by GregoryKimball** [comment] 2022-11-14 04:51
Thank you @revans2 for documenting these observations. It's unfortunate we have to use TPC-DS as a proxy for the customer issue. I'm sure we will find opportunities to address.. but I'm not at all sure it will help the customer!

The second idea you mentioned about stripe size would be a tricky root cause. I expect that we choose a row count per stripe because that is easier to parallelize, rather than having the stripe size adapt based on the encoding efficiency. 

It seems that [PyORC](https://pyorc.readthedocs.io/en/stable/) would be a good tool to study this CPU vs CPU difference. Please let me know if you disagree!

**Comment by vuule** [comment] 2022-11-22 07:23
@revans2 have you verified that #12194 fixes the size difference?
Please let me know if anything is needed on cuDF end before this can be closed.

**Comment by revans2** [comment] 2022-11-22 16:18
From what I have seen it fixed over half of the size difference with the CPU.  The size for the example that I have went down from about 22 GiB to 19 GiB, but the CPU version is at 17 GiB.

@viadea do can you also try this out on the original proprietary data set and see if it is good enough now?

**Comment by vuule** [comment] 2022-11-22 19:08
What about the files that were 10x larger? Are they within a reasonable range now?

**Comment by revans2** [comment] 2022-11-23 20:09
I heard back from the original customer and this has fixed their initial problem enough that we can close this.

**Comment by vyasr** [comment] 2022-11-29 18:24
Closing based on the previous comment.

**Closed by vyasr** 2022-11-29 18:24 UTC
Labels: bug, 0 - Backlog, cuIO, helps: Spark
