### ISSUE TITLE
[FEA] cudf aggregation functions must detect overflow and fail accordingly

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#609] opened 2018-12-27 19:46 UTC
This is a bug against the 0.5 branch.

cudf's API includes aggregation functions which could potentially overflow; and some that could easily overflow (e.g. sums over columns of `GDF_INT8`'s).

We must:
1. Not fail aggregations due to "transient" overflow, i.e. an overflow when aggregating some of the data but not when all data is aggregated.
2. Return an appropriate error (or at the very least crash) when a proper overflow is encountered.

... and, reading the code, it seems we are not currently doing that. Instead, we're just assuming overflow doesn't happen. This may or may not address the first point (depends on PTX overflow semantics which [don't seem to be set down in the PTX reference](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#integer-arithmetic-instructions)).

PS: [this](https://stackoverflow.com/questions/53950234/what-is-the-interger-arithmetic-overflow-behavior-of-nvidia-gpus).

**Comment by thomcom** [comment] 2018-12-27 22:15
I'd love to see a set of unit tests that compare the sum of different dtypes overflow behaviors with cudf. If they were implemented with a @parametrize and included xfails where necessary I'd want to PR that.

**Comment by eyalroz** [comment] 2018-12-27 22:55
@thomcom : I'm not sure I understand your comment. What exactly would you like to compare? Also, I don't know about  `@parameterize`; is this a Google Test concept? And - does "xfails" means "expected to fail"?

**Comment by thomcom** [comment] 2018-12-28 04:40
I think it is `@pytest.mark.parametrize('param_name', [list, of, params))` - it is a pytest concept, yes. Also xfails is a test that is expected to fail. It "passes" when it "fails". :) We use this test methodology pretty frequently where we compare the behavior of cudf with pandas. If we had a set of tests that proved that cudf didn't match pandas, we'd expect them to fail, then change them to expect them to succeed when all the overflows are implemented.

**Comment by jrhemstad** [comment] 2018-12-28 15:13
First, this is a feature request, not a bug. Neither `std::accumulate` nor `thrust::reduce` detect overflow, therefore I do not believe it is errant behavior to not detect a overflow in a reduction operation.

Second, I would have a difficult time supporting the addition of this feature. It would require checking the result for each binary operation, which not only would be slow, but would also prevent us from using things like `cub::BlockReduce` or `thrust::reduce`.

**Comment by thomcom** [comment] 2018-12-28 16:59
I'm entirely in favor of the above and #446. I feel like starting with pytests that demonstrate where we are aligned with pandas and where we aren't are still an awesome starting point - I would not want to write the lower level features without reliable validation first, anyway. I may start on this in python soon, unless someone else swoops in to begin it while I'm doing triage.

**Comment by eyalroz** [comment] 2018-12-28 17:08
> First, this is a feature request, not a bug. Neither `std::accumulate` nor `thrust::reduce` detect overflow, therefore I do not believe it is errant behavior to not detect a overflow in a reduction operation.

I believe you're choosing a wrong point of reference. cudf is providing DBMS-like functionality for higher-level code; otherwise, people could just use `std::accumulate` or `thrust::reduce` (or cub's reduction facilities). In a DBMS, it is unthinkable for an operator to ignore overflow.

> Second, I would have a difficult time supporting the addition of this feature. It would require checking the result for each binary operation, which not only would be slow, but would also prevent us from using things like `cub::BlockReduce` or `thrust::reduce`.

So, you're raising two concerns: Performance and ease of implementation / repeated effort.

Regarding performance:
1. This is the "cost of doing business" in the DBMS world. We can simply not have a person writing `SELECT SUM(c1) FROM t1;` need to question the validity of the result they get.
2. In many column store DBMSes, the overhead is avoided in one of two ways:
  * A larger result type (when that's not constrained)
  * Column-level or chunk-level minimum and maximum value statistics, using which one may determine overflow is impossible and use an overflow-ignoring variant of an operator implementation.
3. The performance penalty may be lower than what you might expect, considering:
  * The penalty is often not at the bottleneck of the computation (although it might be for some group-by-with-aggregation cases).
  * Reductions take up little time compared to the heavier operations such as sorting or hash-joining.
  * When data is large, and exceeds a single GPU's memory capacity, we'll probably be I/O-bound anyways.

Regarding implementation effort:
1. Same argument as above, this is the "cost of doing business" in the DBMS world. It just has to happen.
2. We don't use `thrust::reduce()` for reductions anyway (we do use thrust otherwise in  group-by aggregation, but that would not be affected).
3. We do use `cub::BlockReduce()` when just-reducing, but all of its "smarts" regards cases irrelevant to us: Older GPUs with lower Compute Capability; non-linear grids; an under-utilized GPU; non-commutative reduction binary operators. I may have missed something - I was looking at `block_reduce.cuh` (and especially  `enum BlockReduceAlgorithm`).

**Comment by eyalroz** [comment] 2018-12-28 17:13
@thomcom : #446 mitigates the problem somewhat, but doesn't fundamentally does not change anything - especially since we would still have an API function for reducing smaller types into not-so-large types. But even without that - see my reply to @jrhemstad . This _is_ a bug for a library such as ours.

**Comment by harrism** [comment] 2019-07-04 05:30
Closing for until there is an expressed need.

**Closed by harrism** 2019-07-04 05:30 UTC
Labels: feature request, libcudf (C++/CUDA), wontfix
