### ISSUE TITLE
[BUG] spark rapids has some issue loading datetime columns

### ISSUE THREAD

**Issue by mlahir1** [rapidsai/cudf#12937] opened 2023-03-13 23:07 UTC
Repro:
```

0: jdbc:hive2://localhost:9999> CREATE EXTERNAL TABLE test
. . . . . . . . . . . . . . . > (page_view_event_ts timestamp)
. . . . . . . . . . . . . . . > LOCATION '/root/test/' STORED AS ORC;
+---------+
| Result  |
+---------+
+---------+
No rows selected (0.447 seconds)
0: jdbc:hive2://localhost:9999> 
0: jdbc:hive2://localhost:9999> select page_view_event_ts from test;
+---------------------+
| page_view_event_ts  |
+---------------------+
| NULL                |
| NULL                |
| NULL                |
| NULL                |
| NULL                |
| NULL                |
| NULL                |
| NULL                |
| NULL                |
| NULL                |
+---------------------+
10 rows selected (2.1 seconds)
0: jdbc:hive2://localhost:9999> 
works when loaded with cudf.
In [3]: cudf.read_orc('tsrepro.orc')
Out[3]: 
        page_view_event_ts
0  2023-02-17 00:55:37.504
1  2023-02-17 00:55:31.824
2  2023-02-17 00:20:28.340
3  2023-02-17 00:31:41.551
4  2023-02-17 00:12:09.560
5  2023-02-17 00:37:31.169
6  2023-02-17 00:38:42.220
7  2023-02-17 00:20:41.557
...
```
u can repro with data here:
[tsrepro.orc.zip](https://github.com/rapidsai/cudf/files/10962617/tsrepro.orc.zip)

**Comment by GregoryKimball** [comment] 2023-03-13 23:18
Thank you for posting this issue. Just to clarify, does the file read as expected with cuDF-python? Perhaps the issue is downstream of cuDF/libcudf.

**Comment by mlahir1** [comment] 2023-03-14 01:31
> Does the file read as expected with cuDF-python? @GregoryKimball 
yes. there was issue with cudf, but tzdata reinstall fixed it. https://github.com/rapidsai/cudf/issues/12926

**Comment by GregoryKimball** [comment] 2023-04-02 22:13
Hello @mlahir1 is this issue still needed?

**Comment by GregoryKimball** [comment] 2023-06-05 18:23
Closing in favor of #12926

**Closed by GregoryKimball** 2023-06-05 18:23 UTC
Labels: bug, ? - Needs Triage
