### ISSUE TITLE
'librmm.so': libcuda.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by pdmack** [rapidsai/cudf#519] opened 2018-12-13 20:50 UTC
- [x] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. 
- [x] I have included the version or commit hash I am using for reference.
- [x] I have included the following environment details:
      Linux Distro, Linux Kernel, GPU Model
- [x] I have included the following version information for:
      Arrow, cmake, CUDA, gcc/g++, Numpy, Pandas, Python
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

- nvcr.io/nvidia/rapidsai/rapidsai:cuda9.2_ubuntu16.04
- GKE 1.11.3-gke.18
- Driver Version: 410.79 CUDA Version: 10.0
- LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64
- ldd (Ubuntu GLIBC 2.23-0ubuntu10) 2.23

The underlying reason appears to be that the linker is ignoring the LD_LIBRARY_PATH environment variable and relying solely on `/etc/ld.so.cache`. If I run `ldconfig` (with the appropriate permissions for `/etc`), the cache gets correctly updated and the E2E notebook runs fine.

**Comment by pdmack** [comment] 2018-12-13 21:03
https://gist.github.com/pdmack/9d4110fc4450646341493a42b05b5077

**Comment by harrism** [comment] 2018-12-13 21:43
I believe this is a duplicate of #441.

Do you have the CUDA Toolkit installed?

**Comment by pdmack** [comment] 2018-12-13 23:43
The drivers are loaded into GKE using https://github.com/GoogleCloudPlatform/container-engine-accelerators

Does the Toolkit invoke `ldconfig` in its install/setup?

**Comment by harrism** [comment] 2018-12-14 02:16
The driver is libcuda.so, so that is a different dependency. We see the error you describe from people who have not installed the cuda toolkit, which includes libcudart.so.
________________________________

**Comment by pdmack** [comment] 2018-12-16 00:04
```
KeyError: 'LD_LIBRARY_PATH'
```
The dask GPU workers aren't inheriting the LD_LIBRARY_PATH for some reason.

**Comment by pdmack** [comment] 2018-12-16 02:15
The only way I could get this to work with LD_LIBRARY_PATH was to modify `dask-setup.sh`:

```
screen -dmS dask_scheduler bash -c "source activate $ENVNAME && LD_LIBRARY_PATH=$LD_LIBRARY_PATH dask-scheduler"
```
and
```
        export create_worker="source activate $ENVNAME && \
                              LD_LIBRARY_PATH=$LD_LIBRARY_PATH \
                              dask-worker $MASTER_IPADDR:$DASK_SCHED_PORT \
                                          --host=${MY_IPADDR[0]} --no-nanny \
                                          --nprocs=1 --nthreads=1 \
                                          --memory-limit=0 --name ${MY_IPADDR[0]}_gpu_$worker_id \
                                          --local-directory $DASK_LOCAL_DIR/$name"
```

**Comment by harrism** [comment] 2018-12-16 23:18
@mt-jones can you take a look?

**Comment by kkraus14** [comment] 2019-02-05 05:41
This is an issue with screen, it wipes `LD_LIBRARY_PATH` but can be worked around using `.screenrc` or something similar. Given this and the movement to https://github.com/rapidsai/dask-cuda I'm going to close this issue.

**Closed by kkraus14** 2019-02-05 05:41 UTC
Labels: ? - Needs Triage, CMake, bug
