### ISSUE TITLE
[FEA] Explore additional opportunities for GitHub PR automation

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1070] opened 2019-03-01 16:30 UTC
**Is your feature request related to a problem? Please describe.**

Much of the management of PR titles and tagging is very manual, and often leads to PRs that are mis-labeled which ultimately leads to delays in getting PRs reviewed and merged, which slows down our development velocity.

**Describe the solution you'd like**

I'm wondering if some things in managing Labels could be automated to reduce the amount of manual effort and therefore improve the turnaround on PRs.

The purpose of this issue is to inspire research and investigation. Some of the things I'm suggesting may not be possible. 

Here are some things I've noticed that, if automated, would improve the process of submitting, reviewing, and merging PRs:

- Most users are unable to modify the labels in their PR. This requires them to modify the title with `[REVIEW]` or `[WIP]`, but this does not correspindly update the `In Progress` or `Ready for Review` label. Could the process of keeping these in sync be automated? 

- We have distinct Python and C++ portions of our repo which require corresponding Python and C++ expertise for review. This manifests in the "Needs cuDF" and "Needs libcudf review" Labels, but these labels need to be set manually. Could we detect the extensions of the files modified to automate setting these tags? For example, any modified `.py` file would automatically set "Needs cuDF Review", and any `.c, .cpp, .cu, .cuh` file modified would set "Needs libcudf Review". 

- When a PR has been reviewed and requires action from the author, the label "Waiting on Author" should be set, but again, this is manual and therefore rarely gets done. Could we automate that any time a review that "Requests Changes" is submitted that the "Waiting on Author" Label is automatically set? Likewise, once all of the reviews requested changes have been "Resolved" could we automate resetting the "Ready for Review" label? 

I'm fully aware that some (all?) of these things may not be possible, but I'm hoping that they can at least be explored. 

If anyone else has ideas for how the PR process could be made more streamlined via automation, please add your ideas in this issue.

**Comment by eyalroz** [comment] 2019-03-01 19:26
This sounds like a partial dupe of an issue I filed a while ago.

**Comment by harrism** [comment] 2019-05-15 00:20
The second bullet point in this list is now accomplished via the code owners functionality.

**Comment by jrhemstad** [comment] 2019-05-15 00:48
> The second bullet point in this list is now accomplished via the code owners functionality.

Not quite, as it doesn't update the labels. If we do away with the labels in lieu of just relying on the code owners being requested for review, then that would be a satisfactory solution.

**Closed** 2020-12-14 16:51 UTC
Labels: feature request, git, gpuCI
