### ISSUE TITLE
[BUG] cudf.Series.replace(-1, None) sometimes fills with 0 instead of null

### ISSUE THREAD

**Issue by trstovall** [rapidsai/cudf#4932] opened 2020-04-17 19:29 UTC
**Describe the bug**
cudf.Series.replace(-1, None) sometimes fills with 0 instead of null.

**Steps/Code to reproduce bug**
```
>>> z = cudf.read_orc('replace_nulls.orc')

>>> z[(z.a == 1) & (z.b == 1) & (z.c == 1)].d
75402   -1
Name: d, dtype: int64

>>> z['e'] = z.d.replace(-1, None)

>>> z[(z.a == 1) & (z.b == 1) & (z.c == 1)].e
75402    0
Name: e, dtype: int64
```

**Expected behavior**
All occurrences of -1 should be replaced with null.

**Environment overview (please complete the following information)**
 Docker container built from latest 0.14 nightly.  ORC file is being shared via Slack.

**Comment by ayushdg** [comment] 2020-04-17 22:25
I think this actually might be an issue with the boolean masking step discussed in #4919  rather than the `replace` operations itself. Going through the data:
```python
In [70]: z.e.isna()[75401:75404]                                                                                                                                                                                                                                                           
Out[70]: 
75401    False
75402     True
75403    False
Name: e, dtype: bool
In [71]: z.e.loc[75401:75404]                                                                                                                                                                                                                                                              
Out[71]: 
75401       0
75402    null
75403       0
75404       0
Name: e, dtype: int64
```

But when performing the boolmask operation the null value is getting replaced by a `0`


---
For others attempting to reproduce here is a dataset almost identical to the data @trstovall shared:
```python
In [73]: df = cudf.DataFrame()  
In [74]: n_elem = 5_000_000
In [75]: df['a'] = np.zeros(n_elem)
In [76]: df['b'] = np.zeros(n_elem) 
In [77]: df['b'].loc[75402] = -1                                                                                                                                                                                                                                                           
In [78]: df['c'] = df['b'].replace(-1,None)                                                                                                                                                                                                                                                
In [79]: df[df['c'].isna()]                                                                                                                                                                                                                                                                
Out[79]: 
         a    b    c
75402  1.0 -1.0  0.0

```

**Comment by kkraus14** [comment] 2020-04-20 15:51
Duplicate of #4919

**Closed by kkraus14** 2020-04-20 15:51 UTC
Labels: ? - Needs Triage, bug
