### ISSUE TITLE
[BUG] Behavior of series.unique is different than pandas

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#10801] opened 2022-05-05 19:28 UTC
**Describe the bug**
`series.unique()` returns a `cuDF.Series` while it returns a `numpy.ndarray ` for pandas.

**Steps/Code to reproduce bug**
```python
In [1]: import cudf
In [2]: import pandas as pd

In [3]: type(pd.Series([1,1]).unique())
Out[3]: numpy.ndarray

In [4]: type(cudf.Series([1,1]).unique())
Out[4]: cudf.core.series.Series


```
**Expected behavior**
I would expect `cudf` to return `cupy.array`

**Additional context**

This causes discrepancy in behavior when using  with `dask`  as it returns a `dask_cudf.Series` for `dask_cudf` and  `dask.Array` for `dask` (`pandas`). 

See example: https://github.com/rapidsai/gpu-bdb/pull/255/files#r857919439

**Comment by beckernick** [comment] 2022-05-16 14:31
Closing as a duplicate of https://github.com/rapidsai/cudf/issues/8175 .

Recommend we continue the discussion in the original issue, as I think we still alignment on how to handle `.values` for a dtype CuPy doesn't support (such as strings).

**Closed by beckernick** 2022-05-16 14:31 UTC
Labels: bug, good first issue, cuDF (Python)
