### ISSUE TITLE
[BUG] creating 4GB in size of a dask_cudf dataframe fails with 4 columns

### ISSUE THREAD

**Issue by ahmet-uyar** [rapidsai/cudf#8712] opened 2021-07-12 12:57 UTC
**Describe the bug**
I would like to create a multi giga byte dataframe using dask_cudf running on a dgx-1 machine with 8 gpus. I first create a cudf dataframe and it works fine. 4 columns, each having 125000000 rows and holding int64 values. Then I try to create dask_cudf dataframe using dask_cudf.from_cudf(df, npartitions=4). I call persist and wait for the dast_cudf to be ready but it fails with the following exception:

```
nrows, ncols, npartitions: 125000000 4 4
cudf df constructed.
rows in cudf df: 125000000
distributed.batched - INFO - Batched Comm Closed: Endpoint is closed -- unable to send message
Traceback (most recent call last):
  File "queries/join/shuffle.py", line 156, in <module>
    duration = main(config=config, client=client)
  File "queries/join/shuffle.py", line 112, in main
    ddf = create_dask_cudf_df(nrows=nrows, ncols=number_of_cols, npartitions=npartitions)
  File "queries/join/shuffle.py", line 78, in create_dask_cudf_df
    wait(ddf)
  File "gpu_bdb_dev/lib/python3.8/site-packages/distributed/client.py", line 4137, in wait
    result = client.sync(_wait, fs, timeout=timeout, return_when=return_when)
  File "gpu_bdb_dev/lib/python3.8/site-packages/distributed/client.py", line 843, in sync
    return sync(
  File "gpu_bdb_dev/lib/python3.8/site-packages/distributed/utils.py", line 353, in sync
    raise exc.with_traceback(tb)
  File "gpu_bdb_dev/lib/python3.8/site-packages/distributed/utils.py", line 336, in f
    result[0] = yield future
  File "gpu_bdb_dev/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "gpu_bdb_dev/lib/python3.8/site-packages/distributed/client.py", line 4116, in _wait
    raise CancelledError(cancelled)
concurrent.futures._base.CancelledError: [('from_cudf-5db901b14535c7f1c009aadfa3d52ed8', 3), ('from_cudf-5db901b14535c7f1c009aadfa3d52ed8', 1), ('from_cudf-5db901b14535c7f1c009aadfa3d52ed8', 0), ('from_cudf-5db901b14535c7f1c009aadfa3d52ed8', 2)]
```

When I try to create a dask dataframe with the same size from a pandas dataframe, I get a similar error:
```
nrows, ncols, npartitions: 125000000 4 4
pandas df constructed.
rows in pandas df: 125000000
distributed.batched - INFO - Batched Comm Closed: Endpoint is closed -- unable to send message
Traceback (most recent call last):
  File "queries/join/shuffle.py", line 156, in <module>
    duration = main(config=config, client=client)
  File "queries/join/shuffle.py", line 113, in main
    ddf = create_dask_df(nrows=nrows, ncols=number_of_cols, npartitions=npartitions)
  File "queries/join/shuffle.py", line 59, in create_dask_df
    wait(ddf)
  File "gpu_bdb_dev/lib/python3.8/site-packages/distributed/client.py", line 4137, in wait
    result = client.sync(_wait, fs, timeout=timeout, return_when=return_when)
  File "gpu_bdb_dev/lib/python3.8/site-packages/distributed/client.py", line 843, in sync
    return sync(
  File "gpu_bdb_dev/lib/python3.8/site-packages/distributed/utils.py", line 353, in sync
    raise exc.with_traceback(tb)
  File "gpu_bdb_dev/lib/python3.8/site-packages/distributed/utils.py", line 336, in f
    result[0] = yield future
  File "gpu_bdb_dev/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "gpu_bdb_dev/lib/python3.8/site-packages/distributed/client.py", line 4116, in _wait
    raise CancelledError(cancelled)
concurrent.futures._base.CancelledError: [('from_pandas-c01abbd038269d57a844250f5e24b1b2', 3), ('from_pandas-c01abbd038269d57a844250f5e24b1b2', 2), ('from_pandas-c01abbd038269d57a844250f5e24b1b2', 0), ('from_pandas-c01abbd038269d57a844250f5e24b1b2', 1)]
```

**Steps/Code to reproduce bug**
Here are the functions that I am using to create the dask_cudf dataframe
```
def create_cudf_df(nrows, ncols):
    df = cudf.DataFrame()
    for i in range(ncols):
        df["col-" + str(i)] = cupy.arange(0, nrows, dtype="int64")
    print("cudf df constructed.")
    print("rows in cudf df:", len(df.index))
    return df


def create_dask_cudf_df(nrows, ncols, npartitions):
    df = create_cudf_df(nrows=nrows, ncols=ncols)
    ddf = dask_cudf.from_cudf(df, npartitions=npartitions)
    ddf = ddf.persist()
    wait(ddf)
    print("dask_cudf ddf constructed.")
    print("rows in ddf:", len(ddf.index))
    return ddf
```

Here are the functions that I am using to create the dask dataframe:
```
def create_pandas_df(nrows, ncols):
    df = pd.DataFrame()
    for i in range(ncols):
        df["col-" + str(i)] = np.arange(0, nrows, dtype="int64")
    print("pandas df constructed.")
    print("rows in pandas df:", len(df.index))
    return df


def create_dask_df(nrows, ncols, npartitions):
    df = create_pandas_df(nrows=nrows, ncols=ncols)
    ddf = dd.from_pandas(df, npartitions=npartitions)
    ddf = ddf.persist()
    wait(ddf)
    print("dask ddf constructed.")
    print("rows in ddf:", len(ddf.index))
    return ddf
```

**Expected behavior**
I would like to create dask_cudf dataframes with total memory usage of more than 4GB with 2/4 columns having int64 data types. 

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal DGX-1 machine with redhat. (CentOS Linux release 7.9.2009 (Core))
 - Method of cuDF install: conda installation from https://github.com/rapidsai/gpu-bdb/blob/main/conda/rapids-gpu-bdb.yml

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**
I am running 4 workers and using 4 GPUs on a single node that have 8 GPUs.

Starting UCX scheduler ...
Starting workers with NVLINK ...
device memory limit:  15GB
RMM POOL_SIZE:  29GB
memory limit:  128663M

**Comment by beckernick** [comment] 2021-07-12 13:56
Hi @ahmet-uyar , thanks for filing an issue.

Could you please include a minimal reproducible example including the cluster creation and execution of your operations? Without this, folks can only give high level, general comments.

Note that if you are seeing errors from the following, your error may be unrelated to cuDF/RAPIDS.

```python
df = create_pandas_df(nrows=nrows, ncols=ncols)
ddf = dd.from_pandas(df, npartitions=npartitions)
ddf = ddf.persist()
wait(ddf)
```

**Comment by ahmet-uyar** [comment] 2021-07-12 17:01
Hi @beckernick, thanks for replying quickly.

On a DGX machine:

First step would be to create the conda environment:
conda env create --name large_ddf -f https://raw.githubusercontent.com/rapidsai/gpu-bdb/main/conda/rapids-gpu-bdb.yml 
conda activate large_ddf

Then, copy following two files: 
https://raw.githubusercontent.com/cylondata/gpu-bdb/main/gpu_bdb/min/cluster-startup.sh
https://raw.githubusercontent.com/cylondata/gpu-bdb/main/gpu_bdb/min/large_ddf.py

start the cluster scheduler and 4 workers on a single node:
./cluster-startup.sh

run the code
python large_ddf.py

**Comment by beckernick** [comment] 2021-07-12 17:15
When you run `create_cudf_df` in the Client process to create a 4 GB GPU dataframe, you're operating in a separate process from the 29 GB RMM pool that you've set up on each worker. With 29 GB reserved per worker, this would cause an out of memory even on a 32 GB GPU.

For that reason, we recommend not creating large dataframes in the client process. Perhaps you could create the dataframe with `dask.delayed` if it must be created in memory? This may resolve your issue on the GPU side.

Separately, if your script fails on `create_dask_df` (when the `create_dask_cudf_df` is commented out), something about the cluster set up may be the root cause.

**Comment by ahmet-uyar** [comment] 2021-07-12 18:22
When I start the workers on gpus: 1,2,3,4 and the client on gpu 0, still I can not create the dataframe first on the client gpu process with cudf and transfer them to workers. Since the client is running on a separate gpu, there is no gpu memory issue I think. create_dask_cudf_df still gives the same error. 
I also tried setting DEVICE_MEMORY_LIMIT and POOL_SIZE to smaller values such as 8GB or 10GB but those did not make any difference.

Here is my objective, I would like to create very large dataframes on gpus and perform shuffle on them. I would like to measure the shuffle times in distributed dataframes. For that, first I need to create the dataframe and then, get the time, perform the shuffle and get the time. So, I need to make sure that before the shuffle operation starts, all partitions of the dataframe is created and they are ready. 
For me it is very convenient to create the dataframe on the fly without using files. So, that is why I would like to avoid using files if possible. 
 
I am not sure what is the best way to go forward? Do you suggest using dask.delayed? Can I initiate a large dataframe with dask.delayed and start the timer after that before the shuffle operation?

many thanks,

**Comment by ahmet-uyar** [comment] 2021-07-13 03:16
@beckernick I think for me the best approach would have been to create the partitions of dask_cudf DataFrame as separate cudf tables in gpu memory. Then I could have created a single dask_cudf DataFrame from these tables. But this is not possible I guess since dask_cudf.from_cudf() method does not accept a list of cudf tables. It seems to accept only a single table. 

The other less than optimum choice for me to create the dataframe on client main memory using pandas and load them to worker gpus as partitions as in create_dask_df function. I tried this with smaller DEVICE_MEMORY_LIMIT and POOL_SIZE values such as 8GB or 10GB, but I am still getting the same error. Not sure why.

**Comment by ahmet-uyar** [comment] 2021-07-14 11:02
thank you for your response @beckernick and @pentschev. 
I checked the dask-cuda [shuffle benchmark script](https://github.com/rapidsai/dask-cuda/blob/branch-21.08/dask_cuda/benchmarks/local_cudf_shuffle.py). That one seems to first generate the dataframe on client CPU with pandas and then uploads to worker GPUs. I have tested this approach and it works but kind of slow. My implementation is [at](https://github.com/cylondata/gpu-bdb/blob/main/gpu_bdb/min/large_ddf.py#L109).

My goal is to conduct the shuffling performance not only on a single node but in many nodes settings also. In that case, this approach would be very slow, since dataframe generation would be sequential and involves client-to-worker data transfers.  

Therefore, I tried to create the dask_cudf dataframe on worker GPUs in parallel by using dask.delayed but could not succeed in doing so yet. My draft [implementation](https://github.com/cylondata/gpu-bdb/blob/main/gpu_bdb/min/large_ddf.py#L143). I can create the distributed dask_cudf dataframe on GPUs in parallel and perform some operation on them such as length calculation, but could not get a handle on the dataframe objects without bringing the whole dataframe back to the client. Is there a way to get a handle on these dataframes, so that I can perform the shuffle without bringing them to the client?

or is there any other workaround you can suggest to generate the dask_cudf dataframe in GPUs in parallel, that would also work in multi-node settings. 

Many thanks.

**Comment by ahmet-uyar** [comment] 2021-07-14 11:44
In dask.dataframe, there is [from_delayed function](https://docs.dask.org/en/latest/delayed-collections.html), but this is not supported I think in dask_cudf. That would have solved the issue.

**Comment by beckernick** [comment] 2021-07-14 13:43
Glad that some things are working!

dask_cudf provides a `from_delayed` that can be used with standard delayed objects.

```python
import dask
import dask_cudf
import cudf
​
@dask.delayed
def generate_data(nrows=10):
    return cudf.datasets.randomdata(nrows=nrows)
​
tasks = [generate_data() for x in range(15)]
dask_cudf.from_delayed(tasks).npartitions
15
```

**Comment by ahmet-uyar** [comment] 2021-07-19 10:06
Thank you very much @beckernick. Now it works with dask_cudf.from_delayed

**Comment by beckernick** [comment] 2021-07-19 22:36
Great! I'm going to close this issue as answered. Please feel free to re-open as needed or to file new issues.

**Closed by beckernick** 2021-07-19 22:36 UTC
Labels: bug, cuDF (Python), dask, question
