### ISSUE TITLE
[FEA] to_csv parameter to suppress quotes in output

### ISSUE THREAD

**Issue by gbatmaz** [rapidsai/cudf#2891] opened 2019-09-30 16:27 UTC
**Describe the bug**
to_csv function seems to be adding quotes into the txt. file

**Steps/Code to reproduce bug**
```
import cudf
df = cudf.DataFrame({'text': ['a', 'b'],
                   'id': [1, 2]})
df.to_csv("test.txt",sep='\t',header=False,index=False)

"a"	1
"b"	2

```
**Expected behavior**
Strings should have been written without the quotes.

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull`  rapidsai/rapidsai-dev-nightly:0.10-cuda10.0-devel-ubuntu18.04-py3.7

**Environment details**
./print_env.sh
<details><summary>Click here to see environment details</summary><pre>

     **git***
     Not inside a git repository

     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
     NAME="Ubuntu"
     VERSION="18.04.3 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.3 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux dgx03 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

     ***GPU Information***
     Mon Sep 30 16:18:33 2019
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla V100-SXM2...  On   | 00000000:8A:00.0 Off |                    0 |
     | N/A   33C    P0    57W / 300W |   7508MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+

     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     +-----------------------------------------------------------------------------+

     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              80
     On-line CPU(s) list: 0-79
     Thread(s) per core:  2
     Core(s) per socket:  20
     Socket(s):           2
     NUMA node(s):        2
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               79
     Model name:          Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
     Stepping:            1
     CPU MHz:             3088.805
     CPU max MHz:         3600.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            4389.92
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            256K
     L3 cache:            51200K
     NUMA node0 CPU(s):   0-19,40-59
     NUMA node1 CPU(s):   20-39,60-79
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe                                                                                            syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor                                                                                            ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_                                                                                           lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsba                                                                                           se tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_loc                                                                                           al dtherm ida arat pln pts flush_l1d

     ***CMake***
     /opt/conda/envs/rapids/bin/cmake
     cmake version 3.14.5

     CMake suite maintained and supported by Kitware (kitware.com/cmake).

     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2018 NVIDIA Corporation
     Built on Sat_Aug_25_21:08:01_CDT_2018
     Cuda compilation tools, release 10.0, V10.0.130

     ***Python***
     /opt/conda/envs/rapids/bin/python
     Python 3.7.3

     ***Environment Variables***
     PATH                            : /opt/conda/envs/rapids/bin:/opt/conda/condabin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/u                                                                                           sr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/conda/bin:/conda/bin:/conda/bin
     LD_LIBRARY_PATH                 : /opt/conda/envs/rapids/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/l                                                                                           ib
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /opt/conda/envs/rapids
     PYTHON_PATH                     :

     ***conda packages***
     /opt/conda/condabin/conda
     # packages in environment at /opt/conda/envs/rapids:
     #
     # Name                    Version                   Build  Channel
     absl-py                   0.8.0                    py37_0    conda-forge
     aiohttp                   3.6.1            py37h516909a_0    conda-forge
     alabaster                 0.7.12                     py_0    conda-forge
     arrow-cpp                 0.14.1           py37h5ac5442_4    conda-forge
     asn1crypto                0.24.0                py37_1003    conda-forge
     astor                     0.7.1                      py_0    conda-forge
     async-timeout             3.0.1                   py_1000    conda-forge
     atomicwrites              1.3.0                      py_0    conda-forge
     attrs                     19.1.0                     py_0    conda-forge
     babel                     2.7.0                      py_0    conda-forge
     backcall                  0.1.0                      py_0    conda-forge
     blas                      1.1                    openblas    conda-forge
     bleach                    3.1.0                      py_0    conda-forge
     bokeh                     1.3.4                    py37_0    conda-forge
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     boto                      2.49.0                   pypi_0    pypi
     boto3                     1.9.238                  pypi_0    pypi
     botocore                  1.12.238                 pypi_0    pypi
     bpemb                     0.3.0                    pypi_0    pypi
     brotli                    1.0.7             he1b5a44_1000    conda-forge
     bzip2                     1.0.8                h516909a_1    conda-forge
     c-ares                    1.15.0            h516909a_1001    conda-forge
     ca-certificates           2019.8.28                     0
     certifi                   2019.9.11                py37_0
     cffi                      1.12.3           py37h8022711_0    conda-forge
     chardet                   3.0.4                 py37_1003    conda-forge
     click                     7.0                      pypi_0    pypi
     cloudpickle               1.2.2                      py_0    conda-forge
     cmake                     3.14.5               hf94ab9c_0    conda-forge
     cmake_setuptools          0.1.3                      py_0    rapidsai-nightly
     commonmark                0.9.0                      py_0    conda-forge
     cryptography              2.7              py37h72c5cf5_0    conda-forge
     cudatoolkit               10.0.130                      0    anaconda
     cudf                      0.10.0a0+1659.g0984a873d          pypi_0    pypi
     cugraph                   0.10.0a0+174.g0ccc433          pypi_0    pypi
     cuml                      0.10.0a0+697.gad7242dc.dirty          pypi_0    pypi
     cupy-cuda100              6.4.0                    pypi_0    pypi
     curl                      7.65.3               hf8cf82a_0    conda-forge
     cuspatial                 0.10.0a0+142.gcbe0513          pypi_0    pypi
     cycler                    0.10.0                     py_1    conda-forge
     cyrus-sasl                2.1.27               he38ecfd_0    conda-forge
     cython                    0.29.13          py37he1b5a44_0    conda-forge
     cytoolz                   0.10.0           py37h516909a_0    conda-forge
     dask                      2.4.0                      py_0    conda-forge
     dask-core                 2.4.0                      py_0    conda-forge
     dask-cudf                 0.10.0a0+1659.g0984a873d          pypi_0    pypi
     dask-glm                  0.2.0                      py_1    conda-forge
     dask-labextension         1.0.3                      py_0    conda-forge
     dask-ml                   1.0.0                      py_1    conda-forge
     dask-xgboost              0.1.5                    pypi_0    pypi
     dbus                      1.13.6               he372182_0    conda-forge
     decorator                 4.4.0                      py_0    conda-forge
     defusedxml                0.5.0                      py_1    conda-forge
     deprecated                1.2.6                    pypi_0    pypi
     distributed               2.4.0                      py_0    conda-forge
     dlpack                    0.2                  he1b5a44_1    conda-forge
     docutils                  0.15.2                   py37_0    conda-forge
     double-conversion         3.1.5                he1b5a44_1    conda-forge
     doxygen                   1.8.16               he8d5c6f_0    conda-forge
     entrypoints               0.3                   py37_1000    conda-forge
     expat                     2.2.5             he1b5a44_1003    conda-forge
     fastavro                  0.22.5           py37h516909a_0    conda-forge
     fastrlock                 0.4                      pypi_0    pypi
     flair                     0.4.3                    pypi_0    pypi
     flatbuffers               1.11.0               he1b5a44_0    conda-forge
     fontconfig                2.13.1            h86ecdb6_1001    conda-forge
     freetype                  2.10.0               he983fc9_1    conda-forge
     fsspec                    0.5.1                      py_0    conda-forge
     future                    0.17.1                py37_1000    conda-forge
     gast                      0.3.2                      py_0    conda-forge
     gensim                    3.8.1                    pypi_0    pypi
     gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
     gflags                    2.2.2             he1b5a44_1001    conda-forge
     glib                      2.58.3            h6f030ca_1002    conda-forge
     glog                      0.4.0                he1b5a44_1    conda-forge
     gmp                       6.1.2             hf484d3e_1000    conda-forge
     graphistry                0.9.69                   pypi_0    pypi
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     grpcio                    1.23.0           py37he9ae1f9_0    conda-forge
     gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
     gstreamer                 1.14.5               h36ae1b5_0    conda-forge
     h5py                      2.10.0          nompi_py37h513d04c_100    conda-forge
     hdf5                      1.10.5          nompi_h3c11f04_1103    conda-forge
     heapdict                  1.0.0                 py37_1000    conda-forge
     hyperopt                  0.1.2                    pypi_0    pypi
     hypothesis                4.36.2                   py37_0    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     idna                      2.8                   py37_1000    conda-forge
     imagesize                 1.1.0                      py_0    conda-forge
     importlib_metadata        0.23                     py37_0    conda-forge
     intel-openmp              2019.4                      243
     ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge
     ipython                   7.6.1                    pypi_0    pypi
     ipython_genutils          0.2.0                      py_1    conda-forge
     ipywidgets                7.5.1                    pypi_0    pypi
     jedi                      0.15.1                   py37_0    conda-forge
     jinja2                    2.10.1                     py_0    conda-forge
     jmespath                  0.9.4                    pypi_0    pypi
     joblib                    0.13.2                     py_0    conda-forge
     jpeg                      9c                h14c3975_1001    conda-forge
     json5                     0.8.5                      py_0    conda-forge
     jsonschema                3.0.2                    py37_0    conda-forge
     jupyter                   1.0.0                    pypi_0    pypi
     jupyter-console           6.0.0                    pypi_0    pypi
     jupyter-server-proxy      1.1.0                      py_0    conda-forge
     jupyter_client            5.3.3                    py37_1    conda-forge
     jupyter_core              4.4.0                      py_0    conda-forge
     jupyterlab                1.0.7                    py37_0    conda-forge
     jupyterlab-nvdashboard    0.1.9                    pypi_0    pypi
     jupyterlab_server         1.0.6                      py_0    conda-forge
     keras-applications        1.0.8                      py_1    conda-forge
     keras-preprocessing       1.1.0                      py_0    conda-forge
     kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
     krb5                      1.16.3            h05b26f9_1001    conda-forge
     langdetect                1.0.7                    pypi_0    pypi
     lapack                    3.6.1                ha44fe06_2    conda-forge
     libblas                   3.8.0               12_openblas    conda-forge
     libcblas                  3.8.0               12_openblas    conda-forge
     libclang                  8.0.0                h6bb024c_0    rapidsai
     libcumlprims              0.10.0               cuda10.0_0    rapidsai-nightly
     libcurl                   7.65.3               hda55be3_0    conda-forge
     libedit                   3.1.20170329      hf8c457e_1001    conda-forge
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1             he1b5a44_1006    conda-forge
     libgcc-ng                 7.3.0                hdf63c60_0    anaconda
     libgcrypt                 1.8.4             hf484d3e_1000    conda-forge
     libgfortran               3.0.0                         1    conda-forge
     libgfortran-ng            7.3.0                hdf63c60_0    anaconda
     libgpg-error              1.36                 he1b5a44_0    conda-forge
     libgsasl                  1.8.0             h19a2143_1004    conda-forge
     libiconv                  1.15              h516909a_1005    conda-forge
     liblapack                 3.8.0               12_openblas    conda-forge
     libntlm                   1.4               h14c3975_1002    conda-forge
     libopenblas               0.3.7                h6e990d7_1    conda-forge
     libpng                    1.6.37               hed695b0_0    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librdkafka                1.1.0                hb2b7465_0    conda-forge
     librmm-cffi               0.10.0                   pypi_0    pypi
     libsodium                 1.0.17               h516909a_0    conda-forge
     libssh2                   1.8.2                h22169c7_2    conda-forge
     libstdcxx-ng              7.3.0                hdf63c60_0    anaconda
     libtiff                   4.0.10            h57b8799_1003    conda-forge
     libuuid                   2.32.1            h14c3975_1000    conda-forge
     libuv                     1.31.0               h516909a_0    conda-forge
     libxcb                    1.13              h14c3975_1002    conda-forge
     libxml2                   2.9.9                hee79883_5    conda-forge
     llvmlite                  0.29.0           py37hf484d3e_0    numba
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     make                      4.2.1             h14c3975_2004    conda-forge
     markdown                  2.6.11                   pypi_0    pypi
     markupsafe                1.1.1            py37h14c3975_0    conda-forge
     matplotlib                3.1.1                    py37_1    conda-forge
     matplotlib-base           3.1.1            py37he7580a8_1    conda-forge
     mistune                   0.8.4           py37h14c3975_1000    conda-forge
     mkl                       2019.4                      243
     mock                      3.0.5                    py37_0    conda-forge
     more-itertools            7.2.0                      py_0    conda-forge
     mpld3                     0.3                      pypi_0    pypi
     msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
     multidict                 4.5.2           py37h14c3975_1000    conda-forge
     multipledispatch          0.6.0                      py_0    conda-forge
     nbconvert                 5.6.0                    py37_1    conda-forge
     nbformat                  4.4.0                      py_1    conda-forge
     nbsphinx                  0.4.2                      py_0    conda-forge
     nccl                      2.4.6.1              cuda10.0_0    nvidia
     ncurses                   6.1               hf484d3e_1002    conda-forge
     networkx                  2.3                        py_0    conda-forge
     ninja                     1.9.0            py37hfd86e86_0
     nodejs                    12.4.0               he1b5a44_0    conda-forge
     nomkl                     3.0                           0
     notebook                  6.0.1                    py37_0    conda-forge
     numba                     0.45.1          np116py37hf484d3e_0    numba
     numpy                     1.16.4           py37h95a1406_0    conda-forge
     numpydoc                  0.9.1                      py_0    conda-forge
     nvstrings-cuda100         0.0.0.dev0               pypi_0    pypi
     olefile                   0.46                       py_0    conda-forge
     openblas                  0.3.7                h6e990d7_1    conda-forge
     openssl                   1.1.1d               h7b6447c_1
     packaging                 19.2                       py_0    conda-forge
     pandas                    0.24.2           py37hb3f55d8_0    conda-forge
     pandoc                    1.19.2                        0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.5.1                      py_0    conda-forge
     partd                     1.0.0                      py_0    conda-forge
     patsy                     0.5.1                      py_0    conda-forge
     pcre                      8.41              hf484d3e_1003    conda-forge
     pexpect                   4.7.0                    py37_0    conda-forge
     pickleshare               0.7.5                 py37_1000    conda-forge
     pillow                    6.1.0            py37h6b7be26_1    conda-forge
     pip                       19.2.3                   py37_0    conda-forge
     pluggy                    0.13.0                   py37_0    conda-forge
     prometheus_client         0.7.1                      py_0    conda-forge
     prompt_toolkit            2.0.9                      py_0    conda-forge
     protobuf                  3.8.0            py37he1b5a44_1    conda-forge
     psutil                    5.6.3            py37h516909a_0    conda-forge
     pthread-stubs             0.4               h14c3975_1001    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     py                        1.8.0                      py_0    conda-forge
     py4j                      0.10.8.1                 py37_0
     pyarrow                   0.14.1           py37h8b68381_2    conda-forge
     pycparser                 2.19                     py37_1    conda-forge
     pygments                  2.4.2                      py_0    conda-forge
     pymongo                   3.9.0                    pypi_0    pypi
     pynvml                    8.0.3                      py_0    conda-forge
     pyopenssl                 19.0.0                   py37_0    conda-forge
     pyparsing                 2.4.2                      py_0    conda-forge
     pyqt                      5.9.2            py37hcca6a23_4    conda-forge
     pyrsistent                0.15.4           py37h516909a_0    conda-forge
     pysocks                   1.7.1                    py37_0    conda-forge
     pytest                    5.1.2                    py37_0    conda-forge
     python                    3.7.3                h33d41f4_1    conda-forge
     python-confluent-kafka    1.1.0            py37h516909a_0    conda-forge
     python-dateutil           2.8.0                      py_0    conda-forge
     pytorch                   1.2.0           py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch
     pytorch-transformers      1.2.0                    pypi_0    pypi
     pytz                      2019.2                     py_0    conda-forge
     pyyaml                    5.1.2            py37h516909a_0    conda-forge
     pyzmq                     18.1.0           py37h1768529_0    conda-forge
     qt                        5.9.7                h0c104cb_3    conda-forge
     qtconsole                 4.5.5                    pypi_0    pypi
     rapidjson                 1.1.0             he1b5a44_1002    conda-forge
     re2                       2019.09.01           he1b5a44_0    conda-forge
     readline                  8.0                  hf8c457e_0    conda-forge
     recommonmark              0.6.0                      py_0    conda-forge
     regex                     2019.8.19                pypi_0    pypi
     requests                  2.22.0                   py37_1    conda-forge
     rhash                     1.3.6             h14c3975_1001    conda-forge
     s3transfer                0.2.1                    pypi_0    pypi
     sacremoses                0.0.34                   pypi_0    pypi
     scikit-learn              0.21.3           py37hcdab131_0    conda-forge
     scipy                     1.3.1            py37h921218d_2    conda-forge
     seaborn                   0.9.0                      py_1    conda-forge
     segtok                    1.5.7                    pypi_0    pypi
     send2trash                1.5.0                      py_0    conda-forge
     sentencepiece             0.1.83                   pypi_0    pypi
     setuptools                41.2.0                   py37_0    conda-forge
     simpervisor               0.3                        py_1    conda-forge
     sip                       4.19.8          py37hf484d3e_1000    conda-forge
     six                       1.12.0                py37_1000    conda-forge
     sklearn                   0.0                      pypi_0    pypi
     smart-open                1.8.4                    pypi_0    pypi
     snappy                    1.1.7             he1b5a44_1002    conda-forge
     snowballstemmer           1.9.1                      py_0    conda-forge
     sortedcontainers          2.1.0                      py_0    conda-forge
     sphinx                    2.2.0                      py_0    conda-forge
     sphinx-markdown-tables    0.0.9                    pypi_0    pypi
     sphinx_rtd_theme          0.4.3                      py_0    conda-forge
     sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
     sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
     sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
     sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
     sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
     sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
     sphinxcontrib-websupport  1.1.2                      py_0    conda-forge
     sqlite                    3.29.0               hcee41ef_1    conda-forge
     sqlitedict                1.6.0                    pypi_0    pypi
     statsmodels               0.10.1           py37hc1659b7_0    conda-forge
     streamz                   0.5.2                      py_0    conda-forge
     tabulate                  0.8.5                    pypi_0    pypi
     tblib                     1.4.0                      py_0    conda-forge
     tensorboard               1.13.1                   py37_0    conda-forge
     tensorflow                1.13.1               h5ece82f_5    conda-forge
     tensorflow-base           1.13.1           py37h5ece82f_5    conda-forge
     tensorflow-estimator      1.13.0                     py_0    anaconda
     termcolor                 1.1.0                      py_2    conda-forge
     terminado                 0.8.2                    py37_0    conda-forge
     testpath                  0.4.2                   py_1001    conda-forge
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.9             hed695b0_1003    conda-forge
     toolz                     0.10.0                     py_0    conda-forge
     torchvision               0.4.0                py37_cu100    pytorch
     tornado                   6.0.3            py37h516909a_0    conda-forge
     tqdm                      4.36.1                   pypi_0    pypi
     traitlets                 4.3.2                 py37_1000    conda-forge
     umap-learn                0.3.10                   py37_0    conda-forge
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     urllib3                   1.24.3                   pypi_0    pypi
     wcwidth                   0.1.7                      py_1    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     werkzeug                  0.16.0                     py_0    conda-forge
     wheel                     0.33.6                   py37_0    conda-forge
     widgetsnbextension        3.5.1                    pypi_0    pypi
     wrapt                     1.11.2                   pypi_0    pypi
     xgboost                   1.0.0rapidsdev0-SNAPSHOT          pypi_0    pypi
     xorg-libxau               1.0.9                h14c3975_0    conda-forge
     xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
     xz                        5.2.4             h14c3975_1001    conda-forge
     yaml                      0.1.7             h14c3975_1001    conda-forge
     yarl                      1.3.0           py37h14c3975_1000    conda-forge
     zeromq                    4.3.2                he1b5a44_2    conda-forge
     zict                      1.0.0                    pypi_0    pypi
     zipp                      0.6.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1006    conda-forge
     zstd                      1.4.0                h3b9ef0a_0    conda-forge

**Additional context**

**Comment by ayushdg** [comment] 2019-09-30 16:55
Thanks for raising this issue. FWIW reading the output file using `pandas.read_csv` or `cudf.read_csv` would result in the same dataframe as the one created in the example. The `"` marks will not appear around the strings when reading the files using these libraries.

```
>>> cudf.read_csv(StringIO("\"a\"\t1\n\"b\"\t2"),sep="\t",header=None)
   0  1
0  a  1
1  b  2
```

**Comment by davidwendt** [comment] 2019-09-30 17:01
Quotes are added to strings column in case they contain the delimiter character (or other CSV formatting characters).
This can be done conditionally but then requires the overhead of checking for these characters first.

**Comment by gbatmaz** [comment] 2019-09-30 17:25
Thank you for the quick responses. I read the data from a big file with `cudf.read_csv()` into a dataframe , and then modify it and finally trying to write it into a new file with `to_csv()`, in which I would not like to have extra characters. Is there a workaround not to add quotes? Is it possible to have an option to not write the "", like in pandas? Thank you.

**Comment by davidwendt** [comment] 2019-09-30 17:31
Sorry, there is no current option or workaround this.
Just curious, is there an issue with the quotes in the file?
Any CSV reader should be able to handle quoted entries.

**Comment by BartleyR** [comment] 2019-10-01 17:21
I believe the issue is that @gbatmaz is training his own FLAIR embeddings on a specific corpus (https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_9_TRAINING_LM_EMBEDDINGS.md), and the quotes around the values in the corpus CSV file are causing FLAIR to not interpret the lines correctly.

**Comment by gbatmaz** [comment] 2019-10-02 08:38
Thank you @BartleyR . It'd be nice to have at least an option to not insert the quotes like in pandas' `to_csv`

**Comment by randerzander** [comment] 2019-10-03 21:22
@gbatmaz what's your ingest pipeline look like? Could you not workaround this issue for now by doing text.replace('"', '') or similar?

**Comment by randerzander** [comment] 2019-10-03 22:40
does the file need to be CSV explicitly?

**Comment by gbatmaz** [comment] 2019-10-03 22:42
@randerzander Yes, something similar can be done. We can close the issue as this is not a bug (I originally thought it was because `to_csv` output did not match the pandas `to_csv` output)

**Comment by randerzander** [comment] 2019-10-04 14:55
Per discussion with @davidwendt, the original reason we automatically quoted all string fields in `to_csv` was as a way to avoid the overhead of checking each string to see if it contained a delimiter that needed to be quoted.

We can still avoid that overhead by supporting a "quoting" parameter that if `True` will quote string fields, and if `False` wont quote. The downside is that if `False`, _and_ the string values contain the delimiter character, the output would be an invalid CSV file (some rows would seem to contain more columns).

How does that sound for your uses @gbatmaz @BartleyR ?

**Comment by BartleyR** [comment] 2019-10-04 15:01
@randerzander I think that would be fine for our specific use cases right now. Are there plans for future development to check for a problem delimiter similar to what Pandas does when writing out to CSV?

**Comment by lmeyerov** [comment] 2019-10-14 21:39
We hit this as well. In particular, neo4j's bulk loader is super sensitive.

It's good to have to_csv automate this stuff, but IMO, explicit controls may be even better b/c this stuff is often about IO boundary mismatches of various tools.  (CSV in excel vs google vs sql server is horrible.) Pandas has global quoting/escaping controls, and I can imagine per-column.

**Comment by lmeyerov** [comment] 2019-10-14 21:43
To be clear about our case:

* We need some specific ID columns to have no quotes, b/c neo4j
* We need some other columns to have quotes, b/c they have commas in them
* There's plenty of text data (logs), so as soon as we have quotes and need to combine with ### downstream tools, we also want escaped quotes via both \" (many tools) and "" (csv convention)

**Comment by GregoryKimball** [comment] 2022-11-22 18:57
Closing in favor of #7108

**Closed by GregoryKimball** 2022-11-22 18:57 UTC
Labels: feature request, cuDF (Python), cuIO
