### ISSUE TITLE
performance about kernel matches_re [QST]

### ISSUE THREAD

**Issue by chenrui17** [rapidsai/cudf#7048] opened 2020-12-24 08:11 UTC
**What is your question?**
I run a sql in spark-rapids, and found that matches_re kernel takes almost half the total time by nsys, another is read_parquet, look here :
![image](https://user-images.githubusercontent.com/33319780/103073039-cb05d200-4601-11eb-8463-3c802b91b42f.png)
my question is 
1. string match performance on gpu is not good as cpu , because the filter operator of CPU takes a small proportion of the whole SQL execution time , while on gpu , it takes almost half, so Is there any other way to improve its performance？
2. Why is it so time consuming ?
3. Must string matching be implemented in a regular way on GPU ？Is there any other way to implement ?

thanks, looking forward to your reply.

**Comment by kkraus14** [comment] 2020-12-24 08:19
Could you share the regular expression that's being used in the query? cc @davidwendt for visibility

**Comment by chenrui17** [comment] 2020-12-24 08:32
I don't know how to view the converted regular expression， but i think my regular expression is compares two strings for equality ,because my sql is : 
`sql("select cmatch,query,sum(pv) as real_pv from table where event_day=20201107 and cmatch in (225,222,223) and page_number=0 and (event_isremoraabnor = 0 or (event_isremoraabnor = 1 and adview_hasclick = 1)) group by cmatch,query").show`
and cmatch, pv,page_number is bigint type ,and other related type is string

**Comment by kkraus14** [comment] 2020-12-24 08:37
Will need someone from @rapidsai/cudf-java-codeowners to chime in as to how that would be converted into libcudf calls

**Comment by revans2** [comment] 2020-12-24 13:19
The only places that `matchesRe` are used in the Apache Spark plugin, currently, is for the `like` function, and when casting strings to various things. My guess is that the slowness is from casting `event_isremoraabnor` and `adview_hasclick` to a number from a string. The problem is error handling and trying to match all error cases so that they match Spark directly. There was some work recently to improve this performance for date/timestamp casts.  We can also look at doing the same for number casts.  If so please file an issue in the [NVIDIA spark repo](https://github.com/NVIDIA/spark-rapids/issues/new/choose) and we can look at what it would take to improve the performance for this query, and what changes might be needed in cudf to do this.

On a side note you mentioned that the string match performance is not as good as it is on the CPU.  Spark does not use a regular expression in this case.  It uses hand coded rules to do the conversion.  Also because Spark uses row major processing instead of columnar processing, especially coupled with code generation in spark, you cannot really tell how long an individual operator takes unless you can do profiling in the Spark code and pick apart the different lines in the generated code.

**Comment by revans2** [comment] 2021-01-04 15:28
https://github.com/NVIDIA/spark-rapids/issues/1432 was filed in the spark plugin repo. Closing this for now until we can determine what follow on issues might be needed (if any)

**Closed by revans2** 2021-01-04 15:28 UTC
Labels: libcudf, question, strings
