### ISSUE TITLE
[FEA] libcudf table_view slice should check existence of null values in column before slicing

### ISSUE THREAD

**Issue by chirayuG-nvidia** [rapidsai/cudf#5626] opened 2020-07-02 18:27 UTC
**Describe the bug**
For columns without null values cudf::Slice operation on table_view input can improve performance by not performing null_count computation which requires host to device memcpy.

**Steps/Code to reproduce bug**
Use cudf::Slice on a table_view input without any NULL values in columns.

**Expected behavior**
As discussed with @jrhemstad , there should be a check at https://github.com/rapidsai/cudf/blob/a537380726e9a3e6b7a0f0944ae573053ec5e93e/cpp/src/copying/slice.cpp#L38 before performing the operation.

**Environment overview (please complete the following information)**
 conda cuDF 0.14

**Environment details**

**Additional context**

**Comment by harrism** [comment] 2020-08-23 23:41
This appears to not be a bug, but a performance feature request, so updating appropriately.

**Comment by harrism** [comment] 2020-08-23 23:44
Seems like a sketchy request. If the function is already optimized to be a no-op on non-nullable columns, doing anything further would require adding extra logic and a member variable to track whether `count_nulls()` has been called since any changes were made to the data. Not sure if the complexity is worth it.  

Is this a known performance problem in real code?

**Comment by chirayuG-nvidia** [comment] 2020-08-24 18:04
![cudf_table_slice](https://user-images.githubusercontent.com/48134467/91079574-116a0680-e5f9-11ea-97d6-62d951d3f7c2.png)

I have marked the 4 byte cuda H2D memcpy (followed by a stream sync) in the attached figure. Those calls are made for each columns of the table. In my offline discussion with @jrhemstad  he suggested that this memcpy can be removed if we know there are no NULL values in the columns. These memcpy and stream sync are on NULL stream which makes them perf-limiter to interleave with a custom CUDA code. (leaving the argument of PTDS aside).

**Comment by jrhemstad** [comment] 2020-08-24 19:25
@chirayuG-nvidia I don't understand where the memcpy is coming from in the line you referenced.

`segmented_count_unset_bits` already checks for a non-nullable column and skips a kernel invocation:

https://github.com/rapidsai/cudf/blob/5fbffb6688f8df7a395f54fa552a615a70346b12/cpp/src/bitmask/null_mask.cu#L574-L576

**Comment by jrhemstad** [comment] 2020-08-31 16:07
Closing since we don't have a reproducer of this behavior, and code inspection doesn't show any obvious source of the memcpy.

**Closed by jrhemstad** 2020-08-31 16:07 UTC
Labels: Performance, feature request, libcudf
