### ISSUE TITLE
[BUG] Summing column of NANs gives different results than pandas

### ISSUE THREAD

**Issue by ChrisJar** [rapidsai/cudf#11662] opened 2022-09-07 16:13 UTC
**Describe the bug**
When calling the `sum()` function on a series of column of all `np.nan` with dtype `'O'` cudf gives a different result than pandas:

```python
import pandas as pd
import cudf
import numpy as np

ps = pd.Series([np.nan, np.nan]).astype('O')
gs = cudf.Series([np.nan, np.nan]).astype('O')

print("Pandas:")
print(ps.dtype)
print(ps.sum(skipna=True))

print("cudf:")
print(gs.dtype)
print(gs.sum(skipna=True))
```
returns:
```
Pandas:
object
0
cudf:
object
<NA>
```

**Comment by galipremsagar** [comment] 2022-09-07 16:33
I'd expect it to be expected behavior, This is because result of `cudf.Series([np.nan, np.nan])` is all `<NA>`'s:
```python
In [12]: cudf.Series([np.nan, np.nan])
Out[12]: 
0    <NA>
1    <NA>
dtype: object

In [13]: cudf.Series([np.nan, np.nan], nan_as_null=False)
Out[13]: 
0   NaN
1   NaN
dtype: float64
```

Since there is no true `object` dtype in `cudf`, the equivalent pandas & cudf operations will be:
```python
In [17]: pd.Series([np.nan, np.nan]).astype('str').sum(skipna=True)
Out[17]: 'nannan'

In [18]: cudf.Series([np.nan, np.nan], nan_as_null=False).astype('str').sum(skipna=True)
Out[18]: 'NaNNaN'
```

**Comment by vyasr** [comment] 2022-09-08 00:02
Closing based on the :+1: from @ChrisJar.

**Closed by vyasr** 2022-09-08 00:02 UTC
Labels: 4 - Waiting on Author
