### ISSUE TITLE
[BUG] cannot read rarquet file written with partition_cols

### ISSUE THREAD

**Issue by ahmet-uyar** [rapidsai/cudf#9684] opened 2021-11-15 10:50 UTC
**Describe the bug**
I write a DataFrame to parquet with partition_cols parameter set. When I try to read it back, it can not read it properly. 

**Steps/Code to reproduce bug**
```
>>> import cudf
>>> df=cudf.DataFrame({"a": [1,2,2,1,3], "b": [44,55,66,22,11]})
>>> df
   a   b
0  1  44
1  2  55
2  2  66
3  1  22
4  3  11
>>> df.to_parquet("tmp/prq_df/", partition_cols=["a"])
>>> import os
>>> os.listdir("tmp/prq_df")
['a=1', 'a=2', 'a=3']
>>> df2=cudf.read_parquet("tmp/prq_df")
>>> df2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch_hdd/auyar/gcylon_dev/lib/python3.8/site-packages/cudf/core/dataframe.py", line 1549, in __repr__
    return self._clean_renderable_dataframe(output)
  File "/scratch_hdd/auyar/gcylon_dev/lib/python3.8/site-packages/cudf/core/dataframe.py", line 1428, in _clean_renderable_dataframe
    output = output.to_pandas().to_string(
  File "/scratch_hdd/auyar/gcylon_dev/lib/python3.8/site-packages/cudf/core/dataframe.py", line 5680, in to_pandas
    out_data[i] = self._data[col_key].to_pandas(
  File "/scratch_hdd/auyar/gcylon_dev/lib/python3.8/site-packages/cudf/core/column/numerical.py", line 601, in to_pandas
    pd_series.index = index
  File "/scratch_hdd/auyar/gcylon_dev/lib/python3.8/site-packages/pandas/core/generic.py", line 5500, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 70, in pandas._libs.properties.AxisProperty.__set__
  File "/scratch_hdd/auyar/gcylon_dev/lib/python3.8/site-packages/pandas/core/series.py", line 559, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/scratch_hdd/auyar/gcylon_dev/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 216, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/scratch_hdd/auyar/gcylon_dev/lib/python3.8/site-packages/pandas/core/internals/base.py", line 57, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 5 elements, new values have 1 elements


```

**Expected behavior**
I should be able to get the dataframe that I have written to the file. 

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal]
 - Method of cuDF install: [conda]

**Environment details**
cudf 21.10 installed. 

**Additional context**
Nothing more.

**Comment by quasiben** [comment] 2021-11-15 15:01
I think this will be fixed in 21.12.  Can you try with a nightly cudf version ?

> conda install -c rapidsai-nightly cudf=21.12 ?

```python
In [1]: import cudf

In [2]: df=cudf.DataFrame({"a": [1,2,2,1,3], "b": [44,55,66,22,11]})

In [3]: df.to_parquet("tmp/prq_df/", partition_cols=["a"])
/datasets/bzaitlen/miniconda3/envs/cudf110/lib/python3.8/site-packages/cudf/core/frame.py:3068: FutureWarning: keep_index is deprecated and will be removed in the future.
  warnings.warn(

In [4]: df2=cudf.read_parquet("tmp/prq_df")

In [5]: cudf.__version__
Out[5]: '21.12.00a+237.gd60e2e6b81'
```

**Comment by beckernick** [comment] 2021-11-15 15:58
Interestingly, I'm not able to reproduce this in the 21.12 nightly on a different commit (49d1cc2864):

```python
import cudf

df=cudf.DataFrame({"a": [1,2,2,1,3], "b": [44,55,66,22,11]})
df.to_parquet("tmp/prq_df/", partition_cols=["a"])
df2=cudf.read_parquet("tmp/prq_df")
print(df2)
print(cudf.__version__)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-a00d09df4d44> in <module>
      4 df.to_parquet("tmp/prq_df/", partition_cols=["a"])
      5 df2=cudf.read_parquet("tmp/prq_df")
----> 6 print(df2)
      7 print(cudf.__version__)

~/conda/envs/cudf-21.12/lib/python3.8/site-packages/cudf/core/frame.py in __str__(self)
   5058
   5059     def __str__(self):
-> 5060         return self.to_string()
   5061
   5062     def __deepcopy__(self, memo):

~/conda/envs/cudf-21.12/lib/python3.8/site-packages/cudf/core/frame.py in to_string(self)
   5055         '   key   val\\n0    0  10.0\\n1    1  11.0\\n2    2  12.0'
   5056         """
-> 5057         return self.__repr__()
   5058
   5059     def __str__(self):

~/conda/envs/cudf-21.12/lib/python3.8/site-packages/cudf/core/dataframe.py in __repr__(self)
   1835     def __repr__(self):
   1836         output = self._get_renderable_dataframe()
-> 1837         return self._clean_renderable_dataframe(output)
   1838
   1839     def _repr_html_(self):

~/conda/envs/cudf-21.12/lib/python3.8/site-packages/cudf/core/dataframe.py in _clean_renderable_dataframe(self, output)
   1714             width = None
   1715
-> 1716         output = output.to_pandas().to_string(
   1717             max_rows=max_rows,
   1718             min_rows=min_rows,

~/conda/envs/cudf-21.12/lib/python3.8/site-packages/cudf/core/dataframe.py in to_pandas(self, nullable, **kwargs)
   4736
   4737         for i, col_key in enumerate(self._data):
-> 4738             out_data[i] = self._data[col_key].to_pandas(
   4739                 index=out_index, nullable=nullable
   4740             )

~/conda/envs/cudf-21.12/lib/python3.8/site-packages/cudf/core/column/numerical.py in to_pandas(self, index, nullable, **kwargs)
    585
    586         if index is not None:
--> 587             pd_series.index = index
    588         return pd_series
    589

~/conda/envs/cudf-21.12/lib/python3.8/site-packages/pandas/core/generic.py in __setattr__(self, name, value)
   5498         try:
   5499             object.__getattribute__(self, name)
-> 5500             return object.__setattr__(self, name, value)
   5501         except AttributeError:
   5502             pass

~/conda/envs/cudf-21.12/lib/python3.8/site-packages/pandas/_libs/properties.pyx in pandas._libs.properties.AxisProperty.__set__()

~/conda/envs/cudf-21.12/lib/python3.8/site-packages/pandas/core/series.py in _set_axis(self, axis, labels, fastpath)
    557         if not fastpath:
    558             # The ensure_index call above ensures we have an Index object
--> 559             self._mgr.set_axis(axis, labels)
    560
    561     # ndarray compatibility

~/conda/envs/cudf-21.12/lib/python3.8/site-packages/pandas/core/internals/managers.py in set_axis(self, axis, new_labels)
    214     def set_axis(self, axis: int, new_labels: Index) -> None:
    215         # Caller is responsible for ensuring we have an Index object.
--> 216         self._validate_set_axis(axis, new_labels)
    217         self.axes[axis] = new_labels
    218

~/conda/envs/cudf-21.12/lib/python3.8/site-packages/pandas/core/internals/base.py in _validate_set_axis(self, axis, new_labels)
     55
     56         elif new_len != old_len:
---> 57             raise ValueError(
     58                 f"Length mismatch: Expected axis has {old_len} elements, new "
     59                 f"values have {new_len} elements"

ValueError: Length mismatch: Expected axis has 5 elements, new values have 1 elements
```
cudf commits:
```
conda list | grep cudf
# packages in environment at /home/nicholasb/conda/envs/cudf-21.12:
cudf                      21.12.00a211115 cuda_11_py38_g49d1cc2864_257    rapidsai-nightly
libcudf                   21.12.00a211115 cuda11_g49d1cc2864_257    rapidsai-nightly
```

Environment:

<details>
conda list
# packages in environment at /home/nicholasb/conda/envs/cudf-21.12:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
abseil-cpp                20210324.2           h9c3ff4c_0    conda-forge
anyio                     3.3.4            py38h578d9bd_1    conda-forge
argon2-cffi               21.1.0           py38h497a2fe_2    conda-forge
arrow-cpp                 5.0.0           py38h07a114d_14_cuda    conda-forge
arrow-cpp-proc            3.0.0                      cuda    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
aws-c-auth                0.6.5                h00e28c2_5    conda-forge
aws-c-cal                 0.5.12               h8c99da7_6    conda-forge
aws-c-common              0.6.16               h7f98852_0    conda-forge
aws-c-compression         0.2.14               h4f5cfdb_6    conda-forge
aws-c-event-stream        0.2.7               hedd7935_30    conda-forge
aws-c-http                0.6.10               he2927c9_1    conda-forge
aws-c-io                  0.10.13              h4e1a65d_2    conda-forge
aws-c-mqtt                0.7.8                h1e34fcd_9    conda-forge
aws-c-s3                  0.1.27               hbe77d09_8    conda-forge
aws-c-sdkutils            0.1.1                h4f5cfdb_3    conda-forge
aws-checksums             0.1.12               h4f5cfdb_5    conda-forge
aws-crt-cpp               0.17.4               ha10c5ac_2    conda-forge
aws-sdk-cpp               1.9.140              h94f6c54_1    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1003    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cachetools                4.2.4              pyhd8ed1ab_0    conda-forge
certifi                   2021.10.8        py38h578d9bd_1    conda-forge
cffi                      1.15.0           py38h3931269_0    conda-forge
chardet                   4.0.0            py38h578d9bd_2    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
cryptography              35.0.0           py38h3e25421_2    conda-forge
cudatoolkit               11.2.72              h2bc3f7f_0    nvidia
cudf                      21.12.00a211115 cuda_11_py38_g49d1cc2864_257    rapidsai-nightly
cupy                      9.6.0            py38h177b0fd_0    conda-forge
debugpy                   1.5.1            py38h709712a_0    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dlpack                    0.5                  h9c3ff4c_0    conda-forge
entrypoints               0.3             py38h32f6830_1002    conda-forge
fastavro                  1.4.7            py38h497a2fe_1    conda-forge
fastrlock                 0.8              py38h709712a_1    conda-forge
fsspec                    2021.11.0          pyhd8ed1ab_0    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
glog                      0.5.0                h48cff8f_0    conda-forge
grpc-cpp                  1.41.1               h75e9d12_2    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
importlib-metadata        4.8.2            py38h578d9bd_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.5.0            py38he5a9106_0    conda-forge
ipython                   7.29.0           py38he5a9106_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.0           py38h578d9bd_3    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.2.1              pyhd8ed1ab_0    conda-forge
jupyter_client            7.0.6              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.1            py38h578d9bd_1    conda-forge
jupyter_server            1.11.2             pyhd8ed1ab_0    conda-forge
jupyterlab                3.2.3              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.8.2              pyhd8ed1ab_0    conda-forge
krb5                      1.19.2               hcc1bbae_3    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libblas                   3.9.0           12_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h7f98852_6    conda-forge
libbrotlidec              1.0.9                h7f98852_6    conda-forge
libbrotlienc              1.0.9                h7f98852_6    conda-forge
libcblas                  3.9.0           12_linux64_openblas    conda-forge
libcudf                   21.12.00a211115 cuda11_g49d1cc2864_257    rapidsai-nightly
libcurl                   7.80.0               h2574ce0_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgfortran-ng            11.2.0              h69a702a_11    conda-forge
libgfortran5              11.2.0              h5c6108e_11    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
liblapack                 3.9.0           12_linux64_openblas    conda-forge
libllvm11                 11.1.0               hf817b99_2    conda-forge
libnghttp2                1.43.0               h812cca2_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libprotobuf               3.18.1               h780b84a_0    conda-forge
librmm                    21.12.00a211115 cuda11_gbbfb011_27    rapidsai-nightly
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libthrift                 0.15.0               he6d91bd_1    conda-forge
libutf8proc               2.6.1                h7f98852_0    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
llvmlite                  0.37.0           py38h4630a5e_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markupsafe                2.0.1            py38h497a2fe_1    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py38h497a2fe_1005    conda-forge
nbclassic                 0.3.4              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.8              pyhd8ed1ab_0    conda-forge
nbconvert                 6.3.0            py38h578d9bd_1    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
notebook                  6.4.5              pyha770c72_0    conda-forge
numba                     0.54.1           py38h4bf6c61_0    conda-forge
numpy                     1.20.3           py38h9894fe3_1    conda-forge
nvtx                      0.2.3            py38h497a2fe_0    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
orc                       1.7.1                h68e2c4e_0    conda-forge
packaging                 21.2               pyhd8ed1ab_1    conda-forge
pandas                    1.3.4            py38h43a58ef_1    conda-forge
pandoc                    2.16.1               h7f98852_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parquet-cpp               1.5.1                         1    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0            py38h32f6830_1    conda-forge
pickleshare               0.7.5           py38h32f6830_1002    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
prometheus_client         0.12.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.22             pyha770c72_0    conda-forge
protobuf                  3.18.1           py38h709712a_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pyarrow                   5.0.0           py38hb90f683_14_cuda    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyhd8ed1ab_1    conda-forge
pyrsistent                0.18.0           py38h497a2fe_0    conda-forge
pysocks                   1.7.1            py38h578d9bd_4    conda-forge
python                    3.8.12          hb7a2778_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyzmq                     22.3.0           py38h2035c66_1    conda-forge
re2                       2021.11.01           h9c3ff4c_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
rmm                       21.12.00a211115 cuda11_py38_gbbfb011_27_has_cma    rapidsai-nightly
s2n                       1.2.0                h9b69904_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                59.1.0           py38h578d9bd_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sniffio                   1.2.0            py38h578d9bd_2    conda-forge
spdlog                    1.8.5                h4bd325d_0    conda-forge
sqlite                    3.36.0               h9cd32fc_2    conda-forge
terminado                 0.12.1           py38h578d9bd_1    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
tornado                   6.1              py38h497a2fe_2    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typing_extensions         3.10.0.2           pyha770c72_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.1.0            py38h578d9bd_1    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge
</details>

**Comment by ayushdg** [comment] 2021-11-15 19:18
I believe `cudf.read_parquet` does not support reading partitioned parquet files at the moment and only supports reading from a single folder containing multiple parquet files within it. 
`dask_cudf` on the other hand does support reading partitioned datasets.
In your particular case you could use:
```python
df2=dask_cudf.read_parquet("tmp/prq_df")
# use df2 as a dask-cudf dataframe

df2 = df2.compute() # compute the result and return a cudf dataframe to the client. 
```

We should definitely improve the error message to fail in a more informative way in this case and update the docstrings to indicate that `cudf` doesn't support this today. 

Once that's done this can potentially be marked as a feature request. 

cc: @rjzamora who's worked on some of the logic for reading partitioned parquet files with dask and dask-cudf.

**Comment by rjzamora** [comment] 2021-11-15 20:16
>I believe cudf.read_parquet does not support reading partitioned parquet files at the moment and only supports reading from a single folder containing multiple parquet files within it.
dask_cudf on the other hand does support reading partitioned datasets.

I am pretty sure that @ayushdg is correct about everything here. At this point, it shouldn't be difficult to handle partitioned data in cudf, but the feature hasn't been requested/added yet. I suppose the first step is to modify [this logic](https://github.com/rapidsai/cudf/blob/branch-21.12/python/cudf/cudf/io/parquet.py#L383-L390) in `read_parquet` to check if the dataset is directory partitioned (and throw a clear error if it is).

After clarifying the error, we can attack partitioned-read support. My first impression is that we may want to limit support to the case that is supported by pandas: reading from a single directory path (and not reading specific list of files within the partitioned directory, or a partitioned directory among a list of multiple directory/file paths).

**Comment by ahmet-uyar** [comment] 2021-11-16 10:19
the fact that to_parquet method supports partitioned writing, and there is no documentation about the lack of support in read_parquet, I never thought that it may have not been supported by read_parquet. In addition, read_parquet method was returning a DataFrame without raising any error.  

For us unfortunately, Dask is not an option.

**Comment by rjzamora** [comment] 2021-11-16 14:38
>the fact that to_parquet method supports partitioned writing, and there is no documentation about the lack of support in read_parquet, I never thought that it may have not been supported by read_parquet.

Yes - I completely agree that the lack of documentation (and general return/error behavior) is clearly a bug. It is my understanding that partitioned write support was orginally added in the form of `write_to_dataset` (to mimic the pyarrow function) at a point when the cudf (and likely pandas) read_parquet API was much less mature. My appologies about this - I should have time to investigate a fix very soon.

**Comment by rjzamora** [comment] 2021-11-18 14:22
@ahmet-uyar - Thanks again for reporting this! Hopefully #9720 resolves the issue. Please feel free to give feedback

**Comment by ahmet-uyar** [comment] 2021-11-22 07:28
thank you for the quick fix @rjzamora

**Closed** 2021-12-03 02:19 UTC
Labels: bug, cuDF (Python)
