### ISSUE TITLE
[FEA] Handle setting numpy array to GDF

### ISSUE THREAD

**Issue by esnvidia** [rapidsai/cudf#8674] opened 2021-07-07 15:20 UTC
**Is your feature request related to a problem? Please describe.**
Error message either should be clearer or handle setting values from numpy array to GDF

![image](https://user-images.githubusercontent.com/80840697/124785201-a9709600-df14-11eb-9109-a0d4b8f32929.png)
![image](https://user-images.githubusercontent.com/80840697/124785312-c1481a00-df14-11eb-81ca-3dae4db7551d.png)

**Describe the solution you'd like**
`sk_std_scaler` is scikit-learn standard scaler. 
`sk_gdf.loc[:, numer_cols] = sk_std_scaler.fit_transform(sk_gdf[numer_cols].to_pandas())`

or a more helpful error message:
`Cannot assign numpy array to Device DataFrame. Please convert to cupy.array object first with cupy.array(numpy_array)`

**Describe alternatives you've considered**
Convert to cupy array: `sk_gdf.loc[:, numer_cols] = cp.array(sk_std_scaler.fit_transform(sk_gdf[numer_cols].to_pandas()))`

**Additional context**
[Untitled.zip](https://github.com/rapidsai/cudf/files/6778358/Untitled.zip)
Also see issues here for additional context:
https://github.com/rapidsai/cudf/issues/8672
https://github.com/rapidsai/cuml/issues/4034

**Comment by beckernick** [comment] 2021-07-08 20:43
@esnvidia would you be able to provide a minimal reproducer in Python code (outside of a Jupyter notebook)? Thanks!

**Comment by esnvidia** [comment] 2021-07-10 12:15
[example.zip](https://github.com/rapidsai/cudf/files/6795229/example.zip)
@beckernick Cleaned up code to make a minimal `py` file that I ran with  a conda install of rapids 21.06

**Comment by beckernick** [comment] 2021-07-19 15:45
@esnvidia is this the same issue as https://github.com/rapidsai/cudf/issues/8672

**Comment by esnvidia** [comment] 2021-07-24 20:11
Related but not the same. This one is related to setting a numpy matrix to a set of indices/columns, which is why this is a Feature Request. In #8672  the output is a cupy array IIRC. In that issue, the setting of the cupy array to the DataFrame was wrong.

**Comment by beckernick** [comment] 2021-08-03 19:49
It looks like the Scaler issue was fixed in cuML based on https://github.com/rapidsai/cuml/issues/4034 , and the setitem issue is covered by https://github.com/rapidsai/cudf/issues/8672

As a result, I'm going to close this issue. Please feel to re-open if I have misunderstood what the request is here.

**Closed by beckernick** 2021-08-03 19:49 UTC
Labels: ? - Needs Triage, feature request
