### ISSUE TITLE
[BUG] jitify2 failed to acquire file lock

### ISSUE THREAD

**Issue by abellina** [rapidsai/cudf#7974] opened 2021-04-15 20:41 UTC
@petro-rudenko reported the following happening for him:

```
ai.rapids.cudf.CudfException: Failed to acquire file lock
        at ai.rapids.cudf.ColumnView.binaryOpVS(Native Method)
        at ai.rapids.cudf.ColumnView.binaryOp(ColumnView.java:1008)
        at ai.rapids.cudf.ColumnView.binaryOp(ColumnView.java:998)
        at ai.rapids.cudf.BinaryOperable.equalToNullAware(BinaryOperable.java:542)
        at ai.rapids.cudf.BinaryOperable.equalToNullAware(BinaryOperable.java:549)
        at org.apache.spark.sql.rapids.GpuAnd.$anonfun$doColumnar$2(predicates.scala:80)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.CudfBinaryOperator.withResource(GpuExpressions.scala:240)
        at org.apache.spark.sql.rapids.GpuAnd.$anonfun$doColumnar$1(predicates.scala:79)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.CudfBinaryOperator.withResource(GpuExpressions.scala:240)
        at org.apache.spark.sql.rapids.GpuAnd.doColumnar(predicates.scala:78)
```

This seems to be coming from: https://github.com/NVIDIA/jitify/blob/jitify2/jitify2.hpp#L5353. This is instantiated from: https://github.com/rapidsai/cudf/blob/348ad4dcdd1cc7f970241d4389493176cd58dd5a/cpp/src/jit/cache.cpp#L105. 

The problem is that we have multiple processes in a single machine, and this is likely all using the same filename and getting an exclusive lock on it (via `fcntl` and `F_WRLCK`). 

Reporting this since it seems like a blocker for the 0.19 release. If anyone with more jitify2 experience can take a look at this that would be great. We can work on trying to reproduce if we are not convinced, but it would be good to get an experts opinion.

**Comment by revans2** [comment] 2021-04-15 21:09
It looks like if the file fails to be opened or if the lock fails, not blocks but fails, then this can happen.  Sadly there is no debug logging or extra info in the exception to say what actually happened that made it fail. The code looks correct from what I can see, but my guess is that something else happened in the OS (permission issue, resource problems, etc).

**Comment by cwharris** [comment] 2021-04-15 22:58
The problem is that we should be optimistically creating the file cache. If one process is unable to create the file cache, it should assume that another process is doing it, and move on to working with the in-memory cache (which it can generate itself, the first time around). Alternatively the current process could _wait_ and see if another process successfully creates the cache, but that is harder to coordinate and could actually take more time.

**Comment by petro-rudenko** [comment] 2021-04-19 15:23
Seems like doesn't reproduce any more with a latest cudf build

**Comment by kkraus14** [comment] 2021-04-22 00:06
Fixed by https://github.com/rapidsai/jitify/pull/14

**Closed by kkraus14** 2021-04-22 00:06 UTC
Labels: Jitify, Spark, bug, libcudf
