### ISSUE TITLE
[FEA] groupby.head and tail

### ISSUE THREAD

**Issue by KazukiOnodera** [rapidsai/cudf#12245] opened 2022-11-26 09:49 UTC
I wish I could use cuDF to do groupby.head and tail

I'm expecting this behavior like pandas

```
In [2]: 
   ...: df = pd.DataFrame(
   ...:     [
   ...:         ["A", 1],
   ...:         ["A", 2],
   ...:         ["A", 3],
   ...:         ["B", 4],
   ...:         ["B", 5],
   ...:         ["B", 6],
   ...:         ["B", 7],
   ...:         ["C", 8],
   ...: 
   ...:     ], columns=["x", "y"],)
   ...: 

In [3]: df
Out[3]: 
   x  y
0  A  1
1  A  2
2  A  3
3  B  4
4  B  5
5  B  6
6  B  7
7  C  8

In [4]: df.groupby("x").head(2)
Out[4]: 
   x  y
0  A  1
1  A  2
3  B  4
4  B  5
7  C  8

```

**Comment by beckernick** [comment] 2022-11-30 16:21
This is close to a duplicate of https://github.com/rapidsai/cudf/issues/2592 , though this also asks for `tail`

**Comment by shwina** [comment] 2022-11-30 18:26
I believe this will need `libcudf` support as well (just FYI @GregoryKimball).

**Comment by psulski** [comment] 2023-02-18 09:07
<class 'cudf.core.groupby.groupby.DataFrameGroupBy'>
<cudf.core.groupby.groupby.DataFrameGroupBy object at 0x7faafcc61550>

dff3.head(1)

give AttributeError: DataFrameGroupBy object has no attribute head

dff3.info()
give AttributeError: DataFrameGroupBy object has no attribute info

**Closed** 2023-03-16 17:46 UTC
Labels: feature request, libcudf, cuDF (Python)
