### ISSUE TITLE
[BUG] Groupby operation in groupby.__getattr__?

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#1197] opened 2019-03-14 21:36 UTC
I'm confused by the following code in `SeriesGroupby.__getattr__`

https://github.com/rapidsai/cudf/blob/39e2dcd0124acd7b9938409346efe2ad0d4d6b42/python/cudf/groupby/groupby.py#L29-L46

Why do we call a groupby aggregation here? 

cc @kkraus14 @thomcom

**Comment by kkraus14** [comment] 2019-03-14 21:37
@thomcom I think you're better equipped to answer this than me.

**Comment by kkraus14** [comment] 2019-03-14 21:38
@mrocklin one thing to note, we don't actually apply a groupby on calling groupby. The groupby is actually performed at the same time as the aggregation when you call the aggregation function so this operation is inexpensive.

**Comment by thomcom** [comment] 2019-03-15 13:53
Yeah, the Series groupby in this case is an intermediate object. It stores the dataframe that will be used in the groupby, but the aggregation doesn't happen until either .agg is called or one of the aggregation shorthand functions like `min`.

Is it having unexpected behavior?

**Comment by kkraus14** [comment] 2019-04-02 18:47
Closing this as there hasn't been discussion since the initial question. Feel free to reopen if there's issues.

**Closed by kkraus14** 2019-04-02 18:47 UTC
Labels: bug, question
