### ISSUE TITLE
[BUG]value_counts returns garbage data on large data set

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cudf#2602] opened 2019-08-15 21:05 UTC
**Describe the bug**

In the census notebook, `print(df.INCTOT.value_counts())` should return
```
9999999    4888325
0          2567950
10005       121645
12005       101432
30000       100637
20000        99159
6005         94222
12000        93653
8005         91428
3005         87076
5005         86019
10000        84575
15000        79216
25000        78961
```

instead it returns
```
0         2567950
-20000           3
 10005      121645
-20000           3
 12005      101432
-20000           3
 30000      100637
-20000           3
 20000       99159
-20000           3
 6005        94222
-20000           3
 12000       93653
-20000           3
```

converting to pandas and running value_counts() on the pd dataframe returns the correct response.  this is known to affect the last two nightly containers.  

It is useful to know that value_counts on columns with fewer options seems to return the correct response, based on formatting along, but i can't verify line by line yet

I tried to create a small reproducible code snippet,  using census data, as other attempts failed.  this notebook last worked 8/2

```
import cudf
import numpy as np
import pandas as pd

# download data
!wget https://rapidsai-data.s3.us-east-2.amazonaws.com/datasets/ipums_education2income_1970-2010.csv.gz 

#load helper function
def load_data(cached = 'ipums_education2income_1970-2010.csv.gz',source='ipums'):
    if os.path.exists(cached) and source=='ipums':
        print('use ipums data')
        with gzip.open(cached) as f:
            X = cudf.read_csv(f)
    else:
        print("No data found!  Please uncomment the cell above the 'LOAD_DATA' function and try again!")
        X = null
    return X

#load data and show counts
file = 'ipums_education2income_1970-2010.csv.gz' #incase you wanted to change your file later
df = load_data(file)
print('data',df.shape)
print(df.INCTOT.value_counts())  #<-- here will give you the bad values

#convert cudf dataframe to pandas and run value_counts again
pdf = df.to_pandas()
print(pdf.INCTOT.value_counts())
```

**Comment by ayushdg** [comment] 2019-08-15 21:16
I believe the root cause has been identified and @shwina is working on a fix :D

**Comment by taureandyernv** [comment] 2019-08-15 21:25
Yay!  Thanks @ayushdg and @shwina!

**Comment by kkraus14** [comment] 2019-08-15 21:28
Closing as duplicate of #2597

**Closed by kkraus14** 2019-08-15 21:28 UTC
Labels: ? - Needs Triage, bug
