### ISSUE TITLE
Specifically-sized types for various GDF column types not set in types.h

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#372] opened 2018-11-12 19:14 UTC
GDF columns' element types should be:

* Specified in [`libgdf/include/gdf/cffi/types.h`](https://github.com/rapidsai/cudf/blob/master/libgdf/include/gdf/cffi/types.h), explicitly.
* Have a non-platform-dependent size. (See, e.g. [this StackOverflow question](https://stackoverflow.com/questions/35844586/can-i-assume-the-size-of-long-int-is-always-4-bytes))

This is not the case right now, specifically for `gdf_date32`, `gdf_date64`, `gdf_category`, `gdf_timestamp` (doesn't even exist!).

So, I suggest we do:
```
+#include <stdint.h>
+
 typedef size_t gdf_size_type;
 typedef gdf_size_type gdf_index_type;
-typedef unsigned char gdf_valid_type;
-typedef        long    gdf_date64;
-typedef        int             gdf_date32;
-typedef        int             gdf_category;
+
+typedef uint8_t gdf_valid_type;
+typedef int64_t gdf_date64;
+typedef int32_t gdf_date32;
+typedef int64_t gdf_timestamp;
+typedef int32_t gdf_category;
```
Before suggesting this as a PR - what do you think?

PS - These are still pretty ugly-looking types, but at least they will meet the basic "decency" criteria I've listed above.

**Comment by eyalroz** [comment] 2018-11-12 20:52
@jrhemstad Even if we couldn't make the include from within `types.h`, I'm sure that there is some relevant Python facility in CFFI which could have been used instead. But that doesn't matter now, I suppose.

Also, I'll emphasize that:
* `gdf_timestamp` isn't defined _at all_ right now.
* The include is that `<stdint.h>`, not `<cstdint>`, since we're in the C world.

**Comment by harrism** [comment] 2019-01-08 03:54
We are close to finishing migration away from CFFI, so we should probably revisit this then. I would suggest for 0.6.

**Comment by jrhemstad** [comment] 2019-02-19 21:05
Depends on https://github.com/rapidsai/cudf/issues/599

**Comment by harrism** [comment] 2019-07-04 01:36
Duplicate of #1751

**Closed by harrism** 2019-07-04 01:36 UTC
Labels: code quality, feature request, libcudf (C++/CUDA)
