### ISSUE TITLE
[FEA] JNISupports creating a ColumnVector from an array of UTF8 string directly.

### ISSUE THREAD

**Issue by firestarman** [rapidsai/cudf#8136] opened 2021-05-03 03:29 UTC
cudf cpp expects an UTF8 string to be dealt with. It is missing an API to create a ColumnVector from an array of UTF8 string directly.
e.g.
ColumnVector

This is low priority since now the API `build` can be used to achieve this.

**Comment by davidwendt** [comment] 2021-05-03 20:35
duplicate of #8137 ?

**Comment by jlowe** [comment] 2021-05-03 20:49
Yes, this is a duplicate.

**Closed by jlowe** 2021-05-03 20:49 UTC
Labels: ? - Needs Triage, feature request

**Comment by firestarman** [comment] 2021-05-17 02:27
Thanks for this. 
I filed two similar issues unexpectedly.
