### ISSUE TITLE
[FEA] return first n rows of each group, after doing `groupby` with cudf.

### ISSUE THREAD

**Issue by rnyak** [rapidsai/cudf#4157] opened 2020-02-14 15:35 UTC
**Is your feature request related to a problem? Please describe.**
I'd like to be able to return first n rows of each group, after doing `groupby` with cudf. This can be done with `pdf` as follows:

```
import pandas as pd
pdf = pd.DataFrame({'id6': 4*list(reversed(range(3))), 'v3': 3*list(range(4))})

pdf[['id6', 'v3']].sort_values('v3', ascending=False).groupby(['id6']).head(2)

       id6	v3
3	2	3
7	1	3
11	0	3
2	0	2
6	2	2
10	1	2
```

But `cudf` generates:

``DataFrameGroupBy' object has no attribute 'head'` attribute error.

**Describe alternatives you've considered**
I could not find an alternative solution yet.

**Comment by beckernick** [comment] 2020-02-14 15:49
Thanks for the issue! Closing this as a duplicate of #2592 to consolidate discussion.

**Closed by beckernick** 2020-02-14 15:49 UTC
Labels: ? - Needs Triage, feature request
