### ISSUE TITLE
[FEA] apply_rows() with string values

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#2340] opened 2019-07-18 19:47 UTC
I am trying to add a new column to my dataframe based on the values of another column; consider a simple if-else clause. I am trying to use the apply_rows() function for this, following the example here: https://rapidsai.github.io/projects/cudf/en/latest/api.html#cudf.dataframe.DataFrame.apply_rows

However, if I use string values in my dataframe, I see the error: `AttributeError: 'nvstrings' object has no attribute 'to_gpu_array'`.

Here's the snippet to reproduce the error:

```
import cudf
import numpy as np
df = cudf.DataFrame()
df['in1'] = ["abc","def","xyz"]
df['in2'] = ["a","b","c"]
df['in3'] = ["t1","t2","t3"]

in1 = df['in1']
in2 = df['in2']
in3 = df['in3']

def kernel(in1, in2, in3, out1, out2):
     for i, (x, y, z) in enumerate(zip(in1, in2, in3)):
         out1[i] = 1
         out2[i] = 2

df = df.apply_rows(kernel,
               incols=['in1', 'in2', 'in3'],
               outcols=dict(out1=np.float64, out2=np.float64),
               kwargs={})
```

To narrow down the error, I have removed the if-else clause in the kernel() function. 

I can use `np.where()` with the if-else clause, but that wouldn't be ideal or clean if my conditionals get complex. Any workaround for this currently?

**Comment by kkraus14** [comment] 2019-07-23 19:07
@chinmaychandak StringColumns aren't yet supported in `apply_rows`. Changing this to a feature request.

**Comment by saifrahmed** [comment] 2019-10-19 19:50
Is there an update on this feature? What is the recommended approach for mapping functions onto String cols...should it be done before getting into the cuDF?

**Comment by kkraus14** [comment] 2020-05-29 18:46
Closing as duplicate of #1195

**Closed by kkraus14** 2020-05-29 18:46 UTC
Labels: cuDF (Python), feature request
