### ISSUE TITLE
[FEA] Support reading files from blob using adlfs

### ISSUE THREAD

**Issue by raybellwaves** [rapidsai/cudf#6348] opened 2020-09-29 17:01 UTC
https://github.com/dask/adlfs provides synonymous support for reading files from Azure Blob akin to `s3fs` and `gcsfs`.

It would be good to read in files from blob storage using

`df = cudf.read_parquet(filepath_or_buffer="abfs://folder/file.parquet", storage_options=storage_options)`

cc. https://github.com/BlazingDB/blazingsql/issues/937

**Comment by raybellwaves** [comment] 2020-09-29 17:12
Note: it works using `dask_cudf`

`gdf = dask_cudf.read_parquet(
        path="abfs://folder/file.parquet",
        storage_options=storage_options,
    )`

**Comment by ayushdg** [comment] 2020-09-29 17:21
@raybellwaves Would it be possible to share the stacktrace when reading from blob storage with `cudf`? I tried reading a couple of parquet files from blob storage with `cudf.read_parquet` (0.15) and they worked. Any additional information that can help reproduce the issue would be really helpful.

**Comment by raybellwaves** [comment] 2020-09-29 17:29
@ayushdg of course. Convo started on slack https://rapids-goai.slack.com/archives/C5E06F4DC/p1601395604024000

```
 File "/root/miniconda3/envs/test_env/lib/python3.8/site-packages/cudf/io/parquet.py", line 207, in read_parquet
    return libparquet.read_parquet(
  File "cudf/_lib/parquet.pyx", line 151, in cudf._lib.parquet.read_parquet
  File "cudf/_lib/parquet.pyx", line 163, in cudf._lib.parquet.read_parquet
  File "cudf/_lib/io/utils.pyx", line 42, in cudf._lib.io.utils.make_source_info
IndexError: Out of bounds on buffer access (axis 0)
```

Of you aware of any public blobs which don't have credentials to openly test?

We recently added an options to access public containers in adlfs but it's still on master
https://github.com/dask/adlfs/pull/106

Otherwise you have to go down the azurite route for testing properly https://github.com/dask/adlfs/blob/master/adlfs/tests/test_spec.py#L27

**Comment by raybellwaves** [comment] 2020-09-29 18:09
FYI https://github.com/dask/adlfs/issues/117

**Comment by ayushdg** [comment] 2020-09-29 18:34
Thanks @raybellwaves I tried with an open dataset on abfs and things worked fine 😄 . Here is the example:
```python
df = cudf.read_parquet("abfs://nyctlc/green/puYear=2008/puMonth=12/*.parquet", 
                        storage_options={"account_name":"azureopendatastorage"})
```

I was also able to reproduce the `IndexError: Out of bounds on buffer access (axis 0)` by passing the `filepath_or_buffer` argument to be `abfs://nyctlc/green/puYear=2008/puMonth=12` without the `*.parquet` bit. Looks like it errors out in an unexpected way if a folder name instead of a specific parquet file is provided. I believe the codepath/error message in that case could be improved.

Note: Support for reading multiple parquet files/parquet folder doesn't work with remote datasources as of now #5683 (for tracking) and passing a single parquet file should work.

@raybellwaves Is it possible that `file.parquet` is a folder containing the actual parquet files (and possible some metadata + `_SUCCESS` files)?

**Comment by raybellwaves** [comment] 2020-09-30 15:46
Thanks @ayushdg 

Welcome to close.

Looks as though in the partition parquet file (parquet folder) which it is struggling to read (#5683).

```
>>> cudf.read_parquet('az://nyctlc/green/puYear=2019/puMonth=*/*.parquet', storage_options=storage_options)
/root/miniconda3/envs/test_env/lib/python3.8/site-packages/cudf/utils/ioutils.py:971: UserWarning: `path_or_data` resolved to more than 1 file. Only the first file nyctlc/green/puYear=2019/puMonth=1/part-00066-tid-4753095944193949832-fee7e113-666d-4114-9fcb-bcd3046479f3-2636-2.c000.snappy.parquet will be read.
  warnings.warn(
        vendorID  lpepPickupDatetime  ... totalAmount  tripType
0              2 2019-01-22 06:16:11  ...        7.30         1
1              2 2019-01-06 06:51:26  ...        5.80         1
2              2 2019-01-06 07:02:28  ...       23.16         1
3              2 2019-01-27 14:47:08  ...       18.80         1
4              2 2019-01-07 08:06:13  ...        4.80         1
...          ...                 ...  ...         ...       ...
630884         2 2019-01-24 10:00:23  ...       15.63         2
630885         2 2019-01-24 08:59:59  ...        9.36         1
630886         2 2019-01-24 09:43:41  ...        5.80         1
630887         2 2019-01-24 09:19:01  ...       25.80         1
630888         1 2019-01-24 09:28:17  ...       14.10         1

[630889 rows x 23 columns]
```

Works fine in dask_cudf

```
import dask_cudf
from dask_cuda import LocalCUDACluster
from dask.distributed import Client

cluster = LocalCUDACluster()
client = Client(cluster)

storage_options = {"account_name": "azureopendatastorage"}

gdf = dask_cudf.read_parquet(
        "az://nyctlc/green/puYear=2019/puMonth=*/*.parquet",
        storage_options=storage_options,
    )

len(gdf.vendorID) # 3297967
```

**Comment by ayushdg** [comment] 2020-12-04 19:39
Closing as cudf supports reading from blog using adlfs. Opened #6915 for tracking the issue with reading partitioned parquet datasets.

**Closed by ayushdg** 2020-12-04 19:39 UTC
Labels: cuDF (Python), feature request
