### ISSUE TITLE
[FEA] Drop_duplicates method

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#1946] opened 2019-06-06 20:57 UTC
**Is your feature request related to a problem? Please describe.**
Need a `drop_duplicates` method equivalent in cudf.

Link:
http://pandas.pydata.org/pandas-docs/version/0.17/generated/pandas.DataFrame.drop_duplicates.html

Example of doing this in pandas
```python
import pandas as pd

df = pd.DataFrame(
                    {'col_1': [1, 2, 1, 2],
                     'col_2': [1, 1, 1, 1]
                     }
                  )

print(df.drop_duplicates())
```

Output:
```python
   col_1  col_2
0      1      1
1      2      1
```
**Describe alternatives you've considered**

Current work-around with non-string columns.

```python
import pandas as pd
import cudf

df = pd.DataFrame(
                    {'col_1': [1, 2, 1, 2],
                     'col_2': [1, 1, 1, 1]
                     }
                  )

gdf = cudf.from_pandas(df)

col_ls = ['col_1', 'col_2']

## create  copy of columns
gdf['index_col'] = gdf.index
# get first column
print(gdf.groupby(col_ls).agg('min').to_pandas())
# get last column
print(gdf.groupby(col_ls).agg('max').to_pandas())
```
Output
```python
             index_col
col_1 col_2           
1     1              0
2     1              1
             index_col
col_1 col_2           
1     1              2
2     1              3

```
**Additional context**

This is specially useful for porting queries that have `Select DISTINCT on multiple columns` so is a useful functionality to have.

**Comment by devavret** [comment] 2019-06-06 21:00
Drop this coz it's a duplicate of #1467

**Closed** 2019-06-06 21:03 UTC
Labels: ? - Needs Triage, feature request
