### ISSUE TITLE
[FEA] Python plumbing for cudf::rolling_window

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#1812] opened 2019-05-21 23:38 UTC
In 0.7 we added cudf::rolling_window. We need to get this exposed via the Python API.

libcudf PR (merged) was #1356 .

@kkraus14 assigning you initially to delegate.

**Comment by kkraus14** [comment] 2019-06-03 16:19
Closing as duplicate of #1870

**Closed by kkraus14** 2019-06-03 16:19 UTC
Labels: cuDF (Python), cuStreamz, feature request
