### ISSUE TITLE
[FEA] implement struct-typed scalars 

### ISSUE THREAD

**Issue by gerashegalov** [rapidsai/cudf#7874] opened 2021-04-06 16:55 UTC
**Is your feature request related to a problem? Please describe.**
Spark RAPIDS plugin needs to provide the ability of using scalars for struct columns.

**Describe the solution you'd like**
We should be able to natively pass scalar structs for filters. expressions etc.

**Describe alternatives you've considered**
For some scenarios like filters we can easily rewrite the query by flattening the struct matching individual components connected by AND, e.g. `s = {"John", "Doe"}` is equivalent to `s.firstName = "John" AND s.lastName = "Doe"` 

**Additional context**
Related Spark RAPIDS issue https://github.com/NVIDIA/spark-rapids/issues/1950

**Comment by kkraus14** [comment] 2021-04-06 17:07
Duplicate of #7790

**Closed by kkraus14** 2021-04-06 17:07 UTC
Labels: ? - Needs Triage, Spark, feature request
