### ISSUE TITLE
[QST] cuDF way to do group by e.g. sum TD

### ISSUE THREAD

**Issue by Lion-Mod** [rapidsai/cudf#6422] opened 2020-10-05 14:43 UTC
Looking to do some speedy time series crunching. Is there a way to do a lagged summing to date on a time series in cuDF concisely? I have some stuff up and running in R but wanting to move it over to Python, specifically cuDF! 

e.g. 
person A scores 1, 2, 3 on Mon, Tues, Wed
then
person B scores 4, 5, 6 on Mon, Tues, Wed

Then using whatever function gives `TD_col` 0, 1, 2 for person A and 0, 4, 9

**Comment by Lion-Mod** [comment] 2020-10-05 15:58
Sorry @kkraus14, I realised I was way too unspecific/unclear.

My current idea.

1. `Sort the cuDF dataframe by group then by datetime`
(`a` is the column to sum to date)

2. `s['cumsum'] = s.groupby("a").cumsum()`

3. `s["cumsum_TD"] = s.groupby("a")["cumsum"].shift(1, fill_value = 0)`

This seems to work but was curious if there is something out there to make it work quicker/more concise code.

**Comment by devavret** [comment] 2020-10-12 18:38
What you're asking for then is groupby scan operations. This would be a duplicate of #1298

**Closed by devavret** 2020-10-12 18:38 UTC
Labels: cuDF (Python), question
