### ISSUE TITLE
[BUG] Error in merge of 8million obs dataset in databricks

### ISSUE THREAD

**Issue by matt7salomon** [rapidsai/cudf#16992] opened 2024-10-03 20:46 UTC
I get the following error when I try to merge big cudf datasets on databricks. It seems like cudf or dask is making too many API calls to the driver causing this issue. my code is a simple merge with pandas syntax. Any suggestions?
```
com.databricks.rpc.UnexpectedHttpException: Got invalid response: 404 /ERR_NGROK_3200
	at com.databricks.rpc.Jetty9Client$$anon$1.onComplete(Jetty9Client.scala:1043)
	at shaded.v9_4.org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
	at shaded.v9_4.org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
	at shaded.v9_4.org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:481)
	at shaded.v9_4.org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:461)
	at shaded.v9_4.org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:424)
	at shaded.v9_4.org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:374)
	at shaded.v9_4.org.eclipse.jetty.http.HttpParser.handleContentMessage(HttpParser.java:597)
	at shaded.v9_4.org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1722)
	at shaded.v9_4.org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1551)
	at shaded.v9_4.org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:208)
	at shaded.v9_4.org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:148)
	at shaded.v9_4.org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:80)
	at shaded.v9_4.org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:131)
	at shaded.v9_4.org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:172)
	at shaded.v9_4.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at shaded.v9_4.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at shaded.v9_4.org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
	at shaded.v9_4.org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
	at shaded.v9_4.org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
```

**Comment by bdice** [comment] 2024-10-04 15:00
I can’t see any information related to cudf or dask in this error log, so it does not appear to be a cudf error. I will see if I can find a Databricks expert who might be able to help diagnose a possible root cause.

**Comment by bdice** [comment] 2024-10-04 15:10
It appears this was also asked on the dask issue tracker and resolved there: https://github.com/dask/dask/issues/11413#issuecomment-2393715556

Closing this as not a cudf issue.

**Closed by bdice** 2024-10-04 15:10 UTC
Labels: bug
