### ISSUE TITLE
[BUG] `fillna` forward and backward fill methods fail to replace long ranges of missing values

### ISSUE THREAD

**Issue by Nyrio** [rapidsai/cudf#8673] opened 2021-07-07 15:16 UTC
The following code explains the problem better than words:

```python
import cudf
import pandas as pd
import numpy as np

a_pd = pd.DataFrame([[0, np.nan], *([[np.nan, np.nan]]*14), [np.nan, 1]],
                    columns=list("AB"))
a_cudf = cudf.from_pandas(a_pd)

print(a_pd.fillna(method="ffill").fillna(method="bfill"))
print(a_cudf.fillna(method="ffill").fillna(method="bfill"))
```

```
input            |   pandas output   |  cudf output
                 |                   |
       A     B   |         A    B    |          A     B
0    0.0  <NA>   |   0   0.0  1.0    |   0    0.0  <NA>
1   <NA>  <NA>   |   1   0.0  1.0    |   1    0.0  <NA>
2   <NA>  <NA>   |   2   0.0  1.0    |   2    0.0   1.0
3   <NA>  <NA>   |   3   0.0  1.0    |   3    0.0   1.0
4   <NA>  <NA>   |   4   0.0  1.0    |   4    0.0   1.0
5   <NA>  <NA>   |   5   0.0  1.0    |   5    0.0   1.0
6   <NA>  <NA>   |   6   0.0  1.0    |   6    0.0   1.0
7   <NA>  <NA>   |   7   0.0  1.0    |   7    0.0   1.0
8   <NA>  <NA>   |   8   0.0  1.0    |   8    0.0   1.0
9   <NA>  <NA>   |   9   0.0  1.0    |   9    0.0   1.0
10  <NA>  <NA>   |   10  0.0  1.0    |   10   0.0   1.0
11  <NA>  <NA>   |   11  0.0  1.0    |   11   0.0   1.0
12  <NA>  <NA>   |   12  0.0  1.0    |   12   0.0   1.0
13  <NA>  <NA>   |   13  0.0  1.0    |   13   0.0   1.0
14  <NA>  <NA>   |   14  0.0  1.0    |   14  <NA>   1.0
15  <NA>   1.0   |   15  0.0  1.0    |   15  <NA>   1.0
```

The expected behavior is the pandas output: there shouldn't be any `<NA>` left after an existing value in `ffill` / before in `bfill`.
But cudf can only fill a certain range and then fails to fill subsequent missing values.

(note, however, that filling by value works)

**Comment by beckernick** [comment] 2021-07-08 13:36
I'm able to reproduce this as well. Marking as P0 due to data corruption being a silent failure.

**Closed** 2021-07-16 00:46 UTC
Labels: bug, cuDF (Python), libcudf
